/**
 * This module provides the central view for the platform's advanced compliance and governance capabilities.
 * Business impact: Ensures regulatory adherence, mitigates financial risk, and safeguards institutional reputation by providing real-time oversight and automated policy enforcement.
 * It transforms static compliance into a dynamic, intelligent function, generating long-term business value through reduced penalties, operational efficiency, and enhanced trust with regulators and clients.
 * This system represents a revolutionary, multi-million-dollar infrastructure leap in financial risk management.
 */

import React, { useContext, useState, useEffect } from 'react';
import { DataContext } from '../../../context/DataContext';
import Card from '../../Card';
import { ComplianceCase } from '../../../types'; // Original ComplianceCase type

// --- Local Interfaces and Mock Data for Self-Contained Simulation ---
// In a full commercial system, these types would reside in shared 'types' definitions,
// and mock data would be managed by a dedicated simulation layer or backend services.

/**
 * Defines the structure for a compliance agent, an intelligent entity that automates
 * review, remediation, and governance tasks within the financial infrastructure.
 * These agents are critical for scalable operational intelligence.
 */
export interface ComplianceAgent {
    id: string;
    name: string;
    role: string;
    status: 'active' | 'idle' | 'busy';
}

/**
 * Represents a programmable compliance rule, forming the backbone of the platform's
 * automated governance layer. These rules define criteria and actions for real-time
 * risk detection and policy enforcement.
 */
export interface ComplianceRule {
    id: string;
    name: string;
    description: string;
    criteria: string; // JSON string for rule conditions, e.g., { "transactionAmount": { "$gt": 10000 }, "destinationCountry": "sanctioned" }
    action: 'flag' | 'block' | 'escalate' | 'review';
    priority: 'low' | 'medium' | 'high';
    enabled: boolean;
    createdBy: string;
    lastUpdated: string;
    agentHandlerId?: string; // Optional: id of the agent responsible for handling cases generated by this rule
}

/**
 * Represents a single entry in a cryptographically signed, tamper-evident audit trail.
 * This ensures the integrity and verifiability of all actions taken within the system,
 * crucial for regulatory reporting and operational transparency.
 */
export interface CaseAuditEntry {
    timestamp: string;
    action: string; // e.g., "Case Opened", "Agent Assigned", "Evidence Reviewed", "Case Resolved", "Policy Updated"
    actor: string; // User ID or Agent ID, linked to Digital Identity Layer
    details: string; // Specific details like "Agent 'FraudGuard' assigned for review"
    signature?: string; // Cryptographic signature of the actor for integrity and non-repudiation
}

/**
 * Extends the base ComplianceCase with enriched data, including a full audit trail
 * and assignment details, demonstrating the integration of agentic intelligence and
 * comprehensive governance.
 */
export interface EnhancedComplianceCase extends ComplianceCase {
    auditTrail: CaseAuditEntry[];
    assignedAgentId?: string; // Identifier of the agent currently handling the case
    relatedTransactions?: string[]; // IDs of transactions linked to this case for deep tracing
}

/**
 * Defines the roles for access control simulation, showcasing the platform's
 * granular permissions and digital identity integration.
 */
export type UserRole = 'Compliance Officer' | 'Auditor' | 'Guest';

// Mock Data for Agents and Rules for Simulation
const mockComplianceAgents: ComplianceAgent[] = [
    { id: 'agent-001', name: 'PolicyEnforcer', role: 'Regulatory Compliance Agent', status: 'active' },
    { id: 'agent-002', name: 'FraudGuard', role: 'Anti-Fraud Agent', status: 'idle' },
    { id: 'agent-003', name: 'SettlementAuditor', role: 'Settlement Compliance Agent', status: 'active' },
];

const initialComplianceRules: ComplianceRule[] = [
    {
        id: 'rule-001',
        name: 'High-Value Transaction Flag',
        description: 'Flags transactions exceeding $10,000 for review, invoking FraudGuard for initial assessment, enhancing risk detection.',
        criteria: JSON.stringify({ "transactionAmount": { "$gt": 10000 }, "currency": "USD" }),
        action: 'flag',
        priority: 'medium',
        enabled: true,
        createdBy: 'system-init',
        lastUpdated: '2023-10-26T10:00:00Z',
        agentHandlerId: 'agent-002',
    },
    {
        id: 'rule-002',
        name: 'Sanctioned Entity Block',
        description: 'Blocks payments to entities identified on OFAC or other sanctions lists, preventing illicit financial flows and ensuring global compliance.',
        criteria: JSON.stringify({ "destinationCountry": "IR", "OFAC_match": true }),
        action: 'block',
        priority: 'high',
        enabled: true,
        createdBy: 'system-init',
        lastUpdated: '2023-10-25T14:30:00Z',
        agentHandlerId: 'agent-001',
    },
    {
        id: 'rule-003',
        name: 'Unusual Activity Detection',
        description: 'Triggers review for anomalous transaction patterns, leveraging agentic intelligence to detect emerging fraud vectors and enhance system resilience.',
        criteria: JSON.stringify({ "transactionPattern": "unusual_frequency_value" }),
        action: 'escalate',
        priority: 'high',
        enabled: false, // Initially disabled, can be enabled by officer
        createdBy: 'system-init',
        lastUpdated: '2023-10-20T09:00:00Z',
        agentHandlerId: 'agent-002',
    },
];

/**
 * Generates a simulated cryptographically-linked audit trail for a compliance case.
 * This simulates the immutable logging of events, actors, and actions for transparency
 * and regulatory integrity.
 */
const generateAuditTrail = (caseId: string, assignedAgentId?: string): CaseAuditEntry[] => {
    const trail: CaseAuditEntry[] = [
        {
            timestamp: new Date(Date.now() - 3600000).toISOString(), // 1 hour ago
            action: 'Case Opened',
            actor: 'System (Rule Engine)',
            details: `Automated policy rule triggered for case ${caseId}.`,
            signature: `sig-sys-open-${caseId.substring(0, 8)}-1`,
        },
    ];
    if (assignedAgentId) {
        trail.push({
            timestamp: new Date(Date.now() - 3500000).toISOString(), // 5 minutes after open
            action: 'Agent Assigned',
            actor: assignedAgentId,
            details: `Assigned to agent ${mockComplianceAgents.find(a => a.id === assignedAgentId)?.name || assignedAgentId} for initial review and automated data aggregation.`,
            signature: `sig-agent-assign-${caseId.substring(0, 8)}-1`,
        });
        trail.push({
            timestamp: new Date(Date.now() - 1800000).toISOString(), // 30 minutes after assign
            action: 'Evidence Reviewed',
            actor: assignedAgentId,
            details: 'Initial transaction logs, digital identity verification, and related data points assessed by agent. AI-driven risk scoring applied.',
            signature: `sig-agent-review-${caseId.substring(0, 8)}-1`,
        });
    }
    return trail;
};

/**
 * Enhances a basic compliance case with simulated audit trails, agent assignments,
 * and related transactions, providing a richer data context for investigation.
 */
const enhanceComplianceCase = (c: ComplianceCase): EnhancedComplianceCase => {
    const assignedAgentId = c.status === 'open'
        ? initialComplianceRules.find(r => r.enabled && c.reason.includes(r.name.split(' ')[0]))?.agentHandlerId || mockComplianceAgents[Math.floor(Math.random() * mockComplianceAgents.length)].id
        : undefined;

    return {
        ...c,
        auditTrail: generateAuditTrail(c.id, assignedAgentId),
        assignedAgentId: assignedAgentId,
        relatedTransactions: [`TXN-${c.id.substring(0, 5)}`, `TXN-${c.id.substring(5, 10)}`],
    };
};

/**
 * A reusable component for displaying status badges consistently across the platform.
 * It provides clear visual cues for various operational states, such as case status
 * or rule enablement.
 */
export const StatusBadge: React.FC<{ status: 'open' | 'closed' | 'enabled' | 'disabled' }> = ({ status }) => {
    let bgColor = 'bg-gray-500/20';
    let textColor = 'text-gray-300';

    if (status === 'open') {
        bgColor = 'bg-yellow-500/20';
        textColor = 'text-yellow-300';
    } else if (status === 'enabled') {
        bgColor = 'bg-emerald-500/20';
        textColor = 'text-emerald-300';
    } else if (status === 'disabled') {
        bgColor = 'bg-red-500/20';
        textColor = 'text-red-300';
    }

    return (
        <span className={`px-2 py-1 text-xs font-medium rounded-full capitalize ${bgColor} ${textColor}`}>{status}</span>
    );
};

/**
 * A generic modal component for displaying detailed information or forms,
 * ensuring a consistent user experience for interactive elements.
 */
export const Modal: React.FC<{ isOpen: boolean; onClose: () => void; title: string; children: React.ReactNode; }> = ({ isOpen, onClose, title, children }) => {
    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 bg-black bg-opacity-75 flex justify-center items-center z-50 p-4">
            <div className="bg-gray-800 rounded-lg shadow-xl w-full max-w-2xl border border-gray-700 max-h-[90vh] flex flex-col">
                <div className="flex justify-between items-center p-4 border-b border-gray-700">
                    <h3 className="text-xl font-semibold text-white">{title}</h3>
                    <button onClick={onClose} className="text-gray-400 hover:text-white">
                        <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>
                <div className="p-4 overflow-y-auto flex-grow">
                    {children}
                </div>
            </div>
        </div>
    );
};

/**
 * Component for displaying the detailed view of a compliance case, including its
 * full audit trail, assigned agents, and options for resolution or reassignment.
 * This empowers compliance officers with comprehensive actionable insights.
 */
export const CaseDetailModal: React.FC<{
    isOpen: boolean;
    onClose: () => void;
    caseData: EnhancedComplianceCase | null;
    onResolve: (caseId: string) => void;
    onEscalate: (caseId: string, agentId: string) => void;
    userRole: UserRole;
    availableAgents: ComplianceAgent[];
}> = ({
    isOpen,
    onClose,
    caseData,
    onResolve,
    onEscalate,
    userRole,
    availableAgents,
}) => {
    const [selectedAgentId, setSelectedAgentId] = useState<string | undefined>(caseData?.assignedAgentId);

    useEffect(() => {
        setSelectedAgentId(caseData?.assignedAgentId);
    }, [caseData]);

    if (!caseData) return null;

    return (
        <Modal isOpen={isOpen} onClose={onClose} title={`Compliance Case ${caseData.id} Details`}>
            <div className="p-4 space-y-4 text-gray-300">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                    <div>
                        <p className="mb-1"><strong>Reason:</strong> {caseData.reason}</p>
                        <p className="mb-1"><strong>Entity:</strong> {caseData.entityType} ({caseData.entityId})</p>
                        <p className="mb-1"><strong>Opened:</strong> {caseData.openedDate}</p>
                        <p className="mb-1"><strong>Current Status:</strong> <StatusBadge status={caseData.status} /></p>
                    </div>
                    <div>
                        <p className="mb-1"><strong>Assigned Agent:</strong> {caseData.assignedAgentId ? availableAgents.find(a => a.id === caseData.assignedAgentId)?.name || caseData.assignedAgentId : 'N/A'}</p>
                        <p className="mb-1"><strong>Related Transactions:</strong> {caseData.relatedTransactions?.join(', ') || 'None'}</p>
                        {userRole === 'Compliance Officer' && caseData.status === 'open' && (
                             <div className="mt-2 flex flex-col space-y-2 md:flex-row md:space-x-2 md:space-y-0 items-start md:items-center">
                                <label htmlFor="assignAgent" className="whitespace-nowrap text-gray-400">Reassign Agent:</label>
                                <select
                                    id="assignAgent"
                                    className="bg-gray-700 border border-gray-600 text-white text-sm rounded-lg focus:ring-cyan-500 focus:border-cyan-500 p-1.5 w-full md:w-auto"
                                    value={selectedAgentId || ''}
                                    onChange={(e) => setSelectedAgentId(e.target.value)}
                                >
                                    <option value="">Select Agent</option>
                                    {availableAgents.map(agent => (
                                        <option key={agent.id} value={agent.id}>{agent.name} ({agent.role})</option>
                                    ))}
                                </select>
                                <button
                                    onClick={() => selectedAgentId && onEscalate(caseData.id, selectedAgentId)}
                                    className="text-xs bg-cyan-600 hover:bg-cyan-700 text-white font-bold py-1 px-3 rounded w-full md:w-auto"
                                    disabled={!selectedAgentId || selectedAgentId === caseData.assignedAgentId}
                                >
                                    Reassign
                                </button>
                             </div>
                        )}
                    </div>
                </div>

                <div className="mt-4">
                    <h3 className="text-lg font-semibold text-white mb-2">Audit Trail (Cryptographically Signed Events)</h3>
                    <div className="overflow-y-auto max-h-48 bg-gray-900/50 rounded p-2 border border-gray-700">
                        {caseData.auditTrail.length > 0 ? (
                            caseData.auditTrail.map((entry, index) => (
                                <div key={index} className="text-xs border-b border-gray-800 last:border-b-0 py-1">
                                    <p><strong className="text-cyan-400">[{new Date(entry.timestamp).toLocaleTimeString()}] {entry.actor}:</strong> {entry.action} - {entry.details}</p>
                                    {entry.signature && <p className="text-gray-500 truncate mt-0.5">Hash: {entry.signature.substring(0, 20)}...</p>}
                                </div>
                            ))
                        ) : (
                            <p className="text-gray-500">No tamper-evident audit entries for this case.</p>
                        )}
                    </div>
                </div>

                {userRole === 'Compliance Officer' && caseData.status === 'open' && (
                    <div className="flex justify-end space-x-2 mt-4">
                        <button
                            onClick={() => onResolve(caseData.id)}
                            className="bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-2 px-4 rounded"
                        >
                            Mark as Resolved
                        </button>
                    </div>
                )}
            </div>
        </Modal>
    );
};

/**
 * Component for editing or creating a compliance rule, enabling administrators to
 * dynamically configure automated policy enforcement logic. This is crucial for
 * adapting to new regulations and business requirements.
 */
export const RuleEditModal: React.FC<{
    isOpen: boolean;
    onClose: () => void;
    rule: ComplianceRule | null;
    onSave: (updatedRule: ComplianceRule) => void;
    availableAgents: ComplianceAgent[];
}> = ({ isOpen, onClose, rule, onSave, availableAgents }) => {
    const [currentRule, setCurrentRule] = useState<ComplianceRule | null>(rule);

    useEffect(() => {
        setCurrentRule(rule);
    }, [rule]);

    if (!isOpen || !currentRule) return null;

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        const { name, value, type } = e.target;
        setCurrentRule(prev => prev ? {
            ...prev,
            [name]: type === 'checkbox' ? (e.target as HTMLInputElement).checked : value
        } : null);
    };

    const handleSubmit = () => {
        if (currentRule) {
            onSave({ ...currentRule, lastUpdated: new Date().toISOString() });
            onClose();
        }
    };

    return (
        <Modal isOpen={isOpen} onClose={onClose} title={currentRule.id ? `Edit Policy Rule: ${currentRule.name}` : 'Define New Policy Rule'}>
            <div className="p-4 space-y-4 text-gray-300 text-sm">
                <div>
                    <label htmlFor="ruleName" className="block text-gray-400 mb-1">Rule Name</label>
                    <input type="text" id="ruleName" name="name" value={currentRule.name} onChange={handleChange}
                           className="w-full bg-gray-700 border border-gray-600 rounded p-2 focus:ring-cyan-500 focus:border-cyan-500" />
                </div>
                <div>
                    <label htmlFor="ruleDescription" className="block text-gray-400 mb-1">Description</label>
                    <textarea id="ruleDescription" name="description" value={currentRule.description} onChange={handleChange}
                              className="w-full bg-gray-700 border border-gray-600 rounded p-2 focus:ring-cyan-500 focus:border-cyan-500" rows={3}></textarea>
                </div>
                <div>
                    <label htmlFor="ruleCriteria" className="block text-gray-400 mb-1">Criteria (JSON for Programmable Policy Engine)</label>
                    <textarea id="ruleCriteria" name="criteria" value={currentRule.criteria} onChange={handleChange}
                              className="w-full bg-gray-700 border border-gray-600 rounded p-2 font-mono text-xs focus:ring-cyan-500 focus:border-cyan-500" rows={5}></textarea>
                    <p className="text-gray-500 text-xs mt-1">Example: <code className="bg-gray-700 p-1 rounded">{"{\"transactionAmount\": {\"$gt\": 10000}}"}</code></p>
                </div>
                <div>
                    <label htmlFor="ruleAction" className="block text-gray-400 mb-1">Action</label>
                    <select id="ruleAction" name="action" value={currentRule.action} onChange={handleChange}
                            className="w-full bg-gray-700 border border-gray-600 rounded p-2 focus:ring-cyan-500 focus:border-cyan-500">
                        <option value="flag">Flag for Review</option>
                        <option value="block">Block Transaction (Real-Time Settlement Integration)</option>
                        <option value="escalate">Escalate to Senior Agent</option>
                        <option value="review">Require Manual Review</option>
                    </select>
                </div>
                <div>
                    <label htmlFor="rulePriority" className="block text-gray-400 mb-1">Priority</label>
                    <select id="rulePriority" name="priority" value={currentRule.priority} onChange={handleChange}
                            className="w-full bg-gray-700 border border-gray-600 rounded p-2 focus:ring-cyan-500 focus:border-cyan-500">
                        <option value="low">Low</option>
                        <option value="medium">Medium</option>
                        <option value="high">High</option>
                    </select>
                </div>
                <div>
                    <label htmlFor="ruleAgent" className="block text-gray-400 mb-1">Assigned Agent Handler</label>
                    <select id="ruleAgent" name="agentHandlerId" value={currentRule.agentHandlerId || ''} onChange={handleChange}
                            className="w-full bg-gray-700 border border-gray-600 rounded p-2 focus:ring-cyan-500 focus:border-cyan-500">
                        <option value="">None</option>
                        {availableAgents.map(agent => (
                            <option key={agent.id} value={agent.id}>{agent.name} ({agent.role})</option>
                        ))}
                    </select>
                </div>
                <div className="flex items-center">
                    <input type="checkbox" id="ruleEnabled" name="enabled" checked={currentRule.enabled} onChange={handleChange}
                           className="form-checkbox h-4 w-4 text-cyan-600 bg-gray-700 border-gray-600 rounded focus:ring-cyan-500" />
                    <label htmlFor="ruleEnabled" className="ml-2 text-gray-300">Enabled</label>
                </div>
                <div className="flex justify-end space-x-2 mt-4">
                    <button onClick={onClose} className="bg-gray-600 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
                        Cancel
                    </button>
                    <button onClick={handleSubmit} className="bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-2 px-4 rounded">
                        Save Policy
                    </button>
                </div>
            </div>
        </Modal>
    );
};

/**
 * Displays a table of programmable compliance rules, enabling a clear overview
 * of the automated governance policies and their operational status.
 * It provides tools for rule management, central to proactive risk management.
 */
export const ComplianceRulesTable: React.FC<{
    rules: ComplianceRule[];
    onEditRule: (rule: ComplianceRule) => void;
    onToggleRule: (ruleId: string, enabled: boolean) => void;
    userRole: UserRole;
    onCreateNewRule: () => void;
}> = ({ rules, onEditRule, onToggleRule, userRole, onCreateNewRule }) => {
    return (
        <div>
            {userRole === 'Compliance Officer' && (
                <div className="flex justify-end mb-4">
                    <button onClick={onCreateNewRule} className="bg-cyan-600 hover:bg-cyan-700 text-white font-bold py-2 px-4 rounded">
                        Define New Policy Rule
                    </button>
                </div>
            )}
            <div className="overflow-x-auto">
                <table className="w-full text-sm text-left text-gray-400">
                    <thead className="text-xs text-gray-300 uppercase bg-gray-900/30">
                        <tr>
                            <th scope="col" className="px-6 py-3">Rule ID</th>
                            <th scope="col" className="px-6 py-3">Name</th>
                            <th scope="col" className="px-6 py-3">Action</th>
                            <th scope="col" className="px-6 py-3">Priority</th>
                            <th scope="col" className="px-6 py-3">Status</th>
                            <th scope="col" className="px-6 py-3">Last Updated</th>
                            {userRole === 'Compliance Officer' && <th scope="col" className="px-6 py-3">Actions</th>}
                        </tr>
                    </thead>
                    <tbody>
                        {rules.length === 0 ? (
                            <tr>
                                <td colSpan={7} className="px-6 py-4 text-center text-gray-500">No active compliance rules found.</td>
                            </tr>
                        ) : (
                            rules.map(rule => (
                                <tr key={rule.id} className="border-b border-gray-800 hover:bg-gray-800/50">
                                    <td className="px-6 py-4 font-mono text-white">{rule.id}</td>
                                    <td className="px-6 py-4 font-medium text-white">{rule.name}</td>
                                    <td className="px-6 py-4">{rule.action}</td>
                                    <td className="px-6 py-4 capitalize">{rule.priority}</td>
                                    <td className="px-6 py-4">
                                        <StatusBadge status={rule.enabled ? 'enabled' : 'disabled'} />
                                    </td>
                                    <td className="px-6 py-4 text-xs">{rule.lastUpdated.split('T')[0]}</td>
                                    {userRole === 'Compliance Officer' && (
                                        <td className="px-6 py-4 space-x-2">
                                            <button onClick={() => onEditRule(rule)} className="text-xs text-cyan-300 hover:underline">Edit Policy</button>
                                            <button onClick={() => onToggleRule(rule.id, !rule.enabled)}
                                                    className={`text-xs ${rule.enabled ? 'text-red-400' : 'text-emerald-400'} hover:underline`}>
                                                {rule.enabled ? 'Disable' : 'Enable'}
                                            </button>
                                        </td>
                                    )}
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

/**
 * The ComplianceView component provides a comprehensive dashboard for managing
 * compliance cases and automated policy rules. It integrates agentic intelligence,
 * programmable governance, and immutable audit trails to deliver a robust and
 * transparent financial control environment.
 */
const ComplianceView: React.FC = () => {
    const context = useContext(DataContext);

    if (!context) throw new Error("ComplianceView must be within a DataProvider.");
    const { complianceCases: rawComplianceCases } = context;

    // Simulate user role for RBAC and feature visibility within the UI
    const [currentUserRole, setCurrentUserRole] = useState<UserRole>('Compliance Officer'); // Default role for demonstration

    // State for managing enhanced compliance cases with audit trails and agent assignments
    const [enhancedCases, setEnhancedCases] = useState<EnhancedComplianceCase[]>([]);
    useEffect(() => {
        setEnhancedCases(rawComplianceCases.map(enhanceComplianceCase));
    }, [rawComplianceCases]);

    // State for managing compliance rules, reflecting the programmable value rails
    const [complianceRules, setComplianceRules] = useState<ComplianceRule[]>(initialComplianceRules);

    // State for Case Detail Modal management
    const [isCaseDetailModalOpen, setIsCaseDetailModalOpen] = useState(false);
    const [selectedCase, setSelectedCase] = useState<EnhancedComplianceCase | null>(null);

    // State for Rule Edit Modal management
    const [isRuleEditModalOpen, setIsRuleEditModalOpen] = useState(false);
    const [editingRule, setEditingRule] = useState<ComplianceRule | null>(null);

    /** Opens the case detail modal for a specific compliance case. */
    const openCaseDetailModal = (caseData: EnhancedComplianceCase) => {
        setSelectedCase(caseData);
        setIsCaseDetailModalOpen(true);
    };

    /** Closes the case detail modal. */
    const closeCaseDetailModal = () => {
        setIsCaseDetailModalOpen(false);
        setSelectedCase(null);
    };

    /**
     * Simulates the resolution of a compliance case, updating its status to 'closed'
     * and adding a cryptographically-linked entry to its audit trail.
     */
    const handleResolveCase = (caseId: string) => {
        setEnhancedCases(prevCases => prevCases.map(c =>
            c.id === caseId
                ? {
                    ...c,
                    status: 'closed',
                    auditTrail: [...c.auditTrail, {
                        timestamp: new Date().toISOString(),
                        action: 'Case Resolved',
                        actor: `User: ${currentUserRole}`,
                        details: 'Compliance case successfully resolved and closed, ensuring auditable closure.',
                        signature: `sig-resolve-${caseId}-${Date.now().toString().substring(5)}`
                    }]
                }
                : c
        ));
        closeCaseDetailModal();
    };

    /**
     * Simulates reassigning a compliance case to a different intelligent agent,
     * reflecting dynamic workload management and adding an auditable event.
     */
    const handleEscalateCase = (caseId: string, newAgentId: string) => {
        setEnhancedCases(prevCases => prevCases.map(c =>
            c.id === caseId
                ? {
                    ...c,
                    assignedAgentId: newAgentId,
                    auditTrail: [...c.auditTrail, {
                        timestamp: new Date().toISOString(),
                        action: 'Case Reassigned',
                        actor: `User: ${currentUserRole}`,
                        details: `Case formally reassigned to agent ${mockComplianceAgents.find(a => a.id === newAgentId)?.name || newAgentId} for continued processing.`,
                        signature: `sig-reassign-${caseId}-${Date.now().toString().substring(5)}`
                    }]
                }
                : c
        ));
    };

    /** Opens the rule edit modal for an existing rule. */
    const openRuleEditModal = (rule: ComplianceRule) => {
        setEditingRule(rule);
        setIsRuleEditModalOpen(true);
    };

    /** Initiates the creation of a new compliance rule. */
    const createNewRule = () => {
        const newRuleId = `rule-${Date.now().toString().slice(-6)}`;
        setEditingRule({
            id: newRuleId,
            name: 'New Compliance Policy',
            description: 'Define the purpose, scope, and impact of this new regulatory policy or business logic for automated enforcement.',
            criteria: '{}',
            action: 'flag',
            priority: 'medium',
            enabled: true,
            createdBy: `User: ${currentUserRole}`,
            lastUpdated: new Date().toISOString(),
        });
        setIsRuleEditModalOpen(true);
    };

    /** Closes the rule edit modal. */
    const closeRuleEditModal = () => {
        setIsRuleEditModalOpen(false);
        setEditingRule(null);
    };

    /**
     * Simulates saving a new or updated compliance rule, persisting its definition
     * within the programmable governance engine.
     */
    const handleSaveRule = (updatedRule: ComplianceRule) => {
        setComplianceRules(prevRules => {
            const index = prevRules.findIndex(r => r.id === updatedRule.id);
            if (index > -1) {
                return prevRules.map((r, i) => (i === index ? updatedRule : r));
            } else {
                return [...prevRules, updatedRule];
            }
        });
        closeRuleEditModal();
    };

    /**
     * Simulates enabling or disabling a compliance rule, affecting its real-time
     * enforcement status and logging the change for auditability.
     */
    const handleToggleRule = (ruleId: string, enabled: boolean) => {
        setComplianceRules(prevRules => prevRules.map(r =>
            r.id === ruleId ? {
                ...r,
                enabled: enabled,
                lastUpdated: new Date().toISOString(),
                auditTrail: (r as any).auditTrail ? [...(r as any).auditTrail, {
                    timestamp: new Date().toISOString(),
                    action: enabled ? 'Rule Enabled' : 'Rule Disabled',
                    actor: `User: ${currentUserRole}`,
                    details: `Policy status changed to ${enabled ? 'enabled' : 'disabled'}, impacting real-time enforcement.`,
                    signature: `sig-rule-toggle-${ruleId}-${Date.now().toString().substring(5)}`
                }] : []
            } : r
        ));
    };

    return (
        <div className="space-y-6">
            <h2 className="text-3xl font-bold text-white tracking-wider">Compliance Center: Risk & Governance Automation</h2>

            {/* User Role Selector for Simulation of RBAC */}
            <div className="flex flex-col md:flex-row items-start md:items-center space-y-2 md:space-y-0 md:space-x-4 p-4 bg-gray-900/40 rounded-lg border border-gray-700">
                <label htmlFor="userRole" className="text-gray-300 font-medium whitespace-nowrap">Simulate User Role:</label>
                <select
                    id="userRole"
                    value={currentUserRole}
                    onChange={(e) => setCurrentUserRole(e.target.value as UserRole)}
                    className="bg-gray-700 border border-gray-600 text-white text-sm rounded-lg focus:ring-cyan-500 focus:border-cyan-500 p-1.5 w-full md:w-auto"
                >
                    <option value="Compliance Officer">Compliance Officer (Full Control)</option>
                    <option value="Auditor">Auditor (Read-Only, Full Audit Trail)</option>
                    <option value="Guest">Guest (Limited View)</option>
                </select>
                <p className="text-gray-500 text-xs ml-auto">Control access and capabilities to demonstrate dynamic RBAC based on Digital Identity.</p>
            </div>

            <Card title="Open & Active Compliance Cases">
                <div className="overflow-x-auto">
                    <table className="w-full text-sm text-left text-gray-400">
                        <thead className="text-xs text-gray-300 uppercase bg-gray-900/30">
                            <tr>
                                <th scope="col" className="px-6 py-3">Case ID</th>
                                <th scope="col" className="px-6 py-3">Reason</th>
                                <th scope="col" className="px-6 py-3">Entity</th>
                                <th scope="col" className="px-6 py-3">Opened</th>
                                <th scope="col" className="px-6 py-3">Status</th>
                                <th scope="col" className="px-6 py-3">Assigned Agent</th>
                                <th scope="col" className="px-6 py-3">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {enhancedCases.length === 0 ? (
                                <tr>
                                    <td colSpan={7} className="px-6 py-4 text-center text-gray-500">No active compliance cases found, indicating system integrity.</td>
                                </tr>
                            ) : (
                                enhancedCases.filter(c => c.status === 'open').map(c => (
                                    <tr key={c.id} className="border-b border-gray-800 hover:bg-gray-800/50">
                                        <td className="px-6 py-4 font-mono text-white">{c.id}</td>
                                        <td className="px-6 py-4 font-medium text-white">{c.reason}</td>
                                        <td className="px-6 py-4 font-mono text-xs">{c.entityType}<br/>{c.entityId}</td>
                                        <td className="px-6 py-4">{c.openedDate}</td>
                                        <td className="px-6 py-4"><StatusBadge status={c.status} /></td>
                                        <td className="px-6 py-4 text-cyan-400">{c.assignedAgentId ? mockComplianceAgents.find(a => a.id === c.assignedAgentId)?.name : 'Unassigned'}</td>
                                        <td className="px-6 py-4">
                                            {c.status === 'open' && (
                                                <button onClick={() => openCaseDetailModal(c)} className="text-xs text-cyan-300 hover:underline" disabled={currentUserRole === 'Guest'}>Review Case</button>
                                            )}
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </Card>

            <Card title="Automated Compliance Policies & Ruleset">
                <p className="text-gray-400 text-sm mb-4">This section enables administrators to define, manage, and audit the intelligent policy rules that autonomously trigger compliance cases, enforce settlement conditions, and mitigate risk across the platform's programmable value rails. This capability directly enhances system resilience and adaptability to regulatory changes.</p>
                <ComplianceRulesTable
                    rules={complianceRules}
                    onEditRule={openRuleEditModal}
                    onToggleRule={handleToggleRule}
                    userRole={currentUserRole}
                    onCreateNewRule={createNewRule}
                />
            </Card>

            <Card title="Resolved Cases (Immutable Audit History)" isCollapsible defaultCollapsed>
                <p className="text-gray-400 text-sm mb-4">View a complete, tamper-evident history of all resolved compliance cases. Each entry includes cryptographically signed audit trails, providing irrefutable proof of actions and decisions for regulatory compliance and internal transparency.</p>
                <div className="overflow-x-auto">
                    <table className="w-full text-sm text-left text-gray-400">
                        <thead className="text-xs text-gray-300 uppercase bg-gray-900/30">
                            <tr>
                                <th scope="col" className="px-6 py-3">Case ID</th>
                                <th scope="col" className="px-6 py-3">Reason</th>
                                <th scope="col" className="px-6 py-3">Entity</th>
                                <th scope="col" className="px-6 py-3">Opened</th>
                                <th scope="col" className="px-6 py-3">Status</th>
                                <th scope="col" className="px-6 py-3">Resolved By</th>
                                <th scope="col" className="px-6 py-3">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {enhancedCases.length === 0 ? (
                                <tr>
                                    <td colSpan={7} className="px-6 py-4 text-center text-gray-500">No closed compliance cases found.</td>
                                </tr>
                            ) : (
                                enhancedCases.filter(c => c.status === 'closed').map(c => (
                                    <tr key={c.id} className="border-b border-gray-800 hover:bg-gray-800/50">
                                        <td className="px-6 py-4 font-mono text-white">{c.id}</td>
                                        <td className="px-6 py-4 font-medium text-white">{c.reason}</td>
                                        <td className="px-6 py-4 font-mono text-xs">{c.entityType}<br/>{c.entityId}</td>
                                        <td className="px-6 py-4">{c.openedDate}</td>
                                        <td className="px-6 py-4"><StatusBadge status={c.status} /></td>
                                        <td className="px-6 py-4 text-gray-500">{c.auditTrail.find(a => a.action === 'Case Resolved')?.actor || 'N/A'}</td>
                                        <td className="px-6 py-4">
                                            <button onClick={() => openCaseDetailModal(c)} className="text-xs text-cyan-300 hover:underline" disabled={currentUserRole === 'Guest'}>View Audit</button>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </Card>

            <CaseDetailModal
                isOpen={isCaseDetailModalOpen}
                onClose={closeCaseDetailModal}
                caseData={selectedCase}
                onResolve={handleResolveCase}
                onEscalate={handleEscalateCase}
                userRole={currentUserRole}
                availableAgents={mockComplianceAgents}
            />

            <RuleEditModal
                isOpen={isRuleEditModalOpen}
                onClose={closeRuleEditModal}
                rule={editingRule}
                onSave={handleSaveRule}
                availableAgents={mockComplianceAgents}
            />
        </div>
    );
};

export default ComplianceView;