// Copyright James Burvel O’Callaghan III, Chief Executive Officer, Citibank Demo Business Inc.
// All Rights Reserved. Enterprise Grade Software Solutions.

import React from "react";
import { useHistory } from "react-router-dom";
import {
  ActionItem,
  Icon,
  Popover,
  PopoverPanel,
  PopoverTrigger,
} from "~/common/ui-components";

const bURL = "https://citibankdemobusiness.dev";
const compN = "Citibank Demo Business Inc";

const g = (n: string) => ({
  n,
  apiC: {
    b: `${bURL}/api/v4/connect/${n.toLowerCase().replace(/\s/g, "_")}`,
    rtL: 100,
    to: 15000,
    rh: { Authorization: `Bearer ${compN.replace(/\s/g, "")}_TOKEN` },
  },
  auth: {
    t: "oauth2_jwt",
    cfg: {
      aURL: `${bURL}/oauth/authorize?client=${n.toLowerCase()}`,
      tURL: `${bURL}/oauth/token`,
      rURL: `${bURL}/oauth/refresh`,
      s: [
        "read:profile",
        "write:profile",
        "read:data",
        "write:data",
        "admin",
        "system:all",
      ],
      clientID: `cid_${n.toLowerCase()}_${Date.now()}`,
      clientSecretRef: `vlt://secrets/clients/${n.toLowerCase()}/secret`,
    },
  },
  eps: {
    getUser: { p: "/user", m: "GET" },
    postData: { p: "/data", m: "POST" },
    updateConfig: { p: "/config", m: "PUT" },
    deleteResource: { p: "/resource/:id", m: "DELETE" },
    streamEvents: { p: "/events/stream", m: "GET", stream: true },
    batchProcess: { p: "/batch", m: "POST" },
    getAnalytics: { p: "/analytics", m: "GET" },
    search: { p: "/search", m: "POST" },
    getSchema: { p: "/schema", m: "GET" },
    validate: { p: "/validate", m: "POST" },
    execute: { p: "/execute", m: "POST" },
    getStatus: { p: "/status/:jobId", m: "GET" },
    listResources: { p: "/resources", m: "GET" },
    createWebhook: { p: "/webhooks", m:: "POST" },
    getWebhook: { p: "/webhooks/:hookId", m: "GET" },
    deleteWebhook: { p: "/webhooks/:hookId", m: "DELETE" },
  },
  dMod: {
    user: {
      id: "string",
      name: "string",
      email: "string",
      roles: "array<string>",
    },
    config: {
      key: "string",
      value: "any",
      lastUpdated: "timestamp",
    },
    resource: {
      uuid: "string",
      type: "string",
      owner: "string",
      metadata: "object",
      createdAt: "timestamp",
    },
  },
  webHks: {
    events: [
      "resource.created",
      "resource.updated",
      "resource.deleted",
      "config.changed",
      "user.login",
      "system.reboot",
    ],
    sKeyRef: `vlt://secrets/webhooks/${n.toLowerCase()}/signature`,
  },
  sdk: {
    lang: ["ts", "py", "go", "java", "rb", "php"],
    v: "4.7.1",
    docs: `${bURL}/docs/${n.toLowerCase()}`,
  },
  meta: {
    tags: ["enterprise", "api", "integration", n.toLowerCase()],
    rating: Math.random() * 5,
    active: Math.random() > 0.1,
  },
});

const cNames = [
  "Gemini",
  "ChatGPT",
  "Pipedream",
  "GitHub",
  "Hugging Face",
  "Plaid",
  "Modern Treasury",
  "Google Drive",
  "OneDrive",
  "Azure",
  "Google Cloud",
  "Supabase",
  "Vercel",
  "Salesforce",
  "Oracle",
  "MARQETA",
  "Citibank",
  "Shopify",
  "WooCommerce",
  "GoDaddy",
  "Cpanel",
  "Adobe",
  "Twilio",
  "Stripe",
  "PayPal",
  "Braintree",
  "Adyen",
  "Square",
  "Klarna",
  "Affirm",
  "AWS",
  "DigitalOcean",
  "Heroku",
  "Netlify",
  "Atlassian",
  "Jira",
  "Confluence",
  "Slack",
  "Zoom",
  "Microsoft Teams",
  "Dropbox",
  "Box",
  "Asana",
  "Trello",
  "Monday.com",
  "Notion",
  "Figma",
  "Sketch",
  "InVision",
  "Zendesk",
  "Intercom",
  "HubSpot",
  "Marketo",
  "Mailchimp",
  "SendGrid",
  "Segment",
  "Snowflake",
  "Datadog",
  "New Relic",
  "Sentry",
  "PagerDuty",
  "Okta",
  "Auth0",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "Chef",
  "Puppet",
  "CircleCI",
  "Jenkins",
  "GitLab",
  "Travis CI",
  "Snyk",
  "Cloudflare",
  "Fastly",
  "Akamai",
  "MessageBird",
  "Vonage",
  "Algolia",
  "Elastic",
  "MongoDB",
  "Redis",
  "PostgreSQL",
  "MySQL",
  "CockroachDB",
  "PlanetScale",
  "Docusign",
  "HelloSign",
  "SAP",
  "Workday",
  "Intuit QuickBooks",
  "Xero",
  "Gusto",
  "Rippling",
  "Brex",
  "Ramp",
  "Carta",
  "Airtable",
  "Zapier",
  "IFTTT",
  "Splunk",
  "Sumo Logic",
  "Looker",
  "Tableau",
  "Power BI",
  "Qlik",
  "Miro",
  "Mural",
  "Canva",
  "Grammarly",
  "SurveyMonkey",
  "Typeform",
  "Calendly",
  "DocuSend",
  "PandaDoc",
  "Freshworks",
  "ServiceNow",
  "Databricks",
  "Hadoop",
  "Spark",
  "Kafka",
  "RabbitMQ",
  "Nginx",
  "Apache",
  "Tomcat",
  "GlassFish",
  "JBoss",
  "WebLogic",
  "WebSphere",
  "Cloudinary",
  "Imgix",
  "Mux",
  "Stytch",
  "Clerk",
  "FusionAuth",
  "Keycloak",
  "Ping Identity",
  "OneLogin",
  "LastPass",
  "1Password",
  "Bitwarden",
  "Dashlane",
  "Yubico",
  "Duo Security",
  "CyberArk",
  "CrowdStrike",
  "Palo Alto Networks",
  "Fortinet",
  "Check Point",
  "Cisco Security",
  "McAfee",
  "Symantec",
  "Norton",
  "Trend Micro",
  "Kaspersky",
  "ESET",
  "Sophos",
  "Malwarebytes",
  "Bitdefender",
  "F-Secure",
  "Proofpoint",
  "Mimecast",
  "Barracuda",
  "Qualys",
  "Rapid7",
  "Tenable",
  "Veracode",
  "Checkmarx",
  "SonarQube",
  "JFrog",
  "SonarSource",
  "Postman",
  "Swagger",
  "Stoplight",
  "Insomnia",
  "GraphQL",
  "Apollo",
  "Relay",
  "gRPC",
  "Protobuf",
  "Thrift",
  "Avro",
  "OpenAPI",
  "AsyncAPI",
  "JSON Schema",
  "JWT",
  "SAML",
  "OAuth",
  "OpenID Connect",
  "LDAP",
  "Active Directory",
  "RADIUS",
  "Kerberos",
  "Vault",
  "Consul",
  "Nomad",
  "Vagrant",
  "Packer",
  "Skaffold",
  "Knative",
  "Istio",
  "Linkerd",
  "Envoy",
  "Prometheus",
  "Grafana",
  "Kibana",
  "Fluentd",
  "Logstash",
  "Jaeger",
  "Zipkin",
  "OpenTelemetry",
  "Cypress",
  "Selenium",
  "Puppeteer",
  "Playwright",
  "Jest",
  "Mocha",
  "Chai",
  "Jasmine",
  "Karma",
  "Storybook",
  "Bit",
  "Lerna",
  "Nx",
  "Webpack",
  "Rollup",
  "Vite",
  "esbuild",
  "Babel",
  "TypeScript",
  "ESLint",
  "Prettier",
  "Stylelint",
  "Sass",
  "Less",
  "Stylus",
  "PostCSS",
  "Tailwind CSS",
  "Bootstrap",
  "Material-UI",
  "Ant Design",
  "Chakra UI",
  "Semantic UI",
  "Foundation",
  "Bulma",
  "React",
  "Angular",
  "Vue.js",
  "Svelte",
  "Ember.js",
  "Backbone.js",
  "jQuery",
  "Lodash",
  "Underscore.js",
  "Moment.js",
  "Date-fns",
  "RxJS",
  "Redux",
  "MobX",
  "Vuex",
  "NgRx",
  "Akita",
  "Recoil",
  "Zustand",
  "Jotai",
  "Next.js",
  "Nuxt.js",
  "Gatsby",
  "Sapper",
  "Remix",
  "Astro",
  "Eleventy",
  "Jekyll",
  "Hugo",
  "WordPress",
  "Drupal",
  "Joomla",
  "Magento",
  "BigCommerce",
  "PrestaShop",
  "OpenCart",
  "Spree",
  "Solidus",
  "Sylius",
  "Contentful",
  "Strapi",
  "Sanity",
  "DatoCMS",
  "Prismic",
  "Storyblok",
  "Ghost",
  "Medium",
  "Substack",
  "Revue",
  "Mailgun",
  "Postmark",
  "Amazon SES",
  "Socket.IO",
  "Pusher",
  "Ably",
  "Firebase",
  "Aiven",
  "Upstash",
  "Neon",
  "Hasura",
  "Appwrite",
  "LaunchDarkly",
  "Optimizely",
  "VWO",
  "Amplitude",
  "Mixpanel",
  "Heap",
  "FullStory",
  "Hotjar",
  "LogRocket",
  "Crazy Egg",
  "Mouseflow",
  "Google Analytics",
  "Adobe Analytics",
  "Matomo",
  "Plausible",
  "Fathom",
  "GoSquared",
  "Clicky",
  "Chartbeat",
  "Parse.ly",
  "Newfold Digital",
  "HostGator",
  "Bluehost",
  "SiteGround",
  "A2 Hosting",
  "InMotion Hosting",
  "DreamHost",
  "WP Engine",
  "Kinsta",
  "Flywheel",
  "Pantheon",
  "Acquia",
  "Platform.sh",
  "Render",
  "Fly.io",
  "Railway",
  "Northflank",
  "Cycle.io",
  "Qovery",
  "Webflow",
  "Framer",
  "Squarespace",
  "Wix",
  "Weebly",
  "Jimdo",
  "Bubble",
  "Adalo",
  "Glide",
  "Retool",
  "Airtable Apps",
  "AppGyver",
  "OutSystems",
  "Mendix",
  "Unqork",
  "Appian",
  "Pega",
  "UiPath",
  "Automation Anywhere",
  "Blue Prism",
  "Workato",
  "Tray.io",
  "MuleSoft",
  "Boomi",
  "Celigo",
  "Jitterbit",
  "SnapLogic",
  "Informatica",
  "Talend",
  "Stitch",
  "Fivetran",
  "Airbyte",
  "Matillion",
  "dbt",
  "Trino",
  "Presto",
  "ClickHouse",
  "Druid",
  "Pinot",
  "Kylin",
  "Airflow",
  "Prefect",
  "Dagster",
  "Luigi",
  "Argo",
  "Metaflow",
  "Kubeflow",
  "MLflow",
  "DVC",
  "CML",
  "Weights & Biases",
  "Comet",
  "Neptune.ai",
  "Domino Data Lab",
  "DataRobot",
  "H2O.ai",
  "SageMaker",
  "Vertex AI",
  "Azure Machine Learning",
  "Dataiku",
  "Alteryx",
  "KNIME",
  "RapidMiner",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Scikit-learn",
  "Pandas",
  "NumPy",
  "SciPy",
  "Matplotlib",
  "Seaborn",
  "Plotly",
  "Bokeh",
  "Streamlit",
  "Dash",
  "Gradio",
  "Panel",
  "Jupyter",
  "Colab",
  "Kaggle",
  "Deepnote",
  "Hex",
  "Mode",
  "Datacamp",
  "Coursera",
  "Udacity",
  "edX",
  "Pluralsight",
  "A Cloud Guru",
  "LinkedIn Learning",
  "Skillshare",
  "Udemy",
  "MasterClass",
  "Khan Academy",
  "Codecademy",
  "freeCodeCamp",
  "The Odin Project",
  "LeetCode",
  "HackerRank",
  "Codewars",
  "Topcoder",
  "CodeSignal",
  "Coderbyte",
  "Exercism",
  "Project Euler",
  "Stack Overflow",
  "Reddit",
  "Discord",
  "Telegram",
  "Signal",
  "WhatsApp",
  "Facebook",
  "Instagram",
  "Twitter",
  "LinkedIn",
  "Pinterest",
  "Snapchat",
  "TikTok",
  "YouTube",
  "Vimeo",
  "Dailymotion",
  "Twitch",
  "Spotify",
  "Apple Music",
  "Amazon Music",
  "Tidal",
  "Deezer",
  "Pandora",
  "SoundCloud",
  "Bandcamp",
  "Netflix",
  "Hulu",
  "Disney+",
  "HBO Max",
  "Amazon Prime Video",
  "Apple TV+",
  "Peacock",
  "Paramount+",
  "Discovery+",
  "YouTube TV",
  "Sling TV",
  "FuboTV",
  "Philo",
  "Pluto TV",
  "Tubi",
  "Roku",
  "Fire TV",
  "Chromecast",
  "Apple TV",
  "Nvidia Shield",
  "PlayStation",
  "Xbox",
  "Nintendo Switch",
  "Steam",
  "Epic Games Store",
  "GOG",
  "Itch.io",
  "Humble Bundle",
  "Unity",
  "Unreal Engine",
  "Godot",
  "CryEngine",
  "Blender",
  "Maya",
  "3ds Max",
  "Cinema 4D",
  "ZBrush",
  "Substance Painter",
  "Marmoset Toolbag",
  "Houdini",
  "Nuke",
  "DaVinci Resolve",
  "Final Cut Pro",
  "Adobe Premiere Pro",
  "Adobe After Effects",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe InDesign",
  "Affinity Photo",
  "Affinity Designer",
  "Affinity Publisher",
  "Procreate",
  "CorelDRAW",
  "GIMP",
  "Inkscape",
  "Krita",
  "Audacity",
  "Reaper",
  "FL Studio",
  "Ableton Live",
  "Logic Pro X",
  "Pro Tools",
  "Cubase",
  "Reason",
  "Bitwig Studio",
  "Studio One",
  "LMMS",
  "Ardour",
  "OBS Studio",
  "Streamlabs",
  "XSplit",
  "vMix",
  "Wirecast",
  "HandBrake",
  "FFmpeg",
  "VLC",
  "Plex",
  "Emby",
  "Jellyfin",
  "Kodi",
  "Winamp",
  "Foobar2000",
  "AIMP",
  "MusicBee",
  "MediaMonkey",
  "7-Zip",
  "WinRAR",
  "PeaZip",
  "Notepad++",
  "Sublime Text",
  "Visual Studio Code",
  "Atom",
  "Brackets",
  "Vim",
  "Neovim",
  "Emacs",
  "JetBrains",
  "IntelliJ IDEA",
  "PyCharm",
  "WebStorm",
  "PhpStorm",
  "GoLand",
  "Rider",
  "CLion",
  "DataGrip",
  "AppCode",
  "RubyMine",
  "Android Studio",
  "Xcode",
  "Eclipse",
  "NetBeans",
  "Visual Studio",
  "Docker Desktop",
  "Postman Desktop",
  "Insomnia REST Client",
  "Fiddler",
  "Charles Proxy",
  "Wireshark",
  "PuTTY",
  "iTerm2",
  "Windows Terminal",
  "Hyper",
  "Terminator",
  "FileZilla",
  "Cyberduck",
  "Transmit",
  "WinSCP",
  "Total Commander",
  "FreeCommander",
  "Directory Opus",
  "Beyond Compare",
  "Meld",
  "KDiff3",
  "WinMerge",
  "GitKraken",
  "Sourcetree",
  "Tower",
  "Sublime Merge",
  "GitHub Desktop",
  "Fork",
  "GIMPshop",
  "Photopea",
  "Pixlr",
  "DaVinci",
  "Lightworks",
  "Shotcut",
  "OpenShot",
  "Kdenlive",
  "Blender VSE",
  "Natron",
  "Fusion",
  "Autodesk SketchBook",
  "MediBang Paint",
  "FireAlpaca",
  "Clip Studio Paint",
  "Paint.NET",
  "MyPaint",
  "Vectr",
  "FigmaJam",
  "Penpot",
  "Gravit Designer",
  "Boxy SVG",
  "SVG-Edit",
  "Vectornator",
  "LibreOffice",
  "OpenOffice",
  "WPS Office",
  "FreeOffice",
  "OnlyOffice",
  "Calligra Suite",
  "iWork",
  "Microsoft Office",
  "Google Workspace",
  "Zoho",
  "Proton",
  "Tutanota",
  "Hey.com",
  "Superhuman",
  "Todoist",
  "Things",
  "OmniFocus",
  "Microsoft To Do",
  "Google Keep",
  "Evernote",
  "OneNote",
  "Bear",
  "Ulysses",
  "iA Writer",
  "Scrivener",
  "Simplenote",
  "Joplin",
  "Standard Notes",
  "Obsidian",
  "Roam Research",
  "Logseq",
  "Dendron",
  "Coda",
  "ClickUp",
  "Wrike",
  "Basecamp",
  "Smartsheet",
  "Airtable Automations",
  "Podio",
  "Teamwork",
  "Freedcamp",
  "OpenProject",
  "Redmine",
  "Taiga",
  "Pivotal Tracker",
  "Rally",
  "VersionOne",
  "Targetprocess",
  "YouTrack",
  "Linear",
  "Shortcut",
  "Height",
  "GitHub Issues",
  "GitLab Issues",
  "Bitbucket Issues",
  "TestRail",
  "qTest",
  "Zephyr",
  "PractiTest",
  "TestLodge",
  "Katalon",
  "Testim",
  "Applitools",
  "Percy",
  "Sauce Labs",
  "BrowserStack",
  "LambdaTest",
  "TestingBot",
  "CrossBrowserTesting",
  "Ghost Inspector",
  "Rainforest QA",
  "mabl",
  "Testsigma",
  "AccelQ",
  "Tricentis Tosca",
  "Leapwork",
  "Ranorex",
  "SmartBear",
  "TestComplete",
  "SoapUI",
  "ReadyAPI",
  "LoadRunner",
  "JMeter",
  "Gatling",
  "k6",
  "Locust",
  "Tsung",
  "Artillery",
  "BlazeMeter",
  "LoadNinja",
  "Flood",
  "OctoPerf",
  "WebLOAD",
  "LoadView",
  "NeoLoad",
  "AppDynamics",
  "Dynatrace",
  "Instana",
  "AppNeta",
  "Riverbed",
  "SolarWinds",
  "ManageEngine",
  "PRTG",
  "Zabbix",
  "Nagios",
  "Icinga",
  "Sensu",
  "Consul",
  "etcd",
  "ZooKeeper",
  "CoreDNS",
  "bind9",
  "PowerDNS",
  "Unbound",
  "pfSense",
  "OPNsense",
  "OpenWrt",
  "DD-WRT",
  "Tomato",
  "TrueNAS",
  "Unraid",
  "OpenMediaVault",
  "XigmaNAS",
  "FreeNAS",
  "Proxmox",
  "VMware",
  "vSphere",
  "ESXi",
  "Hyper-V",
  "Xen",
  "KVM",
  "VirtualBox",
  "QEMU",
  "OpenStack",
  "CloudStack",
  "Eucalyptus",
  "OpenNebula",
  "Rancher",
  "OpenShift",
  "Tanzu",
  "Mirantis",
  "Docker Swarm",
  "HashiCorp Nomad",
  "Mesos",
  "Marathon",
  "Chronos",
  "Aurora",
  "Singularity",
  "Ceph",
  "GlusterFS",
  "Lustre",
  "MinIO",
  "Rook",
  "Longhorn",
  "OpenEBS",
  "Portworx",
  "StorageOS",
  "Calico",
  "Flannel",
  "Weave Net",
  "Cilium",
  "Antrea",
  "MetalLB",
  "CoreOS",
  "Flatcar",
  "Alpine Linux",
  "Ubuntu",
  "Debian",
  "CentOS",
  "Fedora",
  "RHEL",
  "SUSE",
  "Arch Linux",
  "Gentoo",
  "Slackware",
  "FreeBSD",
  "OpenBSD",
  "NetBSD",
  "DragonFly BSD",
  "illumos",
  "OpenIndiana",
  "SmartOS",
  "Solaris",
  "AIX",
  "HP-UX",
  "macOS",
  "Windows",
  "Linux",
  "Android",
  "iOS",
  "Go",
  "Rust",
  "Python",
  "JavaScript",
  "Java",
  "C#",
  "C++",
  "C",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "Scala",
  "Haskell",
  "Clojure",
  "Erlang",
  "Elixir",
  "OCaml",
  "F#",
  "Dart",
  "R",
  "Julia",
  "MATLAB",
  "Perl",
  "Lua",
  "Groovy",
  "PowerShell",
  "Bash",
  "Zsh",
  "Fish",
  "Ansible",
  "Terraform",
  "Pulumi",
  "Chef",
  "Puppet",
  "SaltStack",
  "CFEngine",
  "Blade",
  "Laravel",
  "Symfony",
  "CodeIgniter",
  "Yii",
  "Zend Framework",
  "CakePHP",
  "Phalcon",
  "Slim",
  "Lumen",
  "Express.js",
  "Koa",
  "Fastify",
  "NestJS",
  "Hapi",
  "Sails.js",
  "AdonisJS",
  "FeathersJS",
  "LoopBack",
  "Django",
  "Flask",
  "FastAPI",
  "Pyramid",
  "Tornado",
  "Sanic",
  "Bottle",
  "Ruby on Rails",
  "Sinatra",
  "Hanami",
  "Padrino",
  "Grape",
  "Spring",
  "Spring Boot",
  "JAX-RS",
  "Jakarta EE",
  "Play Framework",
  "Akka",
  "Lagom",
  "Micronaut",
  "Quarkus",
  "Helidon",
  "Vert.x",
  "ASP.NET",
  "ASP.NET Core",
  "Nancy",
  "ServiceStack",
  "Giraffe",
  "Saturn",
  "Suave",
  "Phoenix",
  "Plug",
  "Cowboy",
  "Kitura",
  "Vapor",
  "Perfect",
  "Zewo",
  "Gin",
  "Echo",
  "Fiber",
  "Revel",
  "Beego",
  "Martini",
  "Actix",
  "Rocket",
  "Warp",
  "Tide",
  "Axum",
  "SQLAlchemy",
  "Django ORM",
  "Peewee",
  "Pony ORM",
  "SQLObject",
  "TypeORM",
  "Prisma",
  "Sequelize",
  "Mongoose",
  "Bookshelf.js",
  "Knex.js",
  "Objection.js",
  "Drizzle ORM",
  "Active Record",
  "DataMapper",
  "ROM.rb",
  "Hibernate",
  "MyBatis",
  "jOOQ",
  "Ebean",
  "EclipseLink",
  "OpenJPA",
  "Dapper",
  "Entity Framework",
  "NHibernate",
  "LINQ to DB",
  "GORM",
  "sqlx",
  "Diesel",
  "SeaORM",
  "SQLx",
  "Ecto",
  "Slick",
  "Anorm",
  "Exposed",
  "RedBeanPHP",
  "Doctrine",
  "Propel",
  "Eloquent",
  "Cycle ORM",
  "GreenDAO",
  "Room",
  "Core Data",
  "Realm",
  "SQLite",
  "DuckDB",
  "H2",
  "HSQLDB",
  "Derby",
  "Firebird",
  "Informix",
  "DB2",
  "SQL Server",
  "Sybase",
  "Teradata",
  "Vertica",
  "Greenplum",
  "Netezza",
  "Redshift",
  "BigQuery",
  "Athena",
  "Drill",
  "Impala",
  "Hive",
  "HBase",
  "Cassandra",
  "ScyllaDB",
  "DynamoDB",
  "Cosmos DB",
  "Fauna",
  "SimpleDB",
  "Couchbase",
  "CouchDB",
  "RethinkDB",
  "ArangoDB",
  "OrientDB",
  "Neo4j",
  "Memgraph",
  "TigerGraph",
  "Dgraph",
  "JanusGraph",
  "InfluxDB",
  "TimescaleDB",
  "Prometheus",
  "QuestDB",
  "Graphite",
  "OpenTSDB",
  "Varnish",
  "Squid",
  "HAProxy",
  "Traefik",
  "Caddy",
  "OpenResty",
  "Unit",
  "Tengine",
  "Kong",
  "Tyk",
  "Apigee",
  "WSO2",
  "3scale",
  "Gravitee",
  "Ambassador",
  "Gloo",
  "KrakenD",
  "Pomerium",
  "oauth2-proxy",
  "Authelia",
  "Dex",
  "ORY Hydra",
  "ORY Kratos",
  "ORY Oathkeeper",
  "ORY Keto",
  "FreeIPA",
  "OpenLDAP",
  "389 Directory Server",
  "OpenDJ",
  "Apache Directory",
];

const intHub = cNames.reduce((a, c) => ({ ...a, [c.toLowerCase().replace(/\s/g, "_")]: g(c) }), {});

const useNavSys = () => {
  const h = useHistory();
  return {
    p: (path: string) => h.push(path),
    r: (path: string) => h.replace(path),
    gB: () => h.goBack(),
    gF: () => h.goForward(),
    l: h.location,
  };
};

const VctrGfx = ({ i, s = "m", c = "currentColor", cl = "" }: { i: string; s?: "s" | "m" | "l"; c?: string; cl?: string }) => {
  const sz = { s: "16", m: "24", l: "32" }[s];
  const pth = {
    chevron_down: "M7.41 8.59L12 13.17l4.59-4.58L18 10l-6 6-6-6 1.41-1.41z",
    ellipsis: "M6 10c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm12 0c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm-6 0c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z",
  }[i] || "";
  return (
    <svg className={cl} width={sz} height={sz} viewBox="0 0 24 24" fill={c}>
      <path d={pth}></path>
    </svg>
  );
};

const CstmPvrCtxt = React.createContext<{
  isOpn: boolean;
  setOpn: (o: boolean) => void;
  trgRef: React.RefObject<HTMLButtonElement>;
  pnlRef: React.RefObject<HTMLDivElement>;
} | null>(null);

const CstmPvr = ({ children }: { children: React.ReactNode }) => {
  const [o, sO] = React.useState(false);
  const tR = React.useRef<HTMLButtonElement>(null);
  const pR = React.useRef<HTMLDivElement>(null);

  React.useEffect(() => {
    const hdlClickOutside = (e: MouseEvent) => {
      if (pR.current && !pR.current.contains(e.target as Node) && tR.current && !tR.current.contains(e.target as Node)) {
        sO(false);
      }
    };
    document.addEventListener("mousedown", hdlClickOutside);
    return () => document.removeEventListener("mousedown", hdlClickOutside);
  }, [pR, tR]);

  return (
    <CstmPvrCtxt.Provider value={{ isOpn: o, setOpn: sO, trgRef: tR, pnlRef: pR }}>
      <div style={{ position: "relative", display: "inline-block" }}>{children}</div>
    </CstmPvrCtxt.Provider>
  );
};

const ActnTrg = ({ children, bTyp = "primary" }: { children: React.ReactNode; bTyp?: string }) => {
  const ctx = React.useContext(CstmPvrCtxt);
  if (!ctx) throw new Error("ActnTrg must be used within a CstmPvr");
  const { isOpn, setOpn, trgRef } = ctx;

  const stl = {
    primary: { backgroundColor: "#004a9e", color: "white" },
    secondary: { backgroundColor: "#e0e0e0", color: "black" },
  }[bTyp] || {};

  return (
    <button
      ref={trgRef}
      onClick={() => setOpn(!isOpn)}
      style={{
        padding: "8px 16px",
        border: "none",
        borderRadius: "4px",
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        gap: "8px",
        ...stl,
      }}
    >
      {children}
    </button>
  );
};

const FltPnl = ({ children, aOr = { h: "right", v: "bottom" } }: { children: React.ReactNode; aOr?: { h?: string; v?: string } }) => {
  const ctx = React.useContext(CstmPvrCtxt);
  if (!ctx) throw new Error("FltPnl must be used within a CstmPvr");

  const { isOpn, pnlRef, trgRef } = ctx;
  const [pos, setPos] = React.useState({ top: 0, left: 0 });

  React.useLayoutEffect(() => {
    if (isOpn && trgRef.current && pnlRef.current) {
      const trgRect = trgRef.current.getBoundingClientRect();
      const pnlRect = pnlRef.current.getBoundingClientRect();
      let t = 0;
      let l = 0;

      if (aOr.v === "bottom") {
        t = trgRect.height + 4;
      } else {
        t = -pnlRect.height - 4;
      }

      if (aOr.h === "right") {
        l = trgRect.width - pnlRect.width;
      } else {
        l = 0;
      }

      setPos({ top: t, left: l });
    }
  }, [isOpn, aOr.h, aOr.v, trgRef, pnlRef]);

  if (!isOpn) return null;

  return (
    <div
      ref={pnlRef}
      style={{
        position: "absolute",
        top: `${pos.top}px`,
        left: `${pos.left}px`,
        backgroundColor: "white",
        boxShadow: "0 4px 8px rgba(0,0,0,0.1)",
        borderRadius: "4px",
        zIndex: 1000,
        minWidth: "150px",
        border: "1px solid #ccc",
        overflow: "hidden",
      }}
    >
      {children}
    </div>
  );
};

const IntrctvEl = ({ children, t = "normal", onClk }: { children: React.ReactNode; t?: string; onClk?: () => void }) => {
  const [h, sH] = React.useState(false);

  const clr = {
    danger: "#d32f2f",
    normal: "#333",
  }[t] || "#333";

  return (
    <div
      onClick={onClk}
      onMouseEnter={() => sH(true)}
      onMouseLeave={() => sH(false)}
      style={{
        padding: "10px 16px",
        cursor: "pointer",
        color: clr,
        backgroundColor: h ? "#f5f5f5" : "transparent",
        transition: "background-color 0.2s ease",
      }}
    >
      {children}
    </div>
  );
};

interface VirtAcctConfCtrlsProps {
  id: string;
  setDeleteModal: (open: boolean) => void;
}

function VirtAcctConfCtrls({ id: i, setDeleteModal: sDelMdl }: VirtAcctConfCtrlsProps) {
  const nav = useNavSys();
  const [apiState, setApiState] = React.useState({ l: false, e: null, d: null });
  const [activeIntegration, setActiveIntegration] = React.useState("Plaid");

  const fetchConfig = React.useCallback(async (integrationKey: string, resourceId: string) => {
    setApiState({ l: true, e: null, d: null });
    try {
      const config = intHub[integrationKey.toLowerCase().replace(/\s/g, "_")];
      if (!config) throw new Error(`Integration not found: ${integrationKey}`);
      
      const ep = `${config.apiC.b}${config.eps.getSchema.p}/${resourceId}`;
      
      // Mock fetch
      await new Promise(res => setTimeout(res, 500 + Math.random() * 1000));
      
      const mockData = {
        id: resourceId,
        integration: integrationKey,
        schema: config.dMod,
        lastFetched: new Date().toISOString(),
      };
      
      setApiState({ l: false, e: null, d: mockData });
    } catch (err: any) {
      setApiState({ l: false, e: err.message, d: null });
    }
  }, []);

  React.useEffect(() => {
    if (i) {
        fetchConfig(activeIntegration, i);
    }
  }, [i, activeIntegration, fetchConfig]);


  return (
    <CstmPvr>
      <ActnTrg bTyp="primary">
        Operations
        <VctrGfx
          cl="text-white"
          i="chevron_down"
          s="s"
          c="currentColor"
        />
      </ActnTrg>

      <FltPnl aOr={{ h: "right" }}>
        <IntrctvEl
          onClk={() => {
            nav.p(`/operations/virtual_account_settings/${i}/edit`);
          }}
        >
          <div id="edt">Modify Configuration</div>
        </IntrctvEl>
        <IntrctvEl t="danger" onClk={() => sDelMdl(true)}>
          <div id="del">Terminate Account</div>
        </IntrctvEl>
        <hr style={{ margin: 0, border: "none", borderTop: "1px solid #eee"}} />
         {Object.keys(intHub).slice(0, 10).map(k => (
            <IntrctvEl key={k} onClk={() => setActiveIntegration(intHub[k].n)}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <span>{`Sync with ${intHub[k].n}`}</span>
                    {activeIntegration === intHub[k].n && (
                        <span style={{ fontSize: '10px', color: 'green' }}>●</span>
                    )}
                </div>
            </IntrctvEl>
        ))}
      </FltPnl>
    </CstmPvr>
  );
}

export default VirtAcctConfCtrls;
export { intHub, useNavSys, CstmPvr, ActnTrg, FltPnl, IntrctvEl, VctrGfx, cNames, g, bURL, compN };