// Copyright James Burvel Oâ€™Callaghan III
// President Citibank Demo Business Inc.

import { LogicalForm__InputTypeEnum } from "../../../generated/dashboard/graphqlSchema";
import { FilterType } from "./util";

/**
 * Defines a comprehensive set of filter types and their corresponding data structures,
 * specifically tailored for granular financial data such as transaction status,
 * payment method, and account details from integrated payment systems like Stripe,
 * Plaid, Modern Treasury, and internal Citibank systems.
 */
export const FINANCIAL_FILTERS: FilterType[] = [
  {
    key: "transaction_status",
    name: "Transaction Status",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Completed", value: "completed" },
      { name: "Pending", value: "pending" },
      { name: "Failed", value: "failed" },
      { name: "Refunded", value: "refunded" },
      { name: "Disputed", value: "disputed" },
      { name: "Cancelled", value: "cancelled" },
      { name: "Voided", value: "voided" },
      { name: "Settled", value: "settled" },
      { name: "Processing", value: "processing" },
      { name: "Requires Action", value: "requires_action" },
      { name: "Partially Refunded", value: "partially_refunded" },
      { name: "Expired", value: "expired" },
      { name: "Open", value: "open" },
    ],
    placeholder: "Select transaction status",
  },
  {
    key: "transaction_type",
    name: "Transaction Type",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Payment", value: "payment" },
      { name: "Payout", value: "payout" },
      { name: "Refund", value: "refund" },
      { name: "Chargeback", value: "chargeback" },
      { name: "Deposit", value: "deposit" },
      { name: "Withdrawal", value: "withdrawal" },
      { name: "Fee", value: "fee" },
      { name: "Transfer", value: "transfer" },
      { name: "Credit", value: "credit" },
      { name: "Debit", value: "debit" },
      { name: "Adjustment", value: "adjustment" },
      { name: "Interest", value: "interest" },
      { name: "Dividend", value: "dividend" },
      { name: "Loan Origination", value: "loan_origination" },
      { name: "Loan Repayment", value: "loan_repayment" },
    ],
    placeholder: "Select transaction type",
  },
  {
    key: "amount",
    name: "Amount",
    type: LogicalForm__InputTypeEnum.AmountInput,
    unit: "USD", // Default unit, user can select or UI can infer contextually
    placeholder: "Filter by amount range (e.g., 100-500)",
  },
  {
    key: "currency",
    name: "Currency",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "US Dollar (USD)", value: "USD" },
      { name: "Euro (EUR)", value: "EUR" },
      { name: "British Pound (GBP)", value: "GBP" },
      { name: "Canadian Dollar (CAD)", value: "CAD" },
      { name: "Australian Dollar (AUD)", value: "AUD" },
      { name: "Japanese Yen (JPY)", value: "JPY" },
      { name: "Swiss Franc (CHF)", value: "CHF" },
      { name: "Chinese Yuan (CNY)", value: "CNY" },
      { name: "Indian Rupee (INR)", value: "INR" },
      { name: "Brazilian Real (BRL)", value: "BRL" },
      { name: "Mexican Peso (MXN)", value: "MXN" },
      { name: "South African Rand (ZAR)", value: "ZAR" },
      { name: "Singapore Dollar (SGD)", value: "SGD" },
      { name: "Hong Kong Dollar (HKD)", value: "HKD" },
      { name: "New Zealand Dollar (NZD)", value: "NZD" },
      { name: "Swedish Krona (SEK)", value: "SEK" },
      { name: "Norwegian Krone (NOK)", value: "NOK" },
      { name: "Danish Krone (DKK)", value: "DKK" },
      { name: "Russian Ruble (RUB)", value: "RUB" },
      { name: "South Korean Won (KRW)", value: "KRW" },
      { name: "United Arab Emirates Dirham (AED)", value: "AED" },
      { name: "Argentine Peso (ARS)", value: "ARS" },
      { name: "Colombian Peso (COP)", value: "COP" },
    ],
    placeholder: "Select currency",
  },
  {
    key: "transaction_date",
    name: "Transaction Date",
    type: LogicalForm__InputTypeEnum.DateInput,
    placeholder: "Select transaction date range",
  },
  {
    key: "settlement_date",
    name: "Settlement Date",
    type: LogicalForm__InputTypeEnum.DateInput,
    placeholder: "Select settlement date range",
  },
  {
    key: "initiator_id",
    name: "Initiator ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., user_123, merchant_abc, internal_app_id",
  },
  {
    key: "beneficiary_id",
    name: "Beneficiary ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., customer_456, vendor_xyz, external_account_id",
  },
  {
    key: "description",
    name: "Description",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "Search transaction description or memo",
  },
  {
    key: "payment_method_type",
    name: "Payment Method Type",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Credit Card", value: "card" },
      { name: "Bank Transfer", value: "bank_transfer" },
      { name: "ACH (Automated Clearing House)", value: "ach" },
      { name: "SEPA (Single Euro Payments Area)", value: "sepa" },
      { name: "PayPal", value: "paypal" },
      { name: "Cryptocurrency", value: "crypto" },
      { name: "Digital Wallet", value: "wallet" },
      { name: "Check", value: "check" },
      { name: "Real-time Payments (RTP)", value: "rtp" },
      { name: "Wire Transfer", value: "wire" },
      { name: "Interac (Canada)", value: "interac" },
      { name: "Boleto (Brazil)", value: "boleto" },
    ],
    placeholder: "Select payment method type",
  },
  {
    key: "card_brand",
    name: "Card Brand",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Visa", value: "visa" },
      { name: "Mastercard", value: "mastercard" },
      { name: "American Express", value: "amex" },
      { name: "Discover", value: "discover" },
      { name: "JCB", value: "jcb" },
      { name: "Diners Club", value: "diners_club" },
      { name: "UnionPay", value: "unionpay" },
      { name: "Maestro", value: "maestro" },
    ],
    placeholder: "Select card brand",
  },
  {
    key: "card_funding_type",
    name: "Card Funding Type",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Credit", value: "credit" },
      { name: "Debit", value: "debit" },
      { name: "Prepaid", value: "prepaid" },
      { name: "Charge", value: "charge" },
    ],
    placeholder: "Select card funding type",
  },
  {
    key: "bank_account_type",
    name: "Bank Account Type",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Checking", value: "checking" },
      { name: "Savings", value: "savings" },
      { name: "Business Checking", value: "business_checking" },
      { name: "Business Savings", value: "business_savings" },
      { name: "Loan", value: "loan" },
      { name: "Credit Card Account", value: "credit_card_account" },
      { name: "Investment Account", value: "investment_account" },
    ],
    placeholder: "Select bank account type",
  },
  {
    key: "stripe_charge_id",
    name: "Stripe Charge ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., ch_1AbC2dEfG3hI4jKlM5nO6pQr",
  },
  {
    key: "stripe_payment_intent_id",
    name: "Stripe Payment Intent ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., pi_1AbC2dEfG3hI4jKlM5nO6pQr",
  },
  {
    key: "stripe_customer_id",
    name: "Stripe Customer ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., cus_AbC2dEfG3hI4jK",
  },
  {
    key: "stripe_payout_id",
    name: "Stripe Payout ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., po_1AbC2dEfG3hI4jKlM5nO6pQr",
  },
  {
    key: "stripe_dispute_status",
    name: "Stripe Dispute Status",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Needs Response", value: "needs_response" },
      { name: "Under Review", value: "under_review" },
      { name: "Won", value: "won" },
      { name: "Lost", value: "lost" },
      { name: "Closed", value: "closed" },
      { name: "Accepted", value: "accepted" },
      { name: "Warning", value: "warning" },
    ],
    placeholder: "Select Stripe dispute status",
  },
  {
    key: "plaid_account_id",
    name: "Plaid Account ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., xyzabcdef1234567890",
  },
  {
    key: "plaid_item_id",
    name: "Plaid Item ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., abcdef01234567890xyz",
  },
  {
    key: "plaid_institution_name",
    name: "Plaid Institution Name",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., Chase Bank, Wells Fargo, Bank of America",
  },
  {
    key: "plaid_account_subtype",
    name: "Plaid Account Subtype",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Checking", value: "checking" },
      { name: "Savings", value: "savings" },
      { name: "Credit Card", value: "credit_card" },
      { name: "Loan", value: "loan" },
      { name: "Brokerage", value: "brokerage" },
      { name: "IRA", value: "ira" },
      { name: "401k", value: "401k" },
      { name: "Mortgage", value: "mortgage" },
      { name: "Line of Credit", value: "line_of_credit" },
      { name: "CD", value: "cd" },
      { name: "Money Market", value: "money_market" },
      { name: "Student Loan", value: "student_loan" },
      { name: "Auto Loan", value: "auto_loan" },
    ],
    placeholder: "Select Plaid account subtype",
  },
  {
    key: "modern_treasury_payment_order_id",
    name: "Modern Treasury Payment Order ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., po_123xyzABC",
  },
  {
    key: "modern_treasury_expected_payment_id",
    name: "Modern Treasury Expected Payment ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., ep_456defGHI",
  },
  {
    key: "modern_treasury_internal_account_id",
    name: "Modern Treasury Internal Account ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., ia_789jklMNO",
  },
  {
    key: "modern_treasury_external_account_type",
    name: "Modern Treasury External Account Type",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Checking", value: "checking" },
      { name: "Savings", value: "savings" },
      { name: "Loan", value: "loan" },
      { name: "Credit Card Account", value: "credit_card_account" },
      { name: "Operating Account", value: "operating_account" },
      { name: "Reserve Account", value: "reserve_account" },
      { name: "Escrow Account", value: "escrow_account" },
    ],
    placeholder: "Select MT external account type",
  },
  {
    key: "modern_treasury_funding_source",
    name: "Modern Treasury Funding Source",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., 'operating_account', 'reserve_account'",
  },
  {
    key: "citibank_internal_transaction_id",
    name: "Citibank Internal Transaction ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., CITI_TRANS_XYZ123",
  },
  {
    key: "citibank_branch_code",
    name: "Citibank Branch Code",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., 001, Manhattan, 3350",
  },
  {
    key: "citibank_account_number",
    name: "Citibank Account Number",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., 1234567890",
  },
  {
    key: "citibank_customer_segment",
    name: "Citibank Customer Segment",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Corporate", value: "corporate" },
      { name: "Small Business", value: "small_business" },
      { name: "Retail", value: "retail" },
      { name: "Private Bank", value: "private_bank" },
      { name: "Institutional", value: "institutional" },
    ],
    placeholder: "Select Citibank customer segment",
  },
  {
    key: "transaction_category",
    name: "Transaction Category",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Payroll", value: "payroll" },
      { name: "Rent/Mortgage", value: "rent_mortgage" },
      { name: "Utilities", value: "utilities" },
      { name: "Software Subscriptions", value: "software_subscriptions" },
      { name: "Travel & Entertainment", value: "travel_entertainment" },
      { name: "Office Supplies", value: "office_supplies" },
      { name: "Consulting Fees", value: "consulting_fees" },
      { name: "Marketing & Advertising", value: "marketing_advertising" },
      { name: "Sales Revenue", value: "sales_revenue" },
      { name: "Investments", value: "investments" },
      { name: "Loan Payments", value: "loan_payments" },
      { name: "Insurance Premiums", value: "insurance_premiums" },
      { name: "Taxes", value: "taxes" },
      { name: "Other Expenses", value: "other_expenses" },
      { name: "Miscellaneous Income", value: "miscellaneous_income" },
      { name: "Vendor Payments", value: "vendor_payments" },
      { name: "Customer Receipts", value: "customer_receipts" },
    ],
    placeholder: "Select transaction category",
  },
  {
    key: "transaction_subcategory",
    name: "Transaction Subcategory",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., 'electricity', 'internet', 'SaaS platform license'",
  },
  {
    key: "reference_number",
    name: "Reference Number",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "Search by reference number (e.g., invoice number, check number)",
  },
  {
    key: "custom_tag",
    name: "Custom Tag",
    type: LogicalForm__InputTypeEnum.TextInput,
    repeatable: true,
    placeholder: "Add custom tag (e.g., 'Q1_2024_project', 'Marketing_Campaign_X')",
  },
  {
    key: "metadata",
    name: "Custom Metadata",
    type: LogicalForm__InputTypeEnum.MetadataInput,
    repeatable: true,
    placeholder: "Filter by custom metadata key-value (e.g., 'campaign_id: ABC')",
  },
  {
    key: "source_ip_address",
    name: "Source IP Address",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., 192.168.1.1, 203.0.113.45",
  },
  {
    key: "device_id",
    name: "Device ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., unique_device_identifier_xyz",
  },
  {
    key: "geolocation",
    name: "Geolocation (City/Country)",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., New York, USA; London, UK",
  },
  {
    key: "risk_score_range",
    name: "Risk Score",
    type: LogicalForm__InputTypeEnum.AmountInput, // Using AmountInput for numeric range (e.g., 0-100)
    unit: "Score",
    placeholder: "Filter by risk score range (e.g., 0-25)",
  },
  {
    key: "fraud_status",
    name: "Fraud Status",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Not Fraudulent", value: "not_fraudulent" },
      { name: "Potentially Fraudulent", value: "potentially_fraudulent" },
      { name: "Confirmed Fraud", value: "confirmed_fraud" },
      { name: "Under Review", value: "under_review" },
      { name: "Dismissed", value: "dismissed" },
    ],
    placeholder: "Select fraud status",
  },
  {
    key: "source_application",
    name: "Source Application",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Web Application", value: "web_app" },
      { name: "Mobile App (iOS)", value: "mobile_ios" },
      { name: "Mobile App (Android)", value: "mobile_android" },
      { name: "API Integration", value: "api" },
      { name: "Internal Admin Tool", value: "internal_admin" },
      { name: "Point of Sale (POS)", value: "pos" },
    ],
    placeholder: "Select source application",
  },
  {
    key: "batch_id",
    name: "Batch ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., BATCH_20240315_001",
  },
  {
    key: "reconciliation_status",
    name: "Reconciliation Status",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Reconciled", value: "reconciled" },
      { name: "Unreconciled", value: "unreconciled" },
      { name: "Discrepancy", value: "discrepancy" },
      { name: "Manual Review Needed", value: "manual_review" },
    ],
    placeholder: "Select reconciliation status",
  },
  {
    key: "fee_type",
    name: "Fee Type",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Processing Fee", value: "processing" },
      { name: "Interchange Fee", value: "interchange" },
      { name: "Network Fee", value: "network" },
      { name: "Dispute Fee", value: "dispute" },
      { name: "Refund Fee", value: "refund" },
      { name: "FX Fee", value: "fx" },
      { name: "Setup Fee", value: "setup" },
      { name: "Maintenance Fee", value: "maintenance" },
      { name: "ACH Return Fee", value: "ach_return" },
      { name: "Wire Fee", value: "wire_fee" },
    ],
    placeholder: "Select fee type",
  },
  {
    key: "initiating_system",
    name: "Initiating System",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Stripe", value: "stripe" },
      { name: "Plaid", value: "plaid" },
      { name: "Modern Treasury", value: "modern_treasury" },
      { name: "Citibank", value: "citibank" },
      { name: "Internal Ledger", value: "internal_ledger" },
      { name: "CRM", value: "crm" },
      { name: "ERP", value: "erp" },
      { name: "Payment Gateway", value: "payment_gateway" },
    ],
    placeholder: "Select system that initiated transaction",
  },
  {
    key: "ledger_account_id",
    name: "Ledger Account ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., '1000-cash', '4000-sales_revenue'",
    repeatable: true,
  },
  {
    key: "related_entity_type",
    name: "Related Entity Type",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Customer", value: "customer" },
      { name: "Vendor", value: "vendor" },
      { name: "Employee", value: "employee" },
      { name: "Partner", value: "partner" },
      { name: "Bank", value: "bank" },
      { name: "Supplier", value: "supplier" },
    ],
    placeholder: "Select type of related entity",
  },
  {
    key: "related_entity_id",
    name: "Related Entity ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., 'cust_123', 'ven_456', 'emp_789'",
  },
  {
    key: "payment_route",
    name: "Payment Route",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "ACH (US)", value: "ach_us" },
      { name: "SEPA (EU)", value: "sepa_eu" },
      { name: "FedWire (US)", value: "fedwire_us" },
      { name: "SWIFT (International)", value: "swift_int" },
      { name: "RTP (US)", value: "rtp_us" },
      { name: "Faster Payments (UK)", value: "fps_uk" },
      { name: "Cards (Visa/MC/Amex)", value: "cards_visa_mc_amex" },
      { name: "CHAPS (UK)", value: "chaps_uk" },
      { name: "Giro (Europe)", value: "giro_europe" },
    ],
    placeholder: "Select payment route",
  },
  {
    key: "country_code",
    name: "Country Code",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., US, GB, DE (ISO 3166-1 alpha-2)",
  },
  {
    key: "statement_descriptor",
    name: "Statement Descriptor",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "Search by statement descriptor text",
  },
  {
    key: "tax_id",
    name: "Tax ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., EIN, VAT ID, SSN, ABN",
  },
  {
    key: "invoice_number",
    name: "Invoice Number",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., INV-2024-001, 12345",
  },
  {
    key: "purchase_order_number",
    name: "Purchase Order Number",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., PO-2024-005, 98765",
  },
  {
    key: "customer_email",
    name: "Customer Email",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., customer@example.com",
  },
  {
    key: "customer_name",
    name: "Customer Name",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., John Doe Inc., Acme Corp",
  },
  {
    key: "funding_account_id",
    name: "Funding Account ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., internal account 12345, external account ID",
  },
  {
    key: "destination_account_id",
    name: "Destination Account ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., vendor account 67890, beneficiary ID",
  },
  {
    key: "webhook_status",
    name: "Webhook Status",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Sent", value: "sent" },
      { name: "Failed", value: "failed" },
      { name: "Retrying", value: "retrying" },
      { name: "Pending", value: "pending" },
      { name: "Acknowledged", value: "acknowledged" },
    ],
    placeholder: "Select webhook delivery status",
  },
  {
    key: "api_request_id",
    name: "API Request ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., req_abcdef12345",
  },
  {
    key: "payment_purpose_code",
    name: "Payment Purpose Code",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., 'SALA' (Salary), 'TRAD' (Trade Payment), 'RENT'",
  },
  {
    key: "is_live_mode",
    name: "Is Live Mode",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Live", value: "true" },
      { name: "Test", value: "false" },
    ],
    placeholder: "Filter by live/test mode environment",
  },
  {
    key: "audit_trail_id",
    name: "Audit Trail ID",
    type: LogicalForm__InputTypeEnum.TextInput,
    placeholder: "e.g., UUID for audit log entry",
  },
  {
    key: "compliance_status",
    name: "Compliance Status",
    type: LogicalForm__InputTypeEnum.SelectInput,
    options: [
      { name: "Compliant", value: "compliant" },
      { name: "Non-Compliant", value: "non_compliant" },
      { name: "Under Review", value: "under_review" },
      { name: "Exempt", value: "exempt" },
    ],
    placeholder: "Select compliance status",
  },
];