-- This SQL schema defines the structure for storing user preferences,
-- prompt history, generated image metadata, and digital rights management
-- information within the Generative UI system.

-- It is assumed that a UUID extension (e.g., `uuid-ossp` for PostgreSQL or
-- built-in `gen_random_uuid()`) is available and configured for primary keys.

-- Table for managing user accounts and their subscription tiers
CREATE TABLE users (
    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL, -- Stored securely, not raw password
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP WITH TIME ZONE,
    current_subscription_tier_id UUID, -- Foreign Key to subscription_tiers
    user_persona_vector JSONB, -- Stores inferred user aesthetic profile embeddings (from UPI in SPIE)
    account_status VARCHAR(50) NOT NULL DEFAULT 'active', -- 'active', 'suspended', 'deleted'
    consent_state VARCHAR(50) NOT NULL DEFAULT 'granted', -- 'granted', 'denied', 'revoked' (from Ethical AI Considerations)
    last_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table for defining different subscription plans and their features
-- (from Monetization and Licensing Framework)
CREATE TABLE subscription_tiers (
    tier_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tier_name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    max_generations_per_day INT,
    max_resolution_width INT,
    max_resolution_height INT,
    cost_per_month NUMERIC(10, 2) NOT NULL,
    features_json JSONB, -- e.g., {'exclusive_models': ['model_a'], 'fast_generation': true, 'api_access': true}
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add foreign key constraint after both tables are defined
ALTER TABLE users
ADD CONSTRAINT fk_current_subscription_tier
FOREIGN KEY (current_subscription_tier_id) REFERENCES subscription_tiers(tier_id) ON DELETE SET NULL;


-- Table for storing user-submitted prompts and their enhanced versions
-- (from Prompt History and Recommendation Engine PHRE, Semantic Prompt Interpretation Engine SPIE)
CREATE TABLE prompts (
    prompt_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    raw_prompt_text TEXT NOT NULL,
    enhanced_prompt_json JSONB, -- Semantic Prompt Interpretation Engine (SPIE) output, structured for GMAC
    negative_prompt_text TEXT, -- Generated by SPIE
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_modified_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    parent_prompt_id UUID REFERENCES prompts(prompt_id) ON DELETE SET NULL, -- For Prompt Versioning System (PVS)
    semantic_embedding REAL[], -- Array of floats for semantic representations, e.g., CLIP embeddings from SPIE
    context_data_json JSONB, -- Contextual Awareness Integration (e.g., time of day, system theme)
    safety_score REAL, -- From Semantic Prompt Validation Subsystem (SPVS) F_safety
    prompt_quality_score REAL, -- From SPVS Q_prompt
    is_public BOOLEAN DEFAULT FALSE, -- For Prompt Sharing and Discovery Network (PSDN)
    visibility VARCHAR(50) DEFAULT 'private', -- 'private', 'public', 'unlisted'
    source_ip INET -- For auditability and security
);

-- Table for metadata of generated image assets
-- (from Dynamic Asset Management System DAMS, Image Post-Processing Module IPPM)
CREATE TABLE generated_assets (
    asset_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    prompt_id UUID REFERENCES prompts(prompt_id) ON DELETE SET NULL,
    original_image_url TEXT NOT NULL, -- URL to the raw generated image (pre-post-processing)
    optimized_image_url TEXT NOT NULL, -- CDN URL to the final, optimized image (from DAMS)
    thumbnail_url TEXT,
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    model_used VARCHAR(100), -- e.g., 'Stable Diffusion XL', 'DALL-E 3' (from GMAC)
    generation_parameters_json JSONB, -- e.g., {'guidance_scale': 7.5, 'aspect_ratio': '16:9', 'seed': 1234} (from GMAC)
    post_processing_params_json JSONB, -- e.g., {'resolution': '1920x1080', 'color_grade_preset': 'vivid'} (from IPPM)
    aesthetic_score REAL, -- From Computational Aesthetic Metrics Module (CAMM) A_score
    perceptual_distance REAL, -- From CAMM D_perc or CLIP_Score
    semantic_consistency_score REAL, -- From CAMM C_sem
    moderation_status VARCHAR(50) DEFAULT 'clean', -- 'clean', 'flagged', 'blocked', 'under_review' (from CMPES)
    moderation_flags_json JSONB, -- e.g., {'reason': ['nsfw', 'bias'], 'severity': 'high'}
    storage_tier VARCHAR(50) DEFAULT 'hot', -- 'hot', 'cold', 'archive' (from DAMS Data Tiering Engine DTE)
    digital_rights_management_json JSONB, -- e.g., {'owner_id': 'user_id', 'license_type': 'CC BY-NC-SA', 'watermark_applied': true} (from DAMS DRM)
    ipfs_hash VARCHAR(255), -- For Immutable Ledger for Provenance (ILP)
    is_deleted BOOLEAN DEFAULT FALSE, -- Soft delete flag
    version_number INT DEFAULT 1,
    parent_asset_id UUID REFERENCES generated_assets(asset_id) ON DELETE SET NULL, -- For asset versioning (from DAMS)
    last_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table for user-specific aesthetic settings and preferences
-- (from User Preference & History Database UPHD, Persistent Aesthetic State Management PASM)
CREATE TABLE user_preferences (
    preference_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    preference_key VARCHAR(255) NOT NULL, -- e.g., 'default_style', 'theme_palette', 'transition_type', 'parallax_enabled'
    preference_value TEXT, -- Simple string value
    preference_json JSONB, -- For complex preference structures or lists
    last_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, preference_key) -- Ensure only one value per key per user
);

-- Table for tracking user interactions with generated assets (implicit feedback for RLHF)
-- (from User Preference & History Database UPHD, Computational Aesthetic Metrics Module CAMM)
CREATE TABLE user_asset_interactions (
    interaction_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    asset_id UUID NOT NULL REFERENCES generated_assets(asset_id) ON DELETE CASCADE,
    interaction_type VARCHAR(100) NOT NULL, -- 'applied_background', 'liked', 'disliked', 'shared', 'downloaded', 'view_duration', 'reapplied'
    interaction_value TEXT, -- e.g., duration in seconds (as string for flexibility), boolean 'true'/'false'
    interaction_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table for listings on the Asset Marketplace (from Monetization and Licensing Framework)
CREATE TABLE asset_marketplace_listings (
    listing_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id UUID NOT NULL REFERENCES generated_assets(asset_id) ON DELETE CASCADE,
    seller_user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    price NUMERIC(10, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'USD',
    listed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL DEFAULT 'active', -- 'active', 'sold', 'delisted', 'pending'
    platform_royalty_percentage NUMERIC(5, 2) NOT NULL DEFAULT 10.00, -- e.g., 10.00 for 10%
    description TEXT
);

-- Table for tracking billing and usage (from Billing and Usage Tracking Service BUTS)
CREATE TABLE billing_records (
    record_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    transaction_type VARCHAR(100) NOT NULL, -- 'subscription_charge', 'generation_credit_purchase', 'asset_purchase', 'asset_sale_payout', 'api_usage'
    amount NUMERIC(10, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'USD',
    transaction_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    associated_entity_id UUID, -- Can link to prompt_id, asset_id, listing_id, etc. (polymorphic relation)
    credits_consumed INT DEFAULT 0,
    compute_units_consumed REAL DEFAULT 0.0,
    description TEXT,
    api_key_id UUID -- If applicable, links to an API key used for API_access transactions
);

-- Table for comprehensive audit logging across the system
-- (for Accountability and Auditability, Algorithmic Accountability Framework AAF)
CREATE TABLE audit_logs (
    log_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    actor_user_id UUID REFERENCES users(user_id) ON DELETE SET NULL, -- User performing the action, nullable for system actions
    event_type VARCHAR(255) NOT NULL, -- e.g., 'prompt_submission', 'image_generation_success', 'image_generation_failure', 'asset_updated', 'user_login', 'policy_violation_flagged'
    target_entity_type VARCHAR(100), -- 'user', 'prompt', 'asset', 'listing', 'tier', 'system'
    target_entity_id UUID, -- ID of the entity affected by the event, nullable for system-wide events
    details_json JSONB, -- Detailed event parameters, error messages, changes, etc.
    source_ip INET, -- IP address from where the action originated
    service_name VARCHAR(100) -- e.g., 'UIPAM', 'SPIE', 'GMAC', 'CMPES', 'DAMS', 'API_Gateway'
);

-- Table for storing API keys for developers (from Monetization Framework)
CREATE TABLE api_keys (
    api_key_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    api_key_hash VARCHAR(255) NOT NULL UNIQUE, -- Hashed API key
    name VARCHAR(255), -- User-defined name for the key
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT TRUE,
    rate_limit_per_minute INT,
    permissions JSONB -- e.g., {'can_generate': true, 'can_access_history': false}
);

-- Indexes for optimizing query performance
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_subscription_tier_id ON users(current_subscription_tier_id);
CREATE INDEX idx_prompts_user_id ON prompts(user_id);
CREATE INDEX idx_prompts_created_at ON prompts(created_at DESC);
CREATE INDEX idx_prompts_parent_prompt_id ON prompts(parent_prompt_id);
CREATE INDEX idx_generated_assets_user_id ON generated_assets(user_id);
CREATE INDEX idx_generated_assets_prompt_id ON generated_assets(prompt_id);
CREATE INDEX idx_generated_assets_generated_at ON generated_assets(generated_at DESC);
CREATE INDEX idx_generated_assets_moderation_status ON generated_assets(moderation_status);
CREATE INDEX idx_user_preferences_user_id ON user_preferences(user_id);
CREATE INDEX idx_user_asset_interactions_user_id ON user_asset_interactions(user_id);
CREATE INDEX idx_user_asset_interactions_asset_id ON user_asset_interactions(asset_id);
CREATE INDEX idx_user_asset_interactions_type ON user_asset_interactions(interaction_type);
CREATE INDEX idx_asset_marketplace_listings_asset_id ON asset_marketplace_listings(asset_id);
CREATE INDEX idx_asset_marketplace_listings_seller_user_id ON asset_marketplace_listings(seller_user_id);
CREATE INDEX idx_asset_marketplace_listings_status ON asset_marketplace_listings(status);
CREATE INDEX idx_billing_records_user_id ON billing_records(user_id);
CREATE INDEX idx_billing_records_transaction_at ON billing_records(transaction_at DESC);
CREATE INDEX idx_audit_logs_timestamp ON audit_logs(timestamp DESC);
CREATE INDEX idx_audit_logs_user_id ON audit_logs(actor_user_id);
CREATE INDEX idx_audit_logs_target_entity ON audit_logs(target_entity_type, target_entity_id);
CREATE INDEX idx_api_keys_user_id ON api_keys(user_id);