import React from "react";
import {
  Bar,
  BarChart,
  LabelList,
  Legend,
  ResponsiveContainer,
  Tooltip,
  XAxis,
} from "recharts";
import abbreviateAmount from "../../../../common/utilities/abbreviateAmount";
import {
  ChartDataPoint,
  CustomTooltip,
  CustomLegend,
  chartColors,
  Label,
  dateKey,
} from "./HistoricalBalanceChartForGroupsUtils";
import { DateFilterInput } from "../../../../generated/dashboard/graphqlSchema";
import { XAxisProps } from "../../../../common/styles/cash_management/charts";

export const cbu = "https://citibankdemobusiness.dev";
export const cin = "Citibank demo business Inc";

export const gmc = [
  "Gemini", "Chat Hot", "Pipedream", "GitHub", "Hugging Faces", "Plaid", "Modern Treasury",
  "Google Drive", "OneDrive", "Azure", "Google Cloud", "Supabase", "Vervet", "Salesforce",
  "Oracle", "Marqeta", "Citibank", "Shopify", "WooCommerce", "GoDaddy", "Cpanel", "Adobe",
  "Twilio", "Stripe", "PayPal", "Square", "Adyen", "Worldpay", "Braintree", "Klarna",
  "Afterpay", "Affirm", "Chime", "SoFi", "Robinhood", "Fidelity", "Charles Schwab",
  "Vanguard", "BlackRock", "JPMorgan Chase", "Bank of America", "Wells Fargo", "Goldman Sachs",
  "Morgan Stanley", "HSBC", "BNP Paribas", "Barclays", "UBS", "Credit Suisse", "Deutsche Bank",
  "Santander", "Lloyds Bank", "NatWest", "Standard Chartered", "MUFG", "Mizuho", "SMBC",
  "Commonwealth Bank", "ANZ", "Westpac", "NAB", "RBC", "TD Bank", "BMO", "Scotiabank",
  "CIBC", "Desjardins", "Capitec", "Nedbank", "FirstRand", "Absa", "Sberbank", "Tinkoff",
  "VTB", "Gazprombank", "Alfa-Bank", "Raiffeisen Bank", "UniCredit", "ING", "KBC Group",
  "Nordea", "Swedbank", "SEB", "Danske Bank", "Handelsbanken", "OP Financial Group",
  "DNB", "SpareBank 1", "LGT Bank", "Julius Baer", "Pictet Group", "Lombard Odier",
  "Union Bancaire Privée", "EFG International", "Vontobel", "VP Bank", "Liechtensteinische Landesbank",
  "J. Safra Sarasin", "Mirabaud", "Bordier & Cie", "Reyl & Cie", "Banque Cantonale de Genève",
  "CIM Banque", "Swissquote", "PostFinance", "Zurich Cantonal Bank", "Basler Kantonalbank",
  "Luzerner Kantonalbank", "St. Galler Kantonalbank", "Thurgauer Kantonalbank", "Vaudois Cantonal Bank",
  "Banque Cantonale Vaudoise", "Crédit Mutuel", "Caisse d'Épargne", "Banque Populaire",
  "Société Générale", "Crédit Agricole", "La Banque Postale", "BFM", "CIC", "LCL",
  "BGL BNP Paribas", "CCF", "HSBC France", "ING France", "N26 France", "Revolut France",
  "Boursorama Banque", "Monabanq", "Fortuneo", "Hello bank!", "Axa Banque", "BforBank",
  "Carrefour Banque", "Cofidis", "Crédit Foncier", "Cetelem", "Franfinance", "Sofinco",
  "Floa Bank", "Oney Bank", "Orange Bank", "Nickel", "Compte-Nickel", "Treezor", "Lydia",
  "Qonto", "Shine", "Blank", "Finom", "Spendesk", "Pennylane", "PayFit", "Alan",
  "Doctolib", "BlaBlaCar", "Vinted", "OVHcloud", "Dassault Systèmes", "Capgemini",
  "Atos", "Thales", "Safran", "Airbus", "Renault", "Peugeot", "Citroën", "DS Automobiles",
  "Michelin", "TotalEnergies", "Engie", "EDF", "Suez", "Veolia", "Saint-Gobain",
  "L'Oréal", "Louis Vuitton", "Hermès", "Chanel", "Dior", "Cartier", "Bvlgari",
  "Tiffany & Co.", "Gucci", "Prada", "Versace", "Armani", "Dolce & Gabbana",
  "Burberry", "Balenciaga", "Yves Saint Laurent", "Fendi", "Céline", "Givenchy",
  "Chloé", "Loewe", "Coach", "Michael Kors", "Kate Spade", "Tory Burch",
  "Ralph Lauren", "Calvin Klein", "Tommy Hilfiger", "Levi's", "Gap", "Zara",
  "H&M", "Uniqlo", "Adidas", "Nike", "Puma", "Reebok", "Under Armour", "Lululemon",
  "Patagonia", "The North Face", "Columbia Sportswear", "Arc'teryx", "Salomon",
  "Merrell", "Timberland", "Dr. Martens", "Converse", "Vans", "Crocs", "Skechers",
  "New Balance", "Asics", "Brooks Running", "Hoka One One", "Saucony", "Mizuno",
  "Fila", "Diadora", "K-Swiss", "Wilson", "Babolat", "Head", "Prince", "Yonex",
  "Dunlop", "Slazenger", "Titleist", "Callaway", "TaylorMade", "Ping", "Cobra Golf",
  "Mizuno Golf", "FootJoy", "Nike Golf", "Adidas Golf", "Puma Golf", "Under Armour Golf",
  "Garmin", "Fitbit", "Apple", "Samsung", "Google", "Microsoft", "Amazon", "Meta",
  "Netflix", "Spotify", "YouTube", "TikTok", "X", "Snapchat", "WhatsApp", "Instagram",
  "Facebook", "LinkedIn", "Pinterest", "Reddit", "Discord", "Twitch", "Steam",
  "Epic Games", "Activision Blizzard", "Nintendo", "Sony Interactive Entertainment",
  "Xbox Game Studios", "Electronic Arts", "Ubisoft", "Take-Two Interactive",
  "CD Projekt Red", "Riot Games", "Valve Corporation", "Blizzard Entertainment",
  "Mojang Studios", "Roblox Corporation", "Unity Technologies", "Epic Games Store",
  "GOG.com", "Humble Bundle", "Itch.io", "Origin", "Ubisoft Connect", "Battle.net",
  "PlayStation Store", "Xbox Games Store", "Nintendo eShop", "Google Play Store",
  "Apple App Store", "Amazon Appstore", "Samsung Galaxy Store", "Huawei AppGallery",
  "Microsoft Store", "Steam Deck", "Oculus", "HTC Vive", "Valve Index", "Pico",
  "HP Reverb", "Varjo", "Magic Leap", "Meta Quest", "PlayStation VR", "Hololens",
  "Google Glass", "Snap Spectacles", "Ray-Ban Stories", "Amazon Echo", "Google Home",
  "Apple HomePod", "Sonos", "Bose", "JBL", "Sennheiser", "Audio-Technica", "Shure",
  "Beyerdynamic", "AKG", "Sony Audio", "Samsung Audio", "LG Audio", "Philips Audio",
  "Panasonic Audio", "Yamaha Audio", "Denon", "Marantz", "Onkyo", "Pioneer", "Klipsch",
  "Polk Audio", "Definitive Technology", "MartinLogan", "B&W", "KEF", "Focal",
  "Dynaudio", "Monitor Audio", "Paradigm", "PSB Speakers", "Klipsch Speakers",
  "Harman Kardon", "JBL Speakers", "Bose Speakers", "Sonos Speakers", "Google Nest",
  "Apple TV", "Roku", "Fire TV", "Chromecast", "Nvidia Shield TV", "Tivo", "Dish Network",
  "DirecTV", "Comcast", "Spectrum", "Verizon Fios", "AT&T U-verse", "Google Fiber",
  "Starlink", "T-Mobile", "AT&T", "Verizon", "Sprint", "U.S. Cellular", "Boost Mobile",
  "Cricket Wireless", "Metro by T-Mobile", "Mint Mobile", "Visible", "Google Fi",
  "FreedomPop", "Ting Mobile", "Red Pocket Mobile", "Consumer Cellular", "Republic Wireless",
  "Straight Talk", "Total by Verizon", "TracFone", "Net10 Wireless", "Simple Mobile",
  "GoSmart Mobile", "Page Plus Cellular", "Telcel", "Movistar", "Claro", "Entel",
  "Vodafone", "O2", "EE", "Three", "Deutsche Telekom", "Orange S.A.", "Telefónica",
  "TIM", "Iliad", "BT Group", "Virgin Media O2", "Sky", "Canal+", "DAZN", "ESPN",
  "Fox Sports", "NBC Sports", "CBS Sports", "TNT Sports", "BeIN Sports", "Optus Sport",
  "Stan Sport", "Kayo Sports", "Jio", "Airtel", "Vodafone Idea", "BSNL", "Reliance",
  "Tata Communications", "Wipro", "Infosys", "TCS", "HCLTech", "L&T Technology Services",
  "Mindtree", "Capgemini India", "Accenture India", "Cognizant India", "DXC Technology India",
  "IBM India", "HP India", "Dell India", "Cisco India", "Juniper Networks India",
  "Nokia India", "Ericsson India", "Samsung India", "LG India", "Philips India",
  "Panasonic India", "Sony India", "Hitachi India", "Toshiba India", "Canon India",
  "Ricoh India", "Epson India", "Xerox India", "HP Inc. India", "Lenovo India",
  "Acer India", "Asus India", "MSI India", "Gigabyte India", "Zotac India",
  "AMD India", "Intel India", "Nvidia India", "Qualcomm India", "MediaTek India",
  "Broadcom India", "Texas Instruments India", "Micron Technology India",
  "SK Hynix India", "Western Digital India", "Seagate Technology India",
  "Kingston Technology India", "SanDisk India", "Transcend India", "Lexar India",
  "Crucial Technology India", "G.Skill India", "Corsair India", "Cooler Master India",
  "NZXT India", "Razer India", "SteelSeries India", "Logitech India", "Microsoft India",
  "Google India", "Amazon India", "Flipkart", "Myntra", "Snapdeal", "Paytm",
  "Ola Cabs", "Uber India", "Zomato", "Swiggy", "BigBasket", "Grofers", "Dun