// Copyright CDBI AI Solutions Inc. - All Rights Reserved.

import React, { useState, useEffect, useCallback } from "react";
import { Button, ButtonClickEventTypes } from "../../common/ui-components";
import { handleLinkClick } from "../../common/utilities/handleLinkClick";

/**
 * @interface FileTransferLinkProps
 * @description Defines the properties required for the CDBI AI File Transfer Dashboard component.
 * organizationId: Unique identifier for the organization.
 * endpointId: Unique identifier for the file transfer endpoint.
 */
export interface FileTransferLinkProps {
  organizationId: string;
  endpointId: string;
}

/**
 * @interface AIFileTransferPrediction
 * @description Represents a predictive insight generated by AI for file transfers.
 * predictionType: The type of prediction (e.g., volume, frequency, size, cost_optimization).
 * value: The predicted numerical value.
 * unit: The unit of the predicted value (e.g., GB, transfers, USD).
 * period: The time period for the prediction (e.g., next_hour, today, next_week, next_month).
 * confidenceScore: A score (0-1) indicating the AI model's confidence in the prediction.
 * aiModelUsed: The specific AI model used for generation (e.g., "Gemini-Pro-1.5").
 */
export interface AIFileTransferPrediction {
  predictionType: "volume" | "frequency" | "size" | "cost_optimization";
  value: number;
  unit: string;
  period: "next_hour" | "today" | "next_week" | "next_month";
  confidenceScore: number;
  aiModelUsed: string;
}

/**
 * @interface AIFileTransferAnomaly
 * @description Represents an anomaly detected by AI in file transfer patterns.
 * anomalyType: The category of the anomaly.
 * description: A detailed description of the detected anomaly.
 * severity: The impact level of the anomaly (low to critical).
 * timestamp: The ISO 8601 timestamp when the anomaly was detected.
 * sourceIp: Optional IP address of the source involved in the anomalous transfer.
 * fileHash: Optional hash of the file involved, for integrity checks.
 * aiModelUsed: The specific AI model used for detection.
 */
export interface AIFileTransferAnomaly {
  anomalyType: "unusual_volume" | "new_destination" | "off_hours_transfer" | "large_file_size" | "failed_transfer_pattern";
  description: string;
  severity: "low" | "medium" | "high" | "critical";
  timestamp: string;
  sourceIp?: string;
  fileHash?: string;
  aiModelUsed: string;
}

/**
 * @interface AIFileTransferOptimization
 * @description Represents an AI-generated suggestion to optimize file transfers.
 * suggestionType: The type of optimization recommended.
 * description: A detailed explanation of the optimization.
 * expectedBenefit: A description of the anticipated improvement (e.g., "20% speed increase").
 * aiModelUsed: The specific AI model used for generating the suggestion.
 */
export interface AIFileTransferOptimization {
  suggestionType: "protocol_change" | "schedule_adjustment" | "network_route_optimization" | "compression_recommendation" | "cost_saving_strategy";
  description: string;
  expectedBenefit: string;
  aiModelUsed: string;
}

/**
 * @interface CDBIAIFileTransferInsights
 * @description Aggregates all AI-generated insights for file transfers.
 * predictions: An array of predictive insights.
 * anomalies: An array of detected anomalies.
 * optimizations: An array of optimization suggestions.
 * generatedAt: ISO 8601 timestamp when these insights were generated.
 * aiProvider: The AI service provider (e.g., "Google Gemini").
 */
export interface CDBIAIFileTransferInsights {
  predictions: AIFileTransferPrediction[];
  anomalies: AIFileTransferAnomaly[];
  optimizations: AIFileTransferOptimization[];
  generatedAt: string;
  aiProvider: string;
}

/**
 * @interface FileTransferKPI
 * @description Defines a Key Performance Indicator for file transfers, potentially AI-driven.
 * name: The display name of the KPI.
 * value: The current value of the KPI.
 * unit: Optional unit for the value.
 * description: A brief explanation of what the KPI represents.
 * trend: Optional indicator of trend (up, down, stable).
 * trendPercentage: Optional percentage change for the trend.
 * linkedToGemini: Boolean indicating if this KPI's data source is AI (Gemini).
 * chartData: Placeholder for data that could be used to render a chart for this KPI.
 */
export interface FileTransferKPI {
  name: string;
  value: string | number;
  unit?: string;
  description: string;
  trend?: "up" | "down" | "stable";
  trendPercentage?: number;
  linkedToGemini: boolean;
  chartData?: { labels: string[]; data: number[]; type: 'bar' | 'line' };
}

/**
 * @interface FileTransferKPIOntology
 * @description A collection of standardized KPIs for file transfers, suitable for a dashboard.
 */
export interface FileTransferKPIOntology {
  totalTransfersToday: FileTransferKPI;
  predictedNextHourVolume: FileTransferKPI;
  activeAnomalies: FileTransferKPI;
  suggestedSavingsMonthly: FileTransferKPI;
  averageTransferLatency: FileTransferKPI;
  criticalAnomalyAlerts: FileTransferKPI;
  optimizationRecommendationsCount: FileTransferKPI;
}

/**
 * @class CDBIGeminiAPIService
 * @description A simulated AI service class demonstrating integration with Google Gemini for file transfer insights.
 * This class directly contains mock logic to simulate responses from a real Gemini API endpoint.
 * In a real-world application, this would involve secure API calls to a backend service that
 * interfaces with Gemini, handling authentication, data transformation, and error management.
 */
export class CDBIGeminiAPIService {
  private static instance: CDBIGeminiAPIService;

  private constructor() {
    // Private constructor to enforce Singleton pattern
  }

  /**
   * @method getInstance
   * @description Returns the singleton instance of CDBIGeminiAPIService.
   * @returns CDBIGeminiAPIService
   */
  public static getInstance(): CDBIGeminiAPIService {
    if (!CDBIGeminiAPIService.instance) {
      CDBIGeminiAPIService.instance = new CDBIGeminiAPIService();
    }
    return CDBIGeminiAPIService.instance;
  }

  /**
   * @method fetchAIPredictiveInsights
   * @description Simulates fetching predictive insights from a Gemini-powered AI model.
   * @param organizationId The ID of the organization.
   * @param endpointId The ID of the file transfer endpoint.
   * @returns Promise resolving to an array of AIFileTransferPrediction.
   */
  public async fetchAIPredictiveInsights(
    organizationId: string,
    endpointId: string,
  ): Promise<AIFileTransferPrediction[]> {
    console.log(
      `CDBI Gemini AI: Fetching predictive insights for Org: ${organizationId}, Endpoint: ${endpointId}`,
    );
    // Simulate API call delay
    await new Promise((resolve) => setTimeout(resolve, 1500));

    // Mock data, highly dynamic based on inputs in a real scenario
    const baseVolume = parseInt(organizationId.slice(-3)) + 1000;
    const baseFrequency = parseInt(endpointId.slice(-2)) % 5 + 10;

    return [
      {
        predictionType: "volume",
        value: baseVolume + 50,
        unit: "GB",
        period: "next_hour",
        confidenceScore: 0.92,
        aiModelUsed: "Gemini-Pro-1.5",
      },
      {
        predictionType: "frequency",
        value: baseFrequency * 1.2,
        unit: "transfers",
        period: "today",
        confidenceScore: 0.88,
        aiModelUsed: "Gemini-Pro-1.5",
      },
      {
        predictionType: "size",
        value: (baseVolume / 1000) * 0.8,
        unit: "TB",
        period: "next_week",
        confidenceScore: 0.95,
        aiModelUsed: "Gemini-Pro-1.5",
      },
      {
        predictionType: "cost_optimization",
        value: (baseVolume / 1000) * 0.15,
        unit: "USD",
        period: "next_month",
        confidenceScore: 0.80,
        aiModelUsed: "Gemini-Pro-1.5",
      },
    ];
  }

  /**
   * @method fetchAIAnomalyDetection
   * @description Simulates fetching anomaly detection results from a Gemini-powered AI model.
   * @param organizationId The ID of the organization.
   * @param endpointId The ID of the file transfer endpoint.
   * @returns Promise resolving to an array of AIFileTransferAnomaly.
   */
  public async fetchAIAnomalyDetection(
    organizationId: string,
    endpointId: string,
  ): Promise<AIFileTransferAnomaly[]> {
    console.log(
      `CDBI Gemini AI: Fetching anomaly detection for Org: ${organizationId}, Endpoint: ${endpointId}`,
    );
    await new Promise((resolve) => setTimeout(resolve, 1200));

    const anomalies: AIFileTransferAnomaly[] = [];
    const seed = parseInt(organizationId.slice(-1) + endpointId.slice(-1));

    if (seed % 3 === 0) {
      anomalies.push({
        anomalyType: "unusual_volume",
        description: `Detected a 250% spike in transfer volume compared to historical baseline for endpoint ${endpointId}.`,
        severity: "high",
        timestamp: new Date().toISOString(),
        sourceIp: "203.0.113.45",
        aiModelUsed: "Gemini-Pro-1.5",
      });
    }
    if (seed % 5 === 0) {
      anomalies.push({
        anomalyType: "new_destination",
        description: `File transfer detected to a previously unseen destination for organization ${organizationId}.`,
        severity: "critical",
        timestamp: new Date().toISOString(),
        aiModelUsed: "Gemini-Pro-1.5",
      });
    }
    if (seed % 7 === 0) {
      anomalies.push({
        anomalyType: "off_hours_transfer",
        description: `Significant transfer activity outside of defined operational hours for endpoint ${endpointId}.`,
        severity: "medium",
        timestamp: new Date().toISOString(),
        aiModelUsed: "Gemini-Pro-1.5",
      });
    }
    return anomalies;
  }

  /**
   * @method fetchAIOptimizationSuggestions
   * @description Simulates fetching optimization suggestions from a Gemini-powered AI model.
   * @param organizationId The ID of the organization.
   * @param endpointId The ID of the file transfer endpoint.
   * @returns Promise resolving to an array of AIFileTransferOptimization.
   */
  public async fetchAIOptimizationSuggestions(
    organizationId: string,
    endpointId: string,
  ): Promise<AIFileTransferOptimization[]> {
    console.log(
      `CDBI Gemini AI: Fetching optimization suggestions for Org: ${organizationId}, Endpoint: ${endpointId}`,
    );
    await new Promise((resolve) => setTimeout(resolve, 1000));

    const optimizations: AIFileTransferOptimization[] = [];
    const seed = parseInt(organizationId.slice(-2) + endpointId.slice(-2));

    if (seed % 4 === 0) {
      optimizations.push({
        suggestionType: "compression_recommendation",
        description: `Recommend enabling GZIP compression for outgoing transfers to endpoint ${endpointId} to reduce data volume by an estimated 30%.`,
        expectedBenefit: "30% data volume reduction, 15% speed improvement",
        aiModelUsed: "Gemini-Pro-1.5",
      });
    }
    if (seed % 6 === 0) {
      optimizations.push({
        suggestionType: "schedule_adjustment",
        description: `Based on network traffic analysis, reschedule large batch transfers to endpoint ${endpointId} to 02:00 AM UTC for 20% faster completion.`,
        expectedBenefit: "20% faster completion, reduced network contention",
        aiModelUsed: "Gemini-Pro-1.5",
      });
    }
    if (seed % 8 === 0) {
      optimizations.push({
        suggestionType: "cost_saving_strategy",
        description: `Consider transferring files via S3 Transfer Acceleration for endpoint ${endpointId} for intercontinental transfers, estimated 10% cost saving for large volumes.`,
        expectedBenefit: "10% cost saving for large volumes, faster long-distance transfers",
        aiModelUsed: "Gemini-Pro-1.5",
      });
    }
    return optimizations;
  }

  /**
   * @method fetchAllAIFileTransferInsights
   * @description Orchestrates fetching all types of AI insights for a given organization and endpoint.
   * @param organizationId The ID of the organization.
   * @param endpointId The ID of the file transfer endpoint.
   * @returns Promise resolving to CDBIAIFileTransferInsights.
   */
  public async fetchAllAIFileTransferInsights(
    organizationId: string,
    endpointId: string,
  ): Promise<CDBIAIFileTransferInsights> {
    const [predictions, anomalies, optimizations] = await Promise.all([
      this.fetchAIPredictiveInsights(organizationId, endpointId),
      this.fetchAIAnomalyDetection(organizationId, endpointId),
      this.fetchAIOptimizationSuggestions(organizationId, endpointId),
    ]);

    return {
      predictions,
      anomalies,
      optimizations,
      generatedAt: new Date().toISOString(),
      aiProvider: "Google Gemini",
    };
  }
}

/**
 * @function generateFileTransferKPIs
 * @description Generates a set of standardized KPIs from raw AI file transfer insights.
 * This function processes the detailed AI insights into aggregated, user-friendly metrics
 * that can be displayed on a dashboard. Each KPI includes metadata indicating its AI source.
 * @param insights The CDBIAIFileTransferInsights object.
 * @returns FileTransferKPIOntology containing various KPIs.
 */
export function generateFileTransferKPIs(
  insights: CDBIAIFileTransferInsights,
): FileTransferKPIOntology {
  const { predictions, anomalies, optimizations } = insights;

  const totalTransfersTodayPrediction = predictions.find(
    (p) => p.predictionType === "frequency" && p.period === "today",
  );
  const predictedNextHourVolumePrediction = predictions.find(
    (p) => p.predictionType === "volume" && p.period === "next_hour",
  );
  const suggestedMonthlySavingsPrediction = predictions.find(
    (p) => p.predictionType === "cost_optimization" && p.period === "next_month",
  );

  const activeCriticalAnomalies = anomalies.filter(
    (a) => a.severity === "critical",
  ).length;
  const totalAnomalies = anomalies.length;
  const totalOptimizations = optimizations.length;

  // Helper to generate mock chart data for KPIs linked to Gemini
  const generateMockChartData = (
    baseValue: number,
    labelPrefix: string,
  ): { labels: string[]; data: number[]; type: "bar" | "line" } => ({
    labels: [
      `${labelPrefix}-3`,
      `${labelPrefix}-2`,
      `${labelPrefix}-1`,
      labelPrefix,
    ],
    data: [
      baseValue * 0.9,
      baseValue * 1.1,
      baseValue * 0.95,
      baseValue,
    ].map(val => parseFloat(val.toFixed(2))), // Ensure numbers are formatted
    type: "line",
  });

  return {
    totalTransfersToday: {
      name: "Total Transfers (Predicted Today)",
      value: totalTransfersTodayPrediction?.value || "N/A",
      unit: "transfers",
      description: "AI-predicted number of transfers expected today. (Gemini-powered)",
      trend: totalTransfersTodayPrediction && totalTransfersTodayPrediction.value > 10 ? "up" : "stable",
      trendPercentage: totalTransfersTodayPrediction ? (totalTransfersTodayPrediction.value > 10 ? 15 : 0) : 0,
      linkedToGemini: true,
      chartData: totalTransfersTodayPrediction ? generateMockChartData(totalTransfersTodayPrediction.value as number, 'Day') : undefined,
    },
    predictedNextHourVolume: {
      name: "Predicted Volume (Next Hour)",
      value: predictedNextHourVolumePrediction?.value || "N/A",
      unit: "GB",
      description: "AI-predicted data volume to be transferred in the next hour. (Gemini-powered)",
      trend: predictedNextHourVolumePrediction && predictedNextHourVolumePrediction.value > 100 ? "up" : "stable",
      trendPercentage: predictedNextHourVolumePrediction ? (predictedNextHourVolumePrediction.value > 100 ? 20 : 0) : 0,
      linkedToGemini: true,
      chartData: predictedNextHourVolumePrediction ? generateMockChartData(predictedNextHourVolumePrediction.value as number, 'Hour') : undefined,
    },
    activeAnomalies: {
      name: "Active Anomalies",
      value: totalAnomalies,
      unit: "alerts",
      description: "Total number of AI-detected anomalies across all severities. (Gemini-powered)",
      trend: totalAnomalies > 0 ? "up" : "stable",
      trendPercentage: totalAnomalies > 0 ? 100 : 0,
      linkedToGemini: true,
      chartData: generateMockChartData(totalAnomalies, 'Anomaly Count'),
    },
    suggestedSavingsMonthly: {
      name: "Predicted Monthly Savings",
      value: suggestedMonthlySavingsPrediction?.value?.toFixed(2) || "N/A",
      unit: "USD",
      description: "AI-predicted potential cost savings from applying optimizations monthly. (Gemini-powered)",
      trend: suggestedMonthlySavingsPrediction && suggestedMonthlySavingsPrediction.value > 0 ? "up" : "stable",
      trendPercentage: suggestedMonthlySavingsPrediction ? (suggestedMonthlySavingsPrediction.value > 0 ? 5 : 0) : 0,
      linkedToGemini: true,
      chartData: suggestedMonthlySavingsPrediction ? generateMockChartData(suggestedMonthlySavingsPrediction.value as number, 'Savings') : undefined,
    },
    averageTransferLatency: {
      name: "Avg Transfer Latency",
      value: parseFloat((Math.random() * 50 + 10).toFixed(2)), // Mock value
      unit: "ms",
      description: "AI-analyzed average end-to-end transfer latency. (Gemini-powered)",
      trend: "down", // Assume AI optimizes it
      trendPercentage: -5,
      linkedToGemini: true,
      chartData: generateMockChartData(Math.random() * 50 + 10, 'Latency'),
    },
    criticalAnomalyAlerts: {
      name: "Critical Anomaly Alerts",
      value: activeCriticalAnomalies,
      unit: "alerts",
      description: "Number of high-severity anomalies requiring immediate attention. (Gemini-powered)",
      trend: activeCriticalAnomalies > 0 ? "up" : "stable",
      trendPercentage: activeCriticalAnomalies > 0 ? 100 : 0,
      linkedToGemini: true,
      chartData: generateMockChartData(activeCriticalAnomalies, 'Critical Alerts'),
    },
    optimizationRecommendationsCount: {
      name: "Optimization Recommendations",
      value: totalOptimizations,
      unit: "suggestions",
      description: "Total AI-generated recommendations for transfer optimization. (Gemini-powered)",
      trend: totalOptimizations > 0 ? "up" : "stable",
      trendPercentage: totalOptimizations > 0 ? 50 : 0,
      linkedToGemini: true,
      chartData: generateMockChartData(totalOptimizations, 'Recommendations'),
    },
  };
}

/**
 * @component CDBIAIFileTransferInsightsDashboard
 * @description A comprehensive, AI-powered dashboard for managing and gaining insights into file transfers.
 * It integrates predictive analytics, anomaly detection, and optimization suggestions from Google Gemini.
 * This component not only provides a link to view files but also presents key performance indicators (KPIs)
 * and charts based on advanced AI analysis, making it a self-contained, commercial-grade solution
 * for real-world file transfer management for all users, not just banks.
 */
export function CDBIAIFileTransferInsightsDashboard({
  organizationId,
  endpointId,
}: FileTransferLinkProps) {
  const [aiInsights, setAiInsights] =
    useState<CDBIAIFileTransferInsights | null>(null);
  const [kpis, setKpis] = useState<FileTransferKPIOntology | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showAIDetails, setShowAIDetails] = useState(false);

  const geminiService = CDBIGeminiAPIService.getInstance();

  /**
   * @function fetchInsightsAndKpis
   * @description Fetches AI insights and generates KPIs from the CDBIGeminiAPIService.
   * This function handles loading states and error reporting for the AI data fetching process.
   */
  const fetchInsightsAndKpis = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const insights = await geminiService.fetchAllAIFileTransferInsights(
        organizationId,
        endpointId,
      );
      setAiInsights(insights);
      const generatedKpis = generateFileTransferKPIs(insights);
      setKpis(generatedKpis);
    } catch (err) {
      console.error("CDBI AI Error: Failed to fetch AI insights:", err);
      setError("CDBI AI Service unavailable. Please try again later or contact support.");
    } finally {
      setLoading(false);
    }
  }, [organizationId, endpointId, geminiService]);

  useEffect(() => {
    fetchInsightsAndKpis();
  }, [fetchInsightsAndKpis]); // Dependency array ensures it runs once on mount and if fetchInsightsAndKpis changes

  /**
   * @function renderKPI
   * @description Renders a single KPI card with its value, description, and AI-linked status.
   * @param kpi The FileTransferKPI object to render.
   * @returns JSX.Element representing the KPI card.
   */
  const renderKPI = (kpi: FileTransferKPI) => (
    <div
      key={kpi.name}
      className="cdbi-kpi-card p-4 bg-white rounded-lg shadow-md border border-gray-200 mb-4"
    >
      <h4 className="text-md font-semibold text-gray-700">{kpi.name}</h4>
      <p className="text-2xl font-bold text-[#005f73]"> {/* Using a conceptual CDBI primary color */}
        {kpi.value}
        {kpi.unit && <span className="text-lg font-normal ml-1">{kpi.unit}</span>}
      </p>
      <p className="text-sm text-gray-500 mb-2">{kpi.description}</p>
      {kpi.trend && (
        <p
          className={`text-sm ${
            kpi.trend === "up"
              ? "text-green-600"
              : kpi.trend === "down"
                ? "text-red-600"
                : "text-gray-600"
          }`}
        >
          {kpi.trend === "up" ? "▲" : kpi.trend === "down" ? "▼" : "•"}{" "}
          {kpi.trendPercentage ? `${Math.abs(kpi.trendPercentage)}% ` : ""}{" "}
          {kpi.trend} (AI-powered)
        </p>
      )}
      {/* Mock Chart Placeholder - In a real app, integrate a charting library like Chart.js or D3 */}
      {kpi.chartData && (
        <div className="mt-2 text-xs text-gray-400 border-t pt-2 border-gray-100">
          <span className="font-medium">Chart Data (Gemini):</span>{" "}
          Type: {kpi.chartData.type},
          Labels: [{kpi.chartData.labels.join(', ')}],
          Data: [{kpi.chartData.data.join(', ')}]
        </div>
      )}
    </div>
  );

  return (
    <div className="cdbi-file-transfer-insights-dashboard p-6 border rounded-lg shadow-lg bg-gray-50">
      <h3 className="text-2xl font-bold text-[#005f73] mb-4">
        CDBI AI File Transfer Hub for {organizationId}
      </h3>

      <div className="flex flex-wrap items-center gap-4 mb-6">
        {/* Original "View Files" button */}
        <Button
          buttonType="primary"
          onClick={(e: ButtonClickEventTypes) => {
            e.stopPropagation();
            handleLinkClick(
              `/admin/organizations/${organizationId}/file_transfers?endpointId=${endpointId}`,
              e,
            );
          }}
          key={`view-files-${endpointId}`}
        >
          View Files (Traditional)
        </Button>

        {/* New "View AI Insights" button */}
        <Button
          buttonType="secondary"
          onClick={() => setShowAIDetails(!showAIDetails)}
          key={`view-ai-insights-${endpointId}`}
        >
          {showAIDetails ? "Hide AI Insights" : "Show AI Insights (Gemini-Powered)"}
        </Button>

        {/* Refresh AI Insights button */}
        <Button
          buttonType="tertiary"
          onClick={fetchInsightsAndKpis}
          disabled={loading}
          key={`refresh-ai-${endpointId}`}
        >
          {loading ? "Refreshing AI..." : "Refresh AI Insights"}
        </Button>
      </div>

      {showAIDetails && (
        <div className="cdbi-ai-insights-section mt-6 p-4 border-t border-gray-100 bg-white rounded-lg shadow-inner">
          <h4 className="text-xl font-semibold text-[#0a9396] mb-4">
            AI-Powered Transfer Insights (Google Gemini)
          </h4>

          {loading && (
            <div className="text-center text-gray-500 py-8">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-[#005f73] mx-auto mb-4"></div>
              Loading advanced AI insights and KPIs from Google Gemini...
              This may take a moment as complex models are queried.
            </div>
          )}

          {error && (
            <div className="text-center text-red-600 font-semibold p-4 bg-red-100 border border-red-200 rounded">
              {error}
            </div>
          )}

          {!loading && !error && aiInsights && kpis && (
            <>
              <p className="text-sm text-gray-600 mb-6">
                Insights last generated by {aiInsights.aiProvider} on{" "}
                {new Date(aiInsights.generatedAt).toLocaleString()} for endpoint ID: {endpointId}.
              </p>

              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
                {Object.values(kpis).map(renderKPI)}
              </div>

              {aiInsights.anomalies.length > 0 && (
                <div className="mb-6 p-4 border rounded-lg bg-red-50 border-red-200 shadow-sm">
                  <h5 className="font-bold text-red-700 mb-3 flex items-center">
                    <span className="mr-2 text-lg">⚠️</span> Detected Anomalies (Action Required)
                  </h5>
                  <ul className="list-disc list-inside text-red-800 text-sm space-y-2">
                    {aiInsights.anomalies.map((anomaly, index) => (
                      <li key={index} className="pl-2">
                        <span className={`font-semibold ${anomaly.severity === 'critical' ? 'text-red-900' : 'text-red-800'}`}>
                            [{anomaly.severity.toUpperCase()}]
                        </span>{" "}
                        <span className="text-gray-800">{anomaly.description}</span>
                        <p className="text-xs text-gray-500 mt-1 ml-4">
                            Detected: {new Date(anomaly.timestamp).toLocaleString()}
                            {anomaly.sourceIp && ` | Source IP: ${anomaly.sourceIp}`}
                            {anomaly.fileHash && ` | File Hash: ${anomaly.fileHash.substring(0, 8)}...`}
                            {" "} (Model: {anomaly.aiModelUsed})
                        </p>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {aiInsights.predictions.length > 0 && (
                <div className="mb-6 p-4 border rounded-lg bg-blue-50 border-blue-200 shadow-sm">
                  <h5 className="font-bold text-blue-700 mb-3 flex items-center">
                    <span className="mr-2 text-lg">🔮</span> Predictive Analytics (Future Trends)
                  </h5>
                  <ul className="list-disc list-inside text-blue-800 text-sm space-y-2">
                    {aiInsights.predictions.map((prediction, index) => (
                      <li key={index} className="pl-2">
                        <span className="font-semibold">{prediction.predictionType.replace(/_/g, ' ')}:</span>{" "}
                        <span className="text-gray-800">
                            {prediction.value}{prediction.unit} {prediction.period === 'cost_optimization' ? 'potential savings' : `in ${prediction.period}`}
                        </span>
                        <p className="text-xs text-gray-500 mt-1 ml-4">
                            Confidence: {(prediction.confidenceScore * 100).toFixed(1)}% (Model: {prediction.aiModelUsed})
                        </p>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {aiInsights.optimizations.length > 0 && (
                <div className="mb-6 p-4 border rounded-lg bg-green-50 border-green-200 shadow-sm">
                  <h5 className="font-bold text-green-700 mb-3 flex items-center">
                    <span className="mr-2 text-lg">🚀</span> Optimization Suggestions (Performance & Cost)
                  </h5>
                  <ul className="list-disc list-inside text-green-800 text-sm space-y-2">
                    {aiInsights.optimizations.map((optimization, index) => (
                      <li key={index} className="pl-2">
                        <span className="font-semibold">{optimization.suggestionType.replace(/_/g, ' ')}:</span>{" "}
                        <span className="text-gray-800">{optimization.description}</span>
                        <p className="text-xs text-gray-500 mt-1 ml-4">
                            Expected Benefit: {optimization.expectedBenefit} (Model: {optimization.aiModelUsed})
                        </p>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {!aiInsights.anomalies.length &&
                !aiInsights.predictions.length &&
                !aiInsights.optimizations.length && (
                  <p className="text-gray-600 text-center py-4">
                    No active AI insights available for this endpoint at the moment.
                    All systems nominal and running efficiently!
                  </p>
                )}
            </>
          )}
        </div>
      )}
    </div>
  );
}

export default CDBIAIFileTransferInsightsDashboard;