// Copyright CDBI - Cognitive Data-driven Business Intelligence Inc.
// All Rights Reserved. This software is proprietary and confidential.

import React, { useState, useEffect, useCallback } from "react";
import {
  useFileTransferBatchTotalsQuery,
  BatchTypeEnum,
  BatchSubtotal,
} from "../../generated/dashboard/graphqlSchema";
import {
  IndexTable,
  IndexTableSkeletonLoader,
} from "../../common/ui-components"; // Existing UI components

// --- CDBI AI Core Module (Simulated for Frontend Integration) ---
// This module represents the integration point with CDBI's powerful AI backend,
// powered by advanced models like Gemini for cognitive data processing.
// In a real-world application, these would be API calls to a dedicated AI service.

/**
 * Interface for AI-generated anomaly details.
 * @export
 */
export interface AnomalyReport {
  id: string;
  currency: string;
  direction: string;
  metric: "amount" | "count";
  subtotal: BatchSubtotal;
  detectedValue: number;
  expectedRange: [number, number];
  severity: "low" | "medium" | "high" | "critical";
  reason: string;
  suggestedAction: string;
  timestamp: string;
  sourceModel: string; // e.g., "CDBI-Gemini-AnomalyDetector-v2"
}

/**
 * Interface for AI-generated predictive analytics.
 * @export
 */
export interface PredictionReport {
  batchType: BatchTypeEnum;
  currency: string; // The primary currency of the prediction
  predictedVolumeCount: number;
  predictedVolumeAmount: number;
  confidenceScore: number; // 0-100
  predictionHorizon: string; // e.g., "next 24 hours", "next week"
  underlyingModel: string; // e.g., "CDBI-Gemini-TimeSeries-v3"
  trendsDetected: string[];
}

/**
 * Interface for comprehensive AI-generated insights and recommendations.
 * @export
 */
export interface BatchAISuggestions {
  overallSentiment: "positive" | "neutral" | "negative";
  summary: string;
  keyInsights: string[];
  actionableRecommendations: string[];
  riskScore: number; // 0-100, higher means more risk
  geminiModelVersion: string;
}

/**
 * Interface for a Key Performance Indicator (KPI) generated by AI.
 * @export
 */
export interface KPI {
  id: string;
  name: string;
  value: number | string;
  unit?: string;
  trend?: "up" | "down" | "stable";
  lastUpdate: string;
  description: string;
  linkedChartId: string; // Unique ID for a chart displaying this KPI's trend
  aiSource: string; // e.g., "CDBI Anomaly Detection AI", "CDBI Predictive AI"
}

/**
 * Interface for a chart configuration, conceptually linked to Gemini for dynamic rendering.
 * @export
 */
export interface CDBIChartConfig {
  id: string;
  title: string;
  type: "line" | "bar" | "pie" | "gauge";
  dataSeries: { label: string; values: number[] }[];
  labels: string[]; // For x-axis or categories
  options?: any; // Charting library specific options (e.g., D3, Chart.js)
  geminiPrompt?: string; // Prompt used by Gemini to generate/interpret chart data/structure
}

/**
 * Simulated AI service to analyze batch data for anomalies.
 * In a real scenario, this would be an API call to a CDBI AI service endpoint.
 * @param batchTotals - The list of batch subtotals to analyze.
 * @param batchId - The ID of the current batch.
 * @param batchType - The type of the current batch.
 * @returns A promise resolving to an array of AnomalyReport.
 */
export const cdbiAIAnomalyDetectionService = async (
  batchTotals: BatchSubtotal[],
  batchId: string,
  batchType: BatchTypeEnum,
): Promise<AnomalyReport[]> => {
  console.log(
    `CDBI AI: Simulating anomaly detection for batchId: ${batchId}, type: ${batchType}`,
  );
  // Simulate network delay for AI processing
  await new Promise((resolve) => setTimeout(resolve, 1500));

  const anomalies: AnomalyReport[] = [];
  const now = new Date().toISOString();

  // Simple rule-based anomaly simulation for demonstration.
  // In a real system, this would involve complex ML models (e.g., time series analysis, statistical models)
  // powered by Gemini for advanced pattern recognition, contextual understanding, and causality detection.
  batchTotals.forEach((subtotal, index) => {
    // Example: Flag unusually high counts or amounts for specific currencies/directions
    if (
      subtotal.currency === "USD" &&
      subtotal.direction === "DEBIT" &&
      subtotal.count &&
      subtotal.amount
    ) {
      if (subtotal.count > 5000) {
        anomalies.push({
          id: `anomaly-count-${index}-${batchId}`,
          currency: subtotal.currency,
          direction: subtotal.direction,
          metric: "count",
          subtotal: subtotal,
          detectedValue: subtotal.count,
          expectedRange: [0, 5000],
          severity: "high",
          reason: `Unusually high debit count detected for USD. Expected max 5000, found ${subtotal.count}. This could indicate a data entry error or an unexpected surge in specific transaction types.`,
          suggestedAction: "Investigate transaction patterns and originators. Cross-reference with historical data for similar periods using CDBI's Gemini-powered historical analysis.",
          timestamp: now,
          sourceModel: "CDBI-Gemini-AnomalyDetector-v2",
        });
      }
      if (subtotal.amount > 1000000) {
        anomalies.push({
          id: `anomaly-amount-${index}-${batchId}`,
          currency: subtotal.currency,
          direction: subtotal.direction,
          metric: "amount",
          subtotal: subtotal,
          detectedValue: subtotal.amount,
          expectedRange: [0, 1000000],
          severity: "critical",
          reason: `Significantly high debit amount detected for USD. Expected max 1M, found ${subtotal.amount}. This is a critical alert, potentially indicating fraud, error, or a major system event.`,
          suggestedAction:
            "Immediate review of the batch and associated accounts for fraud prevention. Halt processing if necessary. Utilize CDBI's fraud detection AI for deeper analysis.",
          timestamp: now,
          sourceModel: "CDBI-Gemini-AnomalyDetector-v2",
        });
      }
    }
  });

  return anomalies;
};

/**
 * Simulated AI service to predict future batch trends.
 * @param batchTotals - Historical batch data (for a real model, this would be much larger and potentially fetched from a data lake).
 * @param batchType - The type of batch for prediction.
 * @returns A promise resolving to a PredictionReport.
 */
export const cdbiAIPredictiveService = async (
  batchTotals: BatchSubtotal[],
  batchType: BatchTypeEnum,
): Promise<PredictionReport> => {
  console.log(
    `CDBI AI: Simulating predictive analytics for batch type: ${batchType}`,
  );
  await new Promise((resolve) => setTimeout(resolve, 1200));

  // In a real scenario, this would leverage Gemini's time-series forecasting capabilities
  // based on vast historical data, external market indicators, and seasonal adjustments.
  const totalCount = batchTotals.reduce(
    (acc, curr) => acc + (curr.count || 0),
    0,
  );
  const totalAmount = batchTotals.reduce(
    (acc, curr) => acc + (curr.amount || 0),
    0,
  );

  // Simulate slight variance for future prediction
  const predictedCount = totalCount * (1 + Math.random() * 0.1 - 0.05); // +/- 5% variance
  const predictedAmount = totalAmount * (1 + Math.random() * 0.08 - 0.04); // +/- 4% variance

  return {
    batchType: batchType,
    currency: "USD", // Example, in a real system this would be dynamic or multi-currency
    predictedVolumeCount: Math.round(predictedCount),
    predictedVolumeAmount: parseFloat(predictedAmount.toFixed(2)),
    confidenceScore: 92.5, // High confidence for simulation
    predictionHorizon: "next 24 hours",
    underlyingModel: "CDBI-Gemini-TimeSeries-v3",
    trendsDetected: ["Stable daily volume", "Potential slight increase in transaction velocity"],
  };
};

/**
 * Simulated AI service to generate comprehensive insights and recommendations.
 * Integrates results from anomaly detection and predictive analytics using Gemini's reasoning capabilities.
 * @param batchTotals - The original batch data.
 * @param anomalies - Detected anomalies.
 * @param predictions - Predictive insights.
 * @returns A promise resolving to BatchAISuggestions.
 */
export const cdbiAIInsightGeneratorService = async (
  batchTotals: BatchSubtotal[],
  anomalies: AnomalyReport[],
  predictions: PredictionReport,
): Promise<BatchAISuggestions> => {
  console.log(`CDBI AI: Generating comprehensive insights.`);
  await new Promise((resolve) => setTimeout(resolve, 1000));

  let overallSentiment: "positive" | "neutral" | "negative" = "neutral";
  let riskScore = 0;
  const keyInsights: string[] = [];
  const actionableRecommendations: string[] = [];

  if (anomalies.length > 0) {
    overallSentiment = "negative";
    riskScore += anomalies.filter((a) => a.severity === "high").length * 20;
    riskScore +=
      anomalies.filter((a) => a.severity === "critical").length * 40;
    keyInsights.push(
      `Detected ${anomalies.length} potential anomalies in the batch, some with high/critical severity, requiring immediate attention.`,
    );
    anomalies.forEach((anomaly) =>
      actionableRecommendations.push(
        `- Anomaly in ${anomaly.currency} ${anomaly.direction} ${anomaly.metric}: ${anomaly.suggestedAction}`,
      ),
    );
  } else {
    keyInsights.push("No significant anomalies detected in the current batch, indicating smooth processing based on established patterns.");
  }

  keyInsights.push(
    `Next ${predictions.predictionHorizon} prediction: Volume count ~${predictions.predictedVolumeCount}, Amount ~${predictions.predictedVolumeAmount} ${predictions.currency}.`,
  );
  actionableRecommendations.push(
    `Monitor predicted volumes for ${predictions.batchType} transactions over the ${predictions.predictionHorizon} to ensure resource alignment and prevent bottlenecks.`,
  );

  if (riskScore > 50) {
    actionableRecommendations.push(
      "Prioritize review of high-risk transactions identified by CDBI's AI for immediate mitigation actions and compliance checks.",
    );
  } else if (riskScore > 0) {
    actionableRecommendations.push(
      "Regularly review anomaly reports and adjust batch processing rules or thresholds as needed, leveraging CDBI's adaptive learning capabilities.",
    );
  } else {
    overallSentiment = "positive";
    actionableRecommendations.push(
      "Continue standard batch processing. Leverage predictive insights for optimal resource planning and explore opportunities for automation based on consistent performance.",
    );
  }

  const totalAmount = batchTotals.reduce(
    (acc, curr) => acc + (curr.amount || 0),
    0,
  );
  const totalCount = batchTotals.reduce(
    (acc, curr) => acc + (curr.count || 0),
    0,
  );

  const summary = `CDBI AI has processed batch ${batchTotals[0]?.batchId || "N/A"} (${predictions.batchType}) totaling ${totalCount} transactions with an aggregate amount of ${totalAmount}. ${anomalies.length > 0 ? `${anomalies.length} potential issues were identified, raising the overall risk profile.` : "The batch appears to be within normal operational parameters, indicating high data integrity and process efficiency."} Future predictions indicate stable activity for the specified horizon.`;

  return {
    overallSentiment,
    summary,
    keyInsights,
    actionableRecommendations,
    riskScore: Math.min(100, riskScore), // Cap risk score at 100
    geminiModelVersion: "CDBI-Gemini-InsightEngine-v5",
  };
};

/**
 * Simulated service to generate KPIs from AI outputs.
 * @param anomalies - Anomaly reports.
 * @param predictions - Prediction reports.
 * @param insights - General AI insights.
 * @returns An array of KPIs.
 */
export const cdbiKPIGeneratorService = async (
  anomalies: AnomalyReport[],
  predictions: PredictionReport,
  insights: BatchAISuggestions,
): Promise<KPI[]> => {
  console.log(`CDBI AI: Generating KPIs.`);
  await new Promise((resolve) => setTimeout(resolve, 800));
  const now = new Date().toLocaleString();

  const kpis: KPI[] = [];

  // KPI 1: Total Anomalies Detected
  kpis.push({
    id: "kpi-anomaly-count",
    name: "Total Anomalies Detected",
    value: anomalies.length,
    unit: "events",
    trend: anomalies.length > 0 ? "up" : "stable", // Simplified trend based on presence
    lastUpdate: now,
    description: "Number of irregular patterns identified by CDBI AI in the batch, indicating potential deviations from normal operations.",
    linkedChartId: "chart-anomaly-trend",
    aiSource: "CDBI Anomaly Detection AI",
  });

  // KPI 2: Critical Anomaly Rate
  const criticalAnomalies = anomalies.filter(
    (a) => a.severity === "critical",
  ).length;
  kpis.push({
    id: "kpi-critical-anomaly-rate",
    name: "Critical Anomaly Rate",
    value: `${((criticalAnomalies / (anomalies.length || 1)) * 100).toFixed(
      2,
    )}%`,
    unit: "%",
    trend: criticalAnomalies > 0 ? "up" : "stable",
    lastUpdate: now,
    description: "Percentage of detected anomalies classified as 'critical', highlighting high-priority issues that demand immediate attention.",
    linkedChartId: "chart-anomaly-severity-distribution",
    aiSource: "CDBI Anomaly Detection AI",
  });

  // KPI 3: Predicted Next-Day Volume Count
  kpis.push({
    id: "kpi-predicted-volume-count",
    name: `Predicted ${predictions.predictionHorizon} Volume (Count)`,
    value: predictions.predictedVolumeCount,
    unit: "transactions",
    trend: "stable", // Requires historical comparison for a real trend, simplified here
    lastUpdate: now,
    description: `CDBI AI's forecast for transaction count in the ${predictions.predictionHorizon}, critical for capacity planning.`,
    linkedChartId: "chart-volume-prediction",
    aiSource: "CDBI Predictive AI",
  });

  // KPI 4: Predicted Next-Day Volume Amount
  kpis.push({
    id: "kpi-predicted-volume-amount",
    name: `Predicted ${predictions.predictionHorizon} Volume (Amount)`,
    value: predictions.predictedVolumeAmount,
    unit: predictions.currency,
    trend: "stable", // Requires historical comparison for a real trend, simplified here
    lastUpdate: now,
    description: `CDBI AI's forecast for aggregate transaction amount in the ${predictions.predictionHorizon}, crucial for liquidity management.`,
    linkedChartId: "chart-amount-prediction",
    aiSource: "CDBI Predictive AI",
  });

  // KPI 5: Overall Batch Risk Score
  kpis.push({
    id: "kpi-overall-risk-score",
    name: "Overall Batch Risk Score",
    value: insights.riskScore,
    unit: "/100",
    trend: insights.riskScore > 50 ? "up" : "down", // Simplified, based on current score
    lastUpdate: now,
    description: "CDBI AI's synthesized risk assessment for the current batch, incorporating anomalies and predictive elements. Higher score implies higher risk.",
    linkedChartId: "chart-risk-score-history",
    aiSource: "CDBI Insight Engine AI",
  });

  // KPI 6: Average Anomaly Severity (Custom KPI)
  const totalSeverityScore = anomalies.reduce((sum, a) => {
    switch (a.severity) {
      case "low": return sum + 1;
      case "medium": return sum + 3;
      case "high": return sum + 5;
      case "critical": return sum + 10;
      default: return sum;
    }
  }, 0);
  const avgSeverity = anomalies.length > 0 ? (totalSeverityScore / anomalies.length).toFixed(2) : "0";
  kpis.push({
    id: "kpi-avg-anomaly-severity",
    name: "Average Anomaly Severity",
    value: avgSeverity,
    unit: "/10",
    trend: parseFloat(avgSeverity) > 2 ? "up" : "stable", // A simple threshold
    lastUpdate: now,
    description: "The average severity index of detected anomalies, providing a quick health check of batch quality.",
    linkedChartId: "chart-avg-severity-trend",
    aiSource: "CDBI Anomaly Detection AI",
  });


  return kpis;
};

/**
 * A placeholder component to represent a chart dynamically generated or interpreted by Gemini.
 * @param config - Configuration for the chart.
 * @export
 */
export const CDBIChart: React.FC<{ config: CDBIChartConfig }> = ({
  config,
}) => {
  // In a real application, this would integrate with a charting library (e.g., Chart.js, Recharts, D3)
  // and potentially use Gemini's visual generation capabilities or natural language querying
  // to dynamically create or interpret the chart based on data and `geminiPrompt`.

  // Define some conceptual CDBI colors for visual consistency if a full CSS framework is not present
  const CDBI_COLORS = {
    primary: "#007bff", // A strong blue
    primaryDark: "#0056b3",
    primaryLight: "#e6f2ff",
    secondary: "#28a745", // A vibrant green
    secondaryLight: "#e7faeb",
    tertiary: "#6c757d", // A neutral grey
    lightBlue: "#f0f8ff", // A very light blue
    textDark: "#333333",
    textMedium: "#666666",
  };

  const chartContainerStyle: React.CSSProperties = {
    width: "100%",
    minHeight: "250px", // Ensure minimum height
    background: CDBI_COLORS.lightBlue,
    borderRadius: "8px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    color: CDBI_COLORS.textMedium,
    fontSize: "0.9em",
    border: `1px dashed ${CDBI_COLORS.tertiary}`,
    padding: "15px",
    boxSizing: "border-box", // Include padding in width/height
  };

  const titleStyle: React.CSSProperties = {
    fontSize: "1.1em",
    fontWeight: "600",
    color: CDBI_COLORS.textDark,
    marginBottom: "10px",
  };

  const detailStyle: React.CSSProperties = {
    fontSize: "0.85em",
    marginTop: "5px",
  };

  return (
    <Card className="mb-4">
      <div style={chartContainerStyle}>
        <span style={titleStyle}>📊 {config.title} (CDBI AI & Gemini) 📊</span>
        <span style={detailStyle}>
          Chart Type: {config.type.charAt(0).toUpperCase() + config.type.slice(1)}{" "}
          | Data Points:{" "}
          {config.dataSeries.map((s) => s.label).join(", ") || "N/A"}
        </span>
        {config.geminiPrompt && (
          <span style={{ ...detailStyle, color: CDBI_COLORS.tertiary }}>
            Gemini Prompt: "{config.geminiPrompt}"
          </span>
        )}
        <p className="text-center mt-3 text-sm italic">
          This chart represents a dynamic visualization generated and interpreted by CDBI's AI, powered by Gemini. Real-time data feeds and contextual intelligence enable adaptive insights.
        </p>
      </div>
    </Card>
  );
};

// --- End CDBI AI Core Module ---

// --- Internal UI Components (to satisfy "self-contained" and "no dependencies" for new UI elements without modifying existing imports) ---
// These components are defined locally within this file. In a larger project, they would typically
// be part of a shared UI library (`../../common/ui-components`) or a design system.
// They use conceptual class names that would work with frameworks like Tailwind CSS.

interface CardProps {
  children: React.ReactNode;
  className?: string;
}
const Card: React.FC<CardProps> = ({ children, className }) => (
  <div
    className={`bg-white rounded-lg shadow-md p-6 ${className || ""}`}
    style={{ border: "1px solid #e0e0e0" }} // Inline style for guaranteed border
  >
    {children}
  </div>
);

interface AlertProps {
  type: "info" | "success" | "warning" | "danger";
  title: string;
  children: React.ReactNode;
}
const Alert: React.FC<AlertProps> = ({ type, title, children }) => {
  let bgColor, borderColor, textColor;
  // Using direct color values for self-containment without relying on Tailwind config
  switch (type) {
    case "info":
      bgColor = "#e6f2ff"; // CDBI_COLORS.primaryLight
      borderColor = "#007bff"; // CDBI_COLORS.primary
      textColor = "#0056b3"; // CDBI_COLORS.primaryDark
      break;
    case "success":
      bgColor = "#e7faeb"; // CDBI_COLORS.secondaryLight
      borderColor = "#28a745"; // CDBI_COLORS.secondary
      textColor = "#1e7e34"; // Darker green
      break;
    case "warning":
      bgColor = "#fff3cd"; // Light yellow
      borderColor = "#ffc107"; // Yellow
      textColor = "#856404"; // Dark yellow
      break;
    case "danger":
      bgColor = "#f8d7da"; // Light red
      borderColor = "#dc3545"; // Red
      textColor = "#721c24"; // Dark red
      break;
  }
  return (
    <div
      className={`border-l-4 p-4 rounded-md`}
      style={{ backgroundColor: bgColor, borderColor: borderColor, color: textColor }}
      role="alert"
    >
      <p className="font-bold">{title}</p>
      <div className="mt-1 text-sm">{children}</div>
    </div>
  );
};

interface BadgeProps {
  type: "info" | "success" | "warning" | "danger" | "primary" | "secondary";
  children: React.ReactNode;
  className?: string;
}
const Badge: React.FC<BadgeProps> = ({ type, children, className }) => {
  let bgColor, textColor;
  switch (type) {
    case "info":
      bgColor = "#e6f2ff"; textColor = "#0056b3";
      break;
    case "success":
      bgColor = "#e7faeb"; textColor = "#1e7e34";
      break;
    case "warning":
      bgColor = "#fff3cd"; textColor = "#856404";
      break;
    case "danger":
      bgColor = "#f8d7da"; textColor = "#721c24";
      break;
    case "primary": // CDBI specific colors
      bgColor = "#e6f2ff"; textColor = "#007bff";
      break;
    case "secondary": // CDBI specific colors
      bgColor = "#e7faeb"; textColor = "#28a745";
      break;
  }
  return (
    <span
      className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${className || ""}`}
      style={{ backgroundColor: bgColor, color: textColor }}
    >
      {children}
    </span>
  );
};

const Spinner: React.FC<{ className?: string }> = ({ className }) => (
  <svg
    className={`animate-spin h-5 w-5 text-gray-500 ${className || ""}`}
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
  >
    <circle
      className="opacity-25"
      cx="12"
      cy="12"
      r="10"
      stroke="currentColor"
      strokeWidth="4"
    ></circle>
    <path
      className="opacity-75"
      fill="currentColor"
      d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
    ></path>
  </svg>
);

// --- End Internal UI Components ---

const MAPPING = {
  currency: "Currency",
  direction: "Direction",
  amount: "Amount",
  count: "Count",
};

interface FileTransferBatchTotalsViewProps {
  batchId: string;
  batchType: BatchTypeEnum;
}

/**
 * Formats batch subtotal data for display in the IndexTable.
 * Enhances count to ensure it's always rendered as a ReactNode.
 * @param batchTotals - Array of BatchSubtotal objects.
 * @returns Formatted array suitable for IndexTable.
 */
function formatBatchTotals(batchTotals: BatchSubtotal[]) {
  return batchTotals.map((batchSubtotal: BatchSubtotal) => ({
    ...batchSubtotal,
    count: <>{batchSubtotal.count || 0}</>, // Ensure count is always a valid ReactNode
  }));
}

/**
 * The main component for viewing file transfer batch totals with integrated CDBI AI capabilities.
 * This component fetches batch data and then uses CDBI's AI services (simulated)
 * to provide anomaly detection, predictive analytics, comprehensive insights, and KPIs.
 * It's designed for commercial-grade applications, serving banks, financial institutions,
 * e-commerce, logistics, and any entity managing high-volume data transfers.
 */
function FileTransferBatchTotalsView({
  batchId,
  batchType,
}: FileTransferBatchTotalsViewProps) {
  const { loading, data, error } = useFileTransferBatchTotalsQuery({
    skip: !batchId || !batchType,
    variables: { batchId, batchType },
  });

  const batchTotals =
    loading || !data || error ? [] : data?.fileTransferCalculateBatchTotals;

  // --- CDBI AI State Management ---
  const [aiLoading, setAiLoading] = useState(false);
  const [anomalies, setAnomalies] = useState<AnomalyReport[]>([]);
  const [predictions, setPredictions] = useState<PredictionReport | null>(null);
  const [insights, setInsights] = useState<BatchAISuggestions | null>(null);
  const [kpis, setKpis] = useState<KPI[]>([]);
  const [charts, setCharts] = useState<CDBIChartConfig[]>([]);
  const [aiError, setAiError] = useState<string | null>(null);

  // Effect hook to trigger AI analysis when batch data is available
  useEffect(() => {
    const runAIAnalysis = async () => {
      // Skip AI analysis if there's no valid batch data or if data is still loading/errored
      if (!batchId || !batchType || !batchTotals || batchTotals.length === 0 || loading || error) {
        setAnomalies([]);
        setPredictions(null);
        setInsights(null);
        setKpis([]);
        setCharts([]);
        setAiError(null);
        if (!batchId || !batchType) {
          setAiError("Please select a valid Batch ID and Type to enable CDBI AI analysis.");
        }
        return;
      }

      setAiLoading(true);
      setAiError(null);
      try {
        // Run core AI services in parallel for efficiency
        const [detectedAnomalies, generatedPredictions] = await Promise.all([
          cdbiAIAnomalyDetectionService(batchTotals, batchId, batchType),
          cdbiAIPredictiveService(batchTotals, batchType),
        ]);

        // Generate comprehensive insights by combining results from initial AI runs
        const generatedInsights = await cdbiAIInsightGeneratorService(
          batchTotals,
          detectedAnomalies,
          generatedPredictions,
        );

        // Generate Key Performance Indicators (KPIs) based on all AI outputs
        const generatedKpis = await cdbiKPIGeneratorService(
          detectedAnomalies,
          generatedPredictions,
          generatedInsights,
        );

        // Dynamically create chart configurations linked to KPIs for visualization
        const generatedCharts: CDBIChartConfig[] = generatedKpis.map((kpi) => ({
          id: kpi.linkedChartId,
          title: `${kpi.name} Performance`,
          type: "line", // Defaulting to line for trend, but could be dynamic based on KPI
          dataSeries: [{ label: kpi.name, values: [kpi.value as number] }], // Simplified to current value; real charts would use historical data
          labels: [kpi.lastUpdate], // Simplified to last update timestamp
          geminiPrompt: `Visualize the trend for ${kpi.name} (${kpi.id}) for batch type ${batchType} and provide an explanation of its significance.`,
        }));

        setAnomalies(detectedAnomalies);
        setPredictions(generatedPredictions);
        setInsights(generatedInsights);
        setKpis(generatedKpis);
        setCharts(generatedCharts);
      } catch (err) {
        console.error("CDBI AI analysis failed:", err);
        setAiError(`CDBI AI analysis encountered an error: ${err instanceof Error ? err.message : String(err)}. Please try refreshing.`);
      } finally {
        setAiLoading(false);
      }
    };

    runAIAnalysis();
  }, [batchTotals, batchId, batchType, loading, error]); // Dependencies for re-running AI analysis

  return (
    <div className="p-4 space-y-6">
      <Card className="mb-6">
        <h2 className="text-2xl font-bold mb-4" style={{ color: "#007bff" /* CDBI primary */ }}>
          CDBI File Transfer Batch Totals Overview{" "}
          <Badge type="primary" className="ml-2">
            AI Powered
          </Badge>
        </h2>
        <p className="text-gray-700">
          This advanced view provides a comprehensive breakdown of file transfer
          batch totals, augmented with real-time AI analysis from CDBI's
          cognitive engine. Leverage insights for enhanced decision-making,
          proactive risk management, and optimized operations across various
          industries, including finance, logistics, healthcare, and public sector.
        </p>
      </Card>

      {error && (
        <Alert type="danger" title="Data Fetch Error">
          Failed to load batch totals. Please check your connection or try
          again. Detailed Error: {error.message}
        </Alert>
      )}

      {loading ? (
        <Card className="mt-4">
          <IndexTableSkeletonLoader headers={Object.keys(MAPPING)} numRows={4} />
          <div className="mt-4 flex items-center justify-center">
            <Spinner />{" "}
            <span className="ml-2" style={{ color: "#007bff" /* CDBI primary */ }}>
              Loading batch data and initializing CDBI AI analysis...
            </span>
          </div>
        </Card>
      ) : batchTotals.length === 0 && !aiError ? ( // Only show warning if no AI error, otherwise AI error takes precedence
        <Alert type="warning" title="No Batch Data">
          No batch totals found for the selected batch ID and type. CDBI AI analysis requires valid batch data.
        </Alert>
      ) : (
        <>
          <Card>
            <h3 className="text-xl font-semibold mb-4" style={{ color: "#6c757d" /* CDBI tertiary */ }}>
              Raw Batch Totals
            </h3>
            <IndexTable
              data={formatBatchTotals(batchTotals)}
              dataMapping={MAPPING}
            />
          </Card>

          {aiError && (
            <Alert type="danger" title="CDBI AI Analysis Failed">
              {aiError}
              {batchTotals.length > 0 && <p className="mt-2">Despite an error in AI analysis, raw batch data is displayed above.</p>}
            </Alert>
          )}

          {aiLoading && (
            <Card className="flex items-center justify-center p-6" style={{ backgroundColor: "#f0f8ff" /* CDBI light blue */ }}>
              <Spinner className="w-8 h-8" style={{ color: "#007bff" /* CDBI primary */ }} />
              <span className="ml-4 text-lg font-medium" style={{ color: "#007bff" /* CDBI primary */ }}>
                CDBI AI is analyzing batch data with Gemini's advanced cognitive engine...
              </span>
            </Card>
          )}

          {!aiLoading && insights && (
            <Card>
              <h3 className="text-xl font-semibold mb-4 flex items-center" style={{ color: "#6c757d" /* CDBI tertiary */ }}>
                CDBI AI Insights & Recommendations
                <Badge
                  type={
                    insights.overallSentiment === "positive"
                      ? "success"
                      : insights.overallSentiment === "negative"
                        ? "danger"
                        : "warning"
                  }
                  className="ml-2"
                >
                  {insights.overallSentiment.toUpperCase()}
                </Badge>
                <Badge type="info" className="ml-2">
                  Risk Score: {insights.riskScore}/100
                </Badge>
              </h3>
              <p className="mb-3 text-gray-700 font-medium leading-relaxed">
                {insights.summary}
              </p>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <h4 className="text-lg font-medium mb-2" style={{ color: "#007bff" /* CDBI primary */ }}>
                    Key Insights
                  </h4>
                  <ul className="list-disc list-inside text-gray-700 space-y-1">
                    {insights.keyInsights.map((insight, i) => (
                      <li key={`insight-${i}`}>{insight}</li>
                    ))}
                  </ul>
                </div>
                <div>
                  <h4 className="text-lg font-medium mb-2" style={{ color: "#007bff" /* CDBI primary */ }}>
                    Actionable Recommendations
                  </h4>
                  <ul className="list-disc list-inside text-gray-700 space-y-1">
                    {insights.actionableRecommendations.map((rec, i) => (
                      <li key={`rec-${i}`}>{rec}</li>
                    ))}
                  </ul>
                </div>
              </div>
              <p className="text-sm text-gray-500 mt-4">
                Powered by CDBI's Gemini-integrated Insight Engine (v
                {insights.geminiModelVersion.split("-").pop()}) for advanced reasoning and contextual understanding.
              </p>
            </Card>
          )}

          {!aiLoading && anomalies.length > 0 && (
            <Card>
              <h3 className="text-xl font-semibold mb-4" style={{ color: "#6c757d" /* CDBI tertiary */ }}>
                AI Anomaly Detection
              </h3>
              <div className="space-y-4">
                {anomalies.map((anomaly) => (
                  <Alert
                    key={anomaly.id}
                    type={
                      anomaly.severity === "critical"
                        ? "danger"
                        : anomaly.severity === "high"
                          ? "warning"
                          : "info"
                    }
                    title={`Anomaly Detected: ${anomaly.metric.toUpperCase()} in ${anomaly.currency} ${anomaly.direction} (Severity: ${anomaly.severity.toUpperCase()})`}
                  >
                    <p className="font-medium leading-relaxed">{anomaly.reason}</p>
                    <p className="text-sm mt-2">
                      Detected Value:{" "}
                      <span className="font-bold">{anomaly.detectedValue}</span>{" "}
                      (Expected Range: {anomaly.expectedRange[0]} -{" "}
                      {anomaly.expectedRange[1]})
                    </p>
                    <p className="text-sm mt-1">
                      Suggested Action: {anomaly.suggestedAction}
                    </p>
                    <p className="text-xs text-gray-600 mt-2">
                      Reported: {new Date(anomaly.timestamp).toLocaleString()}{" "}
                      | Source: {anomaly.sourceModel}
                    </p>
                  </Alert>
                ))}
              </div>
            </Card>
          )}

          {!aiLoading && predictions && (
            <Card>
              <h3 className="text-xl font-semibold mb-4" style={{ color: "#6c757d" /* CDBI tertiary */ }}>
                AI Predictive Analytics
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-gray-700">
                <div>
                  <p className="mb-2">
                    <span className="font-medium" style={{ color: "#007bff" /* CDBI primary */ }}>Predicted Volume Count:</span>{" "}
                    <span className="text-lg font-semibold">{predictions.predictedVolumeCount}</span> transactions
                  </p>
                  <p className="mb-2">
                    <span className="font-medium" style={{ color: "#007bff" /* CDBI primary */ }}>Predicted Volume Amount:</span>{" "}
                    <span className="text-lg font-semibold">{predictions.predictedVolumeAmount}</span>{" "}
                    {predictions.currency || "USD"}
                  </p>
                  <p className="mb-2">
                    <span className="font-medium" style={{ color: "#007bff" /* CDBI primary */ }}>Confidence Score:</span>{" "}
                    <Badge type="success">
                      {predictions.confidenceScore.toFixed(1)}%
                    </Badge>
                  </p>
                </div>
                <div>
                  <p className="mb-2">
                    <span className="font-medium" style={{ color: "#007bff" /* CDBI primary */ }}>Prediction Horizon:</span>{" "}
                    {predictions.predictionHorizon}
                  </p>
                  <p className="mb-2">
                    <span className="font-medium" style={{ color: "#007bff" /* CDBI primary */ }}>Trends Detected:</span>{" "}
                    <span className="italic">{predictions.trendsDetected.join(", ")}</span>
                  </p>
                  <p className="text-sm text-gray-500 mt-2">
                    Model: {predictions.underlyingModel}
                  </p>
                </div>
              </div>
            </Card>
          )}

          {!aiLoading && kpis.length > 0 && (
            <Card>
              <h3 className="text-xl font-semibold mb-4" style={{ color: "#6c757d" /* CDBI tertiary */ }}>
                Key Performance Indicators (KPIs)
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
                {kpis.map((kpi) => (
                  <Card key={kpi.id} className="p-4" style={{ backgroundColor: "#f9f9f9", borderLeft: `4px solid ${kpi.trend === 'up' ? '#28a745' : kpi.trend === 'down' ? '#dc3545' : '#6c757d'}` /* CDBI secondary/danger/tertiary */ }}>
                    <p className="text-sm text-gray-500 uppercase">{kpi.aiSource}</p>
                    <p className="text-lg font-semibold mt-1">{kpi.name}</p>
                    <p className="text-3xl font-bold mt-2" style={{ color: "#007bff" /* CDBI primary */ }}>
                      {kpi.value}
                      {kpi.unit && <span className="text-xl ml-1">{kpi.unit}</span>}
                    </p>
                    <p className="text-sm text-gray-600 mt-1">
                      <span className="mr-1">
                        {kpi.trend === "up" && "⬆️"}
                        {kpi.trend === "down" && "⬇️"}
                        {kpi.trend === "stable" && "➡️"}
                      </span>
                      {kpi.description}
                    </p>
                    <p className="text-xs text-gray-500 mt-2">
                      Last Update: {kpi.lastUpdate}
                    </p>
                  </Card>
                ))}
              </div>
            </Card>
          )}

          {!aiLoading && charts.length > 0 && (
            <Card>
              <h3 className="text-xl font-semibold mb-4" style={{ color: "#6c757d" /* CDBI tertiary */ }}>
                CDBI AI & Gemini Powered Charts
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {charts.map((chartConfig) => (
                  <CDBIChart key={chartConfig.id} config={chartConfig} />
                ))}
              </div>
              <p className="text-sm text-gray-500 mt-4">
                These charts are dynamically generated and interpreted by
                CDBI's AI, leveraging Gemini's understanding of data context and
                user queries to provide actionable visual insights.
              </p>
            </Card>
          )}

          {!aiLoading &&
            !insights &&
            !anomalies.length &&
            !predictions &&
            !kpis.length &&
            batchTotals.length > 0 && ( // Only show this if batch data is present but AI couldn't generate insights
              <Alert type="info" title="No AI Insights Generated">
                CDBI AI analysis completed, but no specific anomalies, predictions,
                or insights were generated for this batch based on current models.
                This usually indicates the batch falls within normal operational parameters.
              </Alert>
            )}
        </>
      )}
      <div className="mt-8 text-center text-gray-500 text-sm">
        <p>
          CDBI AI - Cognitive Data-driven Business Intelligence Inc. ©{" "}
          {new Date().getFullYear()}
        </p>
        <p>
          Empowering real-world solutions with advanced AI, backed by Google's Gemini
          technology, to solve complex business challenges globally.
        </p>
      </div>
    </div>
  );
}

export default FileTransferBatchTotalsView;