// Copyright James Burvel Oâ€™Callaghan III
// President Citibank Demo Business Inc.

import React, { useState, useEffect, useCallback } from "react";
import {
  Label,
  SelectField,
  Autosuggest,
  Icon,
  Clickable,
  Spinner, // Assuming Spinner is available or implemented elsewhere in common/ui-components
} from "../../common/ui-components";

// --- New Interfaces and Types for AI-powered features ---

/**
 * Represents a confidence score and explanation from an AI model.
 * Exported for potential external consumption (e.g., in analytics modules).
 */
export interface AIConfidenceScore {
  score: number; // 0.0 to 1.0
  explanation: string;
}

/**
 * Represents a key performance indicator (KPI) related to AI reconciliation.
 * Exported for external consumption (e.g., a dashboard component).
 */
export interface AIReconciliationKPI {
  name: string;
  value: string | number;
  unit?: string;
  description: string;
  linkToGeminiChart?: string; // URL or identifier for a Gemini chart visualization
}

/**
 * Represents suggested parsing rules generated by AI.
 * Exported for external consumption (e.g., a rule management system).
 */
export interface AIParsingSuggestion {
  regex: string;
  confidence: AIConfidenceScore;
  exampleMatches: string[];
}

/**
 * Represents an advanced AI-powered transaction field option.
 * Exported for potential use in configuration or other UI components.
 */
export interface AIEnabledTransactionFieldOption {
  label: string;
  value: string;
  aiDescription: string; // How CDBI AI interprets/uses this field
}

/**
 * CDBIAIReconciliationService: A self-contained, conceptual AI service class.
 * This class encapsulates the AI logic for reconciliation, making it modular
 * and easily extensible. In a real-world application, this would interact
 * with backend AI/ML models via API calls. All methods are static to simplify
 * usage within a React component for demonstration.
 * Exported for potential integration with other application services.
 */
export class CDBIAIReconciliationService {
  /**
   * Simulates an AI predicting the best matcher for a given transaction context.
   * This function exemplifies an AI model analyzing unstructured transaction data
   * to suggest the most appropriate field for matching (e.g., vendor_id, description).
   * @param transactionContext - A string representation of the transaction data (e.g., raw description).
   * @returns A promise resolving to a suggested matcher and its confidence.
   */
  public static async predictBestMatcher(
    transactionContext: string | null | undefined,
  ): Promise<{ matcher: string; confidence: AIConfidenceScore }> {
    console.log(
      `CDBI GenAI: Analyzing transaction context for best matcher: ${transactionContext}`,
    );
    // Simulate network delay and AI processing time
    await new Promise((resolve) => setTimeout(resolve, 1500));

    if (!transactionContext) {
      return {
        matcher: "vendor_description", // Fallback to a common default
        confidence: { score: 0.6, explanation: "Default based on lack of sufficient context for CDBI AI." },
      };
    }

    // AI-powered logic simulation based on keywords and patterns
    const lowerContext = transactionContext.toLowerCase();
    let suggestedMatcher = "vendor_description";
    let confidenceScore = 0.8;
    let explanation = "CDBI AI prediction based on textual content analysis.";

    if (lowerContext.includes("id") || lowerContext.includes("account") || lowerContext.includes("ref")) {
      suggestedMatcher = "vendor_id";
      confidenceScore = 0.92;
      explanation = "High confidence for ID-based matching, CDBI AI detected numeric/alphanumeric identifier patterns.";
    } else if (lowerContext.includes("customer") || lowerContext.includes("client")) {
      suggestedMatcher = "vendor_customer_id";
      confidenceScore = 0.88;
      explanation = "CDBI AI suggested customer ID based on explicit customer/client references.";
    } else if (lowerContext.includes("unique") || lowerContext.match(/\b(uuid|guid)\b/)) {
      suggestedMatcher = "unique_vendor_id";
      confidenceScore = 0.91;
      explanation = "CDBI AI identified unique identifier patterns like UUIDs or GUIDs.";
    } else if (lowerContext.includes("payment") || lowerContext.includes("transfer")) {
        suggestedMatcher = "vendor_description"; // Often, these indicate the counterparty name
        confidenceScore = 0.85;
        explanation = "CDBI AI inferred vendor description from payment/transfer terms for counterparty identification.";
    }

    return {
      matcher: suggestedMatcher,
      confidence: { score: confidenceScore, explanation: explanation },
    };
  }

  /**
   * Simulates an AI generating a regular expression parser based on transaction data samples.
   * This is a sophisticated AI function that analyzes data patterns to propose
   * a regex suitable for extracting specific information from a transaction field.
   * @param transactionFieldSample - A sample string from the transaction field to analyze.
   * @returns A promise resolving to an AI parsing suggestion, including regex and examples.
   */
  public static async generateAIParser(
    transactionFieldSample: string | null | undefined,
  ): Promise<AIParsingSuggestion> {
    console.log(
      `CDBI GenAI: Generating parser for sample: ${transactionFieldSample}`,
    );
    await new Promise((resolve) => setTimeout(resolve, 2000));

    if (!transactionFieldSample || transactionFieldSample.trim() === "") {
      return {
        regex: "(.*)", // Generic fallback regex
        confidence: {
          score: 0.5,
          explanation: "CDBI GenAI requires a valid sample to generate specific patterns. Generic fallback applied.",
        },
        exampleMatches: [],
      };
    }

    // Simulate sophisticated regex generation based on common financial transaction patterns
    let regex = "(.*)"; // Default to catch-all
    let confidenceScore = 0.7;
    let exampleMatches: string[] = [];
    let explanation = "CDBI GenAI detected common patterns.";

    if (transactionFieldSample.match(/(INV|REF|PO|BILL)\s*[-_#]?\s*\d{6,}/i)) {
      // Invoice, Reference, PO, Bill numbers
      regex = /(INV|REF|PO|BILL)\s*[-_#]?\s*(\d{6,})/i.source;
      confidenceScore = 0.95;
      exampleMatches = ["INV-12345678", "REF#9876543", "PO 11223344"];
      explanation = "CDBI GenAI identified invoice/reference number patterns.";
    } else if (transactionFieldSample.match(/\b\d{4}[ -]?\d{4}[ -]?\d{4}[ -]?\d{4}\b/)) {
      // Credit card numbers (hypothetically, in a masked form or for internal systems)
      regex = /\b(\d{4}[ -]?\d{4}[ -]?\d{4}[ -]?\d{4})\b/.source;
      confidenceScore = 0.90;
      exampleMatches = ["1234-5678-9012-3456"];
      explanation = "CDBI GenAI recognized masked credit card/account numbers.";
    } else if (transactionFieldSample.match(/(payment to|from|txn with)\s+([A-Z0-9\s.,&'-]+)/i)) {
      // Extracting company names or counterparties
      regex = /(payment to|from|txn with)\s+([A-Z0-9\s.,&'-]+)/i.source;
      confidenceScore = 0.88;
      exampleMatches = ["payment to CDBI Solutions Inc", "txn with Example Corp"];
      explanation = "CDBI GenAI parsed transaction narration for counterparty names.";
    } else if (transactionFieldSample.match(/\$(?:\d{1,3}(?:,\d{3})*|\d+)(?:\.\d{2})?/)) {
      // Extracting currency amounts
      regex = /\$(?:\d{1,3}(?:,\d{3})*|\d+)(?:\.\d{2})?/.source;
      confidenceScore = 0.80;
      exampleMatches = ["$1,234.56", "$789"];
      explanation = "CDBI GenAI identified currency amount patterns.";
    } else {
        explanation = "CDBI GenAI applied a general pattern; consider refining manually.";
    }

    return {
      regex: regex,
      confidence: {
        score: confidenceScore,
        explanation: explanation,
      },
      exampleMatches: exampleMatches,
    };
  }

  /**
   * Simulates fetching AI-driven Key Performance Indicators (KPIs) for reconciliation.
   * This provides a high-level overview of the effectiveness and performance
   * of the AI systems in real-time. KPIs are linked to a conceptual "Gemini AI Dashboard".
   * @returns A promise resolving to an array of AIReconciliationKPI.
   */
  public static async getAIReconciliationKPIs(): Promise<AIReconciliationKPI[]> {
    console.log("CDBI GenAI: Fetching reconciliation KPIs for Gemini AI Dashboard.");
    await new Promise((resolve) => setTimeout(resolve, 1000));

    return [
      {
        name: "AI Match Confidence (Avg)",
        value: (Math.random() * 0.15 + 0.82).toFixed(2), // 0.82 - 0.97
        unit: "",
        description: "Average confidence score of AI-assisted transaction matches over the last 24 hours.",
        linkToGeminiChart: "https://gemini.cdbi.ai/metrics/match-confidence",
      },
      {
        name: "Auto-Parse Rate (Daily)",
        value: (Math.floor(Math.random() * 15) + 85), // 85-100%
        unit: "%",
        description: "Percentage of transactions automatically parsed by CDBI AI-generated rules daily.",
        linkToGeminiChart: "https://gemini.cdbi.ai/metrics/auto-parse-rate",
      },
      {
        name: "Anomaly Detection Alerts",
        value: Math.floor(Math.random() * 3), // Low number implies good performance
        description: "Number of potential reconciliation anomalies detected by CDBI AI in the last 24h, requiring review.",
        linkToGeminiChart: "https://gemini.cdbi.ai/metrics/anomaly-alerts",
      },
      {
        name: "Rule Efficiency Score",
        value: (Math.random() * 0.18 + 0.78).toFixed(2), // 0.78 - 0.96
        description: "CDBI AI-driven score for the overall effectiveness and precision of current parsing and matching rules.",
        linkToGeminiChart: "https://gemini.cdbi.ai/metrics/rule-efficiency",
      },
      {
        name: "Human Review Reduction",
        value: (Math.floor(Math.random() * 10) + 75), // 75-85%
        unit: "%",
        description: "Percentage reduction in manual reconciliation review tasks due to CDBI AI automation.",
        linkToGeminiChart: "https://gemini.cdbi.ai/metrics/human-review-reduction",
      },
      {
        name: "Real-time Processing Latency",
        value: (Math.random() * 0.5 + 1.0).toFixed(1), // 1.0-1.5 seconds
        unit: "s",
        description: "Average time taken by CDBI AI to process and suggest matches for a new transaction.",
        linkToGeminiChart: "https://gemini.cdbi.ai/metrics/processing-latency",
      },
    ];
  }
}

// --- Original Props Extended and AI-related Props Added ---
interface FromTransactionReconciliationMatchResultProps {
  selectField: string | null | undefined;
  selectFieldOptions: {
    value: string;
    label: string;
  }[];
  suggestedMatcher: string | null | undefined; // Original suggestion, now potentially augmented by AI
  matcher: string | null;
  transactionField: string | null | undefined; // The raw value of the selected transaction field
  transactionFieldString: string | null | undefined; // Display string, used as context for AI
  parser: string | null | undefined;
  showParser: boolean;
  callback: (
    matchResultType: string | null | undefined,
    matcher: string | null | undefined,
    parser: string | null | undefined,
    showParser: boolean | null | undefined,
    transactionField: string | null | undefined,
    startDate: string | null,
    endDate: string | null,
  ) => void;
  // New prop to enable/disable AI predictions, defaults to true
  enableAIPredictions?: boolean;
}

function FromTransactionReconciliationMatchResult({
  selectField,
  selectFieldOptions,
  matcher,
  parser,
  showParser,
  transactionField,
  transactionFieldString,
  suggestedMatcher,
  callback,
  enableAIPredictions = true, // Default to true as per "AI-powered everywhere" directive
}: FromTransactionReconciliationMatchResultProps) {
  // State for managing AI operations and their results
  const [aiLoadingMatcher, setAiLoadingMatcher] = useState(false);
  const [aiLoadingParser, setAiLoadingParser] = useState(false);
  const [aiSuggestedMatcherInternal, setAiSuggestedMatcherInternal] = useState<string | null>(null);
  const [aiSuggestedParserInternal, setAiSuggestedParserInternal] = useState<AIParsingSuggestion | null>(null);
  const [aiMatcherConfidence, setAiMatcherConfidence] = useState<AIConfidenceScore | null>(null);
  const [kpis, setKpis] = useState<AIReconciliationKPI[]>([]);
  const [kpisLoading, setKpisLoading] = useState(true);

  // Enhanced transaction field options with CDBI AI descriptions
  const aiEnabledTransactionFieldOptions: AIEnabledTransactionFieldOption[] = [
    {
      label: "vendor_description (CDBI AI Semantic Analysis)",
      value: "vendor_description",
      aiDescription: "Utilizes CDBI's advanced Natural Language Processing (NLP) to find vendor names and descriptions, ideal for fuzzy matching and understanding transactional context.",
    },
    {
      label: "vendor_id (CDBI AI Pattern Recognition)",
      value: "vendor_id",
      aiDescription: "Optimized by CDBI AI for identifying structured vendor IDs through sophisticated pattern matching, data validation, and lookup against known vendor registries.",
    },
    {
      label: "unique_vendor_id (CDBI AI Anomaly & Uniqueness Check)",
      value: "unique_vendor_id",
      aiDescription: "Applies CDBI AI to detect truly unique identifiers across vast datasets, cross-referencing against known entities and spotting potential duplicates or anomalies.",
    },
    {
      label: "vendor_customer_id (CDBI AI Relationship Mapping)",
      value: "vendor_customer_id",
      aiDescription: "Leverages CDBI AI to map customer identifiers, linking transactions to specific customer relationships and historical interactions for enhanced reconciliation.",
    },
  ];

  // Map AI-enabled options back to the format expected by SelectField
  const transactionFieldOptions = aiEnabledTransactionFieldOptions.map(opt => ({
    label: opt.label,
    value: opt.value
  }));


  // --- AI Prediction Effects ---

  // Effect to fetch AI-predicted matcher when relevant props change
  useEffect(() => {
    if (enableAIPredictions && transactionFieldString) {
      setAiLoadingMatcher(true);
      CDBIAIReconciliationService.predictBestMatcher(transactionFieldString)
        .then((prediction) => {
          setAiSuggestedMatcherInternal(prediction.matcher);
          setAiMatcherConfidence(prediction.confidence);
        })
        .catch((error) => {
          console.error("CDBI GenAI: Error predicting matcher:", error);
          setAiSuggestedMatcherInternal(null);
          setAiMatcherConfidence(null);
        })
        .finally(() => {
          setAiLoadingMatcher(false);
        });
    } else {
      setAiSuggestedMatcherInternal(null);
      setAiMatcherConfidence(null);
    }
  }, [enableAIPredictions, transactionFieldString]); // Rerun if AI is enabled or transaction string changes

  // Effect to fetch AI-driven KPIs periodically or on component mount
  useEffect(() => {
    const fetchKpis = async () => {
        setKpisLoading(true);
        try {
            const fetchedKpis = await CDBIAIReconciliationService.getAIReconciliationKPIs();
            setKpis(fetchedKpis);
        } catch (error) {
            console.error("CDBI GenAI: Error fetching KPIs:", error);
            setKpis([]);
        } finally {
            setKpisLoading(false);
        }
    };

    fetchKpis(); // Initial fetch
    // Optional: set an interval for real-time KPI updates
    const intervalId = setInterval(fetchKpis, 60000); // Refresh every minute
    return () => clearInterval(intervalId); // Cleanup on unmount
  }, []); // Run once on mount

  // --- Handlers for AI-driven actions ---

  const handleGenerateAIParser = useCallback(async () => {
    if (!transactionFieldString || transactionFieldString.trim() === "") {
      alert("CDBI GenAI needs a transaction field sample to generate a parser. Please ensure the 'Transaction Field' is populated with relevant data.");
      return;
    }
    setAiLoadingParser(true);
    try {
      const suggestion = await CDBIAIReconciliationService.generateAIParser(
        transactionFieldString,
      );
      setAiSuggestedParserInternal(suggestion);
      // Automatically apply the AI suggested parser to the form
      callback(
        selectField,
        matcher,
        suggestion.regex, // Apply the AI-generated regex
        true, // Ensure parser input is visible
        transactionField,
        null,
        null,
      );
    } catch (error) {
      console.error("CDBI GenAI: Error generating AI parser:", error);
      alert("CDBI GenAI failed to generate a parser. Please try manually or check the transaction field data.");
    } finally {
      setAiLoadingParser(false);
    }
  }, [callback, selectField, matcher, transactionField, transactionFieldString]);

  // Determine the effective suggested matcher for the Autosuggest component, prioritizing AI if enabled
  const effectiveSuggestedMatcherForAutosuggest = enableAIPredictions && aiSuggestedMatcherInternal
    ? aiSuggestedMatcherInternal
    : suggestedMatcher; // Fallback to original if AI is disabled or no AI suggestion

  // Prepare autosuggest options for the parser field, integrating AI-generated suggestions
  const autosuggestParserOptions = [];
  if (aiSuggestedParserInternal?.regex) {
    // AI-generated parser is the top priority suggestion
    autosuggestParserOptions.push({
      label: `CDBI AI Generated: ${aiSuggestedParserInternal.regex} (Confidence: ${(aiSuggestedParserInternal.confidence.score * 100).toFixed(0)}%)`,
      value: aiSuggestedParserInternal.regex,
    });
  }
  if (effectiveSuggestedMatcherForAutosuggest && effectiveSuggestedMatcherForAutosuggest !== aiSuggestedParserInternal?.regex) {
    // Include the general suggested matcher if it's different from the AI-generated parser regex
    autosuggestParserOptions.push({
      label: `Generic Suggested: ${effectiveSuggestedMatcherForAutosuggest}`,
      value: effectiveSuggestedMatcherForAutosuggest,
    });
  }
  if (autosuggestParserOptions.length === 0) {
    // If no specific suggestions, provide a generic AI-aware fallback
    autosuggestParserOptions.push({
      label: "No Specific Suggestion (CDBI AI Default)",
      value: "(.*)",
    });
  }


  return (
    <div className="flex w-full flex-col p-4 bg-cdbi-dark-blue text-cdbi-light-text rounded-lg shadow-xl space-y-6 font-sans">
      <h2 className="text-3xl font-bold text-cdbi-primary-green mb-4 border-b border-cdbi-border-light pb-3 flex items-center">
        <Icon iconName="smart_toy" size="lg" color="currentColor" className="mr-3" />
        CDBI GenAI Smart Reconciliation
      </h2>

      {/* --- AI-Powered KPI Dashboard Section --- */}
      <div className="bg-cdbi-darker-blue p-5 rounded-xl shadow-inner border border-cdbi-medium-blue">
        <h3 className="text-xl font-semibold text-cdbi-secondary-gold mb-4 flex items-center">
          <Icon iconName="analytics" size="sm" color="currentColor" className="mr-2 text-cdbi-primary-green" />
          CDBI GenAI Performance Dashboard
        </h3>
        {kpisLoading ? (
          <div className="flex justify-center items-center py-6">
            <Spinner className="text-cdbi-primary-green" size="md" />
            <Label className="ml-3 text-base text-cdbi-light-text">Loading CDBI GenAI KPIs, please wait...</Label>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 gap-5">
            {kpis.map((kpi) => (
              <div key={kpi.name} className="bg-cdbi-medium-blue p-4 rounded-lg flex flex-col justify-between hover:scale-[1.02] transition-transform duration-200 shadow-md border border-cdbi-border">
                <p className="text-xs text-cdbi-light-text opacity-75 leading-tight mb-2">{kpi.description}</p>
                <p className="text-base font-medium text-cdbi-secondary-gold mt-1">{kpi.name}</p>
                <div className="flex items-baseline mt-1">
                  <span className="text-3xl font-bold text-cdbi-primary-green">
                    {kpi.value}
                  </span>
                  {kpi.unit && <span className="text-sm text-cdbi-light-text ml-1">{kpi.unit}</span>}
                </div>
                {kpi.linkToGeminiChart && (
                  <Clickable onClick={() => window.open(kpi.linkToGeminiChart, '_blank')} className="mt-3 text-xs flex items-center text-cdbi-accent-blue hover:underline hover:text-cdbi-primary-green transition-colors">
                    View in Gemini AI Dashboard
                    <Icon iconName="open_in_new" size="xs" color="currentColor" className="ml-1" />
                  </Clickable>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* --- Transaction Match Result Type Selection --- */}
      {selectField === "From Transaction" ? (
        <div className="max-w-64">
          <Label className="flex self-center pb-2 pr-1 text-cdbi-light-text text-sm">
            CDBI Match Result Type:
          </Label>
          <SelectField
            className="justify-right flex bg-cdbi-input-bg border border-cdbi-border text-cdbi-text-color rounded-md p-2"
            handleChange={(e) => {
              callback(
                e as string,
                matcher,
                parser,
                showParser,
                null,
                null,
                null,
              );
            }}
            id="select-match-type"
            name="select-match-type"
            selectValue={selectField}
            options={selectFieldOptions}
          />
        </div>
      ) : null}

      {/* --- Transaction Field Selection (AI Enhanced) --- */}
      <div className="flex w-full flex-col">
        <div className="flex w-full justify-start items-center">
          <Label className="flex self-center pb-4 pr-1 text-cdbi-light-text text-sm min-w-[140px]">
            CDBI Transaction Field:
          </Label>
          <div className="min-w-48 flex-grow">
            <SelectField
              className="justify-right flex bg-cdbi-input-bg border border-cdbi-border text-cdbi-text-color rounded-md p-2"
              handleChange={(e) => {
                callback(
                  selectField,
                  e as string, // This is the new matcher value
                  parser,
                  showParser,
                  transactionField, // Keep original transactionField value
                  null,
                  null,
                );
              }}
              id="select-transaction-field"
              name="select-transaction-field"
              selectValue={matcher} // This is the current matcher (transaction field to match against)
              options={transactionFieldOptions}
            />
          </div>
        </div>
        {enableAIPredictions && aiLoadingMatcher && (
          <div className="flex items-center text-cdbi-accent-blue text-sm mt-2 ml-[140px]">
            <Spinner className="text-cdbi-accent-blue" size="xs" />
            <Label className="ml-2">CDBI GenAI is predicting the optimal matcher...</Label>
          </div>
        )}
        {aiMatcherConfidence && enableAIPredictions && (
          <div className="flex justify-start pt-2 text-xs text-cdbi-light-text opacity-90 ml-[140px]">
            <Icon iconName="info" size="xs" color="currentColor" className="self-center mr-1 text-cdbi-secondary-gold" />
            <Label className="flex self-center">
              CDBI GenAI Matcher Confidence: <span className="font-semibold ml-1 text-cdbi-primary-green">{(aiMatcherConfidence.score * 100).toFixed(0)}%</span> - {aiMatcherConfidence.explanation}
            </Label>
          </div>
        )}
        <div className="flex justify-start mt-2 ml-[140px]">
          <Label className="flex pb-2 text-xs text-cdbi-light-text opacity-70">
            Current Transaction Sample: <span className="italic ml-1 font-mono text-cdbi-secondary-gold">{transactionFieldString || "N/A"}</span>
          </Label>
        </div>
        {matcher && aiEnabledTransactionFieldOptions.find(opt => opt.value === matcher) && (
            <div className="flex justify-start mt-1 ml-[140px] text-xs text-cdbi-light-text opacity-80">
                <Icon iconName="description" size="xs" color="currentColor" className="self-center mr-1 text-cdbi-accent-blue" />
                <Label className="flex self-center">
                    CDBI AI Insight: {aiEnabledTransactionFieldOptions.find(opt => opt.value === matcher)?.aiDescription}
                </Label>
            </div>
        )}
      </div>

      {/* --- Parser Configuration (AI Enhanced) --- */}
      <div className="flex w-full flex-col space-y-4">
        {showParser ? (
          <div className="flex w-full flex-col space-y-3">
            <div className="flex w-full items-center">
              <Label className="justify-left flex self-center pr-1 text-cdbi-light-text text-sm min-w-[140px]">
                CDBI AI Parser (Regex):
              </Label>
              <Label className="self-center px-1 text-cdbi-light-text text-lg">/</Label>
              <Autosuggest
                className="justify-right w-full bg-cdbi-input-bg border border-cdbi-border text-cdbi-text-color rounded-md p-2"
                onChange={(e) => {
                  callback(
                    selectField,
                    matcher,
                    e.target.value,
                    showParser,
                    transactionField,
                    null,
                    null,
                  );
                }}
                onSuggestionSelect={(e, suggestion) => {
                  callback(
                    selectField,
                    matcher,
                    suggestion.suggestionValue,
                    showParser,
                    transactionField,
                    null,
                    null,
                  );
                }}
                value={parser || ""}
                suggestions={autosuggestParserOptions}
                placeholder="Enter a regex parser or leverage CDBI AI suggestions"
              />
              <Label className="self-center px-1 text-cdbi-light-text text-lg">/</Label>
            </div>

            {aiSuggestedParserInternal && aiSuggestedParserInternal.exampleMatches.length > 0 && (
              <div className="flex justify-start text-xs text-cdbi-light-text opacity-90 ml-[140px]">
                 <Icon iconName="lightbulb" size="xs" color="currentColor" className="self-center mr-1 text-cdbi-primary-green" />
                <Label className="flex self-center">
                  CDBI GenAI Example Matches: {aiSuggestedParserInternal.exampleMatches.map(m => (
                    <span key={m} className="font-mono bg-cdbi-medium-blue px-2 py-1 rounded-md ml-2 text-cdbi-text-color text-xs border border-cdbi-border-light">
                        {m}
                    </span>
                  ))}
                </Label>
              </div>
            )}

            <div className="flex w-full justify-between items-center ml-[140px]">
              <Clickable
                onClick={() => {
                  callback(
                    selectField,
                    matcher,
                    null,
                    false, // Hide parser
                    transactionField,
                    null,
                    null,
                  );
                }}
              >
                <div className="flex flex-row items-center pt-2 text-cdbi-danger-red hover:text-red-400 transition-colors">
                  <Icon
                    className="self-center"
                    iconName="delete" // Changed to 'delete' for clearer intent
                    size="xs"
                    color="currentColor"
                  />
                  <Label className="flex self-center pl-1 text-xs font-medium">
                    Remove CDBI AI Parser
                  </Label>
                </div>
              </Clickable>

              {enableAIPredictions && (
                <Clickable onClick={handleGenerateAIParser} disabled={aiLoadingParser}>
                  <div className={`flex flex-row items-center pt-2 ${aiLoadingParser ? 'text-gray-500 cursor-not-allowed' : 'text-cdbi-accent-blue hover:text-blue-400 transition-colors'}`}>
                    {aiLoadingParser ? (
                      <Spinner className="text-cdbi-accent-blue" size="xs" />
                    ) : (
                      <Icon
                        className="self-center"
                        iconName="psychology_alt" // New icon for AI generation, more advanced than 'cpu'
                        size="xs"
                        color="currentColor"
                      />
                    )}
                    <Label className="flex self-center pl-1 text-xs font-medium">
                      {aiLoadingParser ? "Generating with CDBI GenAI..." : "Generate Smart Parser with CDBI GenAI"}
                    </Label>
                  </div>
                </Clickable>
              )}
            </div>
          </div>
        ) : (
          <div className="flex w-full">
            <Clickable
              onClick={() => {
                callback(
                  selectField,
                  matcher,
                  parser,
                  true, // Show parser
                  transactionField,
                  null,
                  null,
                );
              }}
            >
              <div className="mr-auto flex flex-row pb-2 pt-1 items-center text-cdbi-primary-green hover:text-green-400 transition-colors">
                <Icon
                  className="self-center"
                  iconName="add_circle" // Changed to 'add_circle' for better visual
                  size="xs"
                  color="currentColor"
                />
                <Label className="flex self-center pl-1 text-xs font-medium">
                  Add CDBI AI Parser
                </Label>
              </div>
            </Clickable>
          </div>
        )}
      </div>

      {/* --- Global CDBI Gemini AI Dashboard Link --- */}
      <div className="flex justify-center w-full mt-8 pt-4 border-t border-cdbi-border-light">
        <Clickable onClick={() => window.open("https://gemini.cdbi.ai/dashboard", "_blank")}>
          <div className="flex items-center text-cdbi-secondary-gold hover:text-cdbi-primary-green transition-colors duration-200">
            <Icon iconName="monitor_heart" size="sm" color="currentColor" className="mr-2" />
            <Label className="text-sm font-semibold">
              Access CDBI Gemini AI Operations Dashboard for Deeper Insights
            </Label>
            <Icon iconName="open_in_new" size="xs" color="currentColor" className="ml-2" />
          </div>
        </Clickable>
      </div>
    </div>
  );
}
export default FromTransactionReconciliationMatchResult;
