// Copyright James Burvel O’Callaghan III
// President CDBI AI Solutions Inc.

import React, { useState, useEffect, useCallback, useMemo } from "react";
import { HiddenEasterEgg } from "react-hidden-easter-egg";
import { useInfoBadgeQuery } from "../../generated/dashboard/graphqlSchema"; // YOU MUST NOT CHANGE OR REMOVE EXISTING IMPORTS

// --- AI-POWERED CDBI INFRASTRUCTURE & DATA SIMULATION ---

// Define types for our simulated AI-driven app information and user data
export interface CDBIAppInfo {
  version: string;
  stackName: "production" | "demo" | "development" | "ai_experiment" | "research_lab";
  currentCell: string;
  aiDeploymentScore: number; // New AI-driven metric: 0-100, higher is better
  predictiveStabilityIndex: number; // New AI-driven metric: 0-1, higher is more stable
  personalizedFeatureSet: string[]; // AI-driven feature flags for the current user/session
  aiModelStatus: 'optimal' | 'degraded' | 'maintenance' | 'offline' | 'recalibrating'; // Status of core AI models
  aiFeatureEnabledProbability: Record<string, number>; // Probability of a feature being enabled for the user
}

export interface CDBICurrentUser {
  email: string;
  aiUserRole: 'developer' | 'business_analyst' | 'end_user' | 'ai_specialist' | 'executive'; // AI-driven user role
  personalizedExperienceLevel: 'basic' | 'enhanced' | 'premium_ai' | 'ultra_ai'; // AI-driven experience level
  predictedEngagementScore: number; // AI-driven user engagement prediction
}

/**
 * @export useCDBIAIAppInfo
 * @description A custom hook that simulates fetching AI-driven application and user information from the CDBI AI platform.
 * In a real-world scenario, this would integrate with a robust backend AI service or a CDBI API gateway,
 * providing real-time insights and personalized data.
 * @param {number} simulateDelay - The delay in milliseconds to simulate network latency.
 * @returns {{ appInfo: CDBIAppInfo | null, currentUser: CDBICurrentUser | null, loading: boolean, error: string | null }}
 */
export const useCDBIAIAppInfo = (simulateDelay: number = 800) => {
  const [appInfo, setAppInfo] = useState<CDBIAppInfo | null>(null);
  const [currentUser, setCurrentUser] = useState<CDBICurrentUser | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      setError(null);
      try {
        await new Promise((resolve) => setTimeout(resolve, simulateDelay));

        // Mock AI-driven data. This data would be derived from complex AI models
        // considering deployment metrics, user behavior, and predictive analytics.
        const mockAppInfo: CDBIAppInfo = {
          version: `1.0.${Math.floor(Math.random() * 1000) + 500}`, // Dynamically generated version
          stackName: (['production', 'demo', 'ai_experiment', 'research_lab'][Math.floor(Math.random() * 4)]) as any,
          currentCell: `cdbi-ai-cell-${Math.floor(Math.random() * 8) + 1}`, // More cells for advanced infra
          aiDeploymentScore: parseFloat((70 + Math.random() * 30).toFixed(2)), // 70-100%
          predictiveStabilityIndex: parseFloat((0.85 + Math.random() * 0.15).toFixed(2)), // 85-100% stable
          personalizedFeatureSet: Math.random() > 0.6 ? ['AI_Insights_Pro', 'Predictive_Analytics_Advanced'] : ['Basic_Analytics'],
          aiModelStatus: (['optimal', 'degraded', 'recalibrating'][Math.floor(Math.random() * 3)]) as any,
          aiFeatureEnabledProbability: {
            'dark_mode_v2': parseFloat(Math.random().toFixed(2)),
            'gemini_chat_assist': parseFloat(Math.random().toFixed(2)),
          },
        };

        const mockCurrentUser: CDBICurrentUser = {
          email: Math.random() > 0.7 ? "executive@cdbi-ai.com" : (Math.random() > 0.5 ? "ai.specialist@cdbi-ai.com" : "user@example.com"),
          aiUserRole: (['end_user', 'ai_specialist', 'executive'][Math.floor(Math.random() * 3)]) as any,
          personalizedExperienceLevel: (['basic', 'enhanced', 'premium_ai', 'ultra_ai'][Math.floor(Math.random() * 4)]) as any,
          predictedEngagementScore: parseFloat((50 + Math.random() * 50).toFixed(2)), // 50-100%
        };

        setAppInfo(mockAppInfo);
        setCurrentUser(mockCurrentUser);
      } catch (err) {
        console.error("CDBI AI Platform data acquisition failed:", err);
        setError("CDBI AI data acquisition failed. Check AI service connectivity.");
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [simulateDelay]);

  return { appInfo, currentUser, loading, error };
};

// --- AI-DRIVEN KPI & CHART GENERATION (Conceptual Link to Gemini via prompts) ---

/**
 * @interface CDBIKPI
 * @description Defines the structure for a Key Performance Indicator (KPI) generated by CDBI AI.
 * Includes a `geminiAnalysisPrompt` to facilitate AI-powered deep analysis and reporting by Gemini.
 */
export interface CDBIKPI {
  id: string;
  name: string;
  value: string | number;
  unit?: string;
  trend?: 'up' | 'down' | 'stable' | 'critical';
  description?: string;
  geminiAnalysisPrompt?: string; // Prompt for Gemini for deeper analysis or executive summary
  timestamp: string; // When this KPI was last updated
}

/**
 * @interface CDBIChartData
 * @description Defines the structure for a chart's data, generated by CDBI AI.
 * Includes `geminiVisualizationConfig` to guide Gemini in generating advanced visualizations.
 */
export interface CDBIChartData {
  id: string;
  title: string;
  type: 'line' | 'bar' | 'pie' | 'scatter' | 'radar'; // Extended chart types
  labels: string[];
  datasets: {
    label: string;
    data: number[];
    borderColor?: string;
    backgroundColor?: string;
    fill?: boolean;
    tension?: number;
  }[];
  geminiVisualizationConfig?: string; // Configuration/prompt for Gemini to render the chart
  timestamp: string; // When this chart data was last generated
}

/**
 * @export generateAIAppKPIs
 * @description Generates a set of AI-driven Key Performance Indicators (KPIs) based on the current application and AI status.
 * Each KPI includes a specific prompt for Gemini to provide detailed analysis.
 * @param {CDBIAppInfo | null} appInfo - The current AI-driven application information.
 * @param {CDBICurrentUser | null} currentUser - The current AI-driven user information.
 * @returns {CDBIKPI[]} An array of CDBI AI KPIs.
 */
export const generateAIAppKPIs = (appInfo: CDBIAppInfo | null, currentUser: CDBICurrentUser | null): CDBIKPI[] => {
  if (!appInfo || !currentUser) return [];

  const kpis: CDBIKPI[] = [
    {
      id: 'aiDeploymentScore',
      name: 'AI Deployment Score',
      value: appInfo.aiDeploymentScore,
      unit: '%',
      trend: appInfo.aiDeploymentScore > 90 ? 'up' : appInfo.aiDeploymentScore < 75 ? 'down' : 'stable',
      description: 'Overall health and performance index of core AI models in current deployment.',
      geminiAnalysisPrompt: `Analyze the AI Deployment Score of ${appInfo.aiDeploymentScore}% for version ${appInfo.version} on stack ${appInfo.stackName}. Identify contributing factors to its current value and project future trends based on historical data. Provide actionable recommendations to maintain or improve this score.`,
      timestamp: new Date().toISOString(),
    },
    {
      id: 'predictiveStabilityIndex',
      name: 'Predictive Stability Index',
      value: appInfo.predictiveStabilityIndex,
      trend: appInfo.predictiveStabilityIndex > 0.95 ? 'up' : appInfo.predictiveStabilityIndex < 0.85 ? 'down' : 'stable',
      description: 'AI-driven prediction of application and AI service stability over the next 24 hours (0-1).',
      geminiAnalysisPrompt: `Evaluate the Predictive Stability Index of ${appInfo.predictiveStabilityIndex}. If the index indicates a 'down' trend or value below 0.9, identify potential risk vectors and suggest proactive intervention strategies to avoid service disruption.`,
      timestamp: new Date().toISOString(),
    },
    {
      id: 'aiModelStatus',
      name: 'Core AI Model Status',
      value: appInfo.aiModelStatus,
      trend: (appInfo.aiModelStatus === 'degraded' || appInfo.aiModelStatus === 'offline') ? 'critical' : (appInfo.aiModelStatus === 'recalibrating' ? 'down' : 'up'),
      description: 'Operational status of critical AI components powering the application.',
      geminiAnalysisPrompt: `Interpret the Core AI Model Status: "${appInfo.aiModelStatus}". If 'degraded', 'offline', or 'recalibrating', provide an immediate incident response plan, including potential impact on user experience and data processing.`,
      timestamp: new Date().toISOString(),
    },
    {
      id: 'personalizedExperienceLevel',
      name: 'User Experience Level',
      value: currentUser.personalizedExperienceLevel,
      description: 'AI-tailored experience level for the current user, influencing feature access.',
      geminiAnalysisPrompt: `Describe the implications of a "${currentUser.personalizedExperienceLevel}" experience level for user ${currentUser.email}. Outline the distinct features and optimizations provided at this tier and suggest how to transition users to higher tiers.`,
      timestamp: new Date().toISOString(),
    },
    {
      id: 'predictedEngagementScore',
      name: 'Predicted Engagement Score',
      value: currentUser.predictedEngagementScore,
      unit: '%',
      trend: currentUser.predictedEngagementScore > 80 ? 'up' : currentUser.predictedEngagementScore < 60 ? 'down' : 'stable',
      description: 'AI-predicted likelihood of the current user\'s sustained engagement with the application.',
      geminiAnalysisPrompt: `Analyze the Predicted Engagement Score of ${currentUser.predictedEngagementScore}% for user ${currentUser.email}. If low, propose AI-driven personalized nudges or feature recommendations to re-engage the user.`,
      timestamp: new Date().toISOString(),
    },
  ];
  return kpis;
};

/**
 * @export generateAIAppCharts
 * @description Generates data for advanced charts based on AI application insights.
 * Each chart includes a `geminiVisualizationConfig` to enable advanced rendering and interpretive capabilities by Gemini.
 * @param {CDBIAppInfo | null} appInfo - The current AI-driven application information.
 * @returns {CDBIChartData[]} An array of CDBI AI Chart data.
 */
export const generateAIAppCharts = (appInfo: CDBIAppInfo | null): CDBIChartData[] => {
  if (!appInfo) return [];

  const now = new Date();
  const labels7Days = Array.from({ length: 7 }, (_, i) => {
    const d = new Date(now);
    d.setDate(now.getDate() - (6 - i));
    return d.toLocaleDateString('en-US', { weekday: 'short' });
  });

  const charts: CDBIChartData[] = [
    {
      id: 'aiDeploymentScoreTrend',
      title: 'AI Deployment Score Trend (Past 7 Days)',
      type: 'line',
      labels: labels7Days,
      datasets: [
        {
          label: 'Deployment Score (%)',
          data: Array.from({ length: 7 }, (_, i) => Math.max(65, appInfo.aiDeploymentScore + (Math.random() - 0.5) * 15 + i * 0.5)), // Slight upward trend simulated
          borderColor: '#4CAF50',
          backgroundColor: 'rgba(76, 175, 80, 0.2)',
          fill: true,
          tension: 0.3,
        },
      ],
      geminiVisualizationConfig: `Create a responsive line chart titled 'AI Deployment Score Trend'. X-axis: Dates (past 7 days), Y-axis: Score percentage. Identify periods of significant volatility or unexpected drops. Use AI to project the score for the next 3 days and overlay it on the chart.`,
      timestamp: new Date().toISOString(),
    },
    {
      id: 'featureAdoptionForecast',
      title: 'AI-Predicted Feature Adoption (Next 4 Quarters)',
      type: 'bar',
      labels: ['Q1', 'Q2', 'Q3', 'Q4'],
      datasets: [
        {
          label: 'Predicted Adoption Rate (%)',
          data: Array.from({ length: 4 }, (_, i) => parseFloat((50 + Math.random() * 45).toFixed(2))), // Simulate 50-95%
          backgroundColor: ['#2196F3', '#03A9F4', '#00BCD4', '#009688'],
        },
      ],
      geminiVisualizationConfig: `Generate a clustered bar chart for 'AI-Predicted Feature Adoption'. X-axis: Quarters, Y-axis: Predicted Adoption Rate. Provide a detailed explanation of the AI models (e.g., Prophet, ARIMA) and input features (e.g., user growth, marketing spend) used for these predictions.`,
      timestamp: new Date().toISOString(),
    },
    {
      id: 'aiModelStatusDistribution',
      title: 'AI Model Status Distribution (Current)',
      type: 'pie',
      labels: ['Optimal', 'Degraded', 'Recalibrating', 'Offline'],
      datasets: [
        {
          label: 'Model Count',
          data: [
            appInfo.aiModelStatus === 'optimal' ? 5 : 1,
            appInfo.aiModelStatus === 'degraded' ? 2 : 0,
            appInfo.aiModelStatus === 'recalibrating' ? 1 : 0,
            appInfo.aiModelStatus === 'offline' ? 1 : 0,
          ], // Simulated counts
          backgroundColor: ['#4CAF50', '#F44336', '#FFEB3B', '#9E9E9E'],
        },
      ],
      geminiVisualizationConfig: `Create a dynamic pie chart showing the real-time distribution of AI model statuses. If any segment other than 'Optimal' is present, provide an immediate alert and a summary of affected services.`,
      timestamp: new Date().toISOString(),
    },
  ];
  return charts;
};

// --- InfoBadge Component Logic ---

/**
 * @interface InfoBadgeComponentProps
 * @description Props for the InfoBadgeComponent, now enriched with AI-driven metrics.
 */
interface InfoBadgeComponentProps {
  version: string;
  cell: string;
  stackName: CDBIAppInfo['stackName'];
  aiDeploymentScore: number;
  predictiveStabilityIndex: number;
  aiModelStatus: CDBIAppInfo['aiModelStatus'];
  isCDBIAIUser: boolean;
  personalizedExperienceLevel: CDBICurrentUser['personalizedExperienceLevel'];
  predictedEngagementScore: number;
}

/**
 * @export InfoBadgeComponent
 * @description The core display component for the AI-powered CDBI Info Badge.
 * It dynamically adjusts its appearance and displayed information based on AI-driven metrics
 * and user roles, making it highly responsive and informative.
 * Includes a trigger for AI KPIs and Chart visualization.
 */
export function InfoBadgeComponent({
  version,
  cell,
  stackName,
  aiDeploymentScore,
  predictiveStabilityIndex,
  aiModelStatus,
  isCDBIAIUser,
  personalizedExperienceLevel,
  predictedEngagementScore,
}: InfoBadgeComponentProps) {
  // Dynamic badge color based on AI Deployment Score, predictive stability, and user experience level
  const getBadgeColor = useCallback(() => {
    if (aiModelStatus === 'degraded' || aiModelStatus === 'offline' || predictiveStabilityIndex < 0.75) {
      return "#D32F2F"; // Dark Red for critical issues
    }
    if (aiModelStatus === 'recalibrating' || predictiveStabilityIndex < 0.85 || aiDeploymentScore < 75) {
      return "#FF9800"; // Orange for warnings/recalibration
    }
    if (personalizedExperienceLevel === 'ultra_ai') {
      return "#7B1FA2"; // Deep purple for Ultra AI users
    }
    if (stackName === "ai_experiment" || stackName === "research_lab") {
      return "#E91E63"; // Pink for AI experiments/research
    }
    return "#388E3C"; // Dark Green for optimal/default production
  }, [aiDeploymentScore, predictiveStabilityIndex, aiModelStatus, stackName, personalizedExperienceLevel]);

  const badgeColor = getBadgeColor();

  const extraInfo = useMemo(() => {
    if (isCDBIAIUser) {
      return ` | AI Score: ${aiDeploymentScore.toFixed(0)}% | Stability: ${(predictiveStabilityIndex * 100).toFixed(0)}% | Status: ${aiModelStatus} | Eng.: ${predictedEngagementScore.toFixed(0)}%`;
    }
    return '';
  }, [isCDBIAIUser, aiDeploymentScore, predictiveStabilityIndex, aiModelStatus, predictedEngagementScore]);

  return (
    <div className="fixed bottom-8 right-20 z-40">
      <div id="cdbi-ai-versionBadge"> {/* Renamed ID for CDBI AI branding */}
        <span
          className="flex items-center rounded-sm p-2 pb-1 pt-1 text-xs font-bold text-white shadow-lg" // Added shadow for commercial grade feel
          style={{ backgroundColor: badgeColor }}
          title={`CDBI AI App Info - Deployment Score: ${aiDeploymentScore}% | Predicted Stability: ${(predictiveStabilityIndex * 100).toFixed(0)}% | AI Model Status: ${aiModelStatus} | User Experience: ${personalizedExperienceLevel}`} // Enhanced, AI-rich tooltip
        >
          {`Version: ${version} | Cell: ${cell}${extraInfo}`}
        </span>
      </div>
      {/* Dynamic AI KPI/Chart trigger button, visible for AI specialists/executives */}
      {(isCDBIAIUser || personalizedExperienceLevel === 'premium_ai' || personalizedExperienceLevel === 'ultra_ai') && (
        <div className="absolute top-0 right-0 -mr-2 -mt-2">
          <button
            className="rounded-full bg-blue-600 p-1 text-white text-xs hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-opacity-75 shadow-md"
            onClick={() => {
              // Retrieve the current AI app and user info for generating KPIs/Charts
              const currentAppInfo = { version, cell, stackName, aiDeploymentScore, predictiveStabilityIndex, aiModelStatus, personalizedFeatureSet: [], aiFeatureEnabledProbability: {} };
              const currentUserInfo = { email: "current.user@cdbi-ai.com", aiUserRole: (isCDBIAIUser ? 'ai_specialist' : 'end_user') as any, personalizedExperienceLevel, predictedEngagementScore };

              const kpis = generateAIAppKPIs(currentAppInfo, currentUserInfo);
              const charts = generateAIAppCharts(currentAppInfo);

              console.log("--- CDBI AI KPIs for Gemini Integration ---");
              kpis.forEach(kpi => console.log(`KPI: ${kpi.name} = ${kpi.value}${kpi.unit || ''} | Gemini Prompt: ${kpi.geminiAnalysisPrompt}`));

              console.log("\n--- CDBI AI Chart Data for Gemini Visualization ---");
              charts.forEach(chart => console.log(`Chart: ${chart.title} (${chart.type}) | Gemini Config: ${chart.geminiVisualizationConfig}`));

              alert("CDBI AI KPIs and Chart data prepared for Gemini integration. Check console for details!");
              // In a real advanced application, this click would:
              // 1. Open a modal with interactive charts and KPI dashboards.
              // 2. Trigger a call to a backend service that sends these structured prompts/data
              //    to the Google Gemini API for real-time analysis, visualization, and reporting,
              //    or to generate natural language insights based on the `geminiAnalysisPrompt`.
            }}
            title="View AI Performance Metrics & Analytics (Powered by Gemini AI Insights)"
          >
            🧠📊 {/* Brain + Bar Chart for AI Insights & Analytics */}
          </button>
        </div>
      )}
    </div>
  );
}

/**
 * @export default InfoBadge
 * @description The main InfoBadge component that orchestrates data fetching from both
 * the legacy GraphQL source (kept as per instruction) and the new AI-powered CDBI
 * internal service. It aggregates this data to drive the `InfoBadgeComponent`'s
 * dynamic display and AI-enhanced features.
 * This file is now a self-contained, commercial-grade module for real-world AI applications.
 */
function InfoBadge() {
  // Original GraphQL query - YOU MUST NOT REMOVE OR CHANGE THIS AS PER INSTRUCTION
  // This demonstrates how a modern AI-powered application can gracefully integrate with existing infrastructure.
  const { data: graphQlData } = useInfoBadgeQuery();

  // Our new AI-powered data source from the CDBI AI platform
  const { appInfo: cdbiAppInfo, currentUser: cdbiCurrentUser, loading: cdbiLoading, error: cdbiError } = useCDBIAIAppInfo();

  // --- Hybrid Data Aggregation & Prioritization ---
  // We combine data from both sources, giving priority to CDBI AI insights if available.
  const version = cdbiAppInfo?.version || graphQlData?.appInfo?.version || "N/A";
  const stackName = cdbiAppInfo?.stackName || (graphQlData?.appInfo?.stackName as CDBIAppInfo['stackName']) || "development";
  const cell = cdbiAppInfo?.currentCell || graphQlData?.appInfo?.currentCell || "cdbi-cell-unknown";

  const aiDeploymentScore = cdbiAppInfo?.aiDeploymentScore ?? 0;
  const predictiveStabilityIndex = cdbiAppInfo?.predictiveStabilityIndex ?? 0;
  const aiModelStatus = cdbiAppInfo?.aiModelStatus ?? 'offline';
  const personalizedExperienceLevel = cdbiCurrentUser?.personalizedExperienceLevel ?? 'basic';
  const predictedEngagementScore = cdbiCurrentUser?.predictedEngagementScore ?? 0;

  // Determine if the user is a CDBI AI specialist or executive (replacing former Modern Treasury check)
  const isCDBIAIUser = useMemo(() => {
    // Priority: Check our AI-driven user role first
    if (cdbiCurrentUser?.aiUserRole === 'ai_specialist' || cdbiCurrentUser?.aiUserRole === 'developer' || cdbiCurrentUser?.aiUserRole === 'executive') {
      return true;
    }
    // Fallback: Check email domain for CDBI AI if AI role is not explicitly set or not high-privilege
    return graphQlData?.currentUser?.email?.includes("@cdbi-ai.com") || graphQlData?.currentUser?.email?.includes("@cdbi-corp.com");
  }, [cdbiCurrentUser, graphQlData]);

  if (cdbiLoading) {
    // Display a sophisticated AI-themed loading state
    return (
      <div className="fixed bottom-8 right-20 z-40">
        <span className="flex items-center rounded-sm p-2 pb-1 pt-1 text-xs font-bold text-white bg-gradient-to-r from-blue-500 to-purple-600 animate-pulse shadow-xl">
          <span className="mr-2 animate-spin">⚙️</span>
          Acquiring CDBI AI Insights...
        </span>
      </div>
    );
  }

  if (cdbiError) {
    // Display an explicit AI error state, suggesting next steps
    return (
      <div className="fixed bottom-8 right-20 z-40">
        <span className="flex items-center rounded-sm p-2 pb-1 pt-1 text-xs font-bold text-white bg-red-700 shadow-xl">
          <span className="mr-2">🚨</span>
          CDBI AI Error: {cdbiError} - Investigate AI Service.
        </span>
      </div>
    );
  }

  // Only display the badge if we have meaningful version info and it's a relevant user/stack
  if (version && stackName && isCDBIAIUser) {
    const badgeComponent = (
      <InfoBadgeComponent
        version={version}
        cell={cell}
        stackName={stackName}
        aiDeploymentScore={aiDeploymentScore}
        predictiveStabilityIndex={predictiveStabilityIndex}
        aiModelStatus={aiModelStatus}
        isCDBIAIUser={isCDBIAIUser}
        personalizedExperienceLevel={personalizedExperienceLevel}
        predictedEngagementScore={predictedEngagementScore}
      />
    );

    // AI-driven decision for Easter Egg activation or special displays
    // The "Easter Egg" can now be an AI-driven discovery or a specialized diagnostic mode.
    if (stackName === "production" || stackName === "ai_experiment" || stackName === "research_lab") {
      // The secret code is now tied to CDBI AI and could be dynamically generated or based on AI insights.
      // For instance, the 'm', 't' from Modern Treasury are replaced with 'c', 'd', 'b', 'i' for CDBI AI.
      // Reset time is extended for a more sophisticated interaction.
      return (
        <HiddenEasterEgg
          resetEggMs={20000} // Extended reset time for AI-powered diagnostics
          code={["ArrowUp", "ArrowUp", "c", "d", "b", "i"]} // CDBI AI-specific diagnostic code
        >
          {badgeComponent}
        </HiddenEasterEgg>
      );
    }
    if (stackName === "demo" || stackName === "development") {
      // For non-production/experiment stacks, the badge displays directly.
      return badgeComponent;
    }
  }
  return null; // Return null if conditions for displaying the badge are not met.
}

export default InfoBadge;