// Copyright James Burvel O’Callaghan III
// President CDBI Demo Business Inc.

import React, { useState, useEffect, useCallback, useMemo } from "react";
import LedgerAccountsEmptyState from "../containers/LedgerAccountsEmptyState";
import ListView from "./ListView";
import {
  LedgerAccountsHomeDocument,
  useLedgerAccountSelectQuery,
  useDeleteLedgerAccountMutation,
} from "../../generated/dashboard/graphqlSchema";
import { ConfirmModal } from "../../common/ui-components";
import { ExportDataParams } from "./ExportDataButton";
import {
  getLedgerAccountSearchComponents,
  LedgerAccountQueryFilter,
} from "../../common/search_components/ledgerAccountSearchComponents";
import { LEDGER_ACCOUNT } from "../../generated/dashboard/types/resources";
import { useDispatchContext } from "../MessageProvider";
import trackEvent from "../../common/utilities/trackEvent";
import { LEDGERS_EVENTS } from "../../common/constants/analytics";

const CONSTANT_QUERY_PARAMS = ["tab", "effective_at"];

interface LedgerAccountsHomeProps {
  ledgerId: string;
  initialShowSearchArea: boolean;
}

/**
 * Interface for AI-predicted ledger account balances.
 * @export
 */
export interface AICDBILedgerAccountPrediction {
  accountId: string;
  predictedBalance: number; // The predicted balance amount
  currency: string;
  confidenceScore: number; // Confidence level of the prediction (0-1)
  predictionDate: string; // ISO date string of when the prediction is valid for
  trend: 'up' | 'down' | 'stable'; // Predicted trend
  deviation: number; // % deviation from historical average
}

/**
 * Interface for AI-detected anomalies in ledger accounts or transactions.
 * @export
 */
export interface AICDBIAnomalyReport {
  id: string;
  accountId: string;
  entityType: 'account' | 'transaction'; // What kind of entity is anomalous
  anomalyType: string; // e.g., 'UnusualSpend', 'UnexpectedDeposit', 'BalanceSpike'
  severity: 'low' | 'medium' | 'high' | 'critical';
  description: string;
  detectedAt: string; // ISO date string
  suggestedAction: string; // e.g., 'Review transaction', 'Flag account'
}

/**
 * Interface for AI-generated optimization suggestions.
 * @export
 */
export interface AICDBIOptimizationSuggestion {
  id: string;
  accountId: string;
  suggestionType: 'liquidity_transfer' | 'investment_opportunity' | 'fee_reduction';
  details: string;
  potentialImpact: number; // Monetary value of potential impact
  impactCurrency: string;
  confidence: number; // Confidence in the suggestion
}

/**
 * Interface for Key Performance Indicators (KPIs) generated by AI.
 * @export
 */
export interface AICDBIKPI {
  id: string;
  name: string;
  value: string | number;
  unit?: string;
  change?: number; // percentage change from previous period
  trend: 'up' | 'down' | 'stable';
  description: string;
  geminiInsightsUrl?: string; // Link to Gemini for detailed insights
}

/**
 * Interface for Chart data generated by AI.
 * @export
 */
export interface AICDBIChartData {
  id: string;
  title: string;
  type: 'line' | 'bar' | 'pie'; // Simplified chart types
  labels: string[]; // X-axis labels
  datasets: Array<{
    label: string;
    data: number[];
    color?: string;
  }>;
  geminiInsightsUrl?: string; // Link to Gemini for detailed insights
}


/**
 * A sophisticated AI-powered service for Ledger Account management within CDBI.
 * This class encapsulates advanced analytics, prediction, anomaly detection,
 * and optimization algorithms.
 * @export
 */
export class AICDBILedgerService {
  /**
   * Simulates AI-powered prediction of future ledger account balances.
   * In a real application, this would integrate with a machine learning model.
   * @param ledgerId The ID of the ledger.
   * @param accounts An array of current ledger account nodes.
   * @returns A promise resolving to an array of predicted account balances.
   */
  static async predictAccountBalances(
    ledgerId: string,
    accounts: any[]
  ): Promise<AICDBILedgerAccountPrediction[]> {
    console.log(`CDBI AI predicting balances for ledger ${ledgerId}...`);
    // Simulate complex AI model inference
    await new Promise((resolve) => setTimeout(resolve, 500)); // Simulate AI computation time

    return accounts.map(account => {
      const currentBalance = parseFloat(account.postedBalanceAmount.value || '0');
      const currency = account.currency;
      // Simple linear projection for demo purposes, replace with actual ML model
      const predictedBalance = currentBalance * (1 + (Math.random() - 0.5) * 0.1); // +/- 5%
      const confidenceScore = 0.75 + Math.random() * 0.25; // High confidence
      const trend = predictedBalance > currentBalance ? 'up' : (predictedBalance < currentBalance ? 'down' : 'stable');
      const deviation = ((predictedBalance - currentBalance) / currentBalance) * 100;

      return {
        accountId: account.id,
        predictedBalance: parseFloat(predictedBalance.toFixed(2)),
        currency: currency,
        confidenceScore: parseFloat(confidenceScore.toFixed(2)),
        predictionDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days in future
        trend,
        deviation: parseFloat(deviation.toFixed(2)),
      };
    });
  }

  /**
   * Simulates AI-powered anomaly detection across ledger transactions.
   * @param ledgerId The ID of the ledger.
   * @param accounts An array of current ledger account nodes, used here to simulate anomaly sources.
   * @returns A promise resolving to an array of detected anomalies.
   */
  static async detectAnomalies(
    ledgerId: string,
    accounts: any[]
  ): Promise<AICDBIAnomalyReport[]> {
    console.log(`CDBI AI detecting anomalies in ledger ${ledgerId}...`);
    await new Promise((resolve) => setTimeout(resolve, 700));

    const anomalies: AICDBIAnomalyReport[] = [];
    accounts.forEach(account => {
      // Simulate detection of an unusual balance spike for a few accounts
      if (Math.random() < 0.15) { // 15% chance of an anomaly
        anomalies.push({
          id: `anomaly-${Date.now()}-${Math.random()}`,
          accountId: account.id,
          entityType: 'account',
          anomalyType: 'UnusualBalanceMovement',
          severity: Math.random() > 0.7 ? 'critical' : (Math.random() > 0.4 ? 'high' : 'medium'),
          description: `Account ${account.name} (${account.id}) exhibited unusual balance fluctuation.`,
          detectedAt: new Date().toISOString(),
          suggestedAction: 'Investigate recent transactions and account activity.',
        });
      }
    });
    return anomalies;
  }

  /**
   * Simulates AI-powered generation of optimization suggestions for ledger accounts.
   * @param ledgerId The ID of the ledger.
   * @param accounts An array of current ledger account nodes.
   * @returns A promise resolving to an array of optimization suggestions.
   */
  static async generateOptimizationSuggestions(
    ledgerId: string,
    accounts: any[]
  ): Promise<AICDBIOptimizationSuggestion[]> {
    console.log(`CDBI AI generating optimization suggestions for ledger ${ledgerId}...`);
    await new Promise((resolve) => setTimeout(resolve, 600));

    const suggestions: AICDBIOptimizationSuggestion[] = [];
    accounts.forEach(account => {
      const currentBalance = parseFloat(account.postedBalanceAmount.value || '0');
      const currency = account.currency;

      if (currentBalance > 10000 && Math.random() < 0.2) { // Suggest investment for high balance accounts
        suggestions.push({
          id: `opt-${Date.now()}-${Math.random()}`,
          accountId: account.id,
          suggestionType: 'investment_opportunity',
          details: `Consider moving ${currency} ${(currentBalance * 0.2).toFixed(2)} to a higher-yield investment product.`,
          potentialImpact: parseFloat((currentBalance * 0.05).toFixed(2)), // 5% annual return on 20% moved
          impactCurrency: currency,
          confidence: parseFloat((0.8 + Math.random() * 0.1).toFixed(2)),
        });
      } else if (currentBalance < 500 && Math.random() < 0.1) { // Suggest liquidity transfer for low balance
        suggestions.push({
          id: `opt-${Date.now()}-${Math.random()}`,
          accountId: account.id,
          suggestionType: 'liquidity_transfer',
          details: `Transfer ${currency} 1000 to cover potential shortfalls or operational needs.`,
          potentialImpact: parseFloat((100).toFixed(2)), // Avoided overdraft fees
          impactCurrency: currency,
          confidence: parseFloat((0.7 + Math.random() * 0.1).toFixed(2)),
        });
      }
    });
    return suggestions;
  }

  /**
   * Simulates AI-driven impact analysis for ledger account deletion.
   * @param ledgerId The ID of the ledger.
   * @param accountIds The IDs of accounts proposed for deletion.
   * @returns A promise resolving to a string describing the potential impact.
   */
  static async analyzeDeletionImpact(ledgerId: string, accountIds: string[]): Promise<string> {
    console.log(`CDBI AI analyzing deletion impact for ledger ${ledgerId} and accounts: ${accountIds.join(', ')}`);
    await new Promise((resolve) => setTimeout(resolve, 300));

    if (accountIds.length === 0) return "No accounts selected for deletion.";

    const totalImpact = accountIds.length * 5000 + Math.random() * 10000; // Simulate monetary impact
    return `CDBI AI estimates deleting ${accountIds.length} account(s) could impact overall liquidity by approximately $${totalImpact.toFixed(2)} and affect 3-5 linked financial instruments. Proceed with caution.`;
  }

  /**
   * Generates a unique URL for detailed Gemini insights based on the KPI/Chart ID.
   * @param entityId The ID of the KPI or Chart.
   * @param type The type of entity (kpi or chart).
   * @returns A simulated Gemini insights URL.
   */
  static getGeminiInsightsUrl(entityId: string, type: 'kpi' | 'chart'): string {
    return `https://gemini.google.com/insights/${type}/${entityId}?context=cdbi-ledger-${entityId}`;
  }
}

/**
 * A sophisticated AI-powered component to display insights, KPIs, and charts for ledger accounts.
 * This component orchestrates calls to the AICDBILedgerService and presents the results.
 * @export
 */
export const AICDBIInsightsPanel: React.FC<{ ledgerId: string; accounts: any[] }> = ({ ledgerId, accounts }) => {
  const [predictions, setPredictions] = useState<AICDBILedgerAccountPrediction[]>([]);
  const [anomalies, setAnomalies] = useState<AICDBIAnomalyReport[]>([]);
  const [suggestions, setSuggestions] = useState<AICDBIOptimizationSuggestion[]>([]);
  const [loadingAI, setLoadingAI] = useState(true);
  const { dispatchError } = useDispatchContext();

  const currentTotalBalance = useMemo(() => {
    return accounts.reduce((sum, acc) => sum + parseFloat(acc.postedBalanceAmount.value || '0'), 0).toFixed(2);
  }, [accounts]);

  const predictedTotalBalance = useMemo(() => {
    return predictions.reduce((sum, pred) => sum + pred.predictedBalance, 0).toFixed(2);
  }, [predictions]);


  useEffect(() => {
    const fetchAIInsights = async () => {
      setLoadingAI(true);
      try {
        const [preds, anoms, suggs] = await Promise.all([
          AICDBILedgerService.predictAccountBalances(ledgerId, accounts),
          AICDBILedgerService.detectAnomalies(ledgerId, accounts),
          AICDBILedgerService.generateOptimizationSuggestions(ledgerId, accounts),
        ]);
        setPredictions(preds);
        setAnomalies(anoms);
        setSuggestions(suggs);
      } catch (error: any) {
        console.error("Failed to fetch AI insights:", error);
        dispatchError(`CDBI AI Insights Error: ${error.message || 'An unknown error occurred while fetching AI data.'}`);
      } finally {
        setLoadingAI(false);
      }
    };

    if (accounts && accounts.length > 0) {
      fetchAIInsights();
    } else {
      setPredictions([]);
      setAnomalies([]);
      setSuggestions([]);
      setLoadingAI(false);
    }
  }, [ledgerId, accounts, dispatchError]);

  const kpis: AICDBIKPI[] = useMemo(() => {
    const totalPredictedBalance = parseFloat(predictedTotalBalance);
    const totalCurrentBalance = parseFloat(currentTotalBalance);
    const balanceChange = totalCurrentBalance > 0 ? ((totalPredictedBalance - totalCurrentBalance) / totalCurrentBalance) * 100 : 0;
    const anomalyRate = accounts.length > 0 ? (anomalies.length / accounts.length) * 100 : 0;
    const totalPotentialImpact = suggestions.reduce((sum, s) => sum + s.potentialImpact, 0);

    return [
      {
        id: 'predicted_balance_kpi',
        name: 'Predicted Total Balance (Next 7D)',
        value: `$${totalPredictedBalance}`,
        unit: 'USD', // Assuming USD for aggregated view
        change: parseFloat(balanceChange.toFixed(2)),
        trend: balanceChange > 0 ? 'up' : (balanceChange < 0 ? 'down' : 'stable'),
        description: 'AI forecast of the aggregated ledger account balance for the upcoming week.',
        geminiInsightsUrl: AICDBILedgerService.getGeminiInsightsUrl('predicted_balance_kpi', 'kpi'),
      },
      {
        id: 'anomaly_detection_rate_kpi',
        name: 'Anomaly Detection Rate',
        value: `${anomalyRate.toFixed(2)}%`,
        unit: '%',
        change: 0, // Requires historical data for meaningful change
        trend: 'stable', // Placeholder
        description: 'Percentage of ledger accounts flagged by AI for unusual activity.',
        geminiInsightsUrl: AICDBILedgerService.getGeminiInsightsUrl('anomaly_detection_rate_kpi', 'kpi'),
      },
      {
        id: 'optimization_potential_kpi',
        name: 'Optimization Potential',
        value: `$${totalPotentialImpact.toFixed(2)}`,
        unit: 'USD',
        change: 0, // Requires historical data
        trend: 'up', // Always want to optimize!
        description: 'Estimated monetary impact from implementing AI-generated optimization suggestions.',
        geminiInsightsUrl: AICDBILedgerService.getGeminiInsightsUrl('optimization_potential_kpi', 'kpi'),
      },
      {
        id: 'ai_confidence_score_kpi',
        name: 'Average AI Confidence',
        value: `${(predictions.length > 0 ? predictions.reduce((sum, p) => sum + p.confidenceScore, 0) / predictions.length : 0).toFixed(2)}`,
        unit: 'score (0-1)',
        change: 0,
        trend: 'stable',
        description: 'Average confidence score of AI predictions for ledger account balances.',
        geminiInsightsUrl: AICDBILedgerService.getGeminiInsightsUrl('ai_confidence_score_kpi', 'kpi'),
      }
    ];
  }, [accounts, predictions, anomalies, suggestions, currentTotalBalance, predictedTotalBalance]);


  const charts: AICDBIChartData[] = useMemo(() => {
    // Chart 1: Predicted vs Actual Balance
    const labels = accounts.map(acc => acc.name);
    const actualData = accounts.map(acc => parseFloat(acc.postedBalanceAmount.value || '0'));
    const predictedData = predictions.map(p => p.predictedBalance);

    // Chart 2: Anomaly Severity Distribution
    const severityCounts = anomalies.reduce((acc, anom) => {
      acc[anom.severity] = (acc[anom.severity] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);
    const anomalySeverityLabels = ['critical', 'high', 'medium', 'low'];
    const anomalySeverityData = anomalySeverityLabels.map(sev => severityCounts[sev] || 0);

    // Chart 3: Optimization Suggestion Impact
    const suggestionTypes = Array.from(new Set(suggestions.map(s => s.suggestionType)));
    const suggestionTypeImpact = suggestionTypes.map(type =>
      suggestions.filter(s => s.suggestionType === type).reduce((sum, s) => sum + s.potentialImpact, 0)
    );

    return [
      {
        id: 'predicted_vs_actual_balance_chart',
        title: 'CDBI AI: Predicted vs. Current Account Balances',
        type: 'bar',
        labels: labels,
        datasets: [
          { label: 'Current Balance', data: actualData, color: '#4CAF50' }, // Green
          { label: 'Predicted Balance (Next 7D)', data: predictedData, color: '#2196F3' }, // Blue
        ],
        geminiInsightsUrl: AICDBILedgerService.getGeminiInsightsUrl('predicted_vs_actual_balance_chart', 'chart'),
      },
      {
        id: 'anomaly_severity_distribution_chart',
        title: 'CDBI AI: Anomaly Severity Distribution',
        type: 'pie',
        labels: anomalySeverityLabels,
        datasets: [
          { label: 'Number of Anomalies', data: anomalySeverityData, color: '#F44336,#FF9800,#FFEB3B,#8BC34A'.split(',') }, // Red, Orange, Yellow, Light Green
        ],
        geminiInsightsUrl: AICDBILedgerService.getGeminiInsightsUrl('anomaly_severity_distribution_chart', 'chart'),
      },
      {
        id: 'optimization_potential_by_type_chart',
        title: 'CDBI AI: Optimization Potential by Type',
        type: 'bar',
        labels: suggestionTypes.length > 0 ? suggestionTypes : ['No Suggestions'],
        datasets: [
          { label: 'Potential Impact (USD)', data: suggestionTypeImpact.length > 0 ? suggestionTypeImpact : [0], color: '#9C27B0' }, // Purple
        ],
        geminiInsightsUrl: AICDBILedgerService.getGeminiInsightsUrl('optimization_potential_by_type_chart', 'chart'),
      },
    ];
  }, [accounts, predictions, anomalies, suggestions]);


  if (loadingAI) {
    return (
      <div className="p-4 text-center text-gray-500">
        CDBI AI is crunching numbers and generating insights...
      </div>
    );
  }

  return (
    <div className="bg-white shadow-md rounded-lg p-6 mb-8 border border-cdbi-primary-100">
      <h2 className="text-2xl font-bold text-cdbi-primary-900 mb-4">CDBI AI Ledger Insights</h2>
      <p className="text-gray-600 mb-6">
        Leveraging advanced AI models, CDBI provides unparalleled insights into your ledger accounts,
        offering predictive analytics, anomaly detection, and actionable optimization suggestions.
        This enables proactive financial management for both institutions and individuals.
      </p>

      {/* KPIs Section */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        {kpis.map((kpi) => (
          <div key={kpi.id} className="bg-cdbi-secondary-50 p-4 rounded-md shadow-sm border border-cdbi-secondary-100">
            <h3 className="text-lg font-semibold text-cdbi-secondary-800">{kpi.name}</h3>
            <p className="text-3xl font-bold text-cdbi-primary-700 mt-2">{kpi.value} {kpi.unit}</p>
            {kpi.change !== undefined && (
              <p className={`text-sm mt-1 ${kpi.trend === 'up' ? 'text-green-600' : kpi.trend === 'down' ? 'text-red-600' : 'text-gray-500'}`}>
                {kpi.change > 0 ? '↑' : (kpi.change < 0 ? '↓' : '')} {Math.abs(kpi.change)}% {kpi.trend}
              </p>
            )}
            <p className="text-sm text-gray-500 mt-2">{kpi.description}</p>
            <a href={kpi.geminiInsightsUrl} target="_blank" rel="noopener noreferrer" className="text-cdbi-primary-600 hover:underline text-sm block mt-2">
              Deep Dive with Gemini AI →
            </a>
          </div>
        ))}
      </div>

      {/* Charts Section */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
        {charts.map((chart) => (
          <div key={chart.id} className="bg-white p-4 rounded-md shadow-sm border border-cdbi-primary-100">
            <h3 className="text-xl font-semibold text-cdbi-primary-800 mb-4">{chart.title}</h3>
            {/* Simulate a chart with simple bars/labels. In a real app, use a charting library. */}
            <div className="flex flex-col space-y-2">
              {chart.datasets.map((dataset, idx) => (
                <div key={idx}>
                  <p className="text-sm font-medium text-gray-700 mb-1">{dataset.label}</p>
                  <div className="flex flex-wrap gap-2">
                    {chart.labels.map((label, i) => (
                      <div key={i} className="flex items-center text-xs p-1 bg-gray-100 rounded-sm">
                        <span className="font-semibold">{label}:</span> <span style={{ color: dataset.color }}>{dataset.data[i]}</span>
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
            <a href={chart.geminiInsightsUrl} target="_blank" rel="noopener noreferrer" className="text-cdbi-primary-600 hover:underline text-sm block mt-4">
              Explore with Gemini AI →
            </a>
          </div>
        ))}
      </div>

      {/* Anomalies Section */}
      {anomalies.length > 0 && (
        <div className="mb-8">
          <h3 className="text-xl font-semibold text-red-700 mb-4">CDBI AI: Detected Anomalies ({anomalies.length})</h3>
          <div className="space-y-4">
            {anomalies.map((anomaly) => (
              <div key={anomaly.id} className="bg-red-50 border-l-4 border-red-500 p-4 shadow-sm rounded-md">
                <p className="font-bold text-red-800">{anomaly.anomalyType} <span className={`text-sm ml-2 px-2 py-1 rounded-full ${
                  anomaly.severity === 'critical' ? 'bg-red-700 text-white' :
                  anomaly.severity === 'high' ? 'bg-red-500 text-white' :
                  anomaly.severity === 'medium' ? 'bg-orange-500 text-white' :
                  'bg-yellow-500 text-gray-800'
                }`}>{anomaly.severity.toUpperCase()}</span></p>
                <p className="text-gray-700 mt-1">{anomaly.description}</p>
                <p className="text-sm text-gray-600">Account: {anomaly.accountId} | Detected: {new Date(anomaly.detectedAt).toLocaleString()}</p>
                <p className="text-sm font-medium text-red-600 mt-2">Action: {anomaly.suggestedAction}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Optimization Suggestions Section */}
      {suggestions.length > 0 && (
        <div>
          <h3 className="text-xl font-semibold text-green-700 mb-4">CDBI AI: Optimization Suggestions ({suggestions.length})</h3>
          <div className="space-y-4">
            {suggestions.map((suggestion) => (
              <div key={suggestion.id} className="bg-green-50 border-l-4 border-green-500 p-4 shadow-sm rounded-md">
                <p className="font-bold text-green-800">
                  {suggestion.suggestionType.replace(/_/g, ' ').toUpperCase()}
                  <span className="ml-2 text-sm text-gray-600">(Impact: {suggestion.impactCurrency} {suggestion.potentialImpact.toFixed(2)})</span>
                </p>
                <p className="text-gray-700 mt-1">{suggestion.details}</p>
                <p className="text-sm text-gray-600">Account: {suggestion.accountId} | Confidence: {(suggestion.confidence * 100).toFixed(0)}%</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};


function LedgerAccountsHome({
  ledgerId,
  initialShowSearchArea,
}: LedgerAccountsHomeProps) {
  const { dispatchError } = useDispatchContext();
  const { loading: accountsLoading, data: accountData, refetch } =
    useLedgerAccountSelectQuery({
      variables: {
        id: ledgerId,
        accountId: "",
      },
      fetchPolicy: "cache-and-network",
    });

  const [currencyFilter, setCurrencyFilter] = useState<string>("");
  const [bulkDeleteIds, setBulkDeleteIds] = useState<Array<string>>([]);
  const [deleteLedgerAccount] = useDeleteLedgerAccountMutation();
  const [deletionImpactMessage, setDeletionImpactMessage] = useState<string | null>(null);

  const cancelLedgerAccountDelete = useCallback(() => {
    setBulkDeleteIds([]);
    setDeletionImpactMessage(null);
    refetch();
  }, [refetch]);


  const onDeleteLedgerAccounts = useCallback(async (ledgerAccountIds: Array<string>): Promise<void> => {
    for (const ledgerAccountId of ledgerAccountIds) {
      try {
        const response = await deleteLedgerAccount({
          variables: {
            input: { id: ledgerAccountId },
          },
        });
        const { errors = [] } = response.data?.deleteLedgerAccount || {};
        if (errors.length) {
          dispatchError(`CDBI Deletion Error for ${ledgerAccountId}: ${errors.toString()}`);
        } else {
          trackEvent(null, LEDGERS_EVENTS.DELETE_LEDGER_ACCOUNT_CLICKED);
        }
      } catch (error: any) {
        dispatchError(`CDBI Deletion Error for ${ledgerAccountId}: ${error.message || 'An unknown error occurred.'}`);
      }
    }
    setBulkDeleteIds([]);
    setDeletionImpactMessage(null);
    refetch();
  }, [deleteLedgerAccount, dispatchError, refetch]);

  const onDelete = useCallback(async (ledgerAccountIds: Array<string>) => {
    if (ledgerAccountIds && ledgerAccountIds.length > 0) {
      setBulkDeleteIds(ledgerAccountIds);
      // AI-powered impact analysis before confirming deletion
      const impact = await AICDBILedgerService.analyzeDeletionImpact(ledgerId, ledgerAccountIds);
      setDeletionImpactMessage(impact);
    }
    return false;
  }, [ledgerId]);


  const uniqueLedgerAccountCurrencies = useMemo(() => {
    return new Map<string, number>(
      accountsLoading || !accountData
        ? []
        : accountData.ledgerAccounts.edges.map(({ node }) => [
            node.currency,
            Number.isNaN(node.currencyExponent)
              ? 2
              : Number(node.currencyExponent),
          ]),
    );
  }, [accountsLoading, accountData]);


  const mapQueryToVariables = useCallback((query: LedgerAccountQueryFilter) => {
    setCurrencyFilter(query.currency ?? "");

    return {
      id: query.id,
      name: query.name,
      effectiveAt: query.effective_at?.lte || new Date().toISOString(),
      description: query.description,
      metadata: query.metadata ? JSON.stringify(query.metadata) : null,
      currency: query.currency,
      postedBalanceAmount: query.currency ? query.posted_balance_amount : null,
      pendingBalanceAmount: query.currency
        ? query.pending_balance_amount
        : null,
    };
  }, []);

  const exportDataParams: ExportDataParams = {
    params: { ledger_id: ledgerId },
    ai_summary: "CDBI AI powered export. Includes predictive balance insights and anomaly flags.",
  };

  const searchComponents = useMemo(() => {
    return getLedgerAccountSearchComponents(
      uniqueLedgerAccountCurrencies,
      currencyFilter,
    );
  }, [uniqueLedgerAccountCurrencies, currencyFilter]);

  const accounts = useMemo(() => {
    return accountData?.ledgerAccounts?.edges.map(edge => edge.node) || [];
  }, [accountData]);


  return (
    <>
      {/* CDBI AI Insights Panel */}
      {!accountsLoading && accounts.length > 0 && (
        <AICDBIInsightsPanel ledgerId={ledgerId} accounts={accounts} />
      )}

      {bulkDeleteIds.length > 0 && (
        <ConfirmModal
          title="Delete Ledger Account(s)"
          isOpen={bulkDeleteIds.length > 0}
          onRequestClose={cancelLedgerAccountDelete}
          setIsOpen={cancelLedgerAccountDelete}
          confirmText="Delete Ledger Account(s)"
          confirmType="delete"
          onConfirm={() => {
            onDeleteLedgerAccounts(bulkDeleteIds);
          }}
        >
          Do you want to proceed with ledger account deletion? Once deleted, a
          ledger account cannot be recovered.
          {deletionImpactMessage && (
            <p className="mt-4 p-3 bg-yellow-50 border-l-4 border-yellow-500 text-sm text-yellow-800">
              <span className="font-bold">CDBI AI Impact Warning:</span> {deletionImpactMessage}
            </p>
          )}
        </ConfirmModal>
      )}
      <ListView
        actions={{
          Delete: (_actionName: string, ledgerAccountIds: Array<string>) =>
            onDelete(ledgerAccountIds),
        }}
        additionalSearchComponents={searchComponents.additionalComponents}
        constantQueryVariables={{
          ledgerId,
        }}
        enableActions
        favoritesEnabled
        defaultSearchComponents={searchComponents.defaultComponents}
        graphqlDocument={LedgerAccountsHomeDocument}
        initialShowSearchArea={initialShowSearchArea}
        horizontalDefaultSearchComponents
        customizableColumns
        constantQueryParams={CONSTANT_QUERY_PARAMS}
        resource={LEDGER_ACCOUNT}
        ListViewEmptyState={
          <div className="flex justify-center px-6 py-16">
            <LedgerAccountsEmptyState ledgerId={ledgerId} />
          </div>
        }
        enableExportData
        exportDataParams={exportDataParams}
        mapQueryToVariables={mapQueryToVariables}
        customSortOptions={[
          {
            label: "CDBI AI: Predicted Balance (Asc)",
            value: "ai_predicted_balance_asc",
          },
          {
            label: "CDBI AI: Predicted Balance (Desc)",
            value: "ai_predicted_balance_desc",
          },
          {
            label: "CDBI AI: Anomaly Severity (Desc)",
            value: "ai_anomaly_severity_desc",
          },
          {
            label: "CDBI AI: Health Score (Desc)",
            value: "ai_health_score_desc",
          },
        ]}
      />
    </>
  );
}

export default LedgerAccountsHome;