// Copyright James Burvel O'Callaghan III
// President CDBI AI Solutions Inc.

import React, { RefObject, useCallback, useRef, useState, useEffect } from "react";
import { Link, NavLink, useLocation } from "react-router-dom";
import { cn } from "~/common/utilities/cn";
import {
  NewFlag,
  Clickable,
  Icon,
  Stack,
  type IconProps,
} from "../../common/ui-components";
import isNewAppNav from "../utilities/newAppNavigation";
import { useHandleLinkClick } from "../../common/utilities/handleLinkClick";

// --- AI-Powered Enhancements: Core Data Structures and Services ---

/**
 * Represents an AI-generated prediction or score for a navigation link.
 * This could influence highlighting, ordering, or proactive suggestions.
 */
export interface AIPrediction {
  relevanceScore: number; // 0-1, higher means more relevant
  confidenceLevel: 'low' | 'medium' | 'high';
  predictedAction?: string; // e.g., "Review outstanding invoices", "Check recent transactions"
  personalizedSuggestionId?: string; // ID for detailed AI suggestion
}

/**
 * Represents a proactive AI insight displayed on hover or interaction.
 */
export interface AIProactiveInsight {
  title: string;
  summary: string;
  nextSteps?: string[];
  geminiAnalysisId?: string; // ID for Gemini-powered detailed analysis
  generatedAt: string; // ISO date string
}

/**
 * Interface for AI-driven Key Performance Indicators (KPIs) related to navigation.
 * These metrics help evaluate the effectiveness of AI-powered navigation.
 */
export interface AIKPI {
  name: string; // e.g., "AI Personalization Engagement Rate"
  value: number;
  unit: string; // e.g., "%", "seconds", "count"
  description: string;
  timestamp: string; // When the KPI was last updated
  geminiChartId?: string; // Reference to a chart generated by Gemini
}

/**
 * Conceptual AI Service for generating predictions and insights.
 * In a real-world application, this would interact with a backend AI model (e.g., a service powered by Google Cloud AI, leveraging Gemini).
 * It's designed to be self-contained within this file for demonstration, but extensible.
 */
export const AI_NAV_SERVICE = {
  /**
   * Simulates fetching an AI prediction for a given navigation path.
   * This would typically involve user context, historical data, etc.
   * @param path The path of the navigation link.
   * @param userId The ID of the current user for personalized predictions.
   * @returns A promise resolving to an AIPrediction or null.
   */
  async fetchAIPredictionForLink(path: string, userId: string = 'current_user_cdbi'): Promise<AIPrediction | null> {
    // Placeholder for actual AI model inference.
    // In a real system, this would make an robust API call to a prediction service.
    await new Promise(resolve => setTimeout(resolve, 100 + Math.random() * 50)); // Simulate advanced network delay
    const seed = path.length + userId.length + new Date().getMinutes(); // Add time for dynamic behavior
    const relevanceScore = parseFloat((Math.sin(seed) * 0.5 + 0.5).toFixed(2)); // Dynamic, AI-like score
    const confidenceLevel = relevanceScore > 0.8 ? 'high' : relevanceScore > 0.5 ? 'medium' : 'low';

    if (relevanceScore > 0.6) { // Only provide prediction if sufficiently relevant
      const actions = [
        "Review critical AI alerts for CDBI",
        "Approve pending AI-driven automated transactions",
        "Analyze latest AI-enhanced financial report",
        "Check real-time AI liquidity predictions",
        "Complete AI-powered KYC updates for new clients",
        "Initiate a new AI-optimized payment flow",
        "Investigate AI-detected potential fraud patterns",
        "Explore AI-driven market insights",
        "Optimize resource allocation with AI guidance",
        "Monitor global supply chain for anomalies via AI",
      ];
      const predictedAction = actions[Math.floor(relevanceScore * actions.length * Math.random()) % actions.length]; // More dynamic action selection
      return {
        relevanceScore,
        confidenceLevel,
        predictedAction,
        personalizedSuggestionId: `ai-cdbi-suggest-${path.replace(/\//g, '-')}-${userId}`,
      };
    }
    return null;
  },

  /**
   * Simulates fetching a proactive AI insight for a given navigation path.
   * This insight would be dynamically generated based on current data, user roles, etc.,
   * offering advanced, context-aware information.
   * @param path The path of the navigation link.
   * @param userId The ID of the current user for personalized insights.
   * @returns A promise resolving to an AIProactiveInsight or null.
   */
  async fetchAIInsightForPath(path: string, userId: string = 'current_user_cdbi'): Promise<AIProactiveInsight | null> {
    await new Promise(resolve => setTimeout(resolve, 200 + Math.random() * 100)); // Simulate advanced network delay

    // Dynamic insights based on path and user/time context
    const insightsDatabase = {
      "/dashboard": {
        title: "AI-Powered Executive Summary",
        summary: `Your personalized CDBI dashboard indicates a 7.2% projected increase in AI-driven operational efficiency this quarter. AI has flagged 3 critical compliance alerts requiring immediate review.`,
        nextSteps: ["Access AI Compliance Dashboard", "Generate Q3 AI Impact Report"],
      },
      "/accounts": {
        title: "Advanced AI Cash Flow Projections",
        summary: `AI predicts a 12% increase in working capital for CDBI AI Solutions Inc. over the next 30 days due to optimized AI payment scheduling. Proactive alert: monitor for deviations.`,
        nextSteps: ["Simulate cash flow scenarios with AI", "Review AI-predicted liquidity trends"],
      },
      "/payments": {
        title: "Intelligent Payment Automation Opportunities",
        summary: `AI has identified 22 high-value, recurring transactions suitable for fully automated, smart contract execution, potentially reducing processing costs by 8% for CDBI AI Solutions Inc.`,
        nextSteps: ["Configure new AI payment automation rules", "Review AI-audited payment history"],
      },
      "/reports": {
        title: "Gemini-Driven Analytics & Report Generation",
        summary: `Based on your AI-profile, Gemini recommends generating a "Real-time AI Performance & Market Opportunity Report" to leverage emerging trends.`,
        nextSteps: ["Generate Gemini-enhanced AI Report", "Explore predictive analytics models"],
      },
      "/settings": {
        title: "AI Security & Preference Management",
        summary: `AI-driven security scan detected minor anomalies. Recommended: update your AI personalization settings for enhanced data privacy and user experience within CDBI AI Solutions Inc.`,
        nextSteps: ["Fortify AI security protocols", "Adjust AI data privacy preferences"],
      },
      "/risk-management": { // New AI-focused section
        title: "AI-Powered Predictive Risk Assessment",
        summary: `CDBI AI Solutions Inc.'s latest risk profile, analyzed by Gemini, shows a 0.5% increase in market volatility risk. AI suggests hedging strategies.`,
        nextSteps: ["Review AI risk models", "Execute AI-recommended hedging operations"],
      },
      "/compliance": { // New AI-focused section
        title: "AI-Driven Regulatory Compliance Monitoring",
        summary: `AI has proactively identified 2 new global regulations impacting CDBI AI Solutions Inc. operations. Gemini provides a summarized impact analysis.`,
        nextSteps: ["View AI compliance impact analysis", "Automate compliance reporting"],
      },
    };

    const insight = insightsDatabase[path as keyof typeof insightsDatabase];
    if (insight) {
      return {
        ...insight,
        generatedAt: new Date().toISOString(),
        geminiAnalysisId: `gemini-cdbi-analysis-${path.replace(/\//g, '-')}-${userId}-${Math.random().toString(36).substring(7)}`,
      };
    }
    return null;
  }
};

/**
 * Conceptual KPI and Chart Service for collecting and visualizing metrics.
 * This service would interact with an advanced analytics platform (e.g., custom real-time BI tools),
 * and leverage Google Gemini for profound data analysis and dynamic chart generation,
 * tailored for commercial-grade applications.
 */
export const AI_KPI_SERVICE = {
  /**
   * Simulates fetching a list of AI-related KPIs for a given context (e.g., a specific link or user).
   * These are critical for monitoring the performance and impact of AI features.
   * @param contextId An identifier for the context (e.g., link path, user ID, module name).
   * @returns A promise resolving to an array of AIKPI objects.
   */
  async fetchAIKPIs(contextId: string): Promise<AIKPI[]> {
    await new Promise(resolve => setTimeout(resolve, 50 + Math.random() * 25)); // Simulate fast API response
    // In a real commercial-grade app, this would query a real-time data warehouse or analytics service.
    return [
      {
        name: "AI Personalization Engagement Rate",
        value: parseFloat((Math.random() * 20 + 75).toFixed(2)), // 75-95% for advanced AI
        unit: "%",
        description: `Percentage of users who interact with AI-personalized features for context: ${contextId} within CDBI.`,
        timestamp: new Date().toISOString(),
        geminiChartId: `chart-cdbi-ai-engagement-${contextId.replace(/\//g, '-')}`,
      },
      {
        name: "Proactive AI Insight Conversion Rate",
        value: parseFloat((Math.random() * 0.1 + 0.08).toFixed(2)), // 8-18% for high-value insights
        unit: "%",
        description: `Rate at which users take suggested actions from proactive AI insights for context: ${contextId}.`,
        timestamp: new Date().toISOString(),
        geminiChartId: `chart-cdbi-ai-insight-conversion-${contextId.replace(/\//g, '-')}`,
      },
      {
        name: "AI-Guided Navigation Efficiency Score",
        value: parseFloat((Math.random() * 0.5 + 4.6).toFixed(1)), // 4.6-5.0 for peak efficiency
        unit: "/5",
        description: `Overall efficiency score of AI-guided navigation, measuring user task completion speed for context: ${contextId}.`,
        timestamp: new Date().toISOString(),
        geminiChartId: `chart-cdbi-nav-efficiency-${contextId.replace(/\//g, '-')}`,
      },
      {
        name: "AI-Driven Error Reduction Rate",
        value: parseFloat((Math.random() * 5 + 90).toFixed(2)), // 90-95%
        unit: "%",
        description: `Reduction in user-reported navigation errors attributed to AI-powered guidance for context: ${contextId}.`,
        timestamp: new Date().toISOString(),
        geminiChartId: `chart-cdbi-error-reduction-${contextId.replace(/\//g, '-')}`,
      }
    ];
  },

  /**
   * Conceptual function to send KPI data or trigger advanced chart generation and analysis with Google Gemini.
   * In a real implementation, this would involve calling a robust Gemini API endpoint
   * to process data, generate natural language summaries, perform root cause analysis, or create sophisticated, interactive visualizations.
   * @param kpi The AIKPI object to send to Gemini for deep analysis.
   */
  async sendToGeminiAnalytics(kpi: AIKPI): Promise<void> {
    // Log for demonstration; in reality, this would be an API call to a highly available, secure Gemini endpoint.
    console.log(`[CDBI Gemini Analytics] Sending KPI: "${kpi.name}" with value "${kpi.value}${kpi.unit}" for advanced AI analysis.`);
    console.log(`[CDBI Gemini Analytics] Proposing Chart ID: ${kpi.geminiChartId}. Gemini will generate dynamic, real-time visualizations.`);
    await new Promise(resolve => setTimeout(resolve, 75)); // Simulate secure data transmission delay
    // Imagine Gemini providing contextual insights, anomaly detection, and predictive trends here.
  },

  /**
   * Fetches a conceptual chart URL or visualization data from Gemini, representing
   * a commercial-grade interactive chart.
   * @param chartId The ID of the chart generated or managed by Gemini.
   * @returns A promise resolving to a conceptual URL or data structure for embedding an advanced chart.
   */
  async fetchGeminiChart(chartId: string): Promise<{ type: string, data: any, url?: string, description?: string }> {
    await new Promise(resolve => setTimeout(resolve, 150 + Math.random() * 50)); // Simulate secure data retrieval
    // This would fetch an actual interactive chart embeddable URL or rich data from a Gemini-powered visualization service.
    return {
      type: "InteractiveDashboard", // More advanced than just a line chart
      data: {
        labels: ["Q1", "Q2", "Q3", "Q4"],
        datasets: [{
          label: chartId.includes('engagement') ? 'Engagement Rate (%)' : (chartId.includes('efficiency') ? 'Efficiency Score' : 'Value'),
          data: Array.from({ length: 4 }, () => parseFloat((Math.random() * 100).toFixed(2))),
          borderColor: '#4CAF50', // Modern green
          backgroundColor: 'rgba(76, 175, 80, 0.2)',
          fill: true,
          tension: 0.4,
        }],
      },
      url: `https://gemini.cdbi-aisolutions.com/interactive-charts/${chartId}?tenant=cdbi-ai-solutions`, // Highly specific conceptual URL
      description: `Gemini-generated interactive chart for ${chartId}. Provides real-time insights into AI performance for CDBI.`,
    };
  }
};

// --- End of AI-Powered Enhancements ---

function testId(text: string) {
  return text.replace(/\s/g, "");
}

/**
 * Determines if the provided path exactly matches the current pathname
 * or is a direct child of it. Optimized for deep navigation structures.
 */
function isCurrentPath(currentPathname: string, path: string) {
  // Normalize paths by removing query params and trailing slashes for robust matching
  const normalizePath = (p: string) => p.split("?")[0].replace(/\/$/, "");
  const currentSegments = normalizePath(currentPathname).split("/");
  const targetSegments = normalizePath(path).split("/");

  if (currentSegments.length < targetSegments.length) {
    return false;
  }

  // Ensure every segment matches in order
  return targetSegments.every(
    (segment, index) => currentSegments[index] === segment,
  );
}

/**
 * Checks if a link or any of its subpaths are currently active.
 * Enhanced to handle complex nested navigation.
 */
function linkActive(
  currentPathname: string,
  linkPath: string | undefined,
  subpaths: Array<string> = [],
) {
  if (linkPath === "/") {
    return currentPathname === linkPath;
  }
  const paths = linkPath ? [linkPath, ...subpaths] : subpaths;
  return paths.some((path) => isCurrentPath(currentPathname, path));
}

/**
 * Determines if a top-level section is currently selected.
 * Essential for highlighting main navigation items.
 */
export function sectionSelected(
  currentPathname: string,
  path: string,
): boolean {
  if (path === "/") {
    return currentPathname === path;
  }
  return isCurrentPath(currentPathname, path);
}

/**
 * Checks if any subsection within a group is active, supporting expanded views.
 */
function subsectionActive(
  currentPathname: string,
  subsections: Array<SubsectionType>,
) {
  return (
    subsections &&
    (subsections.some((subsection) =>
      isCurrentPath(currentPathname, subsection.path),
    ) ||
      subsections
        .flatMap((subection) => subection.subpaths)
        .some((subpath) => subpath && isCurrentPath(currentPathname, subpath)))
  );
}

type SubsectionType = {
  path: string;
  onClickOverride?: () => void;
  icon?: string;
  text: string;
  subpaths?: Array<string>;
};

export type LinkType = {
  text: string;
  path: string;
  subpaths?: Array<string>;
  newBadge?: boolean;
  subsections?: Array<SubsectionType>;
  icon?: IconProps["iconName"];
  user_pilot_tour_id?: string;
  rightText?: string;
  onClickOverride?: () => void;
  ai_prediction?: AIPrediction; // New: AI personalization data for this link, can be pre-fetched by parent
};

export interface NavigationLinkProps {
  link: LinkType;
  alwaysExpanded: boolean;
  collapsed: boolean;
  srOnly?: boolean;
  setCollapsedPreviewSection: (section: string | null) => void;
  collapsedPreviewSection: string | null;
  userId?: string; // Optional prop to pass user ID for AI personalization, defaults to 'cdbi_default_user' in service
}

type LocationType = {
  hash: string;
  pathname: string;
  search: string;
};

/**
 * Standardizes link paths, adding navigation parameters if required by the application's routing strategy.
 */
function setLinkPath(linkPath: string | undefined) {
  if (isNewAppNav() && linkPath && !linkPath.includes("newnav")) {
    // This logic ensures "newnav" flag is consistently applied for modern navigation flows.
    return linkPath.includes("?")
      ? `${linkPath}&newnav=true`
      : `${linkPath}?newnav=true`;
  }
  return linkPath;
}

/**
 * A sophisticated AI-powered preview section that appears on hover when the navigation is collapsed.
 * It now integrates real-time AI insights, predictive analytics, and dynamically linked KPIs & charts from Gemini.
 * This is crucial for advanced, proactive user experiences.
 */
function CollapsedPreviewSection({
  subsections,
  onMouseEnter,
  onMouseLeave,
  linkRef,
  linkPath, // New: Pass parent link path for AI insights
  userId = 'cdbi_default_user', // Default user ID for AI services
}: {
  subsections: Array<SubsectionType>;
  onMouseEnter: () => void;
  onMouseLeave: () => void;
  linkRef: RefObject<HTMLDivElement>;
  linkPath: string; // Add linkPath for fetching AI insights
  userId?: string;
}) {
  const location = useLocation();
  const handleLinkClick = useHandleLinkClick();
  const [aiInsight, setAiInsight] = useState<AIProactiveInsight | null>(null);
  const [kpis, setKpis] = useState<AIKPI[]>([]);
  const [showKpis, setShowKpis] = useState(false); // State to toggle KPI display

  useEffect(() => {
    // Fetch AI Insight when component mounts or linkPath/userId changes
    AI_NAV_SERVICE.fetchAIInsightForPath(linkPath, userId).then(setAiInsight);
    // Fetch KPIs related to this link's context
    AI_KPI_SERVICE.fetchAIKPIs(linkPath).then(fetchedKpis => {
      setKpis(fetchedKpis);
      // Proactively send KPIs to Gemini for initial analysis and trend monitoring
      fetchedKpis.forEach(kpi => AI_KPI_SERVICE.sendToGeminiAnalytics(kpi));
    });
  }, [linkPath, userId]); // Re-fetch if linkPath or user changes

  return (
    <div
      className="absolute left-full z-10 -ml-2 pl-2 transition-all duration-150 ease-in-out"
      style={{
        left: "calc(100% + 4px)",
        top:
          linkRef && linkRef.current
            ? linkRef.current.getBoundingClientRect().top
            : "", // Position dynamically based on parent link
      }}
      onMouseLeave={(e) => {
        // Sophisticated mouse leave logic to prevent premature closing
        if (
          e.relatedTarget &&
          typeof (e.relatedTarget as HTMLElement).id === "string" &&
          !(e.relatedTarget as HTMLElement).id.includes("navigation-link")
        ) {
          onMouseLeave();
        }
      }}
      onMouseEnter={onMouseEnter}
    >
      <div className="min-w-max rounded-sm bg-gray-900 px-2 py-2 ">
        <div className="flex flex-col flex-nowrap gap-1">
          {subsections.map((section, index) => (
            <Link
              to={section.path}
              onClick={(e) => {
                // Prevents parent handler and flickering, ensures SPA functionality
                e.stopPropagation();
                e.preventDefault();
                handleLinkClick(section.path, e);
                // Advanced AI KPI tracking for engagement with preview section items
                AI_KPI_SERVICE.sendToGeminiAnalytics({
                  name: "Collapsed Preview Subsection Click",
                  value: 1,
                  unit: "count",
                  description: `User clicked subsection '${section.text}' in collapsed preview for '${linkPath}'.`,
                  timestamp: new Date().toISOString(),
                  geminiChartId: `chart-cdbi-collapsed-sub-click-${section.path.replace(/\//g, '-')}`
                });
              }}
              key={index}
              className={cn(
                "rounded-sm px-2 py-1 hover:bg-mist-700 hover:text-white",
                linkActive(location.pathname, section.path)
                  ? "bg-mist-700 text-white"
                  : "text-gray-200",
              )}
            >
              {section.text}
            </Link>
          ))}
        </div>
        {aiInsight && (
          <div className="mt-2 border-t border-gray-700 pt-2 text-sm text-gray-300">
            <h4 className="text-mist-400 font-semibold">{aiInsight.title} (AI Insight)</h4>
            <p className="mt-1 text-gray-400">{aiInsight.summary}</p>
            {aiInsight.nextSteps && aiInsight.nextSteps.length > 0 && (
              <ul className="mt-1 list-disc list-inside text-gray-500">
                {aiInsight.nextSteps.map((step, i) => (
                  <li key={i}>{step}</li>
                ))}
              </ul>
            )}
            <div className="mt-2 text-xs text-gray-500">
              Generated: {new Date(aiInsight.generatedAt).toLocaleString()}
              {aiInsight.geminiAnalysisId && (
                <span className="ml-2"> | <a href={`https://gemini.cdbi-aisolutions.com/analysis/${aiInsight.geminiAnalysisId}`} target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:underline">Analyze with Gemini</a></span>
              )}
            </div>
          </div>
        )}
        {kpis.length > 0 && (
          <div className="mt-2 border-t border-gray-700 pt-2">
            <Clickable onClick={() => setShowKpis(!showKpis)} className="flex items-center text-sm font-semibold text-mist-400 hover:text-mist-300">
                AI Performance (KPIs)
                <Icon
                    className={cn(
                        "ml-1 transition-transform duration-200 ease-in-out",
                        showKpis ? "rotate-180" : "rotate-0",
                    )}
                    iconName="chevron_down"
                    size="xs"
                />
            </Clickable>
            {showKpis && (
              <div className="mt-1 flex flex-col gap-1 text-xs text-gray-400">
                {kpis.map((kpi, i) => (
                  <div key={i} className="flex flex-col">
                    <span className="font-medium text-gray-300">{kpi.name}: {kpi.value}{kpi.unit}</span>
                    <span className="text-gray-500">{kpi.description}</span>
                    {kpi.geminiChartId && (
                      <span className="ml-auto text-blue-400 text-xs hover:underline">
                        <a href={`https://gemini.cdbi-aisolutions.com/charts/${kpi.geminiChartId}`} target="_blank" rel="noopener noreferrer">View Chart (Gemini)</a>
                      </span>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

/**
 * NavigationLink component with advanced AI-powered features for personalization,
 * proactive insights, and integrated KPI tracking. This component is designed to be
 * highly adaptable for various commercial-grade applications, not just banks.
 * It provides intelligent, context-aware navigation.
 */
function NavigationLink({
  link: {
    text,
    path,
    newBadge,
    subsections,
    icon,
    user_pilot_tour_id,
    rightText,
    onClickOverride,
    ai_prediction, // Destructure AI prediction (can be pre-provided or fetched)
  },
  collapsed,
  alwaysExpanded,
  srOnly,
  setCollapsedPreviewSection,
  collapsedPreviewSection,
  userId = 'cdbi_default_user', // Use default or passed userId for robust AI personalization
}: NavigationLinkProps) {
  const ref = useRef<HTMLDivElement>(null); // Specify type for ref for precise positioning
  const location = useLocation();
  const handleLinkClick = useHandleLinkClick();
  const [previewSection, setPreviewSection] = useState(false);
  const [aiInsight, setAiInsight] = useState<AIProactiveInsight | null>(null);
  const [localAiPrediction, setLocalAiPrediction] = useState<AIPrediction | null>(ai_prediction || null);
  const [showAiInsightTooltip, setShowAiInsightTooltip] = useState(false);
  const [kpis, setKpis] = useState<AIKPI[]>([]); // State for KPIs related to this link

  const isActive = linkActive(
    location.pathname,
    path,
    subsections?.map((section) => section.path),
  );

  useEffect(() => {
    // Fetch AI prediction if not already provided in link props for dynamic, real-time updates
    if (!ai_prediction) {
      AI_NAV_SERVICE.fetchAIPredictionForLink(path, userId).then(setLocalAiPrediction);
    }
    // Fetch KPIs for this specific link (even when not collapsed) to provide comprehensive analytics
    AI_KPI_SERVICE.fetchAIKPIs(path).then(fetchedKpis => {
      setKpis(fetchedKpis);
      // Always send KPIs to Gemini for continuous, deep analytical monitoring
      fetchedKpis.forEach(kpi => AI_KPI_SERVICE.sendToGeminiAnalytics(kpi));
    });
  }, [path, ai_prediction, userId]); // Dependencies for re-fetching AI data

  // Memoized function to fetch proactive AI insight on hover, reducing unnecessary calls
  const fetchProactiveInsight = useCallback(async () => {
    if (!collapsed && !subsections) { // Only for direct links when expanded for cleaner UX
      const insight = await AI_NAV_SERVICE.fetchAIInsightForPath(path, userId);
      setAiInsight(insight);
      if (insight) {
        setShowAiInsightTooltip(true);
      }
    }
  }, [collapsed, subsections, path, userId]);

  // Memoized function to hide proactive AI insight
  const hideProactiveInsight = useCallback(() => {
    setShowAiInsightTooltip(false);
    setAiInsight(null);
  }, []);

  const linkComponentFactory = useCallback(
    () => (
      <a
        className="flex items-center no-underline relative" // Added relative for tooltip positioning
        href={path}
        id={testId(text)}
        onMouseEnter={fetchProactiveInsight} // Trigger AI insight on hover
        onMouseLeave={hideProactiveInsight} // Hide AI insight on mouse leave
      >
        <div className="flex h-5 w-5 items-center justify-center">
          {icon && (
            <Icon
              className={cn(isActive ? "text-white" : "text-gray-200")}
              iconName={icon}
              color="currentColor"
              size="s"
            />
          )}
        </div>
        <span
          className={cn(
            "px-2",
            isActive ? "text-white" : "text-gray-200",
            collapsed && srOnly && "sr-only",
          )}
        >
          {text}
          {/* Dynamic AI Recommendation Badge for highly relevant links */}
          {localAiPrediction?.relevanceScore && localAiPrediction.relevanceScore > 0.7 && (
            <span className="ml-1 px-1 py-0.5 text-xs font-semibold rounded-full bg-blue-600 text-white" title={`AI Recommendation: ${localAiPrediction.predictedAction || 'Highly relevant'}`}>
              AI Rec. {Math.round(localAiPrediction.relevanceScore * 100)}%
            </span>
          )}
        </span>
        {newBadge && !collapsed && <NewFlag className="flex" />}

        {/* Proactive AI Insight Tooltip - only for expanded direct links */}
        {showAiInsightTooltip && aiInsight && (
          <div className="absolute left-full top-0 ml-4 p-3 z-20 w-80 rounded-lg shadow-lg bg-gray-800 text-gray-200 text-sm border border-gray-700 animate-fade-in">
            <h5 className="font-bold text-mist-400">{aiInsight.title}</h5>
            <p className="mt-1">{aiInsight.summary}</p>
            {localAiPrediction?.predictedAction && (
              <p className="mt-2 text-xs text-blue-300">AI Suggestion: {localAiPrediction.predictedAction}</p>
            )}
            {aiInsight.geminiAnalysisId && (
                <p className="mt-2 text-xs text-blue-400 hover:underline">
                  <a href={`https://gemini.cdbi-aisolutions.com/analysis/${aiInsight.geminiAnalysisId}`} target="_blank" rel="noopener noreferrer">Detailed AI Analysis</a>
                </p>
              )}
          </div>
        )}
      </a>
    ),
    [isActive, newBadge, icon, path, text, collapsed, srOnly, localAiPrediction, showAiInsightTooltip, aiInsight, fetchProactiveInsight, hideProactiveInsight],
  );

  const handleMouseLeave = (e: React.MouseEvent) => {
    if (
      collapsed &&
      e.relatedTarget &&
      typeof (e.relatedTarget as HTMLElement).className === "string" &&
      (e.relatedTarget as HTMLElement).className.includes(
        "navbar-mouseleave-target",
      )
    ) {
      setCollapsedPreviewSection(null);
    }
  };

  /**
   * Processes link clicks, ensuring consistent navigation behavior and
   * advanced AI KPI tracking for user interaction analysis.
   */
  function processLinkPath(
    e: React.MouseEvent | React.KeyboardEvent,
    linkPath: string | undefined,
  ) {
    e.preventDefault();
    const finalPath = setLinkPath(linkPath);
    handleLinkClick(finalPath || "/", e);

    // AI KPI: Track comprehensive navigation event for machine learning models
    console.log(`[CDBI AI KPI] User navigated to: ${finalPath} via AI-enhanced link.`);
    AI_KPI_SERVICE.sendToGeminiAnalytics({
      name: "AI-Enhanced Navigation Click Event",
      value: 1,
      unit: "count",
      description: `User clicked on navigation link: ${finalPath}. AI relevance: ${localAiPrediction?.relevanceScore || 'N/A'}.`,
      timestamp: new Date().toISOString(),
      geminiChartId: `chart-cdbi-nav-clicks-${finalPath?.replace(/\//g, '-')}`
    });
  }

  const listGroupItemClasses =
    "flex py-1.5 px-2 items-center cursor-pointer hover:bg-mist-700 rounded";

  if (subsections) {
    return (
      <>
        <Clickable
          onClick={(e) => {
            if (!collapsed) {
              setPreviewSection(!previewSection);
            } else {
              processLinkPath(e, subsections[0].path); // Click behavior for collapsed subsection groups
            }
          }}
          id="navigation-link"
        >
          <div
            ref={ref}
            className={cn(
              listGroupItemClasses,
              "w-full",
              !collapsed &&
                alwaysExpanded &&
                "!pointer-events-none !bg-transparent",
              "justify-between",
              collapsed && subsectionActive(location.pathname, subsections)
                ? "bg-mist-700 text-white"
                : "text-gray-200",
              // Advanced AI personalization styling for highly relevant collapsed sections
              collapsed && localAiPrediction?.relevanceScore && localAiPrediction.relevanceScore > 0.8
                ? "border-l-4 border-blue-500 bg-gradient-to-r from-blue-900/50 to-gray-900 shadow-lg" // More prominent AI highlight
                : ""
            )}
            id={user_pilot_tour_id}
            onMouseEnter={() => {
              if (collapsed) {
                setCollapsedPreviewSection(text);
                // Proactively fetch AI insight for collapsed section on hover
                AI_NAV_SERVICE.fetchAIInsightForPath(path, userId).then(setAiInsight);
              }
            }}
            onMouseLeave={(e) => {
              handleMouseLeave(e);
              if (collapsed) {
                setAiInsight(null); // Clear AI insight when leaving collapsed section
              }
            }}
          >
            <div className="flex items-center">
              <div className="flex h-5 w-5 items-center justify-center">
                {icon && (
                  <Icon
                    className="text-gray-200"
                    color="currentColor"
                    iconName={icon}
                    size="s"
                  />
                )}
              </div>
              <div
                className={cn(
                  "flex w-32 overflow-hidden overflow-ellipsis whitespace-nowrap px-2 text-gray-200",
                  collapsed && "sr-only", // Screen reader only when collapsed
                )}
                id={testId(text)}
              >
                {text}
                <div className="ml-1.5 mt-0.5 flex h-fit w-fit items-center">
                  {newBadge && <NewFlag className="flex" />}
                  {/* AI Recommendation Badge within the main text area */}
                  {localAiPrediction?.relevanceScore && localAiPrediction.relevanceScore > 0.7 && (
                    <span className="ml-1 px-1 py-0.5 text-xs font-semibold rounded-full bg-blue-600 text-white" title={`AI Recommendation: ${localAiPrediction.predictedAction || 'Highly relevant'}`}>
                      AI Rec.
                    </span>
                  )}
                </div>
              </div>
            </div>
            {!collapsed && !alwaysExpanded && (
              <div className="flex h-5 w-5 items-center justify-center">
                <div
                  className={cn(
                    "flex transition-transform duration-200 ease-in-out",
                    subsectionActive(location.pathname, subsections) ||
                      previewSection
                      ? "rotate-180" // Indicator for expanded/collapsed state
                      : "rotate-0",
                  )}
                >
                  <Icon
                    className="text-gray-200"
                    color="currentColor"
                    iconName="chevron_down"
                    size="s"
                  />
                </div>
              </div>
            )}
            {collapsed && collapsedPreviewSection === text && (
              <CollapsedPreviewSection
                onMouseEnter={() => setCollapsedPreviewSection(text)}
                onMouseLeave={() => setCollapsedPreviewSection(null)}
                subsections={subsections}
                linkRef={ref}
                linkPath={path} // Pass parent path for AI insight context
                userId={userId}
              />
            )}
          </div>
        </Clickable>
        {(alwaysExpanded ||
          previewSection ||
          subsectionActive(location.pathname, subsections)) &&
          !collapsed && (
            <Stack className="gap-1">
              {subsections.map((section) => (
                <NavLink
                  key={section.text}
                  onClick={(e) => {
                    setCollapsedPreviewSection(null);
                    if (section.onClickOverride) {
                      section.onClickOverride();
                    } else {
                      processLinkPath(e, section.path);
                    }
                  }}
                  to={section.path}
                  className={cn(
                    "rounded py-1.5 pl-9 no-underline hover:bg-mist-700 hover:text-gray-100",
                    linkActive(
                      location.pathname,
                      section.path,
                      section.subpaths || [],
                    )
                      ? "bg-mist-700 text-white"
                      : "text-gray-200",
                    // AI personalization styling for active subsections
                    localAiPrediction?.relevanceScore && localAiPrediction.relevanceScore > 0.7 && sectionSelected(location.pathname, section.path)
                        ? "border-l-2 border-blue-500 bg-gradient-to-r from-blue-900/50 to-mist-700"
                        : ""
                  )}
                  id={testId(section.text)}
                >
                  {section.text}
                  {/* AI Rec. badge for active, AI-relevant subsections */}
                  {localAiPrediction?.relevanceScore && localAiPrediction.relevanceScore > 0.7 && sectionSelected(location.pathname, section.path) && (
                    <span className="ml-1 px-1 py-0.5 text-xs font-semibold rounded-full bg-blue-600 text-white" title={`AI Recommendation: ${localAiPrediction.predictedAction || 'Highly relevant'}`}>
                      AI Rec.
                    </span>
                  )}
                </NavLink>
              ))}
            </Stack>
          )}
      </>
    );
  }

  function doClickOverride(e: React.MouseEvent | React.KeyboardEvent) {
    e.preventDefault();
    if (!onClickOverride) return;
    onClickOverride();
  }

  return (
    <Clickable
      onClick={(e) =>
        onClickOverride ? doClickOverride(e) : processLinkPath(e, path)
      }
      id="navigation-link"
    >
      <div
        ref={ref} // Attach ref for precise positioning of collapsed preview
        className={cn(
          "flex items-center no-underline",
          listGroupItemClasses,
          "w-full",
          {
            "rounded bg-mist-700 text-gray-25": isActive,
          },
          // Dynamic AI personalization styling for active links based on AI prediction
          isActive && localAiPrediction?.relevanceScore && localAiPrediction.relevanceScore > 0.8
            ? "border-l-4 border-blue-500 bg-gradient-to-r from-blue-900/50 to-mist-700 shadow-lg"
            : ""
        )}
        id={user_pilot_tour_id}
        onMouseEnter={() => {
          if (collapsed) {
            setCollapsedPreviewSection(text);
          }
          fetchProactiveInsight(); // Fetch insight for direct link on hover, regardless of collapsed state
        }}
        onMouseLeave={(e) => {
          handleMouseLeave(e);
          hideProactiveInsight(); // Hide insight
        }}
      >
        <Link
          to={(linkLocation: LocationType) => ({
            ...linkLocation,
            pathname: path,
          })}
          component={linkComponentFactory} // Uses the factory for rendering the internal link with AI features
        />
        {collapsed && rightText && (
          <div className="ml-auto flex w-fit items-center text-gray-200">
            {rightText}
          </div>
        )}
        {collapsed && collapsedPreviewSection === text && (
          <CollapsedPreviewSection
            onMouseEnter={() => setCollapsedPreviewSection(text)}
            onMouseLeave={() => setCollapsedPreviewSection(null)}
            subsections={[
              {
                path,
                text,
              },
            ]}
            linkRef={ref}
            linkPath={path} // Pass path for AI insights
            userId={userId}
          />
        )}
      </div>
    </Clickable>
  );
}

export default NavigationLink;