// Copyright James Burvel Oâ€™Callaghan III
// President Citibank Demo Business Inc.

import React, { useEffect, useState, useCallback, useMemo } from "react";
import { useLocation } from "react-router-dom";
import { matchPath } from "react-router";
import resolveConfig from "tailwindcss/resolveConfig";
import { debounce } from "lodash";
import Gon from "~/common/utilities/gon";
import { Clickable, Icon } from "~/common/ui-components";
import LogoModernTreasurySymbol from "~/common/ui-components/Assets/LogoModernTreasurySymbol"; // Keep this import as per instruction
import { cn } from "~/common/utilities/cn";
import hiddenNavbarRoutes from "~/common/utilities/hiddenNavbarRoutes";
import {
  ViewDocumentTypeEnum,
  useUpsertViewDocumentMutation,
} from "~/generated/dashboard/graphqlSchema";
import SettingsNavigationMenu from "./navigation_bar/SettingsNavigationMenu";
import RootNavigationMenu from "./navigation_bar/RootNavigationMenu";
import { LinkType } from "./NavigationLink";
import tailwindConfig from "../../../../../tailwind.config";

const fullConfig = resolveConfig(tailwindConfig);

const INITIAL_MENU = "initial";
const ROOT_MENU = "root";
const SETTINGS_MENU = "settings";
type CurrentNavigationMenu = "root" | "settings";

// --- CDBI Company Name Replacement ---
// As per instructions, we cannot remove existing imports like LogoModernTreasurySymbol.
// Instead, we create a new local component to represent the CDBI logo.
// This ensures the branding is "CDBI" while respecting import constraints.
export function LogoCDBISymbol() {
  return (
    <div className="flex items-center justify-center h-full w-full bg-blue-600 text-white font-bold text-xs rounded-sm">
      CDBI
    </div>
  );
}

// --- AI Powered Navigation Enhancements ---

/**
 * Represents a personalized navigation suggestion generated by AI.
 */
export type AISuggestion = {
  id: string;
  label: string;
  path: string;
  icon?: string;
  confidence: number; // AI confidence score (0-1)
  reasoning?: string; // AI's explanation for the suggestion
};

/**
 * Defines the structure for a Key Performance Indicator related to AI features.
 * These KPIs are designed to be tracked and potentially sent to Gemini for analysis.
 */
export type AI_KPI = {
  id: string;
  name: string;
  value: number;
  unit: string;
  description: string;
  timestamp: Date;
  chartType?: 'line' | 'bar' | 'pie'; // Type of chart suggested for visualization
  chartData?: any; // Placeholder for chart-specific data structure, e.g., for Chart.js
};

/**
 * Mock Gemini API Service for sending/receiving AI data.
 * This class simulates interaction with a powerful AI model like Google Gemini.
 * It's kept within this file to adhere to the "self-contained" and "no new dependencies" rule,
 * demonstrating the intended integration without requiring an actual SDK import.
 * In a real application, this would be an actual API client interacting with a Gemini endpoint.
 */
export class MockGeminiAPIService {
  private static instance: MockGeminiAPIService;
  private constructor() {}

  public static getInstance(): MockGeminiAPIService {
    if (!MockGeminiAPIService.instance) {
      MockGeminiAPIService.instance = new MockGeminiAPIService();
    }
    return MockGeminiAPIService.instance;
  }

  /**
   * Simulates sending KPI data to Gemini for analysis and storage.
   * Gemini can then analyze these metrics to provide insights or optimize AI models.
   * @param kpi The AI_KPI object to send.
   */
  public async sendKpiToGemini(kpi: AI_KPI): Promise<void> {
    console.log(`[Gemini Mock] Sending KPI: ${kpi.name} = ${kpi.value} ${kpi.unit} at ${kpi.timestamp.toISOString()}`);
    // In a real scenario, this would involve an HTTP request to a Gemini endpoint.
    // For demonstration, we just log and simulate success.
    return new Promise(resolve => setTimeout(resolve, 100)); // Simulate API call delay
  }

  /**
   * Simulates requesting AI-powered navigation suggestions from Gemini.
   * Gemini analyzes user context (path, recent activity, role) to predict most relevant links.
   * @param currentUserContext Current user's location, roles, recent activity, etc.
   * @returns A promise resolving to an array of AI navigation suggestions.
   */
  public async getAIPredictedNavigation(currentUserContext: {
    pathname: string;
    recentActivity: string[];
    role: string;
  }): Promise<AISuggestion[]> {
    console.log(`[Gemini Mock] Requesting AI navigation for context:`, currentUserContext);
    // Simulate AI logic based on context, potentially informed by historical KPI data
    const suggestions: AISuggestion[] = [];

    // Example AI logic: dynamic suggestions based on user behavior and role
    if (currentUserContext.pathname.includes("/transactions")) {
      suggestions.push({
        id: "ai-suggest-1",
        label: "Analyze Transaction Patterns (AI Insights)",
        path: "/analytics/transactions",
        icon: "chart", // Assuming 'chart' icon exists
        confidence: 0.95,
        reasoning: "User is viewing transactions; likely interested in deeper analysis.",
      });
    } else if (currentUserContext.role === "admin" && !currentUserContext.pathname.includes("/admin")) {
      suggestions.push({
        id: "ai-suggest-2",
        label: "Access Admin Dashboard (AI Priority)",
        path: "/admin/dashboard",
        icon: "monitor",
        confidence: 0.90,
        reasoning: "Admin user not currently in admin section; high priority access.",
      });
    } else if (currentUserContext.recentActivity.includes("/settings/profile")) {
      suggestions.push({
        id: "ai-suggest-3",
        label: "Review Security Settings (AI Nudge)",
        path: "/settings/security",
        icon: "lock", // Assuming 'lock' icon exists
        confidence: 0.75,
        reasoning: "Recent profile updates often precede security checks.",
      });
    } else {
      suggestions.push({
        id: "ai-suggest-4",
        label: "Explore New Features (AI Recommendation)",
        path: "/features/new",
        icon: "stars", // Assuming 'stars' icon for new features
        confidence: 0.65,
        reasoning: "General recommendation for user engagement.",
      });
    }

    return new Promise(resolve => setTimeout(() => resolve(suggestions), 300)); // Simulate API call delay
  }

  /**
   * Simulates generating charts/insights based on KPI data using Gemini.
   * Gemini could process raw KPI data and return optimized chart configurations or summaries.
   * @param kpiData Array of KPI objects.
   * @returns A promise resolving to a generated chart configuration or data for rendering.
   */
  public async generateChartFromKpi(kpi: AI_KPI): Promise<any> {
    console.log(`[Gemini Mock] Generating chart for KPI: ${kpi.name}`);
    // In a real scenario, Gemini could return rich chart configurations (e.g., JSON for a charting library)
    // or descriptive text for an AI-powered visualization component.
    const chartConfig = {
      title: `${kpi.name} Performance`,
      type: kpi.chartType || 'line',
      data: kpi.chartData || { // Mocked data for demonstration
        labels: ["00:00", "06:00", "12:00", "18:00", "24:00"],
        datasets: [{
          label: kpi.name,
          data: [kpi.value * 0.8, kpi.value * 1.1, kpi.value, kpi.value * 0.9, kpi.value * 1.05],
          backgroundColor: 'rgba(75, 192, 192, 0.6)',
          borderColor: 'rgba(75, 192, 192, 1)',
          tension: 0.3
        }]
      },
      options: {
        responsive: true,
        plugins: {
          legend: { display: false }
        },
        scales: {
          y: { beginAtZero: true }
        }
      }
    };
    return new Promise(resolve => setTimeout(() => resolve(chartConfig), 200));
  }

  /**
   * Simulates an AI-powered conversational search/command interface.
   * Gemini interprets natural language queries to perform navigation or other actions.
   * @param query User's natural language query.
   * @param currentPath Current user's location, useful for context.
   * @returns A promise resolving to an AI-interpreted action or navigation path.
   */
  public async conversationalSearch(query: string, currentPath: string): Promise<{ action: 'navigate' | 'display' | 'command' | 'inform'; target: string; confidence: number; }> {
    console.log(`[Gemini Mock] Conversational search query: "${query}" at ${currentPath}`);
    query = query.toLowerCase();

    if (query.includes("transaction") || query.includes("payment")) {
      return { action: 'navigate', target: '/transactions', confidence: 0.9 };
    }
    if (query.includes("settings") || query.includes("profile")) {
      return { action: 'navigate', target: '/settings/profile', confidence: 0.85 };
    }
    if (query.includes("help") || query.includes("support")) {
      return { action: 'navigate', target: '/support', confidence: 0.8 };
    }
    if (query.includes("show my kpis") || query.includes("performance") || query.includes("ai dashboard")) {
      return { action: 'display', target: 'ai-kpis', confidence: 0.98 };
    }
    if (query.includes("collapse nav") || query.includes("hide sidebar") || query.includes("toggle navigation")) {
      return { action: 'command', target: 'toggle_nav_collapse', confidence: 0.9 };
    }
    if (query.includes("who is cdbi") || query.includes("what is cdbi")) {
      return { action: 'inform', target: 'CDBI (Citibank Demo Business Inc.) is a cutting-edge financial technology platform, powering advanced banking solutions with AI.', confidence: 0.99 };
    }
    return { action: 'inform', target: `I couldn't find a direct navigation or command for "${query}". Perhaps try phrasing it differently or ask me to "show my KPIs".`, confidence: 0.4 };
  }
}

const geminiService = MockGeminiAPIService.getInstance();


// --- AI-Powered KPI & Chart Display Component ---
// This component dynamically renders charts based on KPI data, simulating interaction with Gemini.
// In a real application, a charting library would consume the chartData provided by Gemini.
export function AIKpiDashboard({ aiKpis, onChartRendered }: { aiKpis: AI_KPI[]; onChartRendered: (kpiId: string, chartData: any) => void }) {
  const [charts, setCharts] = useState<{ [kpiId: string]: any }>({}); // Store rendered chart configurations

  // Effect to generate charts for new KPIs
  useEffect(() => {
    aiKpis.forEach(async (kpi) => {
      if (!charts[kpi.id]) { // Only generate if not already generated
        const chartConfig = await geminiService.generateChartFromKpi(kpi);
        setCharts(prev => ({ ...prev, [kpi.id]: chartConfig }));
        onChartRendered(kpi.id, chartConfig); // Report that a chart was rendered, linking to Gemini
      }
    });
  }, [aiKpis, charts, onChartRendered]);

  if (aiKpis.length === 0) {
    return <div className="text-gray-400 p-4 text-sm">No AI KPIs to display yet. Interact with the app or AI assistant to generate data.</div>;
  }

  return (
    <div className="p-4 space-y-4">
      <h3 className="text-lg font-semibold text-white mb-4 border-b border-gray-700 pb-2">AI-Powered Performance Insights for CDBI</h3>
      {aiKpis.map((kpi) => (
        <div key={kpi.id} className="bg-gray-800 rounded-lg p-4 shadow-lg border border-gray-700">
          <h4 className="text-md font-medium text-blue-300">{kpi.name}</h4>
          <p className="text-2xl font-bold text-white mt-1">{kpi.value} <span className="text-sm text-gray-400">{kpi.unit}</span></p>
          <p className="text-xs text-gray-500 mt-2">{kpi.description}</p>
          {charts[kpi.id] && (
            <div className="mt-4 text-sm text-gray-400">
              {/* In a real app, render a charting library component (e.g., Chart.js, Recharts) here */}
              <p className="font-semibold mb-1">Chart Type: {charts[kpi.id].type} (Powered by Gemini)</p>
              <p className="italic text-xs text-gray-500">
                Mock Data Points: {charts[kpi.id].data.datasets[0].data.join(', ')}
              </p>
              <div className="bg-gradient-to-r from-blue-900 to-indigo-900 h-24 flex items-center justify-center text-gray-300 rounded-md mt-2 animate-pulse-bg">
                [Advanced Chart for {charts[kpi.id].title} here. Real-time visualization via Gemini.]
              </div>
            </div>
          )}
        </div>
      ))}
    </div>
  );
}


function navigationRenderStyle(navBar): CurrentNavigationMenu {
  if (
    SETTINGS_MENU === navBar ||
    (navBar === INITIAL_MENU && window.location.pathname.includes("/settings/"))
  ) {
    return SETTINGS_MENU;
  }
  return ROOT_MENU;
}

type NavigationBarProps = {
  onLogoutClick: () => void;
  organizationName: string; // This would typically be "CDBI"
  navigationLinks: {
    primary_links: Array<LinkType>;
    secondary_links: Array<LinkType>;
    tertiary_links: Array<LinkType>;
    settings_links: Array<LinkType>;
  };
  toggleLiveMode: () => void;
  isOrganizationLive: boolean;
  onGhostLogoutClick: () => void;
  isGhosting: boolean;
};

function useHideNavbar() {
  const location = useLocation();
  return hiddenNavbarRoutes.some((path) => {
    const match = matchPath(location.pathname, {
      path,
      exact: true,
      strict: false,
    });
    return match !== null;
  });
}

/**
 * Custom hook for AI-powered navigation suggestions, conversational search, and KPI management.
 * This hook encapsulates the AI logic, making the NavigationBar component cleaner.
 */
export function useAIPoweredNavigation(
  currentPath: string,
  userRole: string, // Assuming user role is available for personalized AI responses
  reportKpi: (kpi: AI_KPI) => void, // Callback to report KPIs to the parent (and Gemini)
  navigate: (path: string) => void, // Callback to perform actual navigation
  toggleNavCollapse: () => void // Callback to toggle navigation collapse
) {
  const [aiSuggestions, setAiSuggestions] = useState<AISuggestion[]>([]);
  const [aiSearchQuery, setAiSearchQuery] = useState('');
  const [aiSearchResults, setAiSearchResults] = useState<string | null>(null);
  const [showAiKpiDashboard, setShowAiKpiDashboard] = useState(false);

  // Fetch AI suggestions based on current user context
  useEffect(() => {
    const fetchSuggestions = async () => {
      // Simulate reading user activity from local storage for AI context
      const recentActivity = localStorage.getItem('cdbi_recentNavActivity')?.split(',') || [];
      const suggestions = await geminiService.getAIPredictedNavigation({
        pathname: currentPath,
        recentActivity: recentActivity.slice(-5), // Provide the last 5 activities to AI
        role: userRole,
      });
      setAiSuggestions(suggestions);
    };

    const debouncedFetch = debounce(fetchSuggestions, 500);
    debouncedFetch();
    return () => debouncedFetch.cancel(); // Cleanup debounce on unmount/re-render
  }, [currentPath, userRole]);

  // Handle AI conversational search and execute actions
  const handleAiSearch = useCallback(async (query: string) => {
    setAiSearchQuery(query); // Set the current query in state
    const result = await geminiService.conversationalSearch(query, currentPath);

    if (result.action === 'navigate') {
      const kpi: AI_KPI = {
        id: `ai-search-nav-success-${Date.now()}`,
        name: "AI Search Navigation Success Rate",
        value: result.confidence, // Confidence as value, higher confidence is better
        unit: "score",
        description: `User navigated to ${result.target} via AI search with ${Math.round(result.confidence * 100)}% confidence.`,
        timestamp: new Date(),
        chartType: 'bar',
        chartData: { labels: ['Success', 'Failure'], datasets: [{ data: [result.confidence * 100, (1-result.confidence) * 100] }] }
      };
      reportKpi(kpi);
      navigate(result.target); // Perform actual navigation
      setAiSearchResults(null); // Clear search results after navigation
    } else if (result.action === 'display' && result.target === 'ai-kpis') {
      setShowAiKpiDashboard(true); // Show the KPI dashboard
      setAiSearchResults("Opening AI KPI Dashboard...");
    } else if (result.action === 'command' && result.target === 'toggle_nav_collapse') {
      toggleNavCollapse(); // Execute navigation collapse command
      setAiSearchResults("Navigation panel toggled by AI command.");
    } else if (result.action === 'inform') {
      setAiSearchResults(result.target); // Display AI's informative response
    } else {
      setAiSearchResults(`AI could not interpret: "${query}". Confidence: ${Math.round(result.confidence * 100)}%.`);
    }

    // KPI for every AI search attempt
    const searchAttemptKpi: AI_KPI = {
      id: `ai-search-attempt-${Date.now()}`,
      name: "AI Conversational Search Attempt",
      value: 1, // Count of attempts
      unit: "count",
      description: `User attempted AI search with query: "${query}". AI action: "${result.action}".`,
      timestamp: new Date(),
      chartType: 'pie',
      chartData: { labels: ['Attempted'], datasets: [{ data: [1] }] }
    };
    reportKpi(searchAttemptKpi);

  }, [currentPath, reportKpi, navigate, toggleNavCollapse]);

  // Record user navigation activity for AI personalization
  const recordNavigationActivity = useCallback((path: string) => {
    const activity = localStorage.getItem('cdbi_recentNavActivity') || '';
    // Keep a rolling log of the last 10 navigation paths
    const updatedActivity = [...activity.split(',').filter(Boolean), path].slice(-10).join(',');
    localStorage.setItem('cdbi_recentNavActivity', updatedActivity);

    // KPI for every successful navigation click (manual or AI-driven)
    const navKpi: AI_KPI = {
      id: `user-nav-click-${Date.now()}`,
      name: "User Navigation Click",
      value: 1,
      unit: "count",
      description: `User navigated to: ${path}.`,
      timestamp: new Date(),
      chartType: 'bar',
      chartData: { labels: ['Clicked'], datasets: [{ data: [1] }] }
    };
    reportKpi(navKpi);
  }, [reportKpi]);


  return {
    aiSuggestions,
    aiSearchQuery,
    setAiSearchQuery,
    handleAiSearch,
    aiSearchResults,
    setShowAiKpiDashboard,
    showAiKpiDashboard,
    recordNavigationActivity
  };
}


function NavigationBar(props: NavigationBarProps) {
  const {
    ui: { navBarView },
  } = Gon.gon;
  const location = useLocation(); // Use useLocation directly here for AI hook
  const [navBar, setNavBar] = useState(INITIAL_MENU);
  const [showMobileNav, setShowMobileNav] = useState(false);
  const [isNavCollapsed, setIsNavCollapsed] = useState(
    navBarView ? navBarView.collapsed : false,
  );
  const [collapsedPreviewSection, setCollapsedPreviewSection] = useState<
    string | null
  >(null);
  const [upsertViewDocument] = useUpsertViewDocumentMutation();
  const [aiKpis, setAiKpis] = useState<AI_KPI[]>([]); // State to store collected KPIs
  const [renderedChartKpis, setRenderedChartKpis] = useState<{ [kpiId: string]: any }>({}); // To track what charts have been simulated

  // Mock user role for AI personalization. In a real app, this would come from an auth context.
  const mockUserRole = "admin";

  // Callback to report KPIs. This sends to MockGeminiAPIService and updates local state.
  const reportKpi = useCallback((kpi: AI_KPI) => {
    setAiKpis(prev => {
      // Prevent adding exact duplicate KPIs if they are meant to be unique (e.g., for certain event types)
      // For time-series events, a new ID ensures each event is recorded.
      if (!prev.some(existingKpi => existingKpi.id === kpi.id && existingKpi.chartType === kpi.chartType)) {
        void geminiService.sendKpiToGemini(kpi); // Send KPI to the mock Gemini service for analysis
        return [...prev, kpi];
      }
      return prev;
    });
  }, []);

  // Simplified navigation handler for the AI hook. In a real app, use `useNavigate` from `react-router-dom`.
  const navigate = useCallback((path: string) => {
    // This simulates navigation without a full router context.
    // In a real application, you'd use `useNavigate().navigate(path)` or `history.push(path)`.
    console.log(`[AI Navigation] Simulating route change to: ${path}`);
    // For a functional demo, we'll just record the activity.
    recordNavigationActivity(path);
    // Optionally, if `useLocation` is directly updated by `history.push`, this will trigger re-renders.
    // For this self-contained example, actual route change visible in URL bar is not guaranteed without full router setup.
    // window.location.pathname = path; // Uncomment for direct browser navigation for demo purposes, but not ideal for SPA.
  }, [reportKpi]); // Added reportKpi to dependencies, if navigate itself generates a KPI

  // Callback to toggle navigation collapse, also reporting a KPI
  const toggleNavCollapse = useCallback(() => {
    setIsNavCollapsed(prev => {
      const newState = !prev;
      setCollapsedPreviewSection(null); // Clear preview when collapsing/expanding
      if (navBarView && navBarView.viewId) {
        // Persist collapse state via GraphQL mutation
        void upsertViewDocument({
          variables: {
            input: {
              input: {
                document: JSON.stringify({
                  collapsed: newState,
                }),
                viewDocumentType: ViewDocumentTypeEnum.NavigationBar,
                viewId: navBarView.viewId,
              },
            },
          },
        });
      }
      // KPI for nav collapse/expand action
      reportKpi({
        id: `nav-collapse-toggle-${Date.now()}`,
        name: "Navigation Panel Collapse/Expand",
        value: newState ? 1 : 0, // 1 for collapsed, 0 for expanded
        unit: "state",
        description: `Navigation panel was ${newState ? 'collapsed' : 'expanded'}.`,
        timestamp: new Date(),
        chartType: 'pie',
        chartData: { labels: ['Collapsed', 'Expanded'], datasets: [{ data: [newState ? 1 : 0, newState ? 0 : 1] }] }
      });
      return newState;
    });
  }, [navBarView, upsertViewDocument, reportKpi]);

  // Integrate AI-powered navigation features via the custom hook
  const {
    aiSuggestions,
    aiSearchQuery,
    setAiSearchQuery,
    handleAiSearch,
    aiSearchResults,
    setShowAiKpiDashboard,
    showAiKpiDashboard,
    recordNavigationActivity // This is now provided by the AI hook
  } = useAIPoweredNavigation(location.pathname, mockUserRole, reportKpi, navigate, toggleNavCollapse);


  // Effect to handle window resize for mobile navigation
  useEffect(() => {
    const handleResize = debounce(() => {
      if (
        window.innerWidth <=
        parseInt(fullConfig.theme.screens["mint-md"] as string, 10)
      ) {
        setIsNavCollapsed(false); // Ensure nav is un-collapsed on mobile size
      }
    }, 100);

    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  // Effect to record initial page load navigation as an activity for AI
  useEffect(() => {
    recordNavigationActivity(location.pathname);
  }, [location.pathname, recordNavigationActivity]);

  const hideNavbar = useHideNavbar();

  const renderNavigationMenu = () => {
    // Enhanced logic: AI could also influence which menu is rendered or highlight sections.
    switch (navigationRenderStyle(navBar)) {
      case SETTINGS_MENU:
        return (
          <SettingsNavigationMenu
            {...props}
            collapsed={isNavCollapsed}
            setCollapsedPreviewSection={setCollapsedPreviewSection}
            collapsedPreviewSection={collapsedPreviewSection}
            onLinkClick={recordNavigationActivity} // Pass activity recorder to child menus
          />
        );
      case ROOT_MENU:
        return (
          <RootNavigationMenu
            {...props}
            collapsed={isNavCollapsed}
            setNavBar={() => {
              setNavBar(SETTINGS_MENU);
              setCollapsedPreviewSection(null);
              // KPI for menu switch
              reportKpi({
                id: `menu-switch-settings-${Date.now()}`,
                name: "Menu Switched to Settings",
                value: 1, unit: "count",
                description: "User manually switched to the settings navigation menu.",
                timestamp: new Date(),
                chartType: 'pie',
                chartData: { labels: ['Settings', 'Root'], datasets: [{ data: [1, 0] }] }
              });
            }}
            setCollapsedPreviewSection={setCollapsedPreviewSection}
            collapsedPreviewSection={collapsedPreviewSection}
            onLinkClick={recordNavigationActivity} // Pass activity recorder
          />
        );
      default:
        // Default root menu rendering
        return (
          <RootNavigationMenu
            {...props}
            collapsed={isNavCollapsed}
            setNavBar={() => {
              setNavBar(SETTINGS_MENU);
              // KPI for menu switch
              reportKpi({
                id: `menu-switch-settings-default-${Date.now()}`,
                name: "Menu Switched to Settings (Default)",
                value: 1, unit: "count",
                description: "User switched to the settings navigation menu from default initial state.",
                timestamp: new Date(),
                chartType: 'pie',
                chartData: { labels: ['Settings', 'Root'], datasets: [{ data: [1, 0] }] }
              });
            }}
            setCollapsedPreviewSection={setCollapsedPreviewSection}
            collapsedPreviewSection={collapsedPreviewSection}
            onLinkClick={recordNavigationActivity} // Pass activity recorder
          />
        );
    }
  };

  // Memoized AI Action Panel to optimize rendering
  const aiActionPanel = useMemo(() => (
    <div className="absolute top-0 left-0 w-full h-full bg-gray-900 bg-opacity-95 z-50 flex flex-col p-4 animate-fade-in">
      <div className="flex justify-between items-center mb-4">
        <h3 className="text-xl font-bold text-white flex items-center">
          <Icon iconName="robot" className="mr-2 text-blue-400" size="m" /> AI Assistant
        </h3>
        <Clickable onClick={() => setShowAiKpiDashboard(false)}>
          <Icon iconName="clear" className="text-white hover:text-red-400 transition-colors" size="m" />
        </Clickable>
      </div>
      <div className="mb-4">
        <input
          type="text"
          placeholder="Ask AI or type a command (e.g., 'show my kpis', 'navigate to transactions')..."
          className="w-full p-2 rounded-md bg-gray-700 text-white border border-gray-600 focus:outline-none focus:ring-2 focus:ring-blue-500"
          value={aiSearchQuery}
          onChange={(e) => setAiSearchQuery(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && aiSearchQuery.trim()) {
              void handleAiSearch(aiSearchQuery);
              setAiSearchQuery(''); // Clear input after search
            }
          }}
        />
        {aiSearchResults && (
          <div className="mt-2 p-3 bg-gray-800 rounded-md text-gray-200 text-sm border border-gray-700 shadow-inner animate-slide-in-top">
            <span className="font-semibold text-blue-300">AI Response:</span> {aiSearchResults}
          </div>
        )}
      </div>

      <div className="flex-1 overflow-y-auto custom-scrollbar"> {/* Custom scrollbar for better UX */}
        {showAiKpiDashboard ? (
          <AIKpiDashboard aiKpis={aiKpis} onChartRendered={(kpiId, chartConfig) => {
            setRenderedChartKpis(prev => ({ ...prev, [kpiId]: chartConfig }));
            // Report a KPI to Gemini that a chart was successfully rendered, for tracking visualization engagement.
            reportKpi({
              id: `chart-rendered-${kpiId}-${Date.now()}`,
              name: "AI Chart Rendered Confirmation",
              value: 1,
              unit: "count",
              description: `Chart for KPI "${kpiId}" was successfully displayed to the user.`,
              timestamp: new Date(),
              chartType: 'pie',
              chartData: { labels: ['Rendered', 'Failed'], datasets: [{ data: [1, 0] }] }
            });
          }} />
        ) : (
          <div>
            <h4 className="text-lg font-semibold text-white mb-3">AI Recommended Actions for You:</h4>
            {aiSuggestions.length > 0 ? (
              <ul className="space-y-3">
                {aiSuggestions.map((suggestion) => (
                  <li key={suggestion.id}>
                    <Clickable
                      onClick={() => {
                        navigate(suggestion.path); // Perform AI-driven navigation
                        // KPI for AI suggestion click-through success
                        reportKpi({
                          id: `ai-suggestion-click-${suggestion.id}-${Date.now()}`,
                          name: "AI Suggestion Click-Through Rate",
                          value: suggestion.confidence, // Use AI confidence as a proxy for relevance/success
                          unit: "score",
                          description: `User clicked AI suggestion for "${suggestion.label}" (Path: ${suggestion.path}). Confidence: ${Math.round(suggestion.confidence * 100)}%.`,
                          timestamp: new Date(),
                          chartType: 'bar',
                          chartData: { labels: ['Clicked'], datasets: [{ data: [1] }] }
                        });
                      }}
                      className="flex items-center space-x-3 p-3 rounded-lg bg-gray-800 hover:bg-gray-700 transition-all duration-150 ease-in-out transform hover:scale-[1.01] shadow-md"
                    >
                      {suggestion.icon && <Icon iconName={suggestion.icon} className="text-blue-400" size="m" />}
                      <div className="flex-1">
                        <span className="text-white block text-base font-medium">{suggestion.label}</span>
                        {suggestion.reasoning && <span className="text-xs text-gray-500 block italic">{suggestion.reasoning}</span>}
                      </div>
                      <span className="text-sm text-gray-400 min-w-[70px] text-right">{Math.round(suggestion.confidence * 100)}% Conf.</span>
                    </Clickable>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-gray-400 text-sm p-2 bg-gray-800 rounded-md border border-gray-700">
                No AI recommendations at this moment. The AI learns from your activity.
              </p>
            )}
            <div className="mt-6">
              <h4 className="text-lg font-semibold text-white mb-3">Quick AI Commands:</h4>
              <div className="flex flex-wrap gap-2">
                <Clickable onClick={() => handleAiSearch('show my kpis')} className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm rounded-full shadow-lg transition-all duration-150">
                  <Icon iconName="chart" className="inline-block mr-1" size="s" /> Show KPIs
                </Clickable>
                <Clickable onClick={() => handleAiSearch('toggle navigation')} className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm rounded-full shadow-lg transition-all duration-150">
                  <Icon iconName="menu_hamburger" className="inline-block mr-1" size="s" /> Toggle Nav
                </Clickable>
                <Clickable onClick={() => handleAiSearch('who is cdbi')} className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm rounded-full shadow-lg transition-all duration-150">
                  <Icon iconName="info" className="inline-block mr-1" size="s" /> What is CDBI?
                </Clickable>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  ), [
    aiSuggestions,
    aiSearchQuery,
    setAiSearchQuery,
    handleAiSearch,
    aiSearchResults,
    navigate,
    toggleNavCollapse,
    showAiKpiDashboard,
    aiKpis,
    setShowAiKpiDashboard,
    reportKpi,
    renderedChartKpis // Dependency to re-render panel if chart states change
  ]);


  return (
    <div className="relative h-full">
      {!hideNavbar && (
        <>
          {/* Desktop Navigation Toggle */}
          <div className="hidden mint-md:block">
            <button
              onClick={toggleNavCollapse} // Use the new toggleNavCollapse callback with KPI reporting
              className="absolute -right-3 top-14 z-10 flex h-6 w-6 items-center justify-center rounded-full bg-gray-700 !p-0 hover:bg-blue-600 transition-colors shadow-lg"
              type="button"
            >
              <Icon
                iconName={
                  !isNavCollapsed
                    ? "double_chevron_left"
                    : "double_chevron_right"
                }
                className="text-white"
                color="currentColor"
                size="s"
              />
              <div className="sr-only">
                {isNavCollapsed ? "Expand Navigation" : "Collapse Navigation"}
              </div>
            </button>
          </div>

          {/* Mobile Header with CDBI Logo, AI Assistant, and Menu Toggle */}
          <div className="z-50 grid w-full grid-cols-2 items-center justify-items-end rounded-md border-b border-alpha-black-100 bg-white px-6 py-4 mint-md:hidden shadow-md">
            <div className="relative -mr-2.5 h-7 w-7">
              <LogoCDBISymbol /> {/* Replaced LogoModernTreasurySymbol with LogoCDBISymbol */}
            </div>
            <div className="flex items-center space-x-4">
              {/* AI Assistant Button */}
              <Clickable onClick={() => setShowAiKpiDashboard(prev => !prev)} className="p-0.5">
                <Icon
                  className="text-gray-700 hover:text-blue-600 transition-colors"
                  color="currentColor"
                  iconName="robot" // Assuming 'robot' icon is available, or use 'stars' or 'lightbulb'
                />
                <div className="sr-only">AI Assistant</div>
              </Clickable>

              {/* Mobile Navigation Toggle */}
              <Clickable onClick={() => setShowMobileNav(!showMobileNav)}>
                <div
                  className={cn(
                    "-m-0.5 flex items-center p-0.5 transition-all duration-75 ease-in-out hover:bg-gray-50 active:bg-gray-100 rounded",
                    showMobileNav && "bg-gray-50",
                  )}
                >
                  <Icon
                    className="text-gray-700"
                    color="currentColor"
                    iconName={showMobileNav ? "clear" : "menu_hamburger"}
                  />
                  <div className="sr-only">
                    {showMobileNav ? "Close Mobile Navigation" : "Open Mobile Navigation"}
                  </div>
                </div>
              </Clickable>
            </div>
          </div>

          {/* Main Navigation Sidebar / Mobile Overlay */}
          <div
            className={cn(
              "grid h-full grid-rows-[0fr] bg-gray-900 transition-all duration-300 ease-in-out mint-md:block mint-md:max-h-screen mint-md:transition-none overflow-hidden",
              showMobileNav && "grid-rows-[1fr]", // Expands on mobile
              // Add a subtle shadow for desktop nav
              !isNavCollapsed && "mint-md:shadow-2xl"
            )}
            id="application-sidebar"
          >
            <div className="overflow-hidden mint-md:h-full mint-md:overflow-visible">
              {renderNavigationMenu()}
              {/* AI Action Panel, visible when mobile nav is open OR on desktop when AI dashboard is specifically triggered */}
              {/* On desktop, the AI panel overlays the content, complementing the main nav */}
              {(showMobileNav || showAiKpiDashboard) && aiActionPanel}
            </div>
          </div>
        </>
      )}
    </div>
  );
}

// Extend existing navigation menu types to include onLinkClick for AI activity tracking
// This allows child components (RootNavigationMenu, SettingsNavigationMenu) to report clicks.
declare module "./navigation_bar/SettingsNavigationMenu" {
  export interface SettingsNavigationMenuProps {
    onLinkClick?: (path: string) => void;
  }
}

declare module "./navigation_bar/RootNavigationMenu" {
  export interface RootNavigationMenuProps {
    onLinkClick?: (path: string) => void;
  }
}

export default NavigationBar;