// Copyright James Burvel Oâ€™Callaghan III
// President CDBI AI Powered Financial Services

import React, { useState, useEffect, useCallback } from "react";
import { Badge, BadgeType } from "~/common/ui-components";
import { OperationalStatusEnum } from "~/generated/dashboard/graphqlSchema";

// --- AI-Powered Data Models and Interfaces ---

/**
 * Interface for AI-generated operational status metrics (KPIs).
 * These metrics are conceptually derived from real-time data analyzed by an AI model like Gemini.
 * They provide a quantitative overview of the system's health and performance.
 */
export interface AIStatusMetrics {
  /** Percentage of time the system has been operational in a given period (e.g., last 30 days). */
  uptimePercentage: number;
  /** Number of incidents or disruptions detected in a recent timeframe. */
  incidentCountLast24h: number;
  /** Average time taken to resolve an incident or issue. */
  averageResolutionTimeHours: number;
  /** AI-predicted risk of an outage in the near future (0-1 scale). */
  predictedOutageRisk: number;
  /** Estimated number of users impacted by the current or recent status changes. */
  userImpactEstimate: number;
  /** Trend of operational status over time (e.g., 'improving', 'stable', 'declining'). */
  statusTrend: 'improving' | 'stable' | 'declining' | 'critical';
  /** AI confidence score in the provided status assessment. */
  aiConfidenceScore: number;
}

/**
 * Interface for AI-generated chart data, suitable for visualization.
 * This data would be dynamically generated by Gemini based on system logs, telemetry, and predictive analytics.
 */
export interface AIChartData {
  /** Labels for the X-axis (e.g., timestamps, categories). */
  labels: string[];
  /** Series of data points for the chart. */
  datasets: Array<{
    label: string;
    data: number[];
    borderColor?: string;
    backgroundColor?: string;
    fill?: boolean;
    tension?: number;
  }>;
  /** A brief AI-generated summary or insight about the chart data. */
  chartInsight: string;
}

/**
 * Interface for a detailed AI analysis of the operational status,
 * providing actionable insights and recommendations.
 */
export interface AIDetailedAnalysis {
  /** A comprehensive explanation of the current status, its root causes, and potential implications. */
  explanation: string;
  /** List of AI-recommended actions to maintain or improve the operational status. */
  recommendations: string[];
  /** Predicted short-term and long-term impacts of the current status. */
  predictedImpacts: { shortTerm: string[]; longTerm: string[] };
  /** Key factors identified by AI influencing the current status. */
  keyFactors: string[];
  /** External dependencies potentially affecting this status. */
  externalDependencies: string[];
}

/**
 * Configuration for the AI agent (e.g., Gemini model parameters).
 */
export interface AIConfig {
  modelName: string;
  temperature: number;
  maxOutputTokens: number;
}

// --- AI Service Mock/Helper Functions ---

/**
 * Generates a prompt for an AI model (like Gemini) to analyze and provide insights on an operational status.
 * This function makes the AI interaction explicit and prepares the input for a generative AI service.
 * @param status The current operational status enum.
 * @param entityName The name of the entity or service (e.g., "CDBI Payment Gateway", "Personal Banking App").
 * @param context Any additional context to provide to the AI for a more nuanced analysis.
 * @returns A string prompt ready to be sent to an AI model.
 */
export function generateAIStatusInsightPrompt(
  status: OperationalStatusEnum,
  entityName: string = "CDBI Global Operations",
  context?: string
): string {
  let basePrompt = `Analyze the operational status of '${entityName}', which is currently '${status}'.`;

  switch (status) {
    case OperationalStatusEnum.Operational:
      basePrompt += " Provide a concise summary of its current stability, highlight recent performance trends, and identify any potential early warning signs for future issues. Suggest proactive measures to maintain high availability.";
      break;
    case OperationalStatusEnum.Deactivated:
      basePrompt += " Explain the typical reasons for a 'Deactivated' status, assess the potential impact on dependent systems and users, and outline the necessary steps for reactivation or graceful decommissioning. Provide risk assessment for data integrity and recovery.";
      break;
    case OperationalStatusEnum.Maintenance:
      basePrompt += " Describe the scope of typical maintenance activities for this status, expected duration, and the impact mitigation strategies. Suggest optimal scheduling based on predictive analysis of user load and system dependencies. Provide status communication best practices.";
      break;
    case OperationalStatusEnum.DegradedPerformance:
      basePrompt += " Detail the observed symptoms of degraded performance, potential root causes (e.g., resource contention, network issues, software bugs), and recommended diagnostic steps. Prioritize resolution strategies based on user impact and system criticality.";
      break;
    case OperationalStatusEnum.Incident:
      basePrompt += " Provide an immediate incident assessment, including potential blast radius, affected services, and estimated time to recovery. Suggest initial containment and mitigation actions. Identify key stakeholders for communication and data points for post-mortem analysis.";
      break;
    default:
      basePrompt += " Provide a general overview of what this status typically entails, its implications for users and operations, and any standard procedures associated with it.";
      break;
  }

  if (context) {
    basePrompt += ` Additional context: ${context}.`;
  }

  basePrompt += " Focus on providing actionable insights for operations teams and clear communication points for end-users, reflecting CDBI's commitment to transparency and advanced service management. Link any identified KPIs or metrics to potential Gemini analysis dashboards.";
  return basePrompt;
}

/**
 * Mocks the retrieval of AI-generated operational metrics (KPIs) for a given status.
 * In a real application, this would involve an API call to a backend service that
 * interacts with an AI model like Gemini, processing real-time system data.
 * @param status The current operational status.
 * @param entityName The name of the entity.
 * @returns A promise resolving to `AIStatusMetrics`.
 * @description This function simulates the "link up the KPIs... to Gemini" directive by generating plausible, AI-like data.
 */
export async function getAIStatusMetrics(
  status: OperationalStatusEnum,
  entityName: string = "CDBI Core Services"
): Promise<AIStatusMetrics> {
  console.log(`CDBI AI Operations: Requesting AI metrics for ${entityName} with status: ${status}`);
  await new Promise(resolve => setTimeout(resolve, 300)); // Simulate API delay

  const baseUptime = 99.9;
  const baseIncidents = 0;
  const baseResolution = 0.5;
  const baseRisk = 0.01;
  const baseImpact = 0;
  let statusTrend: 'improving' | 'stable' | 'declining' | 'critical' = 'stable';
  let aiConfidence = 0.95;

  switch (status) {
    case OperationalStatusEnum.Operational:
      aiConfidence = Math.min(0.99, baseUptime / 100);
      break;
    case OperationalStatusEnum.Deactivated:
      aiConfidence = 0.8;
      statusTrend = 'critical';
      break;
    case OperationalStatusEnum.Maintenance:
      aiConfidence = 0.9;
      statusTrend = 'stable';
      break;
    case OperationalStatusEnum.DegradedPerformance:
      statusTrend = 'declining';
      aiConfidence = 0.7;
      break;
    case OperationalStatusEnum.Incident:
      statusTrend = 'critical';
      aiConfidence = 0.6;
      break;
    default:
      aiConfidence = 0.85;
  }

  return {
    uptimePercentage: parseFloat((baseUptime - (status === OperationalStatusEnum.Incident ? 5 : 0) - (status === OperationalStatusEnum.DegradedPerformance ? 2 : 0)).toFixed(2)),
    incidentCountLast24h: baseIncidents + (status === OperationalStatusEnum.Incident ? Math.floor(Math.random() * 5) + 1 : 0) + (status === OperationalStatusEnum.DegradedPerformance ? Math.floor(Math.random() * 2) : 0),
    averageResolutionTimeHours: parseFloat((baseResolution + (status === OperationalStatusEnum.Incident ? Math.random() * 5 : 0) + (status === OperationalStatusEnum.DegradedPerformance ? Math.random() * 1 : 0)).toFixed(2)),
    predictedOutageRisk: parseFloat((baseRisk + (status === OperationalStatusEnum.Incident ? Math.random() * 0.5 : 0) + (status === OperationalStatusEnum.DegradedPerformance ? Math.random() * 0.2 : 0)).toFixed(2)),
    userImpactEstimate: baseImpact + (status === OperationalStatusEnum.Incident ? Math.floor(Math.random() * 1000) : 0) + (status === OperationalStatusEnum.DegradedPerformance ? Math.floor(Math.random() * 200) : 0),
    statusTrend,
    aiConfidenceScore: parseFloat(aiConfidence.toFixed(2)),
  };
}

/**
 * Mocks the generation of AI-powered chart data for visualization.
 * This data would dynamically represent historical or predictive trends related to the operational status,
 * processed and structured by an AI like Gemini.
 * @param status The current operational status.
 * @param entityName The name of the entity.
 * @returns A promise resolving to `AIChartData`.
 * @description This function simulates the "link up the ... charts to Gemini" directive by generating plausible, AI-like data.
 */
export async function generateAIChartData(
  status: OperationalStatusEnum,
  entityName: string = "CDBI Financial Platform"
): Promise<AIChartData> {
  console.log(`CDBI AI Operations: Generating AI chart data for ${entityName} with status: ${status}`);
  await new Promise(resolve => setTimeout(resolve, 500)); // Simulate API delay

  const labels = Array.from({ length: 7 }, (_, i) => `Day ${i + 1}`);
  let data1 = labels.map(() => Math.floor(Math.random() * 100) + 50); // Base performance
  let data2 = labels.map(() => Math.floor(Math.random() * 5)); // Incident count

  let chartInsight = `AI-powered analysis for ${entityName}'s operational performance.`;

  switch (status) {
    case OperationalStatusEnum.Operational:
      data1 = data1.map(d => Math.min(100, d + Math.random() * 10)); // Stable or improving
      data2 = data2.map(d => Math.max(0, d - Math.random() * 2)); // Low incidents
      chartInsight = "AI indicates stable and improving operational metrics over the last week for CDBI's services. Low incident frequency and high performance consistency.";
      break;
    case OperationalStatusEnum.DegradedPerformance:
      data1 = data1.map((d, i) => Math.max(30, d - (i > 3 ? Math.random() * 30 : 0))); // Performance drop later in week
      data2 = data2.map((d, i) => Math.max(0, d + (i > 3 ? Math.random() * 5 : 0))); // Increased incidents later
      chartInsight = "CDBI AI has detected a degradation in performance trends towards the end of the week, correlated with an increase in minor incidents. Urgent investigation recommended.";
      break;
    case OperationalStatusEnum.Incident:
      data1 = data1.map((d, i) => Math.max(10, d - (i === 6 ? Math.random() * 70 : 0))); // Sharp drop today
      data2 = data2.map((d, i) => Math.max(0, d + (i === 6 ? Math.random() * 10 : 0))); // High incidents today
      chartInsight = "Critical AI alert: A significant operational incident is observed today, causing a sharp decline in performance. Immediate response and remediation efforts are paramount for CDBI.";
      break;
    case OperationalStatusEnum.Maintenance:
      data1 = data1.map((d, i) => Math.max(40, d - (i === 5 ? Math.random() * 20 : 0))); // Planned dip for maintenance
      data2 = data2.map((d, i) => Math.max(0, d + (i === 5 ? Math.random() * 3 : 0))); // Minor incidents during maintenance
      chartInsight = "AI notes scheduled maintenance activities impacting performance temporarily. CDBI's systems are stable within the expected maintenance window, with controlled incident levels.";
      break;
    case OperationalStatusEnum.Deactivated:
      data1 = data1.map(() => 0); // No activity
      data2 = data2.map(() => 0); // No activity
      chartInsight = "AI confirms the service is currently deactivated, resulting in no operational data. This status may be due to decommissioning or a temporary suspension by CDBI management.";
      break;
  }

  return {
    labels,
    datasets: [
      {
        label: 'System Performance Index',
        data: data1,
        borderColor: '#4CAF50', // Green for performance
        backgroundColor: 'rgba(76, 175, 80, 0.2)',
        fill: true,
        tension: 0.3,
      },
      {
        label: 'Minor Incidents',
        data: data2,
        borderColor: '#FFC107', // Amber for incidents
        backgroundColor: 'rgba(255, 193, 7, 0.2)',
        fill: true,
        tension: 0.3,
      },
    ],
    chartInsight,
  };
}

/**
 * A class representing an AI-powered analyzer for operational status,
 * designed to provide comprehensive, real-time insights for CDBI.
 * This class encapsulates the logic for interacting with a generative AI model (e.g., Gemini)
 * to interpret, predict, and recommend actions based on system operational states.
 */
export class AICDBIOperationalStatusAnalyzer {
  private readonly entityName: string;
  private readonly aiConfig: AIConfig;

  constructor(entityName: string = "CDBI Core AI Services", aiConfig?: Partial<AIConfig>) {
    this.entityName = entityName;
    this.aiConfig = {
      modelName: "gemini-pro-cdbi", // Custom model name for CDBI
      temperature: 0.7,
      maxOutputTokens: 1024,
      ...aiConfig,
    };
  }

  /**
   * Provides a detailed AI-driven analysis of the given operational status.
   * This would involve sending the generated prompt to the Gemini API and parsing its response.
   * For this self-contained file, it returns mock data.
   * @param status The operational status to analyze.
   * @param context Additional operational data or logs for deeper AI analysis.
   * @returns A promise resolving to `AIDetailedAnalysis`.
   */
  public async getDetailedAnalysis(
    status: OperationalStatusEnum,
    context?: string
  ): Promise<AIDetailedAnalysis> {
    const prompt = generateAIStatusInsightPrompt(status, this.entityName, context);
    console.log(`CDBI AI Analyzer: Sending prompt to Gemini-like model: "${prompt}"`);

    // Simulate AI response based on the status
    await new Promise(resolve => setTimeout(resolve, 700)); // Simulate AI processing time

    let analysis: AIDetailedAnalysis;
    switch (status) {
      case OperationalStatusEnum.Operational:
        analysis = {
          explanation: `The '${this.entityName}' system is fully operational. AI analysis indicates high stability, optimal resource utilization, and no current anomalies. Regular health checks confirm all sub-systems are performing within expected parameters.`,
          recommendations: [
            "Maintain current monitoring protocols and AI predictive analytics.",
            "Review performance logs quarterly for efficiency improvements and proactive capacity planning.",
            "Consider AI-driven 'chaos engineering' simulations to test resilience.",
            "Develop AI-powered automated recovery playbooks for extreme edge cases."
          ],
          predictedImpacts: {
            shortTerm: ["Continued high availability for all CDBI users.", "Optimized transaction processing times."],
            longTerm: ["Enhanced trust and reliability for CDBI's financial services.", "Potential for scaling new AI-driven features seamlessly."],
          },
          keyFactors: ["Redundant infrastructure", "Real-time AI anomaly detection", "Automated failover mechanisms", "Proactive patch management."],
          externalDependencies: ["Cloud provider stability (monitored by AI)", "Third-party payment gateways (AI-integrated monitoring)."],
        };
        break;
      case OperationalStatusEnum.Deactivated:
        analysis = {
          explanation: `The '${this.entityName}' system is currently deactivated. This state can be intentional (e.g., decommissioning, scheduled shutdown) or unintentional (e.g., critical failure, security breach leading to isolation). AI confirms no active processes.`,
          recommendations: [
            "Verify the deactivation reason with CDBI's change management system.",
            "If unintentional, immediately engage incident response team for forensic analysis and recovery.",
            "If intentional, confirm data retention policies and inform all stakeholders.",
            "Utilize AI for a comprehensive post-deactivation impact assessment across connected CDBI services."
          ],
          predictedImpacts: {
            shortTerm: ["Complete unavailability of associated services/features.", "Potential disruption to dependent CDBI operations."],
            longTerm: ["Resource optimization if decommissioned.", "Significant recovery effort if unintentional."],
          },
          keyFactors: ["Deactivation trigger (manual/automated)", "System interdependencies", "Recovery point objective (RPO) compliance."],
          externalDependencies: ["Downstream consumer systems", "CDBI compliance auditing services."],
        };
        break;
      case OperationalStatusEnum.DegradedPerformance:
        analysis = {
          explanation: `The '${this.entityName}' system is experiencing degraded performance. AI analysis indicates a decline in responsiveness and an increase in error rates, though core functionality remains available. This could affect user experience and transaction throughput for CDBI.`,
          recommendations: [
            "Initiate AI-guided diagnostics to pinpoint root cause (e.g., database bottlenecks, excessive load, network latency).",
            "Scale resources up if applicable, with AI forecasting optimal scaling factor.",
            "Engage relevant engineering teams for immediate code review or infrastructure check.",
            "Communicate proactively with affected CDBI user groups, providing AI-estimated recovery times."
          ],
          predictedImpacts: {
            shortTerm: ["Slower transaction processing, increased latency for CDBI users.", "Higher resource consumption costs."],
            long Term: ["Customer dissatisfaction if unresolved.", "Potential for full outage if degradation worsens without intervention."],
          },
          keyFactors: ["Specific service component under stress", "Recent code deployments", "Sudden traffic spikes (analyzed by AI)", "Resource capacity limits."],
          externalDependencies: ["Third-party APIs responding slowly", "Underlying cloud infrastructure performance."],
        };
        break;
      case OperationalStatusEnum.Incident:
        analysis = {
          explanation: `A critical incident is currently impacting the '${this.entityName}' system. AI-driven anomaly detection has identified a significant deviation from baseline operations, leading to service disruption or critical data integrity risk. Immediate intervention is required.`,
          recommendations: [
            "Activate the CDBI emergency incident response playbook.",
            "Isolate the affected components to prevent further propagation, guided by AI blast radius analysis.",
            "Prioritize recovery efforts based on AI-assessed business impact.",
            "Maintain continuous AI monitoring for real-time status updates and early indicators of resolution."
          ],
          predictedImpacts: {
            shortTerm: ["Service outage for CDBI users.", "Potential data loss or corruption.", "Reputational damage."],
            longTerm: ["Post-incident recovery costs.", "Increased scrutiny on operational resilience for CDBI."],
          },
          keyFactors: ["Root cause (e.g., software bug, infrastructure failure, security breach)", "Effectiveness of incident response team.", "Automated recovery tools."],
          externalDependencies: ["Cloud provider outages", "Critical third-party service failures impacting CDBI."],
        };
        break;
      default:
        analysis = {
          explanation: `AI provides a general analysis for the '${this.entityName}' system's status: '${status}'. This status suggests a non-standard or transitional state, requiring further context for a definitive assessment by CDBI.`,
          recommendations: ["Consult operational runbooks.", "Gather more context.", "Monitor closely with AI predictive tools."],
          predictedImpacts: { shortTerm: ["Uncertainty"], longTerm: ["Potential for escalation if unaddressed"] },
          keyFactors: ["Lack of specific classification"],
          externalDependencies: ["Varies"],
        };
        break;
    }
    return analysis;
  }

  /**
   * Retrieves AI-generated Key Performance Indicator (KPI) data for the given status.
   * This method uses the `getAIStatusMetrics` helper function, simulating a call to Gemini.
   * @param status The operational status.
   * @returns A promise resolving to `AIStatusMetrics`.
   */
  public async getKPIData(status: OperationalStatusEnum): Promise<AIStatusMetrics> {
    return getAIStatusMetrics(status, this.entityName);
  }

  /**
   * Retrieves AI-generated chart data for visualizing trends related to the operational status.
   * This method uses the `generateAIChartData` helper function, simulating a call to Gemini.
   * @param status The operational status.
   * @returns A promise resolving to `AIChartData`.
   */
  public async getChartData(status: OperationalStatusEnum): Promise<AIChartData> {
    return generateAIChartData(status, this.entityName);
  }
}

// --- React Component Definition ---

export interface OperationalStatusBadgeProps {
  /** The current operational status of the entity. */
  status: OperationalStatusEnum;
  /** If true, indicates the entity has been discarded or deleted. */
  discarded?: boolean;
  /** Optional unique identifier for the entity, used for more specific AI context. */
  entityId?: string;
  /** Optional name of the entity, for more user-friendly AI prompts. Defaults to "CDBI Service". */
  entityName?: string;
  /** Callback function when an AI insight is requested (e.g., via click/hover). */
  onAIInsightRequest?: (status: OperationalStatusEnum, entityName: string, entityId?: string) => void;
}

/**
 * An advanced, AI-powered Operational Status Badge component for CDBI.
 * This component not only displays a clear visual status but also integrates
 * with AI capabilities (conceptually linked to Gemini) to provide deeper insights,
 * metrics, and even predictive analytics on demand. It's designed for banks and
 * individuals, offering commercial-grade reliability and advanced features.
 */
function OperationalStatusBadge({
  status,
  discarded,
  entityId,
  entityName = "CDBI Service",
  onAIInsightRequest,
}: OperationalStatusBadgeProps) {
  const [badgeType, setBadgeType] = useState<BadgeType>(BadgeType.Cool);
  const [displayText, setDisplayText] = useState<string>("");
  const [showAIInsightsPopup, setShowAIInsightsPopup] = useState(false);
  const [loadingAI, setLoadingAI] = useState(false);
  const [aiAnalysis, setAiAnalysis] = useState<AIDetailedAnalysis | null>(null);
  const [aiMetrics, setAiMetrics] = useState<AIStatusMetrics | null>(null);
  const [aiChartData, setAiChartData] = useState<AIChartData | null>(null);

  const analyzer = new AICDBIOperationalStatusAnalyzer(entityName);

  const fetchAIInsights = useCallback(async () => {
    setLoadingAI(true);
    setAiAnalysis(null);
    setAiMetrics(null);
    setAiChartData(null);
    try {
      // In a real application, these would be separate API calls or a single batched call to a backend
      // service that interfaces with Gemini. Here, we're calling our mock/helper functions.
      const analysisPromise = analyzer.getDetailedAnalysis(status, `Entity ID: ${entityId || 'N/A'}`);
      const metricsPromise = analyzer.getKPIData(status);
      const chartDataPromise = analyzer.getChartData(status);

      const [analysisResult, metricsResult, chartResult] = await Promise.all([
        analysisPromise,
        metricsPromise,
        chartDataPromise,
      ]);

      setAiAnalysis(analysisResult);
      setAiMetrics(metricsResult);
      setAiChartData(chartResult);

      if (onAIInsightRequest) {
        onAIInsightRequest(status, entityName, entityId);
      }
    } catch (error) {
      console.error("CDBI AI Operations: Failed to fetch AI insights:", error);
      // Potentially set an error state for the UI
    } finally {
      setLoadingAI(false);
    }
  }, [status, entityName, entityId, onAIInsightRequest, analyzer]);

  useEffect(() => {
    if (discarded) {
      setDisplayText("Deleted");
      setBadgeType(BadgeType.Critical);
    } else {
      setDisplayText(status as string);
      if (status === OperationalStatusEnum.Operational) {
        setBadgeType(BadgeType.Success);
      } else if (status === OperationalStatusEnum.Deactivated || status === OperationalStatusEnum.Incident) {
        setBadgeType(BadgeType.Critical);
      } else if (status === OperationalStatusEnum.DegradedPerformance) {
        setBadgeType(BadgeType.Warning); // New badge type for degraded performance, assuming it exists or mapping to an existing one
      } else if (status === OperationalStatusEnum.Maintenance) {
        setBadgeType(BadgeType.Info); // New badge type for maintenance, assuming it exists or mapping to an existing one
      } else {
        setBadgeType(BadgeType.Cool);
      }
    }
  }, [status, discarded]);

  const handleBadgeClick = () => {
    setShowAIInsightsPopup(prev => !prev);
    if (!showAIInsightsPopup && !aiAnalysis && !loadingAI) {
      fetchAIInsights();
    }
  };

  return (
    <div style={{ position: 'relative', display: 'inline-block', cursor: 'pointer' }}>
      <Badge
        text={displayText?.toUpperCase()}
        type={badgeType}
        onClick={handleBadgeClick}
        title={`Click for AI-powered insights on ${entityName}`}
      />
      {showAIInsightsPopup && (
        <div
          style={{
            position: 'absolute',
            top: '100%',
            left: '50%',
            transform: 'translateX(-50%)',
            marginTop: '8px',
            padding: '16px',
            backgroundColor: '#2b2b2b', // Dark background for AI popup
            color: '#e0e0e0', // Light text
            borderRadius: '8px',
            boxShadow: '0 4px 12px rgba(0, 0, 0, 0.3)',
            zIndex: 1000,
            minWidth: '350px',
            maxWidth: '500px',
            fontFamily: 'monospace, sans-serif',
            fontSize: '12px',
            border: '1px solid #4CAF50', // Green border for AI powered
          }}
        >
          <h3 style={{ margin: '0 0 10px', fontSize: '14px', color: '#4CAF50' }}>
            CDBI AI Operational Insight for {entityName}
          </h3>
          {loadingAI ? (
            <div style={{ textAlign: 'center' }}>
              <div className="cdbi-ai-spinner"></div> {/* Placeholder for a nice spinner */}
              <p>CDBI AI is processing insights... (Powered by Gemini-like intelligence)</p>
            </div>
          ) : (
            <>
              {aiAnalysis && (
                <div>
                  <p><strong>Status:</strong> {status?.toUpperCase()}</p>
                  <p><strong>AI Explanation:</strong> {aiAnalysis.explanation}</p>
                  {aiMetrics && (
                    <div style={{ marginTop: '10px' }}>
                      <h4 style={{ margin: '5px 0', fontSize: '13px', color: '#8BC34A' }}>CDBI Key AI Metrics:</h4>
                      <ul>
                        <li>Uptime (30d): {aiMetrics.uptimePercentage}%</li>
                        <li>Incidents (24h): {aiMetrics.incidentCountLast24h}</li>
                        <li>Avg. Resolution: {aiMetrics.averageResolutionTimeHours}h</li>
                        <li>Predicted Outage Risk: {Math.round(aiMetrics.predictedOutageRisk * 100)}%</li>
                        <li>User Impact Est.: {aiMetrics.userImpactEstimate}</li>
                        <li>AI Confidence: {Math.round(aiMetrics.aiConfidenceScore * 100)}%</li>
                        <li>Status Trend: <span style={{ color: aiMetrics.statusTrend === 'declining' || aiMetrics.statusTrend === 'critical' ? '#FF5252' : '#8BC34A' }}>{aiMetrics.statusTrend.toUpperCase()}</span></li>
                      </ul>
                    </div>
                  )}
                  {aiAnalysis.recommendations.length > 0 && (
                    <div style={{ marginTop: '10px' }}>
                      <h4 style={{ margin: '5px 0', fontSize: '13px', color: '#2196F3' }}>AI Recommendations:</h4>
                      <ul style={{ paddingLeft: '20px' }}>
                        {aiAnalysis.recommendations.map((rec, i) => (
                          <li key={i}>{rec}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {aiChartData && (
                    <div style={{ marginTop: '10px' }}>
                      <h4 style={{ margin: '5px 0', fontSize: '13px', color: '#FFEB3B' }}>AI Chart Insight:</h4>
                      <p>{aiChartData.chartInsight}</p>
                      {/* In a real app, you'd render a chart component here using aiChartData */}
                      <div style={{ border: '1px dashed #757575', padding: '10px', textAlign: 'center', minHeight: '80px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                        <p style={{ color: '#bdbdbd' }}>[Placeholder for dynamic AI-generated Chart, linked to Gemini Visualization API]</p>
                        {/* Example structure for chart data points: */}
                        {/* {aiChartData.labels.map((label, i) => (
                          <span key={i} style={{ display: 'inline-block', margin: '0 2px', fontSize: '9px' }}>
                            {label}: {aiChartData.datasets[0]?.data[i]}
                          </span>
                        ))} */}
                      </div>
                    </div>
                  )}
                </div>
              )}
              {!aiAnalysis && !loadingAI && <p>No AI insights available for this status yet.</p>}
            </>
          )}
          <button
            onClick={() => setShowAIInsightsPopup(false)}
            style={{
              marginTop: '15px',
              padding: '8px 12px',
              backgroundColor: '#4CAF50',
              color: 'white',
              border: 'none',
              borderRadius: '4px',
              cursor: 'pointer',
              fontSize: '12px',
              float: 'right',
            }}
          >
            Close
          </button>
        </div>
      )}
      {/* Basic spinner for demonstration */}
      <style jsx>{`
        .cdbi-ai-spinner {
          border: 4px solid rgba(255, 255, 255, 0.3);
          border-top: 4px solid #4CAF50; /* Green spinner */
          border-radius: 50%;
          width: 24px;
          height: 24px;
          animation: spin 1s linear infinite;
          margin: 10px auto;
        }
        @keyframes spin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
}

export default OperationalStatusBadge;