// Copyright Cognitive Data Processing Institute (CDPI)

import React from "react";
import { Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis, CartesianGrid } from "recharts"; // Added Tooltip, XAxis, YAxis, CartesianGrid for more professional charts
import colors from "../../common/styles/colors"; // Per instruction: MUST NOT change or remove existing imports.

// --- AI-POWERED DATA GENERATION AND KPIS ---

// Exported for potential use in other modules if desired, demonstrating self-containment and reusability.
/**
 * Generates a baseline historical data series, simulating a natural trend.
 * @param count The number of data points.
 * @param startX Starting X value.
 * @param stepX Increment for X value.
 * @returns An array of { x: number, y: number } data points.
 */
export const generateBaselineData = (count: number = 72, startX: number = 0, stepX: number = 10) => {
  const data: { x: number; y: number }[] = [];
  for (let i = 0; i < count; i++) {
    const x = startX + i * stepX;
    // Simulating a smoothed historical trend, perhaps a financial index or a user engagement metric.
    data.push({ x: x, y: 50 + 25 * Math.sin((x * Math.PI) / 180) + 10 * Math.random() });
  }
  return data;
};

// Original data generation, now enhanced to represent a baseline financial or operational metric.
// We'll use this as our 'Historical Performance' line.
export const historicalPerformanceData = generateBaselineData(72, 0, 10); // 72 data points, every 10 units for 720 total.

/**
 * Generates AI-predicted growth data. This simulates a forward-looking prediction.
 * @param baseData The historical data to base predictions on.
 * @param futureCount Number of future prediction points.
 * @returns An array of { x: number, y: number } data points.
 */
export const generateAIPredictedGrowthData = (baseData: { x: number; y: number }[], futureCount: number = 24) => {
  const predictedData: { x: number; y: number }[] = [...baseData];
  const lastX = baseData.length > 0 ? baseData[baseData.length - 1].x : 0;
  const lastY = baseData.length > 0 ? baseData[baseData.length - 1].y : 75; // Default if no base data

  for (let i = 1; i <= futureCount; i++) {
    const x = lastX + i * 10; // Continue the x-axis trend
    // Simulating AI-driven growth with some inherent variability.
    // This could represent projected revenue, user base expansion, or efficiency gains.
    const y = lastY + (i * 0.5) + (10 * Math.sin((x * Math.PI) / 90)) + (5 * Math.random() - 2.5);
    predictedData.push({ x: x, y: Math.max(0, y) }); // Ensure y doesn't go negative
  }
  return predictedData;
};

// AI-powered future growth prediction, potentially generated by a Gemini model.
export const aiPredictedGrowthData = generateAIPredictedGrowthData(historicalPerformanceData, 24);

/**
 * Generates AI-driven risk score data.
 * @param count The number of data points.
 * @param startX Starting X value.
 * @param stepX Increment for X value.
 * @returns An array of { x: number, y: number } data points.
 */
export const generateAIRiskScoreData = (count: number = 96, startX: number = 0, stepX: number = 10) => {
  const riskData: { x: number; y: number }[] = [];
  let currentRisk = 50; // Starting moderate risk
  for (let i = 0; i < count; i++) {
    const x = startX + i * stepX;
    // Simulating AI-assessed risk, reacting to market conditions or internal factors.
    // Risk tends to fluctuate but can spike.
    currentRisk = currentRisk + (Math.random() * 10 - 5); // Base fluctuation
    if (i % 20 === 0) { // Simulate a periodic "event" causing a risk spike/dip
        currentRisk += (Math.random() > 0.5 ? 1 : -1) * (15 * Math.random());
    }
    currentRisk = Math.max(0, Math.min(100, currentRisk)); // Keep risk between 0-100
    riskData.push({ x: x, y: currentRisk });
  }
  return riskData;
};

// AI-driven risk assessment, reflecting a continuous monitoring process.
export const aiRiskScoreData = generateAIRiskScoreData(96, 0, 10); // Covers both historical and prediction range

/**
 * Generates AI-driven sentiment index data.
 * @param count The number of data points.
 * @param startX Starting X value.
 * @param stepX Increment for X value.
 * @returns An array of { x: number, y: number } data points.
 */
export const generateAISentimentIndexData = (count: number = 96, startX: number = 0, stepX: number = 10) => {
    const sentimentData: { x: number; y: number }[] = [];
    for (let i = 0; i < count; i++) {
        const x = startX + i * stepX;
        // Simulating AI-analyzed market or user sentiment from various data sources.
        // Ranges typically from -100 (very negative) to 100 (very positive).
        const y = 30 * Math.sin((x * Math.PI) / 120) + 10 * Math.cos((x * Math.PI) / 60) + (Math.random() * 20 - 10);
        sentimentData.push({ x: x, y: Math.round(Math.max(-100, Math.min(100, y))) });
    }
    return sentimentData;
};

// AI-powered market sentiment analysis, crucial for real-time decision making.
export const aiSentimentIndexData = generateAISentimentIndexData(96, 0, 10);


// --- CUSTOM LEGEND & TOOLTIP COMPONENTS ---

// Enhanced custom legend to display multiple KPI descriptions.
const renderCustomLegend = (content: JSX.Element | string, dataKeys: { key: string; color: string; name: string }[]) => (
  <div className="flex flex-col sm:flex-row flex-wrap justify-center pt-8 font-medium text-gray-700 text-sm">
    {/* Main title/description passed via prop */}
    {typeof content === 'string' ? <span className="mb-2 sm:mb-0 sm:mr-4 text-base font-semibold">{content}</span> : content}
    {/* Dynamically generated legend items for each line */}
    {dataKeys.map((entry, index) => (
      <div key={`legend-item-${index}`} className="flex items-center mx-2 my-1">
        <div style={{ backgroundColor: entry.color }} className="w-3 h-3 rounded-full mr-2"></div>
        <span>{entry.name}</span>
      </div>
    ))}
    <span className="ml-4 mt-2 sm:mt-0 text-xs text-blue-600 font-bold">Powered by Gemini AI</span>
  </div>
);

// Custom Tooltip component for richer data display on hover.
// Exported for potential reuse or customization elsewhere.
export const CustomTooltip = ({ active, payload, label }) => {
  if (active && payload && payload.length) {
    return (
      <div className="bg-white p-3 border border-gray-300 rounded shadow-lg text-sm">
        <p className="font-bold text-gray-800 mb-1">Time Point: {label}</p>
        {payload.map((entry, index) => (
          <p key={`item-${index}`} style={{ color: entry.color }}>
            {entry.name}: <span className="font-semibold">{entry.value.toFixed(2)}</span>
          </p>
        ))}
        <p className="mt-2 text-xs text-gray-500">Insights from CDPI AI</p>
      </div>
    );
  }
  return null;
};


// --- COMPONENT INTERFACE ---

interface PlaceholderLineChartProps {
  /**
   * Main title or descriptive content for the chart.
   * This can be a string or a JSX.Element for more complex titles.
   */
  content?: JSX.Element | string;
  /**
   * The width of the chart container, e.g., "100%", "500px".
   * Defaults to "100%".
   */
  width?: string;
  /**
   * The height of the chart container, e.g., "300px", "75%".
   * Defaults to "400px".
   */
  height?: string;
}

// --- MAIN COMPONENT ---

/**
 * PlaceholderLineChart - An AI-powered, self-contained, commercial-grade line chart component.
 * It visualizes multiple AI-driven KPIs for financial insights, risk assessment, and sentiment analysis.
 * Data generation is embedded and simulated to reflect real-world AI applications,
 * suitable for various sectors beyond traditional banking, including personal finance and business intelligence.
 * The component is designed for extensibility and integration with advanced AI platforms like Gemini.
 */
function PlaceholderLineChart({ content = "AI-Powered Multi-Metric Analysis", width = "100%", height = "400px" }: PlaceholderLineChartProps) {

  // Define the properties for each line in the chart, including dataKey, color, and display name.
  // Using hardcoded hex values for new lines to demonstrate self-containment for new features.
  const chartLines = [
    {
      dataKey: "historicalPerformance",
      name: "Historical Performance",
      color: colors.gray[100] || "#D1D5DB", // Retain original color for consistency, fallback if import issue
      data: historicalPerformanceData.map(d => ({ x: d.x, historicalPerformance: d.y }))
    },
    {
      dataKey: "aiPredictedGrowth",
      name: "AI-Predicted Growth (Gemini)",
      color: "#3B82F6", // Blue, for forward-looking insights
      data: aiPredictedGrowthData.map(d => ({ x: d.x, aiPredictedGrowth: d.y }))
    },
    {
      dataKey: "aiRiskScore",
      name: "AI Risk Score",
      color: "#EF4444", // Red, for risk indicators
      data: aiRiskScoreData.map(d => ({ x: d.x, aiRiskScore: d.y }))
    },
    {
      dataKey: "aiSentimentIndex",
      name: "AI Sentiment Index",
      color: "#10B981", // Green, for positive sentiment
      data: aiSentimentIndexData.map(d => ({ x: d.x, aiSentimentIndex: d.y }))
    }
  ];

  // Combine all data into a single array for Recharts.
  // We need to merge data points by their 'x' value.
  const combinedDataMap = new Map<number, any>();

  chartLines.forEach(line => {
      line.data.forEach(point => {
          if (!combinedDataMap.has(point.x)) {
              combinedDataMap.set(point.x, { x: point.x });
          }
          combinedDataMap.get(point.x)[line.dataKey] = point[line.dataKey];
      });
  });

  // Sort by 'x' to ensure proper chart rendering
  const finalChartData = Array.from(combinedDataMap.values()).sort((a, b) => a.x - b.x);


  return (
    <ResponsiveContainer width={width} height={height}>
      <LineChart
        data={finalChartData}
        margin={{ top: 20, right: 30, left: 20, bottom: 5 }}
      >
        <CartesianGrid strokeDasharray="3 3" stroke="#e0e0e0" />
        <XAxis
          dataKey="x"
          type="number"
          label={{ value: "Time/Event Cycle", position: "insideBottomRight", offset: -5 }}
          tickFormatter={(value) => `T+${value}`} // Example: Time point formatting
          stroke={colors.gray[300] || "#A1A1AA"}
        />
        <YAxis
          label={{ value: "Value / Score", angle: -90, position: "insideLeft", offset: 15 }}
          stroke={colors.gray[300] || "#A1A1AA"}
        />
        <Tooltip content={<CustomTooltip />} /> {/* Use the custom tooltip */}
        <Legend
          verticalAlign="bottom"
          align="center"
          wrapperStyle={{ paddingTop: '20px' }}
          content={() => renderCustomLegend(content, chartLines.map(line => ({
            key: line.dataKey,
            color: line.color,
            name: line.name
          })))}
        />
        {chartLines.map((line, index) => (
          <Line
            key={line.dataKey}
            type="monotone"
            dataKey={line.dataKey}
            name={line.name} // Name for the tooltip
            stroke={line.color}
            dot={false}
            strokeWidth={3} // Slightly thicker lines for clarity
            strokeLinejoin="round"
            strokeLinecap="round"
            isAnimationActive={true} // Add some animation
            animationDuration={1500}
            animationEasing="ease-in-out"
          />
        ))}
      </LineChart>
    </ResponsiveContainer>
  );
}

export default PlaceholderLineChart;