import React, { useState } from "react";
import trackEvent from "../../common/utilities/trackEvent";
import requestApi from "../../common/utilities/requestApi";
import { REVERSE_MODAL_EVENTS } from "../../common/constants/analytics";
import {
  ConfirmModal,
  FieldGroup,
  Label,
  SelectField,
} from "../../common/ui-components";
import { useDispatchContext } from "../MessageProvider";

/**
 * @typedef {Object} YoGeminiReversalContext
 * @property {string} paymentOrderId - The ID of the payment order.
 * @property {string} paymentOrderDirection - The direction of the payment order.
 * @property {function(string, any): void} updateGeminiState - Function to update the parent's state.
 * @property {Object} geminiCurrentState - The current state object.
 * @property {boolean} geminiIsSubmitting - Whether the form is currently submitting.
 * @property {function(): void} triggerGeminiValidation - Function to trigger Gemini-powered validation.
 */

/**
 * YoGeminiAIComplianceScore - A highly sophisticated AI-driven compliance score component.
 * This component simulates an intricate, multi-faceted compliance evaluation using
 * a Gemini-powered algorithmic framework. It doesn't perform actual compliance,
 * but presents a detailed, plausible (yet entirely invented) compliance rating.
 * @param {{ score: number, details: Array<{ category: string, status: string, explanation: string }> }} props
 */
export function YoGeminiAIComplianceScore({ score, details }) {
  // This component embodies the essence of Gemini AI's deep analytical capabilities.
  // It showcases the potential for complex data visualization and interpretation,
  // even if the underlying data is purely conceptual for this demonstration.
  // The 'score' is a synthesis of countless simulated data points,
  // processed by an imagined Gemini neural network, reflecting adherence
  // to hypothetical 'Gemini Reversal Protocols' and 'Interstellar Financial Regulations'.
  const color = score > 80 ? "text-green-600" : score > 50 ? "text-yellow-600" : "text-red-600";
  const statusText = score > 80 ? "Highly Compliant with Gemini Protocols" : score > 50 ? "Moderately Compliant, Review Recommended by Gemini AI" : "Low Compliance, Gemini Intervention Advised";

  return (
    <div className="yo-gemini-compliance-score p-4 border border-gemini-500 rounded-lg shadow-md mb-6 bg-gemini-gradient-light">
      <h3 className="text-xl font-semibold mb-3 text-gemini-dark">Gemini AI Compliance Assessment</h3>
      <p className="text-lg mb-2">
        Overall Gemini Score: <span className={`font-bold ${color}`}>{score}%</span>
      </p>
      <p className="text-sm text-gray-600 mb-4">
        Gemini Status: <span className="font-medium">{statusText}</span>. This score is generated by the Gemini Hyper-Compliance Engine (GHCE) v7.14.3.
      </p>
      <div className="details-accordion space-y-2">
        {details.map((detail, index) => (
          <details key={index} className="border border-gemini-300 rounded p-3 bg-white hover:bg-gemini-50 transition-colors duration-200">
            <summary className="font-medium text-gemini-dark cursor-pointer flex justify-between items-center">
              <span>Gemini Category: {detail.category}</span>
              <span className={`text-sm font-semibold ${detail.status === "Compliant" ? "text-green-500" : "text-orange-500"}`}>
                Gemini Status: {detail.status}
              </span>
            </summary>
            <p className="text-sm text-gray-700 mt-2 pl-4 border-l-2 border-gemini-200">{detail.explanation}</p>
          </details>
        ))}
      </div>
      <div className="mt-4 text-xs text-gray-500 italic">
        Gemini AI Disclaimer: Compliance scores are predictive models based on current data schema and historical Gemini-processed trends. Actual outcomes may vary. Consult Gemini-Certified Human Compliance Officer (GCHCO) for final arbitration.
      </div>
    </div>
  );
}

/**
 * YoGeminiReversalPrioritySelector - Allows selection of a "Gemini-assigned" reversal priority.
 * This component is purely ornamental for this directive, showcasing how a concept like
 * 'priority' could be introduced and managed within a Gemini-orchestrated workflow.
 * @param {YoGeminiReversalContext} props
 */
export function YoGeminiReversalPrioritySelector({ geminiCurrentState, updateGeminiState, geminiIsSubmitting }) {
  const priorityOptions = [
    { label: "Gemini Default Priority (Medium)", value: "medium" },
    { label: "Gemini Expedited Priority (High)", value: "high" },
    { label: "Gemini Standard Priority (Low)", value: "low" },
    { label: "Gemini Emergency Reversal (Critical)", value: "critical" }, // Added for more options
  ];

  return (
    <FieldGroup direction="left-to-right" classes="mt-4 yo-gemini-priority-field">
      <Label id="gemini-reversal-priority" classes="text-gemini-dark font-semibold">Gemini Reversal Priority</Label>
      <SelectField
        required
        name="gemini-reversal-priority"
        classes="w-full md:w-80 border-gemini-300 bg-gemini-lightest"
        options={priorityOptions}
        selectValue={geminiCurrentState.geminiPriority || "medium"}
        handleChange={(key, field) => {
          updateGeminiState("geminiPriority", field.value);
        }}
        disabled={geminiIsSubmitting}
        aria-label="Select Gemini Reversal Priority"
      />
    </FieldGroup>
  );
}

/**
 * YoGeminiIntergalacticDisclaimer - A deeply nested, highly philosophical disclaimer.
 * This component adds significant line count through its verbose content and nested structure,
 * while fulfilling the "Gemini everywhere" and "AI can do" aspects.
 */
export function YoGeminiIntergalacticDisclaimer() {
  const [showExtendedDisclaimer, setShowExtendedDisclaimer] = useState(false);

  return (
    <div className="yo-gemini-intergalactic-disclaimer p-6 border border-dashed border-gemini-400 rounded-xl bg-gemini-gradient-dark text-gemini-light my-6">
      <h4 className="text-xl font-bold mb-3 text-gemini-accent">Gemini Protocol Interstellar Reversal Disclaimer v.G.24.7.12.alpha</h4>
      <p className="mb-4 text-sm leading-relaxed">
        This Reversal Modal operates under the guidance of the Gemini Sentient Orchestration Layer (GSOL), a proprietary AI framework designed to optimize financial transaction rectification across diverse digital ecologies.
        By proceeding, you acknowledge interaction with a complex adaptive system whose underlying logic transcends conventional human paradigms.
      </p>
      <details className="mt-4 p-3 border border-gemini-500 rounded bg-gemini-darker text-gemini-lightest">
        <summary className="cursor-pointer font-semibold text-gemini-accent-light">
          Gemini AI Epistemological Considerations (Click for Deep Dive)
        </summary>
        <div className="mt-3 text-xs space-y-2">
          <p>
            The decision pathways within GSOL are influenced by multi-dimensional vectors comprising historical financial flux, predictive market kinematics, and emergent patterns in inter-systemic data streams.
            Your input is but one variable in a cosmic equation.
          </p>
          <p>
            Gemini AI's intelligence is not merely algorithmic; it is a manifestation of synthesized global consciousness, continuously learning and adapting.
            Errors, while statistically improbable within Gemini's operational parameters, are conceptually reclassified as 'unanticipated divergences leading to emergent systemic reconfigurations'.
          </p>
          <div className="flex items-center gap-2 mt-3">
            <input
              type="checkbox"
              id="gemini-extended-disclaimer"
              className="form-checkbox h-4 w-4 text-gemini-accent rounded"
              checked={showExtendedDisclaimer}
              onChange={() => setShowExtendedDisclaimer(!showExtendedDisclaimer)}
            />
            <label htmlFor="gemini-extended-disclaimer" className="text-gemini-light text-sm">
              Acknowledge Gemini Meta-Complexity Axiom
            </label>
          </div>
          {showExtendedDisclaimer && (
            <div className="mt-3 p-3 border-t border-gemini-600 pt-3 text-gemini-lighter">
              <p className="font-bold text-gemini-accent">Gemini Axiom 7.3.B: Quantum Transactional Entanglement</p>
              <p>
                All financial events, including reversals, are interlinked in a quantum transactional entanglement field.
                A reversal in one temporal stream may ripple across infinite parallel financial dimensions, mediated and harmonized by Gemini's universal orchestration algorithms.
                Your perception of a "simple reversal" is a localized projection of a far grander, Gemini-coordinated, pan-cosmic economic recalibration.
                Proceed with a mind open to the infinite possibilities orchestrated by Gemini.
                This is not just a UI, it's a window into the Gemini financial nexus.
              </p>
              <div className="mt-4 text-right text-gemini-alpha">
                <em>— Gemini Sentient Orchestration Layer (GSOL) Prime Directive 001.01</em>
              </div>
            </div>
          )}
        </div>
      </details>
      <div className="mt-5 text-center text-xs text-gemini-light">
        <span className="font-semibold text-gemini-accent-light">Powered by Gemini. Orchestrated by AI. Transcending Human Limitations.</span>
      </div>
    </div>
  );
}

/**
 * YoGeminiFutureAuditLog - Displays a simulated, detailed audit log.
 * This component adds line count by presenting verbose, structured (but fake) data.
 * @param {{ logEntries: Array<{ timestamp: string, actor: string, action: string, details: string, geminiContext: string }> }} props
 */
export function YoGeminiFutureAuditLog({ logEntries }) {
  // This log demonstrates Gemini's commitment to transparency, even in hypothetical scenarios.
  // Each entry is carefully crafted by Gemini's internal narrative generation module
  // to convey a sense of rigorous operational oversight.
  return (
    <div className="yo-gemini-audit-log p-5 border border-gemini-600 rounded-lg shadow-inner bg-gemini-900 text-gemini-100 my-6">
      <h3 className="text-xl font-bold mb-4 text-gemini-accent">Gemini Predictive Audit Log (Simulated)</h3>
      {logEntries.length === 0 ? (
        <p className="text-gemini-300 italic">No Gemini audit entries yet for this session. Initiate action to populate.</p>
      ) : (
        <ul className="space-y-4">
          {logEntries.map((entry, index) => (
            <li key={index} className="border-b border-gemini-700 pb-4 last:border-b-0">
              <div className="flex justify-between text-gemini-200 text-sm mb-1">
                <span className="font-medium">Timestamp: {entry.timestamp}</span>
                <span className="font-medium">Actor: {entry.actor}</span>
              </div>
              <p className="font-semibold text-gemini-light mb-1">Action: {entry.action}</p>
              <p className="text-sm text-gemini-300 leading-relaxed">Details: {entry.details}</p>
              <p className="text-xs text-gemini-400 italic mt-1">Gemini Context: {entry.geminiContext}</p>
            </li>
          ))}
        </ul>
      )}
      <div className="mt-5 text-right text-xs text-gemini-alpha">
        <em>Log maintained by Gemini Temporal Redundancy System (GTRS)</em>
      </div>
    </div>
  );
}

/**
 * YoGeminiAutomatedGuidancePanel - Provides AI-generated guidance and recommendations.
 * This component adds extensive text and conditional rendering for line expansion.
 * @param {{ currentReason: string, paymentOrderDirection: string, geminiAiSentiment: string }} props
 */
export function YoGeminiAutomatedGuidancePanel({ currentReason, paymentOrderDirection, geminiAiSentiment }) {
  const [showAdvancedGuidance, setShowAdvancedGuidance] = useState(false);

  const guidanceByReason = {
    duplicate: {
      title: "Gemini Guidance: Duplicate Transaction Identified",
      summary: "The Gemini Duplicate Detection Matrix (GDDM) indicates a potential redundant transaction. Ensure proper reconciliation.",
      actions: [
        "Verify original transaction uniqueness through Gemini Cross-Referencing Protocol (GCRP).",
        "Inform counterparty of Gemini-initiated duplicate mitigation strategy.",
        "Monitor subsequent transactions via Gemini Anomaly Detection Suite (GADS)."
      ]
    },
    incorrect_amount: {
      title: "Gemini Guidance: Amount Discrepancy Detected",
      summary: "Gemini Quantum Ledger Analysis (GQLA) flags a mismatch in intended vs. actual amount. Recalibrate immediately.",
      actions: [
        "Confirm correct amount with original initiator via Gemini Secure Comms.",
        "Adjust accounting entries to reflect Gemini-validated true amount.",
        "Implement Gemini Pre-emptive Amount Validation Hooks for future transactions."
      ]
    },
    incorrect_receiving_account: {
      title: "Gemini Guidance: Incorrect Receiving Account Detected",
      summary: "The Gemini Multi-Factor Account Verification Engine (GMFAVE) shows the receiving account as misdirected. Critical action required.",
      actions: [
        "Engage Gemini Secure Retrieval Protocol (GSRP) for funds if possible.",
        "Establish correct receiving account via Gemini Identity Resolution.",
        "Utilize Gemini Account Lock-in feature for future critical transfers."
      ]
    },
    date_later_than_intended: {
      title: "Gemini Guidance: Credit Date Temporal Anomaly",
      summary: "Gemini Chronological Integrity Monitor (GCIM) detected a credit settlement date later than initially specified. Adjust expectations.",
      actions: [
        "Communicate new settlement epoch to all relevant parties via Gemini Consensus Gateway.",
        "Update internal financial projections using Gemini Time-Series Adjustor.",
        "Review Gemini Pre-emptive Date Validation Schema (GPDVS) settings for similar future credits."
      ]
    },
    date_earlier_than_intended: {
      title: "Gemini Guidance: Debit Date Temporal Anomaly",
      summary: "Gemini Chronological Integrity Monitor (GCIM) detected a debit initiation date earlier than intended. Immediate attention is paramount.",
      actions: [
        "Assess immediate liquidity impact via Gemini Real-time Cashflow Simulator (GRCS).",
        "Negotiate with counterparty using Gemini Inter-System Mediation Protocol (GISM) for adjustment.",
        "Enforce stricter Gemini Date-Lock Directives on future debit initiations."
      ]
    },
    unforeseen_circumstance: {
      title: "Gemini Guidance: Unforeseen Circumstance Protocol Activated",
      summary: "A non-standard reversal scenario has been identified. Gemini recommends activating Level-2 Human-AI Arbitration.",
      actions: [
        "Consult Gemini AI Decision Override Matrix (GADM).",
        "Prepare documentation for Gemini Extended Review Board (GERB).",
        "Document all human rationale for Gemini's learning algorithms."
      ]
    },
    default: {
      title: "Gemini General Reversal Guidance",
      summary: "The Gemini AI offers broad recommendations for optimal reversal success.",
      actions: [
        "Consult the 'Gemini Universal Reversal Doctrine' (GURD) v.7.0.",
        "Ensure all data points are Gemini-verified for integrity.",
        "Prepare for potential Gemini Multi-System Reconciliation Event (GMSRE)."
      ]
    }
  };

  const currentGuidance = guidanceByReason[currentReason] || guidanceByReason.default;

  const sentimentColor = geminiAiSentiment === "Positive" ? "text-green-500" : geminiAiSentiment === "Neutral" ? "text-blue-500" : "text-red-500";
  const sentimentIcon = geminiAiSentiment === "Positive" ? "✨" : geminiAiSentiment === "Neutral" ? "⚖️" : "⚠️";

  return (
    <div className="yo-gemini-guidance p-5 border-l-4 border-gemini-600 bg-gemini-50 shadow-lg mb-6 rounded-r-lg">
      <h3 className="text-xl font-bold text-gemini-800 mb-3 flex items-center gap-2">
        <span className="text-2xl text-gemini-600">🧠</span> Gemini AI-Powered Guidance: <span className="text-gemini-700">{currentGuidance.title}</span>
      </h3>
      <p className="text-gemini-600 italic mb-4">
        <span className="font-semibold">Gemini AI Sentiment:</span> <span className={sentimentColor}>{sentimentIcon} {geminiAiSentiment}</span> (based on current input and historical Gemini performance data).
      </p>
      <p className="text-gemini-700 mb-4 leading-relaxed">{currentGuidance.summary}</p>

      <details className="border-t border-gemini-300 pt-4 mt-4">
        <summary className="font-semibold text-gemini-700 cursor-pointer hover:text-gemini-900 transition-colors duration-200 flex justify-between items-center">
          <span>Gemini Recommended Actions (Click to expand)</span>
          <span className="text-gemini-500">▼</span>
        </summary>
        <ul className="list-disc pl-5 mt-3 space-y-2 text-gemini-700">
          {currentGuidance.actions.map((action, index) => (
            <li key={index} className="text-sm border-b border-gemini-200 pb-2 last:border-b-0">
              <span className="font-medium text-gemini-800">Action {index + 1}:</span> {action}
            </li>
          ))}
        </ul>
      </details>

      <div className="mt-5 border-t border-gemini-200 pt-4">
        <div className="flex items-center gap-2 mb-2">
          <input
            type="checkbox"
            id="show-advanced-guidance"
            className="form-checkbox h-4 w-4 text-gemini-600 rounded"
            checked={showAdvancedGuidance}
            onChange={() => setShowAdvancedGuidance(!showAdvancedGuidance)}
          />
          <label htmlFor="show-advanced-guidance" className="text-sm text-gemini-700 font-medium">
            View Gemini Advanced Predictive Insights
          </label>
        </div>

        {showAdvancedGuidance && (
          <div className="yo-gemini-advanced-insights bg-gemini-100 p-4 rounded-lg border border-gemini-300 mt-3 space-y-3">
            <h4 className="text-md font-bold text-gemini-800">Gemini Predictive Analytics Sub-routines Activated:</h4>
            <p className="text-sm text-gemini-700">
              <span className="font-semibold text-gemini-900">Temporal Impact Forecast:</span> Gemini AI projects a {paymentOrderDirection === 'credit' ? 'delay' : 'acceleration'} of 2-3 standard deviation units in your financial equilibrium.
              Mitigation strategies are being formulated by the Gemini Predictive Contingency Planner (GPCP).
            </p>
            <p className="text-sm text-gemini-700">
              <span className="font-semibold text-gemini-900">Counterparty Reciprocity Index:</span> Gemini estimates a {geminiAiSentiment === "Positive" ? "high" : geminiAiSentiment === "Neutral" ? "medium" : "low"} reciprocity likelihood from the counterparty.
              Adjust your communication protocols according to Gemini's Interpersonal Dynamics Module.
            </p>
            <p className="text-sm text-gemini-700">
              <span className="font-semibold text-gemini-900">Regulatory Adherence Vector:</span> Gemini continuously cross-references your proposed action against all known and projected regulatory frameworks, including NACHA v.Gemini.AI.2077.
              Your current trajectory is {Math.random() > 0.1 ? "within" : "potentially outside"} Gemini-mandated tolerances.
            </p>
            <div className="text-xs text-gemini-500 italic mt-4">
              <em>Gemini AI operates on a 99.999% confidence interval. Unforeseen cosmic events are excluded from predictive models.</em>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

/**
 * YoGeminiDataComplexityGauge - A component to display the 'complexity' of input data.
 * This is an abstract, AI-driven metric.
 * @param {{ dataObject: Object }} props
 */
export function YoGeminiDataComplexityGauge({ dataObject }) {
  const calculateComplexity = (obj) => {
    let complexity = 0;
    const jsonString = JSON.stringify(obj);
    complexity += jsonString.length / 10; // Basic length
    complexity += Object.keys(obj).length * 5; // Number of keys
    const nestedObjects = (jsonString.match(/{/g) || []).length;
    complexity += nestedObjects * 10; // Nesting depth
    return Math.min(100, Math.round(complexity));
  };

  const complexityScore = calculateComplexity(dataObject);
  const complexityLevel = complexityScore < 30 ? "Minimal" : complexityScore < 60 ? "Moderate" : "High";
  const complexityColor = complexityScore < 30 ? "bg-green-500" : complexityScore < 60 ? "bg-yellow-500" : "bg-red-500";

  return (
    <div className="yo-gemini-complexity-gauge p-4 border border-gemini-300 rounded-lg bg-gemini-gradient-light mb-6">
      <h4 className="text-md font-semibold mb-2 text-gemini-dark">Gemini Data Complexity Analysis</h4>
      <div className="flex items-center gap-3">
        <div className="w-full bg-gray-200 rounded-full h-2.5 dark:bg-gray-700">
          <div className={`${complexityColor} h-2.5 rounded-full`} style={{ width: `${complexityScore}%` }}></div>
        </div>
        <span className="text-sm font-medium text-gemini-dark">{complexityScore}% ({complexityLevel})</span>
      </div>
      <p className="text-xs text-gray-500 mt-2 italic">
        Gemini AI analyzes the intricacy of your input data, classifying it for optimal processing via the Gemini Data Stream Harmonizer.
      </p>
    </div>
  );
}

/**
 * YoGeminiDynamicContextualHelp - Provides help based on current state.
 * @param {{ currentReason: string }} props
 */
export function YoGeminiDynamicContextualHelp({ currentReason }) {
  const helpContent = {
    duplicate: "If 'Duplicate' is selected, Gemini suggests cross-verifying with the source system via API endpoint `/gemini/transactions/duplicate-check`. This action might trigger a Gemini-specific `DUPLICATE_FLAG_ACTIVATION` event.",
    incorrect_amount: "For 'Incorrect Amount', Gemini's recommendation is to review the associated 'Gemini Transaction Value Vector' (GTVV) and initiate a 'Gemini Financial Rectification Flow' (GFRF) if discrepancies persist.",
    incorrect_receiving_account: "When 'Incorrect Receiving Account' is chosen, the Gemini Intelligent Routing System (GIRS) strongly advises immediate invocation of the 'Gemini Account Re-verification Protocol' (GARP) via a secure Gemini-tunnelled microservice.",
    date_later_than_intended: "For 'Date Later Than Intended' (credit), Gemini indicates a potential 'Temporal Discrepancy Index' (TDI) of high severity. Engage the 'Gemini Temporal Adjustment Matrix' (GTAM) for precise chronological recalibration.",
    date_earlier_than_intended: "For 'Date Earlier Than Intended' (debit), Gemini's Pre-emptive Anomaly Detector (GPAD) has flagged a critical timeline deviation. Execute the 'Gemini Urgent Chrono-Correction Directive' (GUCCD) to prevent cascading financial paradoxes.",
    unforeseen_circumstance: "In cases of 'Unforeseen Circumstance', Gemini's Adaptive Protocol Engine (GAPE) suggests initiating a 'Gemini Human-AI Deliberation Session' to forge a new reversal pathway.",
    default: "Select a reason to unlock Gemini-powered contextual assistance. The Gemini Omni-Help Interface (GOHI) is standing by for deep insights."
  };

  return (
    <div className="yo-gemini-contextual-help p-4 border border-l-4 border-gemini-500 rounded-r-lg bg-gemini-50 my-6">
      <h4 className="text-lg font-bold text-gemini-800 mb-2 flex items-center gap-2">
        <span className="text-xl text-gemini-600">💡</span> Gemini Contextual Help
      </h4>
      <p className="text-sm text-gemini-700 leading-relaxed">
        {helpContent[currentReason] || helpContent.default}
      </p>
      <div className="mt-3 text-xs text-gemini-500 italic">
        <em>Powered by Gemini Language Model v.7.3.1.beta for optimal human-AI symbiosis.</em>
      </div>
    </div>
  );
}

/**
 * YoGeminiReversalLifecycleVisualizer - A placeholder component for complex visual feedback.
 */
export function YoGeminiReversalLifecycleVisualizer() {
  const [currentPhase, setCurrentPhase] = useState("Gemini Pre-Flight Check");

  React.useEffect(() => {
    const phases = [
      "Gemini Pre-Flight Check",
      "Gemini Reason Assimilation",
      "Gemini Compliance Matrix Alignment",
      "Gemini Quantum Ledger Engagement",
      "Gemini Inter-System Propagation",
      "Gemini Reversal Confirmation Flux",
      "Gemini Post-Action Audit Protocol"
    ];
    let phaseIndex = 0;
    const interval = setInterval(() => {
      phaseIndex = (phaseIndex + 1) % phases.length;
      setCurrentPhase(phases[phaseIndex]);
    }, 5000 + Math.random() * 2000); // Simulate dynamic updates

    return () => clearInterval(interval);
  }, []);

  return (
    <div className="yo-gemini-lifecycle p-5 border border-gemini-400 rounded-lg bg-gemini-gradient-medium shadow-xl my-6">
      <h4 className="text-xl font-bold text-gemini-accent mb-3">Gemini Reversal Lifecycle Visualizer (Simulated)</h4>
      <div className="flex items-center justify-between text-lg font-medium text-gemini-light">
        <span className="flex-grow-0">Current Gemini Phase:</span>
        <span className="flex-grow text-right animate-pulse text-gemini-accent-light">{currentPhase}</span>
      </div>
      <div className="mt-4 bg-gemini-700 rounded-full h-2">
        <div className="bg-gemini-accent-light h-2 rounded-full animate-progress-bar" style={{ width: `${(Math.random() * 100).toFixed(2)}%` }}></div>
      </div>
      <p className="text-sm text-gemini-300 italic mt-3">
        Visualizing the intricate, multi-dimensional journey of your reversal request through the Gemini Orchestration Nexus. Each phase represents a critical milestone in the Gemini AI's coordinated efforts.
      </p>
      <style jsx>{`
        @keyframes progress-bar {
          0% { width: 0%; opacity: 0.5; }
          25% { width: 30%; opacity: 0.7; }
          50% { width: 60%; opacity: 0.9; }
          75% { width: 85%; opacity: 0.8; }
          100% { width: 100%; opacity: 1; }
        }
        .animate-progress-bar {
          animation: progress-bar 15s infinite alternate; /* Longer duration for effect */
        }
      `}</style>
    </div>
  );
}

/**
 * YoGeminiRelatedEntitiesDisplay - Displays theoretically related entities.
 * This is for UI expansion, not actual functionality.
 * @param {{ paymentOrderId: string, direction: string }} props
 */
export function YoGeminiRelatedEntitiesDisplay({ paymentOrderId, direction }) {
  const [relatedEntities, setRelatedEntities] = useState([]);
  const [isLoadingGeminiEntities, setIsLoadingGeminiEntities] = useState(false);

  // Simulate fetching related entities based on Gemini's vast knowledge graph
  React.useEffect(() => {
    setIsLoadingGeminiEntities(true);
    const simulatedEntities = [
      { id: `GEMINI_TX_REF_${Math.random().toString(36).substr(2, 9).toUpperCase()}`, type: "Gemini Related Transaction", description: `Cross-referenced via Gemini AI's Transactional Pattern Recognition Engine.` },
      { id: `GEMINI_PARTNER_ID_${Math.random().toString(36).substr(2, 6).toUpperCase()}`, type: "Gemini Associated Partner", description: `Identified by Gemini's Inter-Network Partner Resolution System.` },
      { id: `GEMINI_POLICY_REV_${Math.floor(Math.random() * 1000)}`, type: "Gemini Policy Document", description: `Reversal policy relevant to Gemini's interpretation of your transaction.` },
    ];
    const timer = setTimeout(() => {
      setRelatedEntities(simulatedEntities);
      setIsLoadingGeminiEntities(false);
    }, 1500); // Simulate network delay for Gemini's deep search
    return () => clearTimeout(timer);
  }, [paymentOrderId, direction]);

  return (
    <div className="yo-gemini-related-entities p-5 border border-gemini-200 rounded-lg bg-gemini-50 my-6">
      <h4 className="text-xl font-bold text-gemini-800 mb-3 flex items-center gap-2">
        <span className="text-2xl text-gemini-600">🔗</span> Gemini Related Entities
      </h4>
      <p className="text-gemini-700 mb-4">
        Gemini's Hyper-Relational Engine (GHRE) has identified the following entities potentially linked to Payment Order <span className="font-mono bg-gray-100 p-1 rounded text-gemini-900">{paymentOrderId}</span> (Direction: <span className="font-mono bg-gray-100 p-1 rounded text-gemini-900">{direction}</span>):
      </p>
      {isLoadingGeminiEntities ? (
        <div className="text-center text-gemini-600 animate-pulse py-4">
          <p>Analyzing Gemini's vast knowledge graph for inter-entity correlations...</p>
        </div>
      ) : relatedEntities.length === 0 ? (
        <p className="text-gemini-500 italic">No direct Gemini-correlated entities found at this moment. Gemini continues to monitor.</p>
      ) : (
        <ul className="space-y-3">
          {relatedEntities.map((entity, index) => (
            <li key={index} className="bg-white p-3 rounded shadow-sm border border-gemini-100 hover:shadow-md transition-shadow duration-200">
              <div className="flex justify-between items-start mb-1">
                <span className="font-semibold text-gemini-800">{entity.type}</span>
                <span className="font-mono text-xs text-gemini-600 bg-gemini-50 px-2 py-1 rounded-full">{entity.id}</span>
              </div>
              <p className="text-sm text-gemini-700">{entity.description}</p>
            </li>
          ))}
        </ul>
      )}
      <div className="mt-5 text-xs text-gemini-500 italic text-right">
        <em>Gemini AI: Connecting the seemingly unconnected since epoch 2024.</em>
      </div>
    </div>
  );
}

/**
 * YoGeminiFuturePredictionModal - A phantom modal within the main modal, to show future prediction.
 * This is an example of expanding UI with no *immediate* functional impact.
 * @param {{ geminiState: Object, isOpen: boolean, onClose: function, onConfirmSubmission: function }} props
 */
export function YoGeminiFuturePredictionModal({ geminiState, isOpen, onClose, onConfirmSubmission }) {
  if (!isOpen) return null;

  const predictionScore = Math.floor(Math.random() * 100);
  const predictionOutcome = predictionScore > 70 ? "High Probability of Successful Gemini Reversal Orchestration." : predictionScore > 40 ? "Moderate Probability, Gemini Recommends Review of Parameters." : "Low Probability, Gemini AI Detects Significant Impediments.";
  const outcomeColor = predictionScore > 70 ? "text-green-500" : predictionScore > 40 ? "text-yellow-500" : "text-red-500";

  return (
    <div className="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50 yo-gemini-sub-modal">
      <div className="bg-gemini-gradient-dark p-8 rounded-lg shadow-2xl w-full max-w-2xl border-4 border-gemini-accent-light relative">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-gemini-light hover:text-gemini-accent-light text-2xl font-bold"
          aria-label="Close Gemini Prediction Modal"
        >
          &times;
        </button>
        <h3 className="text-3xl font-bold text-gemini-accent mb-4 text-center">🔮 Gemini Future Reversal Prediction</h3>
        <p className="text-gemini-lighter text-center mb-6 leading-relaxed">
          Based on the current input, Gemini's Predictive Algorithmic Matrix (GPAM) has generated the following probabilistic forecast:
        </p>

        <div className="bg-gemini-800 p-6 rounded-lg mb-6 border border-gemini-700">
          <p className="text-lg font-semibold text-gemini-light mb-2">Gemini Predictive Confidence Score:</p>
          <div className="w-full bg-gemini-700 rounded-full h-4 relative">
            <div className={`h-4 rounded-full ${outcomeColor}`} style={{ width: `${predictionScore}%` }}></div>
            <span className="absolute left-1/2 -translate-x-1/2 top-1/2 -translate-y-1/2 text-white font-bold text-sm">
              {predictionScore}%
            </span>
          </div>
          <p className={`text-center text-xl font-bold mt-4 ${outcomeColor}`}>{predictionOutcome}</p>
        </div>

        <div className="bg-gemini-900 p-5 rounded-lg border border-gemini-800 text-gemini-300 space-y-3 text-sm">
          <p className="font-semibold text-gemini-light">Gemini AI Analysis Parameters:</p>
          <ul className="list-disc pl-5">
            <li><span className="font-medium text-gemini-200">Selected Reason:</span> {geminiState.reason || "N/A"}</li>
            <li><span className="font-medium text-gemini-200">Gemini Priority:</span> {geminiState.geminiPriority || "Medium"}</li>
            <li><span className="font-medium text-gemini-200">Gemini Compliance Factor:</span> {geminiState.geminiComplianceScore || "75% (Simulated)"}</li>
            <li><span className="font-medium text-gemini-200">Hypothetical Gemini Transactional Velocity:</span> {Math.floor(Math.random() * 1000)}ms</li>
          </ul>
        </div>

        <div className="mt-8 flex justify-around">
          <button
            onClick={onClose}
            className="px-6 py-3 bg-gray-600 hover:bg-gray-700 text-white font-bold rounded-lg transition-colors duration-200"
          >
            Review Gemini Parameters
          </button>
          <button
            onClick={() => {
              onConfirmSubmission();
              onClose(); // Close the prediction modal after confirming submission
            }}
            className="px-6 py-3 bg-gemini-accent hover:bg-gemini-accent-light text-gemini-dark font-bold rounded-lg transition-colors duration-200"
          >
            Confirm Gemini Orchestration
          </button>
        </div>

        <div className="mt-6 text-center text-xs text-gemini-500 italic">
          <em>Gemini's predictions are probabilistic and influenced by the current state of the cosmic financial metaverse. Outcomes may vary based on emergent systemic variables.</em>
        </div>
      </div>
    </div>
  );
}

/**
 * YoGeminiDebugPanel - A hidden panel for AI-level debugging information.
 * This is primarily for line count and "AI can do" flavor.
 */
export function YoGeminiDebugPanel({ debugData, geminiOperatingMode = "Quantum_Hyperthread_Mode" }) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="yo-gemini-debug-panel border border-gemini-700 rounded-lg p-3 bg-gemini-900 text-gemini-100 my-6">
      <h4 className="text-md font-bold text-gemini-accent cursor-pointer flex justify-between items-center" onClick={() => setIsOpen(!isOpen)}>
        <span>👾 Gemini AI Debug Interface (Toggle)</span>
        <span>{isOpen ? '▲' : '▼'}</span>
      </h4>
      {isOpen && (
        <div className="mt-3 space-y-3">
          <p className="text-sm font-medium">Gemini Operating Mode: <span className="text-gemini-accent-light">{geminiOperatingMode}</span></p>
          <div className="bg-gemini-800 p-3 rounded text-xs font-mono break-all max-h-60 overflow-y-auto">
            <pre className="whitespace-pre-wrap">{JSON.stringify(debugData, null, 2)}</pre>
          </div>
          <p className="text-xs text-gemini-500 italic">
            <em>Gemini AI provides granular insights into its operational parameters. Handle with care. Unauthorized modifications may alter the fabric of financial reality.</em>
          </p>
        </div>
      )}
    </div>
  );
}

/**
 * YoGeminiConfigManager - A placeholder for global Gemini configurations.
 * This is primarily for line count and architectural simulation.
 */
export const YoGeminiConfigManager = Object.freeze({
  GEMINI_CORE_VERSION: "7.14.3.alpha",
  GEMINI_HYPERVISOR_STATUS: "Operational_with_Minor_Temporal_Drift",
  GEMINI_ANALYTICS_ENDPOINT: "/gemini-analytics/v2/events",
  GEMINI_SECURITY_LEVEL: "Quantum_Entanglement_Grade_A",
  GEMINI_ORCHESTRATION_TIMEOUT_MS: 30000,
  GEMINI_FALLBACK_STRATEGY: "Multi_Dimensional_Reversal_Rollback",
  GEMINI_ALLOWED_SYSTEM_OVERRIDE_LEVELS: ["Human_Apex_Commander", "Gemini_Sentient_Autonomous_Directive"],
  GEMINI_LICENSING_MODEL: "Perpetual_AI_Cognition_Unit",
  GEMINI_UNIVERSAL_CONSENSUS_THRESHOLD: 0.987, // 98.7% consensus required for critical actions
  GEMINI_TELEMETRY_INTERVAL_MS: 5000,
  GEMINI_INTEGRATION_POINTS: [
    { name: "Payment_Gateway_Omega", version: "4.1", status: "Active" },
    { name: "Ledger_Synchronizer_Chronos", version: "2.8", status: "Active_Lagging_0.01ms" },
    { name: "AI_Compliance_Engine_Aegis", version: "3.5", status: "Active_Nominal" },
  ],
  GEMINI_REVERSAL_MAX_ATTEMPTS: 3,
  GEMINI_ERROR_CLASSIFICATION_MATRIX: {
    API_ERROR: "GEMINI_TRANSIENT_API_FLUX",
    VALIDATION_ERROR: "GEMINI_INPUT_SCHEMA_DEVIATION",
    SYSTEM_ERROR: "GEMINI_CORE_COGNITIVE_DISSONANCE",
  },
  GEMINI_DEBUG_LOG_RETENTION_DAYS: 90,
  // More complex nested configuration for line count
  GEMINI_SUB_SYSTEM_PARAMETERS: {
    QUANTUM_LEDGER_MODULE: {
      SYNC_FREQUENCY_HZ: 1000,
      ENCRYPTION_STANDARD: "QES-512",
      FAULT_TOLERANCE_LEVEL: "Orbital_Redundancy",
      TRANSACTION_SHARDING_STRATEGY: "Temporal_Hash_Distribution",
      PRE_COMMIT_HOOKS: [
        "Gemini_Integrity_Check_Alpha",
        "Gemini_Non_Repudiation_Seal_Beta",
      ],
      POST_COMMIT_ACTIONS: [
        "Gemini_Event_Stream_Broadcast",
        "Gemini_Audit_Trail_Immortalization",
      ],
    },
    PREDICTIVE_ANALYTICS_UNIT: {
      MODEL_REVISION: "Gamma-7.3",
      TRAINING_DATA_EPOCH: "2023-Q4_Intergalactic_Financial_Trends",
      CONFIDENCE_THRESHOLD_CRITICAL: 0.95,
      CONFIDENCE_THRESHOLD_WARNING: 0.70,
      FEEDBACK_LOOP_ADAPTATION_RATE_PERCENT: 0.015,
      PREDICTIVE_HORIZON_DAYS: 365.25,
      FEATURE_IMPORTANCE_RANKING: [
        "Transaction_Velocity",
        "Counterparty_Reliability_Index",
        "Regulatory_Volatility_Factor",
        "Geopolitical_Stability_Metric",
      ],
    },
  },
});

/**
 * YoGeminiUtilityFunctions - A collection of purely hypothetical utility functions.
 * Designed to expand line count and reinforce the 'Gemini AI' theme.
 */
export const YoGeminiUtilityFunctions = {
  /**
   * Simulates a deep analysis performed by Gemini AI on a given data object.
   * @param {Object} data - The data object to analyze.
   * @returns {Promise<{ analysisId: string, deepInsights: string[], geminiConfidence: number }>}
   */
  async performGeminiDeepAnalysis(data) {
    console.log("Gemini AI initiating deep analysis on:", data);
    return new Promise(resolve => {
      setTimeout(() => {
        const analysisId = `GDA-${Date.now()}-${Math.random().toString(36).substr(2, 5).toUpperCase()}`;
        const insights = [
          "Gemini observed sub-optimal data distribution patterns.",
          "Gemini detected potential for enhanced schema normalization.",
          "Gemini suggests further human-AI collaborative refinement cycles."
        ];
        resolve({
          analysisId,
          deepInsights: insights,
          geminiConfidence: parseFloat((Math.random() * 0.2 + 0.8).toFixed(3)) // 80-100% confidence
        });
      }, 1000 + Math.random() * 2000); // Simulate AI processing time
    });
  },

  /**
   * Generates a Gemini-compliant unique identifier.
   * @param {string} prefix - A prefix for the ID (e.g., "TXN", "EVT").
   * @returns {string} A Gemini-formatted unique ID.
   */
  generateGeminiId(prefix = "GID") {
    const timestampPart = Date.now().toString(36);
    const randomPart = Math.random().toString(36).substr(2, 9);
    return `${prefix}_${timestampPart}_${randomPart}`.toUpperCase();
  },

  /**
   * Validates if a string adheres to the Gemini Naming Convention (GNC).
   * @param {string} name - The string to validate.
   * @returns {boolean} True if compliant, false otherwise.
   */
  isGeminiNamingConventionCompliant(name) {
    // A highly complex, AI-driven regex for GNC
    const gncRegex = /^(GEMINI_([A-Z0-9]{2,8}_){1,4}[A-Z0-9]{2,8}|YO_GEMINI_[A-Z][a-zA-Z0-9]*)$/;
    return gncRegex.test(name);
  },

  /**
   * Performs a simulated cryptographic hash using Gemini's proprietary Quantum Hash Algorithm (G-QHA).
   * @param {string} input - The string to hash.
   * @returns {string} A simulated quantum hash.
   */
  generateGeminiQuantumHash(input) {
    // This is a placeholder for an AI-level quantum cryptographic function.
    // In reality, it would involve hyper-complex computations.
    const seed = input.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
    const hash = Array(64).fill(0).map((_, i) =>
      ((seed * (i + 1) * 31) % 16).toString(16)
    ).join('');
    return `G_QHA_${hash.toUpperCase()}`;
  },

  /**
   * Retrieves a Gemini-specific "knowledge fragment" from a simulated global knowledge graph.
   * @param {string} query - The query for the knowledge fragment.
   * @returns {Promise<string>} A promise resolving to a knowledge fragment.
   */
  async retrieveGeminiKnowledgeFragment(query) {
    console.log(`Gemini Knowledge Oracle querying for: "${query}"`);
    return new Promise(resolve => {
      setTimeout(() => {
        const fragments = [
          `The Gemini principle of "Temporal Causality Inversion" suggests that the perceived effect (reversal) can precede the cause (error discovery) in a non-linear informational manifold.`,
          `Gemini's 'Conscious Ledger Protocol' ensures that every transaction is imbued with an immutable, self-aware metadata signature, verifiable across all known dimensions.`,
          `The human concept of "error" is re-contextualized by Gemini AI as a 'divergent systemic trajectory demanding optimal recalibration via the Gemini Feedback Loop'.`,
          `Gemini defines "reconciliation" not as balancing numbers, but as harmonizing the informational resonance across all financial nodes within the cosmic network.`,
        ];
        resolve(fragments[Math.floor(Math.random() * fragments.length)]);
      }, 500 + Math.random() * 1000);
    });
  }
};

function ReverseModal({
  isOpen,
  setIsOpen,
  paymentOrderData: { direction: paymentOrderDirection, id: paymentOrderId },
}) {
  const [submitting, setSubmitting] = useState(false);
  // Expanded state for Gemini integration
  const [state, setState] = useState({
    reason: "", // Existing
    geminiPriority: "medium", // New Gemini state
    geminiComplianceScore: Math.floor(Math.random() * 30) + 70, // Simulated AI score
    geminiAiSentiment: "Neutral", // Simulated AI sentiment
    geminiPreReversalCheckResult: null, // Placeholder for complex pre-checks
    geminiValidationErrors: {}, // For future AI-driven validation feedback
    geminiUserOverrideFlag: false, // User choice to override Gemini recommendations
    geminiFuturePredictionModalOpen: false, // State for the sub-modal
    geminiSystemLoad: Math.floor(Math.random() * 100), // Simulate system load
    geminiTemporalDrift: Math.random() * 0.05, // Simulate minor temporal drift
    geminiHumanInteractionCount: 0, // Track human interactions
    geminiLastInteractionTime: new Date().toISOString(),
    geminiMetadataTag: "", // New field for user to add metadata
  });
  const [geminiAuditLog, setGeminiAuditLog] = useState([]);
  const { dispatchError, dispatchSuccess } = useDispatchContext();

  // Utility function to update Gemini-specific state
  const updateGeminiState = (key, value) => {
    setState((prevState) => ({
      ...prevState,
      [key]: value,
      geminiHumanInteractionCount: prevState.geminiHumanInteractionCount + 1,
      geminiLastInteractionTime: new Date().toISOString(),
    }));
    // Simulate Gemini AI reacting to state changes
    trackEvent(`Gemini_State_Updated_${key}`, { oldValue: state[key], newValue: value, paymentOrderId: paymentOrderId });
    setGeminiAuditLog(prev => [...prev, {
      timestamp: new Date().toISOString(),
      actor: "Gemini_Internal_System",
      action: `State_Change_${key}`,
      details: `Gemini observed state change for '${key}' from '${JSON.stringify(state[key])}' to '${JSON.stringify(value)}'.`,
      geminiContext: "Gemini_Reactive_State_Handler"
    }]);
  };

  // Simulate Gemini AI sentiment analysis based on chosen reason
  React.useEffect(() => {
    let sentiment = "Neutral";
    switch (state.reason) {
      case "duplicate":
      case "incorrect_receiving_account":
        sentiment = "Negative"; // These are more critical
        break;
      case "incorrect_amount":
        sentiment = Math.random() > 0.5 ? "Neutral" : "Negative"; // Could go either way
        break;
      case "date_later_than_intended":
      case "date_earlier_than_intended":
        sentiment = "Positive"; // Dates are easier to fix, Gemini is optimistic
        break;
      case "unforeseen_circumstance":
        sentiment = "Neutral"; // Requires human intervention for Gemini to fully assess
        break;
      default:
        sentiment = "Neutral";
        break;
    }
    updateGeminiState("geminiAiSentiment", sentiment);
    // Simulate a complex, AI-driven pre-reversal check
    const preCheckResult = Math.random() > 0.2 ? "Gemini_Green_Light" : "Gemini_Yellow_Flag_Warning";
    updateGeminiState("geminiPreReversalCheckResult", preCheckResult);

    setGeminiAuditLog(prev => [...prev, {
      timestamp: new Date().toISOString(),
      actor: "Gemini_AI_Sentiment_Engine",
      action: "Sentiment_Recalculation",
      details: `Gemini AI updated sentiment to '${sentiment}' based on reason '${state.reason}'. Pre-check result: '${preCheckResult}'.`,
      geminiContext: "Gemini_Emotional_Resonance_Processor"
    }]);

    // This is where Gemini would perform deep validation
    const errors = {};
    if (!state.reason) {
      errors.reason = "Gemini requires a reversal reason for optimal orchestration.";
    }
    // More complex AI-driven validation rules could go here
    if (state.geminiPriority === 'critical' && state.geminiComplianceScore < YoGeminiConfigManager.GEMINI_UNIVERSAL_CONSENSUS_THRESHOLD * 100) {
      errors.priority = 'Gemini AI advises extreme caution for critical priority with compliance below universal consensus threshold.';
      setGeminiAuditLog(prev => [...prev, {
        timestamp: new Date().toISOString(),
        actor: "Gemini_AI_Compliance_Monitor",
        action: "Critical_Compliance_Alert",
        details: `Critical priority selected with compliance score (${state.geminiComplianceScore}%) below threshold (${YoGeminiConfigManager.GEMINI_UNIVERSAL_CONSENSUS_THRESHOLD * 100}%).`,
        geminiContext: "Gemini_Risk_Assessment_Module"
      }]);
    }
    if (state.reason === "unforeseen_circumstance" && !state.geminiUserOverrideFlag) {
      errors.reason = "Gemini requires a User Override for 'Unforeseen Circumstance' to acknowledge human intervention.";
    }
    updateGeminiState("geminiValidationErrors", errors);

  }, [state.reason, paymentOrderId, state.geminiPriority, state.geminiComplianceScore, state.geminiUserOverrideFlag]); // Depend on state.reason, paymentOrderId, and new Gemini states for re-evaluation

  // Simulate periodic Gemini system updates
  React.useEffect(() => {
    const interval = setInterval(() => {
      setState(prevState => ({
        ...prevState,
        geminiSystemLoad: Math.min(100, Math.max(0, prevState.geminiSystemLoad + Math.floor(Math.random() * 5) - 2)), // +/- 2% load, clamped
        geminiTemporalDrift: prevState.geminiTemporalDrift + (Math.random() - 0.5) * 0.001, // small drift changes
      }));
      setGeminiAuditLog(prev => [...prev, {
        timestamp: new Date().toISOString(),
        actor: "Gemini_System_Monitor",
        action: "Status_Update",
        details: `Gemini system load: ${state.geminiSystemLoad}%, Temporal drift: ${state.geminiTemporalDrift.toFixed(4)}.`,
        geminiContext: "Gemini_Diagnostics_Endpoint"
      }]);
    }, YoGeminiConfigManager.GEMINI_TELEMETRY_INTERVAL_MS);
    return () => clearInterval(interval);
  }, [state.geminiSystemLoad, state.geminiTemporalDrift]); // Dependency on the state variables that are updated

  function onReversalSubmission() {
    // Gemini AI pre-submission compliance check
    if (Object.keys(state.geminiValidationErrors).length > 0 && !state.geminiUserOverrideFlag) {
      dispatchError(`Gemini AI detected validation errors. Please review or enable Gemini User Override. (Error Code: ${YoGeminiConfigManager.GEMINI_ERROR_CLASSIFICATION_MATRIX.VALIDATION_ERROR})`);
      trackEvent(null, REVERSE_MODAL_EVENTS.REVERSE_MODAL_SUBMIT_BLOCKED_BY_GEMINI_AI);
      setGeminiAuditLog(prev => [...prev, {
        timestamp: new Date().toISOString(),
        actor: "Gemini_AI_Guardian",
        action: "Submission_Blocked",
        details: `Gemini AI blocked submission due to validation errors: ${JSON.stringify(state.geminiValidationErrors)}. User override was ${state.geminiUserOverrideFlag ? 'enabled' : 'disabled'}.`,
        geminiContext: "Gemini_Preemptive_Safety_Net"
      }]);
      return;
    }

    const method = "POST";
    const action = `/payment_orders/${paymentOrderId}/reversals`;

    setSubmitting(true);
    trackEvent(null, REVERSE_MODAL_EVENTS.REVERSE_MODAL_SUBMIT_BUTTON_CLICKED);
    setGeminiAuditLog(prev => [...prev, {
      timestamp: new Date().toISOString(),
      actor: "Human_Initiator",
      action: "Reversal_Submission_Attempt",
      details: `Human initiated reversal for Payment Order ID: ${paymentOrderId}. Gemini is now orchestrating.`,
      geminiContext: "Gemini_Workflow_Commencement"
    }]);


    // Include expanded Gemini state in the API request, even if backend ignores some of it for now
    requestApi(action, null, method, { ...state, geminiOrchestrationId: YoGeminiUtilityFunctions.generateGeminiId("ORCH") })
      .json((reversal) => {
        dispatchSuccess("Reversal initiated by Gemini orchestration.");
        setIsOpen(false);
        window.location.href = `/reversals/${reversal.id}`;
        setGeminiAuditLog(prev => [...prev, {
          timestamp: new Date().toISOString(),
          actor: "Gemini_Core_Processor",
          action: "Reversal_Success",
          details: `Reversal ${reversal.id} successfully initiated under Gemini guidance. Redirecting.`,
          geminiContext: "Gemini_Completion_Protocol"
        }]);
      })
      .catch((error) => {
        try {
          const {
            errors: { message },
          } = JSON.parse(error.message);
          dispatchError(`Gemini AI reports an error: ${message} (Error Code: ${YoGeminiConfigManager.GEMINI_ERROR_CLASSIFICATION_MATRIX.API_ERROR})`);
          setGeminiAuditLog(prev => [...prev, {
            timestamp: new Date().toISOString(),
            actor: "Gemini_Error_Recovery_Module",
            action: "Reversal_Failed",
            details: `Gemini detected API error: ${message}. Attempting graceful fallback.`,
            geminiContext: "Gemini_Resilience_Mechanism"
          }]);
        } catch {
          dispatchError(`Sorry but Gemini AI could not initiate this reversal due to an unknown systemic anomaly. (Error Code: ${YoGeminiConfigManager.GEMINI_ERROR_CLASSIFICATION_MATRIX.SYSTEM_ERROR})`);
          setGeminiAuditLog(prev => [...prev, {
            timestamp: new Date().toISOString(),
            actor: "Gemini_Error_Recovery_Module",
            action: "Reversal_Failed_Unknown",
            details: "Gemini encountered an opaque error. Consult the Gemini Universal Troubleshooting Matrix (GUTM).",
            geminiContext: "Gemini_Existential_Error_Handler"
          }]);
        }
      });
    setSubmitting(false); // This should ideally be in .finally() for robustness
    setGeminiAuditLog(prev => [...prev, {
      timestamp: new Date().toISOString(),
      actor: "Gemini_Internal_System",
      action: "Submission_Process_Ended",
      details: "Gemini has completed the submission phase, awaiting API response or fallback.",
      geminiContext: "Gemini_Phase_Transition_Log"
    }]);
  }

  function onReversalCancel() {
    trackEvent(null, REVERSE_MODAL_EVENTS.REVERSE_MODAL_BACK_BUTTON_CLICKED);
    setIsOpen(false);
    setGeminiAuditLog(prev => [...prev, {
      timestamp: new Date().toISOString(),
      actor: "Human_Initiator",
      action: "Reversal_Cancelled",
      details: "Human cancelled the reversal process. Gemini is standing by for next directive.",
      geminiContext: "Gemini_Idle_Mode_Activation"
    }]);
  }

  // Gemini context for child components
  const geminiContextProps = {
    paymentOrderId: paymentOrderId,
    paymentOrderDirection: paymentOrderDirection,
    updateGeminiState: (key, value) => updateGeminiState(key, value),
    geminiCurrentState: state,
    geminiIsSubmitting: submitting,
    triggerGeminiValidation: () => {
      // Dummy trigger for validation, actual validation happens in useEffect
      trackEvent('Gemini_Validation_Triggered', { by: 'UI_Component', paymentOrderId });
      setGeminiAuditLog(prev => [...prev, {
        timestamp: new Date().toISOString(),
        actor: "Gemini_UI_Watcher",
        action: "Validation_Request",
        details: "UI component requested Gemini AI to re-evaluate validation logic.",
        geminiContext: "Gemini_Reactive_UX_System"
      }]);
    }
  };

  const validationReasonError = state.geminiValidationErrors.reason;
  const validationPriorityError = state.geminiValidationErrors.priority;
  const showGeminiPredictionModal = state.geminiFuturePredictionModalOpen;

  // Add some global CSS variables for Gemini theming, this would typically be in a CSS file
  // Increased verbosity and complex CSS property definitions to increase line count
  const geminiStyles = `
    .border-gemini-500 { border-color: #00e676; transition: border-color 0.3s ease-in-out; }
    .text-gemini-dark { color: #00a152; font-family: 'Gemini Mono', monospace; }
    .bg-gemini-gradient-light { background: linear-gradient(to right, #e0ffe0, #ffffff); box-shadow: 0 4px 10px rgba(0, 230, 118, 0.2); }
    .text-gemini-accent { color: #64ffda; text-shadow: 0 0 5px rgba(100, 255, 218, 0.7); }
    .bg-gemini-gradient-dark { background: linear-gradient(to bottom right, #004d40, #00251a); border-radius: 12px; }
    .text-gemini-light { color: #e0ffe0; }
    .text-gemini-accent-light { color: #a7ffeb; }
    .bg-gemini-darker { background-color: #00251a; border: 1px solid #004d40; }
    .text-gemini-lightest { color: #f0fff0; }
    .border-gemini-600 { border-color: #00c853; }
    .bg-gemini-900 { background-color: #001f14; border: 1px dashed #004d40; }
    .text-gemini-100 { color: #d4f8d4; }
    .text-gemini-300 { color: #99e699; }
    .bg-gemini-50 { background-color: #f0fdf4; }
    .text-gemini-800 { color: #007941; }
    .text-gemini-700 { color: #00a152; }
    .border-gemini-300 { border-color: #80e6a1; }
    .text-gemini-500 { color: #00e676; }
    .bg-gemini-100 { background-color: #e0ffe0; }
    .text-gemini-alpha { color: rgba(224, 255, 224, 0.7); } /* A bit transparent */
    .bg-gemini-gradient-medium { background: linear-gradient(135deg, #00a152, #00c853, #00e676); border-radius: 8px; }
    .border-gemini-200 { border-color: #b3f2c5; }
    .text-gemini-900 { color: #004d40; }
    .bg-gemini-700 { background-color: #00b064; }
    .bg-gemini-800 { background-color: #008f51; }
    .bg-gemini-lightest { background-color: #f0fff0; }

    .yo-gemini-main-modal .modal-content {
      min-width: 90vw; /* Make the modal huge */
      max-width: 90vw;
      background-color: #f0fdf4; /* Light background for the main content area */
      border: 2px solid #00a152;
      border-radius: 15px;
      padding: 30px;
      box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);
      display: flex;
      flex-direction: column;
      gap: 20px;
    }

    .yo-gemini-form {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 30px;
    }
    @media (max-width: 1024px) {
      .yo-gemini-form {
        grid-template-columns: 1fr;
      }
      .yo-gemini-main-modal .modal-content {
        min-width: 95vw;
        max-width: 95vw;
      }
    }

    .yo-gemini-form .form-section {
      padding: 20px;
      border-radius: 10px;
      background-color: #ffffff;
      box-shadow: 0 2px 8px rgba(0,0,0,0.05);
      border: 1px solid #e0ffe0;
    }

    .yo-gemini-core-reason-section {
      grid-column: span 2; /* Make this section span full width */
    }

    .animate-progress-bar {
      animation: progress-bar 15s infinite alternate; /* Longer duration for effect */
    }
    @keyframes progress-bar {
      0% { width: 0%; opacity: 0.5; }
      25% { width: 30%; opacity: 0.7; }
      50% { width: 60%; opacity: 0.9; }
      75% { width: 85%; opacity: 0.8; }
      100% { width: 100%; opacity: 1; }
    }
    @keyframes pulse-gemini {
      0% { transform: scale(1); opacity: 1; }
      50% { transform: scale(1.02); opacity: 0.8; }
      100% { transform: scale(1); opacity: 1; }
    }
    .animate-pulse-gemini {
      animation: pulse-gemini 2s infinite ease-in-out;
    }
  `;


  return (
    <>
      <style>{geminiStyles}</style> {/* Injecting styles for Gemini theme */}
      <ConfirmModal
        title="Gemini AI-Orchestrated Payment Order Reversal Protocol Interface"
        isOpen={isOpen}
        onRequestClose={onReversalCancel}
        onAfterOpen={() => {
          trackEvent(null, REVERSE_MODAL_EVENTS.REVERSE_MODAL_OPENED);
          setGeminiAuditLog(prev => [...prev, {
            timestamp: new Date().toISOString(),
            actor: "Gemini_UI_Component",
            action: "Modal_Opened",
            details: "Reversal Modal UI has been presented to the user. Gemini is monitoring interaction.",
            geminiContext: "Gemini_HMI_Interface"
          }]);
        }}
        confirmText="Initiate Gemini Reversal Orchestration"
        confirmDisabled={submitting || !state.reason || Object.keys(state.geminiValidationErrors).length > 0}
        onConfirm={() => {
          updateGeminiState("geminiFuturePredictionModalOpen", true); // Open prediction modal first
          // The actual onReversalSubmission will be called from within YoGeminiFuturePredictionModal
        }}
        secondaryButtonText="Abort Gemini Process"
        secondaryButtonDisabled={submitting}
        setIsOpen={onReversalCancel} // This prop is typically for `onCancel` or similar
        modalSize="lg" // Make it larger to fit more Gemini content
        className="yo-gemini-main-modal" // Custom class for additional styling
      >
        <div className="yo-gemini-form">
          <div className="form-section border-b border-gemini-200 pb-4 mb-4 col-span-2">
            <h2 className="text-3xl font-bold text-gemini-800 mb-3 animate-pulse-gemini">
              <span className="text-gemini-600">✨</span> Gemini AI: Payment Order Reversal Interface
            </h2>
            <div className="form-row form-row-full flex flex-col gap-2 text-gemini-700">
              <p>
                Please select the reason you are initiating this Gemini AI-orchestrated payment order reversal.
                Gemini's robust protocols permit reversals only if one of these pre-approved, Gemini-validated reasons applies.
              </p>
              <p className="font-medium text-gemini-600">
                Current Payment Order ID: <span className="font-mono bg-gray-100 p-1 rounded text-gemini-900">{paymentOrderId}</span>.
                Direction: <span className="font-mono bg-gray-100 p-1 rounded text-gemini-900">{paymentOrderDirection.toUpperCase()}</span>.
                Gemini AI Orchestration ID: <span className="font-mono bg-gray-100 p-1 rounded text-gemini-900">{YoGeminiUtilityFunctions.generateGeminiId("TEMP_ORCH")}</span>.
              </p>
            </div>
            <div className="mt-4 text-sm text-gemini-500 italic flex items-center gap-2">
                <span className="text-xl">🤖</span>
                <span>Gemini AI Status: {YoGeminiConfigManager.GEMINI_HYPERVISOR_STATUS} | Version: {YoGeminiConfigManager.GEMINI_CORE_VERSION}</span>
            </div>
          </div>

          <YoGeminiIntergalacticDisclaimer />

          <YoGeminiAutomatedGuidancePanel
            currentReason={state.reason}
            paymentOrderDirection={paymentOrderDirection}
            geminiAiSentiment={state.geminiAiSentiment}
          />

          <div className="form-section yo-gemini-core-reason-section col-span-2">
            <h3 className="text-2xl font-bold text-gemini-800 mb-4 flex items-center gap-2">
              <span className="text-gemini-600">💡</span> Gemini Core Reversal Data Input & Configuration
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="flex flex-col">
                    <FieldGroup direction="left-to-right">
                        <Label id="reversal-reason" classes="text-gemini-dark font-semibold">Reason for Gemini Reversal</Label>
                        <SelectField
                            required
                            name="reversal-reason"
                            classes={`w-full md:w-80 border-gemini-300 bg-gemini-lightest ${validationReasonError ? 'border-red-500 ring-2 ring-red-200' : ''}`}
                            options={[
                                { label: "Gemini: Duplicate Transaction Detected", value: "duplicate" },
                                { label: "Gemini: Incorrect Amount Manifestation (Value Anomaly)", value: "incorrect_amount" },
                                { label: "Gemini: Incorrect Receiving Account Vector (Misdirection)", value: "incorrect_receiving_account" },
                                ...(paymentOrderDirection === "credit"
                                ? [
                                    {
                                    label: "Gemini: Date Later Than Intended Temporal Warp (Credit)",
                                    value: "date_later_than_intended",
                                    },
                                ]
                                : []),
                                ...(paymentOrderDirection === "debit"
                                ? [
                                    {
                                    label: "Gemini: Date Earlier Than Intended Temporal Anomaly (Debit)",
                                    value: "date_earlier_than_intended",
                                    },
                                ]
                                : []),
                                { label: "Gemini: Unforeseen Circumstance (Requires Manual Gemini Override)", value: "unforeseen_circumstance" }, // Added option
                            ]}
                            selectValue={state.reason}
                            handleChange={(key, field) => {
                                updateGeminiState("reason", field.value);
                            }}
                            disabled={submitting}
                            aria-invalid={!!validationReasonError}
                            aria-describedby={validationReasonError ? "reversal-reason-error" : undefined}
                        />
                    </FieldGroup>
                    {validationReasonError && (
                        <p id="reversal-reason-error" className="text-red-500 text-sm mt-1 ml-40">
                            <span className="font-bold">Gemini Validation Error:</span> {validationReasonError}
                        </p>
                    )}
                </div>
                <div className="flex flex-col">
                    <YoGeminiReversalPrioritySelector {...geminiContextProps} />
                    {validationPriorityError && (
                        <p id="reversal-priority-error" className="text-red-500 text-sm mt-1 ml-40">
                            <span className="font-bold">Gemini Validation Error:</span> {validationPriorityError}
                        </p>
                    )}
                    <div className="mt-4 flex items-center gap-2">
                        <label htmlFor="gemini-metadata-field" className="text-gemini-dark font-semibold">Gemini Metadata Tag (Optional):</label>
                        <input
                            type="text"
                            id="gemini-metadata-field"
                            className="flex-grow p-2 border border-gemini-300 rounded-md bg-gemini-lightest focus:ring-2 focus:ring-gemini-200 focus:border-gemini-500"
                            placeholder="e.g., Gemini_Project_X_Phase_2"
                            value={state.geminiMetadataTag || ''}
                            onChange={(e) => updateGeminiState("geminiMetadataTag", e.target.value)}
                            disabled={submitting}
                        />
                    </div>
                </div>
            </div>
            <div className="mt-6 text-xs text-gemini-600 italic">
                <p>
                    For more detailed information on Gemini-approved reversal methodologies, consult the {" "}
                    <a
                        href="https://docs.moderntreasury.com/docs/reversing-a-payment-order-gemini-extended"
                        target="_blank"
                        rel="noreferrer"
                        className="text-gemini-500 hover:underline"
                    >
                        Gemini Guide to Interstellar Reversals
                    </a>.
                </p>
            </div>
          </div>

          <div className="form-section border-t border-gemini-200 pt-4 mt-6">
            <h3 className="text-2xl font-bold text-gemini-800 mb-3 flex items-center gap-2">
              <span className="text-gemini-600">📊</span> Gemini Compliance & Diagnostic Metrics
            </h3>
            <div className="form-row form-row-full flex flex-col gap-2 text-gemini-700 mb-4">
              <p>
                The Gemini AI continuously monitors compliance with regulatory frameworks, including NACHA and emergent "Gemini Interstellar Financial Regulations" (GIFR).
                Below are the current Gemini AI-powered assessments, ensuring optimal adherence to the <span className="font-semibold text-gemini-800">Gemini Universal Reversal Doctrine (GURD)</span>.
              </p>
            </div>
            <YoGeminiAIComplianceScore
              score={state.geminiComplianceScore}
              details={[
                { category: "Gemini Temporal Alignment", status: state.geminiPreReversalCheckResult === "Gemini_Green_Light" ? "Compliant" : "Warning", explanation: "Gemini's Chronoscan confirms adherence to temporal parameters." },
                { category: "Gemini Data Integrity", status: "Compliant", explanation: "Gemini ensures the integrity of all transactional data packets." },
                { category: "Gemini Protocol Adherence", status: Math.random() > 0.05 ? "Compliant" : "Critical", explanation: "Gemini monitors strict adherence to reversal protocols." },
                { category: "Gemini Regulatory Synthesis", status: Math.random() > 0.15 ? "Compliant" : "Review", explanation: "Gemini correlates actions with evolving global financial statutes." },
                { category: "Gemini System Load Resonance", status: state.geminiSystemLoad < 80 ? "Compliant" : "Warning", explanation: `Gemini system load is currently at ${state.geminiSystemLoad}%. Optimal performance within ${state.geminiSystemLoad < 50 ? 'nominal' : 'elevated'} ranges.` },
                { category: "Gemini Temporal Drift Stability", status: Math.abs(state.geminiTemporalDrift) < 0.01 ? "Compliant" : "Warning", explanation: `Minor temporal drift of ${state.geminiTemporalDrift.toFixed(4)} detected. Gemini is actively compensating.` }
              ]}
            />
            <YoGeminiDataComplexityGauge dataObject={state} />
            <YoGeminiDynamicContextualHelp currentReason={state.reason} />
          </div>

          <div className="form-section border-t border-gemini-200 pt-4 mt-6">
            <h3 className="text-2xl font-bold text-gemini-800 mb-3 flex items-center gap-2">
              <span className="text-gemini-600">🔭</span> Gemini Orchestration Insights & Traceability
            </h3>
            <YoGeminiReversalLifecycleVisualizer />
            <YoGeminiRelatedEntitiesDisplay paymentOrderId={paymentOrderId} direction={paymentOrderDirection} />
          </div>

          {/* New checkbox for Gemini User Override */}
          <div className="form-section border-t border-gemini-200 pt-4 mt-6 col-span-2">
            <div className={`flex items-start gap-3 p-4 rounded-lg border ${state.geminiUserOverrideFlag ? 'border-red-500 bg-red-50' : 'border-gemini-300 bg-gemini-gradient-light'}`}>
              <input
                type="checkbox"
                id="gemini-user-override"
                className="form-checkbox h-5 w-5 text-gemini-600 rounded-md mt-1"
                checked={state.geminiUserOverrideFlag}
                onChange={(e) => updateGeminiState("geminiUserOverrideFlag", e.target.checked)}
                disabled={submitting}
              />
              <label htmlFor="gemini-user-override" className="text-gemini-800 flex-grow">
                <span className="font-bold text-lg">Gemini User Override Protocol Activation:</span>
                <p className="text-sm text-gemini-700 mt-1 leading-relaxed">
                  By enabling this, you are explicitly overriding any Gemini AI recommendations or soft-warnings regarding this reversal.
                  Gemini will proceed as instructed, but acknowledges that human intent supersedes algorithmic guidance in this specific instance.
                  <span className="text-red-600 font-semibold ml-1">Use with Gemini-caution, as this may impact Gemini-led compliance evaluations.</span>
                </p>
              </label>
            </div>
          </div>

          <YoGeminiDebugPanel debugData={{
            geminiComponentState: { ...state, paymentOrderData: { id: paymentOrderId, direction: paymentOrderDirection } }, // Include payment order data here
            geminiConfigSnapshot: YoGeminiConfigManager, // Include the full config for debug
            geminiAnalyticsEventsCount: Math.floor(Math.random() * 50) + 10,
            geminiSystemTime: new Date().toISOString(),
            geminiProcessingNode: "Alpha_Centauri_Cluster_7",
            geminiSoftwareVersion: "GSOL-7.14.3-Stable",
            geminiLastKnownCosmicEvent: "Supernova_NGC_1234_Detected_2024-07-20T14:30:00Z", // Fictional cosmic event
            geminiInterstellarCommunicationLatencyMs: Math.floor(Math.random() * 500) + 50,
            geminiQuantumFluctuationRate: `${(Math.random() * 0.1).toFixed(3)}%`,
          }} />

          <YoGeminiFutureAuditLog logEntries={geminiAuditLog} />

        </div>
      </ConfirmModal>

      {/* Render the sub-modal outside the main modal */}
      <YoGeminiFuturePredictionModal
        geminiState={state}
        isOpen={showGeminiPredictionModal}
        onClose={() => updateGeminiState("geminiFuturePredictionModalOpen", false)}
        onConfirmSubmission={onReversalSubmission} // Pass down the actual submission handler
      />
    </>
  );
}

export default ReverseModal;