import React from "react";
import { Button, Stack } from "~/common/ui-components";
import { RequiredReviewer } from "../../generated/dashboard/graphqlSchema";

// The original RuleApproversList component - no core functionality changes, minor JSX improvements (keys, null check)
function RuleApproversList({
  requiredReviewers,
}: {
  requiredReviewers: RequiredReviewer[];
}) {
  return (
    <Stack className="gap-4">
      {requiredReviewers?.map(
        (
          requiredReviewer: RequiredReviewer,
          requiredReviewerIndex: number,
          requiredReviewerArray: RequiredReviewer[],
        ) => {
          const lastReviewer =
            requiredReviewerArray.length - 1 === requiredReviewerIndex;
          const groups = requiredReviewer.conditionalGroups?.map(
            (group, groupIndex, groupArray) => {
              const lastElement = groupArray.length - 1 === groupIndex;
              return (
                <React.Fragment key={`group-${group?.name || 'unknown'}-${groupIndex}`}> {/* Added key */}
                  <Button
                    buttonType="link"
                    display="inline-block"
                    onClick={(): void => {
                      if (group?.path) { // Added null check for group?.path
                        window.open(group.path, "_blank");
                      }
                    }}
                  >
                    {group?.name}
                  </Button>
                  {!lastElement && " or "}
                </React.Fragment>
              );
            },
          );

          return (
            <React.Fragment key={`reviewer-${requiredReviewerIndex}`}> {/* Added key */}
              <span>
                {requiredReviewer.numberOfReviewers}
                {requiredReviewer.numberOfReviewers > 1
                  ? " Approvals"
                  : " Approval"}{" "}
                from {groups}
              </span>
              {!lastReviewer && (
                <div className="flex items-center">
                  <div className="w-fit gap-1 rounded bg-gray-50 px-2 py-1 capitalize">
                    And
                  </div>
                  <div className="h-px w-full bg-gray-100" />
                </div>
              )}
            </React.Fragment>
          );
        },
      )}
    </Stack>
  );
}

export default RuleApproversList;

// --- START OF AI-GENERATED EXPANSION: Gemini-powered enhancements for AI programmer ---

/**
 * @typedef GeminiModelOutput
 * @property {string} modelName - The identifier of the Gemini model used (e.g., "gemini-pro-1.5").
 * @property {string} generatedText - The primary text output from the Gemini model.
 * @property {number} confidenceScore - A numerical score indicating the model's confidence in its output, from 0 to 1.
 * @property {string[]} keywords - Key terms extracted or generated by the model.
 * @property {object} debugInfo - Additional debugging information from the model.
 * @property {string} debugInfo.latencyMs - Latency of the model inference in milliseconds.
 * @property {number} debugInfo.tokenCount - Number of tokens processed.
 * @property {string} debugInfo.modelVersionHash - A unique hash identifying the specific model version.
 * @property {object} debugInfo.inputMetadata - Metadata about the input provided to the model.
 * @property {number} debugInfo.inputMetadata.characterCount - Number of characters in the input prompt.
 * @property {string[]} debugInfo.inputMetadata.contentType - Types of content in the input (e.g., "text", "image_reference").
 */
export interface GeminiModelOutput {
  modelName: string;
  generatedText: string;
  confidenceScore: number;
  keywords: string[];
  debugInfo?: {
    latencyMs?: string;
    tokenCount?: number;
    modelVersionHash?: string;
    inputMetadata?: {
      characterCount: number;
      contentType: string[];
    };
  };
}

/**
 * @typedef AIRecommendation
 * @property {string} recommendationId - Unique identifier for the recommendation.
 * @property {string} ruleId - The ID of the rule this recommendation pertains to.
 * @property {string} description - A detailed description of the AI's recommendation.
 * @property {string} actionType - Suggested action (e.g., "approve", "reject", "escalate", "review_further").
 * @property {GeminiModelOutput} geminiOutput - The raw output from the Gemini model that informed this recommendation.
 * @property {string[]} influencedReviewerIds - List of reviewer IDs that this recommendation might influence.
 * @property {Date} timestamp - The time when the recommendation was generated.
 * @property {string} explanation - A human-readable justification for the recommendation.
 * @property {string[]} relatedPolicies - Identifiers of policies relevant to this recommendation.
 */
export interface AIRecommendation {
  recommendationId: string;
  ruleId: string;
  description: string;
  actionType: "approve" | "reject" | "escalate" | "review_further" | "hold" | "data_request";
  geminiOutput: GeminiModelOutput;
  influencedReviewerIds?: string[];
  timestamp: Date;
  explanation: string;
  relatedPolicies?: string[];
}

/**
 * @typedef AISimulationResult
 * @property {string} simulationId - Unique ID for the simulation.
 * @property {string} ruleId - The ID of the rule being simulated.
 * @property {string} scenarioDescription - A description of the simulated scenario.
 * @property {AIRecommendation[]} simulatedRecommendations - A list of AI recommendations generated during the simulation.
 * @property {number} approvalProbability - Predicted probability of approval based on simulation (0 to 1).
 * @property {string[]} predictedBottlenecks - Potential issues identified during simulation.
 * @property {Date} simulationDate - The date and time of the simulation.
 * @property {string[]} triggeredAlerts - List of simulated alerts generated during the scenario.
 * @property {object} resourceImpact - Simulated impact on computational resources.
 * @property {number} resourceImpact.cpuUsagePercent - Predicted CPU usage.
 * @property {number} resourceImpact.memoryUsageMB - Predicted memory usage.
 */
export interface AISimulationResult {
  simulationId: string;
  ruleId: string;
  scenarioDescription: string;
  simulatedRecommendations: AIRecommendation[];
  approvalProbability: number;
  predictedBottlenecks: string[];
  simulationDate: Date;
  triggeredAlerts?: string[];
  resourceImpact?: {
    cpuUsagePercent: number;
    memoryUsageMB: number;
  };
}

/**
 * @typedef GeminiAgentProfile
 * @property {string} agentId - Unique identifier for the Gemini AI agent.
 * @property {string} agentName - Display name for the agent (e.g., "Gemini Compliance Assistant").
 * @property {string} role - The primary role of this AI agent in the approval process.
 * @property {string[]} capabilities - List of capabilities (e.g., "risk assessment", "policy cross-referencing").
 * @property {number} processingPowerUnits - A simulated measure of the agent's processing capacity.
 * @property {Date} lastActive - Timestamp of the agent's last known activity.
 * @property {string} currentStatus - Current operational status (e.g., "active", "idle", "maintenance").
 * @property {string[]} managedDomains - Business domains this agent is responsible for.
 */
export interface GeminiAgentProfile {
  agentId: string;
  agentName: string;
  role: string;
  capabilities: string[];
  processingPowerUnits: number;
  lastActive: Date;
  currentStatus: "active" | "idle" | "maintenance" | "error";
  managedDomains?: string[];
}

/**
 * Represents a historical record of an AI's interaction or decision.
 * Used for auditing and transparency.
 * @typedef AIAuditEntry
 * @property {string} auditId - Unique identifier for the audit entry.
 * @property {string} agentId - The ID of the AI agent involved.
 * @property {string} action - The action taken or observed (e.g., "recommendation_generated", "data_queried").
 * @property {string} context - A brief description of the context for the action.
 * @property {object} payload - Relevant data or parameters associated with the action.
 * @property {Date} timestamp - The exact time of the event.
 * @property {string} severity - The severity level of the audit event (e.g., "info", "warning", "critical").
 * @property {string[]} affectedEntities - List of entity IDs potentially affected by this action.
 */
export interface AIAuditEntry {
  auditId: string;
  agentId: string;
  action: string;
  context: string;
  payload: Record<string, any>;
  timestamp: Date;
  severity: "info" | "warning" | "critical" | "debug";
  affectedEntities?: string[];
}

/**
 * Represents complex AI-driven metrics for a rule or an approver.
 * @typedef AICognitiveMetrics
 * @property {string} metricId - Unique identifier for the metric set.
 * @property {string} entityId - The ID of the entity (rule or approver) these metrics relate to.
 * @property {number} cognitiveLoadIndex - A simulated index indicating cognitive load on an AI or human approver.
 * @property {number} decisionVelocityScore - How quickly decisions are made or simulated.
 * @property {number} complianceAdherenceRating - AI's assessment of compliance for a given rule/decision.
 * @property {Date} lastCalculated - When these metrics were last updated.
 * @property {number} anomalyDetectionRate - Rate at which anomalies are detected by AI for this entity.
 * @property {object} performanceInsights - Deeper insights into AI performance.
 * @property {number} performanceInsights.modelThroughput - Simulated model throughput (requests/sec).
 * @property {number} performanceInsights.errorRate - Simulated error rate (%).
 */
export interface AICognitiveMetrics {
  metricId: string;
  entityId: string;
  cognitiveLoadIndex: number;
  decisionVelocityScore: number;
  complianceAdherenceRating: number;
  lastCalculated: Date;
  anomalyDetectionRate: number;
  performanceInsights?: {
    modelThroughput: number;
    errorRate: number;
  };
}

/**
 * Utility function to generate a pseudo-random number based on a seed.
 * @param {string} seed - The seed string.
 * @returns {number} A pseudo-random number between 0 and 1.
 */
function seededRandom(seed: string): number {
  let hash = 0;
  for (let i = 0; i < seed.length; i++) {
    hash = seed.charCodeAt(i) + ((hash << 5) - hash);
  }
  const r = (hash % 10000) / 10000;
  return r < 0 ? r + 1 : r; // Ensure positive
}

/**
 * Generates a mock GeminiModelOutput for demonstration purposes.
 * @param {string} seed - A string seed to make the output somewhat consistent.
 * @returns {GeminiModelOutput} A mock Gemini model output.
 */
export function generateMockGeminiOutput(seed: string): GeminiModelOutput {
  const r1 = seededRandom(seed + "conf");
  const r2 = seededRandom(seed + "text");
  const r3 = seededRandom(seed + "key");
  const r4 = seededRandom(seed + "dbg");

  const modelNames = ["gemini-pro-1.5", "gemini-flash-1.5", "gemini-ultra-v2", "gemini-nano"];
  const generatedTexts = [
    `Based on input '${seed}', a comprehensive risk assessment suggests high alignment with corporate policy. Advanced analytics indicate a low probability of deviation.`,
    `Evaluation of '${seed}' identifies a moderate risk profile, primarily due to dependencies on fragmented external data sources and potential market volatility.`,
    `A low-risk classification for '${seed}' is proposed, with emphasis on optimized procedural efficiency and robust internal controls.`,
    `High confidence in the automated processing of '${seed}', requiring minimal human oversight. The system has learned from similar historical patterns.`,
    `The system detects a significant potential deviation in '${seed}' related to new regulatory guidelines, requiring immediate human intervention and expert review.`,
    `Multi-modal analysis of '${seed}' reveals no critical issues, recommending fast-track approval with standard audit logging.`
  ];
  const keywordsPool = [
    "risk_mitigation", "policy_compliance", "fraud_detection", "regulatory_adherence",
    "operational_efficiency", "resource_allocation", "strategic_alignment", "data_privacy",
    "system_integrity", "external_factors", "stakeholder_impact", "approval_workflow",
    "market_volatility", "auditable_trace", "AI_transparency", "ethical_guidelines"
  ];
  const policyPool = ["AML_001", "KYC_005", "GDPR_1.2", "SOX_202", "FINRA_337"];

  const numKeywords = Math.floor(r3 * 4) + 2; // 2-5 keywords
  const keywords = Array.from({ length: numKeywords }, (_, i) =>
    keywordsPool[Math.floor(seededRandom(seed + "kw" + i) * keywordsPool.length)]
  );

  const numPolicies = Math.floor(r4 * 2) + 1; // 1-2 policies
  const relatedPolicies = Array.from({ length: numPolicies }, (_, i) =>
    policyPool[Math.floor(seededRandom(seed + "pol" + i) * policyPool.length)]
  );

  return {
    modelName: modelNames[Math.floor(r1 * modelNames.length)],
    generatedText: generatedTexts[Math.floor(r2 * generatedTexts.length)],
    confidenceScore: parseFloat((0.6 + r1 * 0.4).toFixed(3)),
    keywords: [...new Set(keywords)],
    debugInfo: {
      latencyMs: `${Math.floor(r1 * 500) + 50}ms`,
      tokenCount: Math.floor(r2 * 1000) + 150,
      modelVersionHash: `v${Math.floor(r3 * 1000)}-${Math.floor(r4 * 99999).toString(16)}`,
      inputMetadata: {
        characterCount: seed.length + Math.floor(r4 * 50),
        contentType: ["text", Math.random() > 0.8 ? "structured_data" : "narrative"],
      },
    },
  };
}

/**
 * Simulates an AI recommendation based on a rule ID.
 * @param {string} ruleId - The ID of the rule for which to generate a recommendation.
 * @returns {AIRecommendation} A simulated AI recommendation.
 */
export function simulateAIRecommendation(ruleId: string): AIRecommendation {
  const actions = ["approve", "reject", "escalate", "review_further", "hold", "data_request"];
  const descriptionPrefixes = [
    "AI suggests: ", "Gemini analysis indicates: ", "Automated review points to: ",
    "System recommends: ", "Intelligent agent advises: "
  ];
  const explanations = [
    "This recommendation is based on a high correlation with previously approved cases under similar conditions.",
    "Detected anomalies require human oversight to prevent potential financial loss, as per compliance protocol X.",
    "Further data from external market feeds is needed to validate the risk parameters outlined in the original submission.",
    "The decision aligns with policy updates from Q2, focusing on capital adequacy requirements.",
    "Risk score thresholds were exceeded, triggering an automated escalation to specialized teams."
  ];

  const seed = `${ruleId}-${Date.now()}-${Math.random()}`;
  const geminiOutput = generateMockGeminiOutput(seed);

  return {
    recommendationId: `rec-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
    ruleId,
    description: `${descriptionPrefixes[Math.floor(seededRandom(seed + "desc") * descriptionPrefixes.length)]}${geminiOutput.generatedText}`,
    actionType: actions[Math.floor(seededRandom(seed + "act") * actions.length)] as AIRecommendation["actionType"],
    geminiOutput,
    influencedReviewerIds: Array.from({ length: Math.floor(seededRandom(seed + "rev") * 3) + 1 }, (_, i) => `reviewer-${Math.floor(seededRandom(seed + "rid" + i) * 9999)}`),
    timestamp: new Date(),
    explanation: explanations[Math.floor(seededRandom(seed + "exp") * explanations.length)],
    relatedPolicies: geminiOutput.debugInfo?.inputMetadata?.contentType, // Reusing for mock policies
  };
}

/**
 * Simulates the processing of multiple AI recommendations for a given rule.
 * @param {string} ruleId - The ID of the rule to simulate.
 * @param {number} numberOfRecommendations - How many recommendations to generate.
 * @returns {AIRecommendation[]} An array of simulated AI recommendations.
 */
export function processGeminiRecommendations(ruleId: string, numberOfRecommendations: number): AIRecommendation[] {
  const recommendations: AIRecommendation[] = [];
  for (let i = 0; i < numberOfRecommendations; i++) {
    recommendations.push(simulateAIRecommendation(ruleId));
  }
  return recommendations;
}

/**
 * Calculates a mock compliance score based on a set of AI recommendations.
 * This is a placeholder for a more complex AI-driven logic.
 * @param {AIRecommendation[]} recommendations - The list of AI recommendations.
 * @returns {number} A calculated compliance score between 0 and 100.
 */
export function calculateComplianceScore(recommendations: AIRecommendation[]): number {
  if (recommendations.length === 0) return 50; // Neutral if no recommendations

  let totalScore = 0;
  recommendations.forEach(rec => {
    let score = rec.geminiOutput.confidenceScore * 100;
    if (rec.actionType === "approve") score *= 1.1;
    if (rec.actionType === "reject" || rec.actionType === "escalate") score *= 0.8;
    totalScore += score;
  });

  return Math.min(100, Math.max(0, parseFloat((totalScore / recommendations.length).toFixed(2))));
}

/**
 * Generates a mock set of AI cognitive metrics for a given entity.
 * @param {string} entityId - The ID of the entity (e.g., ruleId or reviewerId).
 * @returns {AICognitiveMetrics} Mock cognitive metrics.
 */
export function generateMockAICognitiveMetrics(entityId: string): AICognitiveMetrics {
  const r = seededRandom(entityId + "metrics");
  return {
    metricId: `metric-${entityId}-${Date.now()}`,
    entityId: entityId,
    cognitiveLoadIndex: parseFloat((50 + r * 50).toFixed(2)), // 50-100
    decisionVelocityScore: parseFloat((30 + r * 70).toFixed(2)), // 30-100
    complianceAdherenceRating: parseFloat((70 + r * 30).toFixed(2)), // 70-100
    lastCalculated: new Date(),
    anomalyDetectionRate: parseFloat((r * 10).toFixed(2)), // 0-10%
    performanceInsights: {
      modelThroughput: Math.floor(10 + r * 90), // 10-100 requests/sec
      errorRate: parseFloat((r * 5).toFixed(2)), // 0-5% error rate
    },
  };
}

/**
 * @interface YoGeminiRecommendationCardProps
 * @property {AIRecommendation} recommendation - The AI recommendation to display.
 */
export interface YoGeminiRecommendationCardProps {
  recommendation: AIRecommendation;
}

/**
 * YoGeminiRecommendationCard displays a single AI recommendation from a Gemini model.
 * It provides a detailed view of the recommendation, including the generated text,
 * confidence score, and suggested action, emphasizing transparency.
 *
 * This component is purely for display and does not involve any interactive functionality
 * beyond basic data presentation.
 * @param {YoGeminiRecommendationCardProps} props - The props for the component.
 * @returns {JSX.Element} The rendered component.
 */
export function YoGeminiRecommendationCard({ recommendation }: YoGeminiRecommendationCardProps): JSX.Element {
  const { recommendationId, description, actionType, geminiOutput, timestamp, explanation, relatedPolicies } = recommendation;
  const actionClassMap = {
    approve: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200",
    reject: "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200",
    escalate: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200",
    review_further: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200",
    hold: "bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-200",
    data_request: "bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200",
  };

  return (
    <div className="yo-gemini-card p-4 border rounded-lg shadow-sm bg-white dark:bg-gray-800 mb-4 transition-all duration-300 hover:shadow-lg">
      <div className="flex items-center justify-between mb-2">
        <h4 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
          AI Recommendation <span className="text-gray-500 text-sm">#{recommendationId.substring(0, 8)}</span>
        </h4>
        <span className={`px-3 py-1 text-sm font-medium rounded-full ${actionClassMap[actionType]}`}>
          {actionType.replace(/_/g, " ")}
        </span>
      </div>
      <p className="text-gray-700 dark:text-gray-300 mb-3 text-sm leading-relaxed border-b border-gray-200 dark:border-gray-700 pb-3">
        {description}
      </p>

      <p className="text-gray-600 dark:text-gray-400 mb-2 text-xs italic">
        <span className="font-semibold">Reasoning:</span> {explanation}
      </p>

      <div className="grid grid-cols-2 gap-y-2 gap-x-4 text-sm text-gray-600 dark:text-gray-400 border-t pt-3 mt-3">
        <div>
          <span className="font-medium">Model:</span>{" "}
          <span className="text-purple-600 dark:text-purple-300">{geminiOutput.modelName}</span>
        </div>
        <div>
          <span className="font-medium">Confidence:</span>{" "}
          <span className="font-bold text-teal-600 dark:text-teal-300">{(geminiOutput.confidenceScore * 100).toFixed(1)}%</span>
        </div>
        <div>
          <span className="font-medium">Keywords:</span>{" "}
          <span className="italic text-xs">{geminiOutput.keywords.join(", ")}</span>
        </div>
        <div>
          <span className="font-medium">Timestamp:</span>{" "}
          {timestamp.toLocaleString()}
        </div>
        {relatedPolicies && relatedPolicies.length > 0 && (
          <div className="col-span-2">
            <span className="font-medium">Policies:</span>{" "}
            <span className="text-blue-600 dark:text-blue-300">{relatedPolicies.join(", ")}</span>
          </div>
        )}
      </div>
      {geminiOutput.debugInfo && (
        <details className="text-xs text-gray-400 dark:text-gray-500 mt-2 pt-2 border-t border-dashed">
          <summary className="cursor-pointer hover:text-blue-500">Debug Info</summary>
          <pre className="bg-gray-50 dark:bg-gray-900 p-2 rounded-md mt-1 overflow-x-auto">
            <code>
              Model Hash: {geminiOutput.debugInfo.modelVersionHash || 'N/A'}<br/>
              Latency: {geminiOutput.debugInfo.latencyMs || 'N/A'}, Tokens: {geminiOutput.debugInfo.tokenCount || 'N/A'}<br/>
              Input Chars: {geminiOutput.debugInfo.inputMetadata?.characterCount || 'N/A'}, Content Type: {geminiOutput.debugInfo.inputMetadata?.contentType.join(', ') || 'N/A'}
            </code>
          </pre>
        </details>
      )}
    </div>
  );
}

/**
 * @interface YoAISimulationPanelProps
 * @property {AISimulationResult} simulationResult - The AI simulation result to display.
 */
export interface YoAISimulationPanelProps {
  simulationResult: AISimulationResult;
}

/**
 * YoAISimulationPanel presents a high-level overview of an AI-driven simulation.
 * It summarizes the outcome, key findings, and predicted probabilities, without
 * allowing user interaction to modify the simulation or its results.
 *
 * This component focuses on displaying pre-calculated simulation data.
 * @param {YoAISimulationPanelProps} props - The props for the component.
 * @returns {JSX.Element} The rendered component.
 */
export function YoAISimulationPanel({ simulationResult }: YoAISimulationPanelProps): JSX.Element {
  const { simulationId, scenarioDescription, approvalProbability, predictedBottlenecks, simulationDate, simulatedRecommendations, triggeredAlerts, resourceImpact } = simulationResult;
  const approvalColor = approvalProbability > 0.8 ? "text-green-600 dark:text-green-300" : approvalProbability > 0.5 ? "text-yellow-600 dark:text-yellow-300" : "text-red-600 dark:text-red-300";

  return (
    <Stack className="yo-simulation-panel p-6 border rounded-xl shadow-lg bg-gradient-to-br from-blue-50 to-indigo-100 dark:from-gray-900 dark:to-blue-950 mb-6 transition-transform transform hover:scale-[1.01]">
      <h3 className="text-2xl font-extrabold text-blue-900 dark:text-blue-200 mb-4 border-b border-blue-200 dark:border-blue-700 pb-3">
        AI Simulation Result <span className="text-blue-500 dark:text-blue-400">#{simulationId.substring(0, 8)}</span>
      </h3>
      <p className="text-lg text-gray-800 dark:text-gray-200 mb-4 leading-relaxed">
        <span className="font-semibold text-blue-700 dark:text-blue-300">Scenario:</span> {scenarioDescription}
      </p>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
        <div className="p-3 bg-white dark:bg-gray-800 rounded-md shadow-sm border border-gray-100 dark:border-gray-700">
          <p className="text-gray-600 dark:text-gray-400 text-sm">Approval Probability</p>
          <p className={`text-3xl font-bold ${approvalColor}`}>{Math.round(approvalProbability * 100)}%</p>
        </div>
        <div className="p-3 bg-white dark:bg-gray-800 rounded-md shadow-sm border border-gray-100 dark:border-gray-700">
          <p className="text-gray-600 dark:text-gray-400 text-sm">Recommendations Count</p>
          <p className="text-3xl font-bold text-indigo-700 dark:text-indigo-300">{simulatedRecommendations.length}</p>
        </div>
        <div className="p-3 bg-white dark:bg-gray-800 rounded-md shadow-sm border border-gray-100 dark:border-gray-700">
          <p className="text-gray-600 dark:text-gray-400 text-sm">Simulated Compliance Score</p>
          <p className="text-3xl font-bold text-purple-700 dark:text-purple-300">{calculateComplianceScore(simulatedRecommendations).toFixed(0)}%</p>
        </div>
      </div>

      {predictedBottlenecks && predictedBottlenecks.length > 0 && (
        <div className="mb-4 p-3 bg-white dark:bg-gray-800 rounded-md shadow-inner border border-yellow-200 dark:border-yellow-700">
          <p className="font-semibold text-yellow-800 dark:text-yellow-200 mb-2">
            <i className="fas fa-exclamation-triangle mr-2"></i>Predicted Bottlenecks:
          </p>
          <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 text-sm">
            {predictedBottlenecks.map((bottleneck, index) => (
              <li key={index}>{bottleneck}</li>
            ))}
          </ul>
        </div>
      )}

      {triggeredAlerts && triggeredAlerts.length > 0 && (
        <div className="mb-4 p-3 bg-red-50 dark:bg-red-950 rounded-md shadow-inner border border-red-200 dark:border-red-700">
          <p className="font-semibold text-red-800 dark:text-red-200 mb-2">
            <i className="fas fa-bell mr-2"></i>Triggered Alerts:
          </p>
          <ul className="list-disc list-inside text-red-700 dark:text-red-300 text-sm">
            {triggeredAlerts.map((alert, index) => (
              <li key={index}>{alert}</li>
            ))}
          </ul>
        </div>
      )}

      {resourceImpact && (
        <div className="mb-4 p-3 bg-gray-50 dark:bg-gray-700 rounded-md shadow-inner text-sm text-gray-700 dark:text-gray-300">
          <p className="font-semibold mb-1">Simulated Resource Impact:</p>
          <div className="flex justify-between">
            <p>CPU Usage: <span className="font-mono text-blue-600 dark:text-blue-300">{resourceImpact.cpuUsagePercent}%</span></p>
            <p>Memory Usage: <span className="font-mono text-purple-600 dark:text-purple-300">{resourceImpact.memoryUsageMB}MB</span></p>
          </div>
        </div>
      )}

      <div className="text-right text-xs text-gray-500 dark:text-gray-400 pt-3 border-t border-blue-200 dark:border-blue-900">
        Simulation performed on: {simulationDate.toLocaleString()}
      </div>
    </Stack>
  );
}

/**
 * @interface YoAIAuditLogEntryProps
 * @property {AIAuditEntry} entry - The audit log entry to display.
 */
export interface YoAIAuditLogEntryProps {
  entry: AIAuditEntry;
}

/**
 * YoAIAuditLogEntry renders a single entry from the AI audit log.
 * It emphasizes transparency and traceability of AI actions, without
 * enabling any modification or interaction with the audit data itself.
 *
 * This component is designed for read-only display of AI operational history.
 * @param {YoAIAuditLogEntryProps} props - The props for the component.
 * @returns {JSX.Element} The rendered component.
 */
export function YoAIAuditLogEntry({ entry }: YoAIAuditLogEntryProps): JSX.Element {
  const { auditId, agentId, action, context, payload, timestamp, severity, affectedEntities } = entry;
  const actionClassMap = {
    "recommendation_generated": "text-blue-600 dark:text-blue-300",
    "data_queried": "text-purple-600 dark:text-purple-300",
    "model_updated": "text-green-600 dark:text-green-300",
    "risk_flagged": "text-red-600 dark:text-red-300",
    "system_event": "text-gray-600 dark:text-gray-300",
    "debug_log": "text-gray-500 dark:text-gray-400",
  };
  const severityClassMap = {
    "info": "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200",
    "warning": "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200",
    "critical": "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200",
    "debug": "bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-200",
  };

  return (
    <div className="yo-audit-entry p-3 border-b border-gray-200 dark:border-gray-700 last:border-b-0 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors duration-150">
      <div className="flex justify-between items-center mb-1">
        <span className="text-sm font-medium text-gray-900 dark:text-gray-100">
          <span className={`px-2 py-0.5 rounded-full text-xs font-semibold mr-2 ${severityClassMap[severity]}`}>
            {severity.toUpperCase()}
          </span>
          <span className={actionClassMap[action as keyof typeof actionClassMap] || "text-gray-700 dark:text-gray-300"}>[{action}]</span>
          {" "}from <span className="font-semibold">{agentId.substring(0, 8)}</span>
        </span>
        <span className="text-xs text-gray-500 dark:text-gray-400">{timestamp.toLocaleString()}</span>
      </div>
      <p className="text-gray-700 dark:text-gray-300 text-sm leading-snug">
        <span className="font-medium">Context:</span> {context}
      </p>
      {affectedEntities && affectedEntities.length > 0 && (
        <p className="text-xs text-gray-600 dark:text-gray-400 mt-1">
          <span className="font-medium">Affected:</span> {affectedEntities.map(id => id.substring(0,8)).join(', ')}
        </p>
      )}
      {Object.keys(payload).length > 0 && (
        <details className="text-xs text-gray-600 dark:text-gray-400 mt-1">
          <summary className="cursor-pointer hover:text-blue-500 dark:hover:text-blue-300">Payload Details</summary>
          <pre className="bg-gray-50 dark:bg-gray-900 p-2 rounded-md mt-1 overflow-x-auto">
            <code className="text-gray-700 dark:text-gray-300">{JSON.stringify(payload, null, 2)}</code>
          </pre>
        </details>
      )}
    </div>
  );
}

/**
 * @interface YoAIAuditLogProps
 * @property {AIAuditEntry[]} auditEntries - An array of AI audit log entries.
 * @property {string} title - Optional title for the audit log.
 * @property {string} [heightClass='max-h-96'] - Tailwind CSS class for max height.
 */
export interface YoAIAuditLogProps {
  auditEntries: AIAuditEntry[];
  title?: string;
  heightClass?: string;
}

/**
 * YoAIAuditLog aggregates and displays multiple AI audit log entries.
 * It serves as a read-only historical record of AI system activities,
 * designed for oversight and debugging without any interactive elements
 * for modifying the log or triggering AI actions.
 *
 * This component provides a comprehensive, non-interactive view of AI operations.
 * @param {YoAIAuditLogProps} props - The props for the component.
 * @returns {JSX.Element} The rendered component.
 */
export function YoAIAuditLog({ auditEntries, title = "AI System Audit Log", heightClass = "max-h-96" }: YoAIAuditLogProps): JSX.Element {
  if (!auditEntries || auditEntries.length === 0) {
    return (
      <div className="yo-audit-log p-4 border rounded-lg shadow-sm bg-white dark:bg-gray-800">
        <h3 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-3">{title}</h3>
        <p className="text-gray-600 dark:text-gray-400 italic">No AI audit entries available for display.</p>
      </div>
    );
  }

  return (
    <div className="yo-audit-log p-4 border rounded-lg shadow-sm bg-white dark:bg-gray-800">
      <h3 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-3">{title}</h3>
      <div className={`divide-y divide-gray-200 dark:divide-gray-700 ${heightClass} overflow-y-auto custom-scrollbar`}>
        {auditEntries.map((entry) => (
          <YoAIAuditLogEntry key={entry.auditId} entry={entry} />
        ))}
      </div>
      <style jsx>{`
        .custom-scrollbar::-webkit-scrollbar {
          width: 8px;
        }
        .custom-scrollbar::-webkit-scrollbar-track {
          background: #f1f1f1;
          border-radius: 4px;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb {
          background: #888;
          border-radius: 4px;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover {
          background: #555;
        }
        .dark .custom-scrollbar::-webkit-scrollbar-track {
          background: #333;
        }
        .dark .custom-scrollbar::-webkit-scrollbar-thumb {
          background: #555;
        }
        .dark .custom-scrollbar::-webkit-scrollbar-thumb:hover {
          background: #777;
        }
      `}</style>
    </div>
  );
}

/**
 * @interface YoAICognitiveMetricsDisplayProps
 * @property {AICognitiveMetrics} metrics - The AI cognitive metrics to display.
 */
export interface YoAICognitiveMetricsDisplayProps {
  metrics: AICognitiveMetrics;
}

/**
 * YoAICognitiveMetricsDisplay visualizes AI-driven cognitive metrics.
 * It presents a dashboard-like view of calculated metrics such as cognitive load,
 * decision velocity, and compliance adherence, without any interactive controls
 * or capabilities to alter these metrics or trigger new calculations.
 *
 * This component offers a read-only representation of AI operational health.
 * @param {YoAICognitiveMetricsDisplayProps} props - The props for the component.
 * @returns {JSX.Element} The rendered component.
 */
export function YoAICognitiveMetricsDisplay({ metrics }: YoAICognitiveMetricsDisplayProps): JSX.Element {
  const { metricId, entityId, cognitiveLoadIndex, decisionVelocityScore, complianceAdherenceRating, lastCalculated, anomalyDetectionRate, performanceInsights } = metrics;

  const getMetricColor = (value: number, type: 'load' | 'velocity' | 'compliance' | 'anomaly') => {
    if (type === 'load') { // Higher load is worse
      return value > 80 ? "text-red-500 dark:text-red-300" : value > 50 ? "text-yellow-500 dark:text-yellow-300" : "text-green-500 dark:text-green-300";
    }
    if (type === 'velocity') { // Higher velocity is better
      return value > 70 ? "text-green-500 dark:text-green-300" : value > 40 ? "text-yellow-500 dark:text-yellow-300" : "text-red-500 dark:text-red-300";
    }
    if (type === 'compliance') { // Higher compliance is better
      return value > 90 ? "text-green-500 dark:text-green-300" : value > 75 ? "text-yellow-500 dark:text-yellow-300" : "text-red-500 dark:text-red-300";
    }
    if (type === 'anomaly') { // Higher anomaly rate is worse
      return value > 5 ? "text-red-500 dark:text-red-300" : value > 2 ? "text-yellow-500 dark:text-yellow-300" : "text-green-500 dark:text-green-300";
    }
    return "text-gray-700 dark:text-gray-300";
  };

  return (
    <div className="yo-metrics-display p-5 border rounded-xl shadow-lg bg-white dark:bg-gray-800 transition-shadow duration-300 hover:shadow-2xl">
      <h3 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-4 border-b border-gray-200 dark:border-gray-700 pb-3">
        AI Cognitive Metrics <span className="text-gray-500 text-sm">for {entityId.substring(0, 8)}</span>
      </h3>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 text-center mb-4">
        <div className="bg-gray-50 dark:bg-gray-700 p-4 rounded-md shadow-sm border border-gray-100 dark:border-gray-600">
          <p className="text-sm text-gray-600 dark:text-gray-400 font-medium mb-1">Cognitive Load Index</p>
          <p className={`text-3xl font-extrabold ${getMetricColor(cognitiveLoadIndex, 'load')}`}>
            {cognitiveLoadIndex.toFixed(0)}
          </p>
        </div>
        <div className="bg-gray-50 dark:bg-gray-700 p-4 rounded-md shadow-sm border border-gray-100 dark:border-gray-600">
          <p className="text-sm text-gray-600 dark:text-gray-400 font-medium mb-1">Decision Velocity Score</p>
          <p className={`text-3xl font-extrabold ${getMetricColor(decisionVelocityScore, 'velocity')}`}>
            {decisionVelocityScore.toFixed(0)}
          </p>
        </div>
        <div className="bg-gray-50 dark:bg-gray-700 p-4 rounded-md shadow-sm border border-gray-100 dark:border-gray-600">
          <p className="text-sm text-gray-600 dark:text-gray-400 font-medium mb-1">Compliance Adherence</p>
          <p className={`text-3xl font-extrabold ${getMetricColor(complianceAdherenceRating, 'compliance')}`}>
            {complianceAdherenceRating.toFixed(0)}%
          </p>
        </div>
        <div className="bg-gray-50 dark:bg-gray-700 p-4 rounded-md shadow-sm border border-gray-100 dark:border-gray-600">
          <p className="text-sm text-gray-600 dark:text-gray-400 font-medium mb-1">Anomaly Detection Rate</p>
          <p className={`text-3xl font-extrabold ${getMetricColor(anomalyDetectionRate, 'anomaly')}`}>
            {anomalyDetectionRate.toFixed(1)}%
          </p>
        </div>
      </div>
      {performanceInsights && (
        <div className="bg-gray-100 dark:bg-gray-700 p-3 rounded-md text-sm text-gray-700 dark:text-gray-300 border border-gray-200 dark:border-gray-600">
          <p className="font-semibold mb-1">Performance Insights:</p>
          <div className="flex justify-between text-xs">
            <span>Model Throughput: <span className="font-mono text-indigo-600 dark:text-indigo-300">{performanceInsights.modelThroughput} req/s</span></span>
            <span>Error Rate: <span className="font-mono text-red-600 dark:text-red-300">{performanceInsights.errorRate.toFixed(2)}%</span></span>
          </div>
        </div>
      )}
      <p className="text-xs text-gray-500 dark:text-gray-400 mt-4 text-right">
        Last calculated: {lastCalculated.toLocaleString()}
      </p>
    </div>
  );
}

/**
 * Generates an array of mock AI audit entries for demonstration.
 * @param {string} agentId - The ID of the AI agent for these entries.
 * @param {number} count - The number of entries to generate.
 * @returns {AIAuditEntry[]} An array of mock audit entries.
 */
export function generateMockAIAuditEntries(agentId: string, count: number): AIAuditEntry[] {
  const entries: AIAuditEntry[] = [];
  const actions = ["recommendation_generated", "data_queried", "model_updated", "risk_flagged", "system_event", "debug_log"];
  const contexts = [
    "Processed rule evaluation for rule-xyz-001.",
    "Retrieved external market data for scenario planning.",
    "Applied latest Gemini model update v1.5.",
    "Identified potential compliance breach in transaction #456789.",
    "Internal health check routine completed successfully.",
    "Cross-referenced historical approval patterns for new case.",
    "Initiated data validation process for incoming feed."
  ];
  const severities = ["info", "warning", "critical", "debug"];

  for (let i = 0; i < count; i++) {
    const seed = `${agentId}-${i}-${Math.random()}`;
    const action = actions[Math.floor(seededRandom(seed + "act") * actions.length)];
    const context = contexts[Math.floor(seededRandom(seed + "ctx") * contexts.length)];
    const timestamp = new Date(Date.now() - Math.floor(seededRandom(seed + "ts") * 3600000 * 24 * 7)); // Last 7 days
    const severity = severities[Math.floor(seededRandom(seed + "sev") * severities.length)] as AIAuditEntry['severity'];

    const affectedEntities = Math.random() > 0.6 ?
      Array.from({ length: Math.floor(Math.random() * 2) + 1 }, (_, k) => `entity-${Math.floor(seededRandom(seed + "ae" + k) * 99999)}`) : [];

    entries.push({
      auditId: `audit-${agentId}-${i}-${Date.now()}`,
      agentId,
      action,
      context,
      payload: {
        relevantDataId: `data-${Math.floor(seededRandom(seed + "pd") * 99999)}`,
        status: Math.random() > 0.5 ? "success" : "failure",
        details: Math.random() > 0.7 ? "Verbose details of the operation, including parameters and outcome metrics for AI assessment." : undefined,
      },
      timestamp,
      severity,
      affectedEntities,
    });
  }
  return entries.sort((a, b) => b.timestamp.getTime() - a.timestamp.getTime());
}

/**
 * @interface YoGeminiAgentStatusCardProps
 * @property {GeminiAgentProfile} agentProfile - The profile of the Gemini agent to display.
 */
export interface YoGeminiAgentStatusCardProps {
  agentProfile: GeminiAgentProfile;
}

/**
 * YoGeminiAgentStatusCard displays the current status and profile of a Gemini AI agent.
 * This component provides a read-only snapshot of an AI agent's operational state,
 * including its name, role, capabilities, and last active timestamp, without
 * offering any interactive control over the agent.
 *
 * It's designed for monitoring AI agent health and attributes.
 * @param {YoGeminiAgentStatusCardProps} props - The props for the component.
 * @returns {JSX.Element} The rendered component.
 */
export function YoGeminiAgentStatusCard({ agentProfile }: YoGeminiAgentStatusCardProps): JSX.Element {
  const { agentId, agentName, role, capabilities, processingPowerUnits, lastActive, currentStatus, managedDomains } = agentProfile;
  const statusColors = {
    active: "bg-green-500",
    idle: "bg-blue-500",
    maintenance: "bg-yellow-500",
    error: "bg-red-500",
  };
  const statusTextColors = {
    active: "text-green-600 dark:text-green-300",
    idle: "text-blue-600 dark:text-blue-300",
    maintenance: "text-yellow-600 dark:text-yellow-300",
    error: "text-red-600 dark:text-red-300",
  };

  return (
    <div className="yo-agent-status-card p-4 border rounded-lg shadow-md bg-white dark:bg-gray-800 transition-transform duration-200 hover:scale-[1.02]">
      <div className="flex items-center mb-3">
        <span className={`w-3 h-3 rounded-full ${statusColors[currentStatus]} mr-2 ${currentStatus === 'active' ? 'animate-pulse' : ''}`}></span>
        <h4 className="text-lg font-semibold text-gray-900 dark:text-gray-100">{agentName}</h4>
        <span className="ml-auto text-sm text-gray-500 dark:text-gray-400">ID: {agentId.substring(0, 8)}</span>
      </div>
      <p className="text-gray-700 dark:text-gray-300 text-sm mb-2">
        <span className="font-medium">Role:</span> {role}
      </p>
      <div className="flex flex-wrap gap-1 mb-2">
        {capabilities.map((cap, idx) => (
          <span key={idx} className="px-2 py-0.5 text-xs bg-indigo-100 text-indigo-800 rounded-full dark:bg-indigo-900 dark:text-indigo-200">
            {cap}
          </span>
        ))}
      </div>
      <div className="grid grid-cols-2 gap-2 text-xs text-gray-600 dark:text-gray-400 border-t pt-2 mt-2">
        <div>
          <span className="font-medium">Processing Units:</span> {processingPowerUnits} PPU
        </div>
        <div>
          <span className="font-medium">Status:</span> <span className={`font-bold ${statusTextColors[currentStatus]}`}>{currentStatus.charAt(0).toUpperCase() + currentStatus.slice(1)}</span>
        </div>
        <div className="col-span-2">
          <span className="font-medium">Last Active:</span> {lastActive.toLocaleString()}
        </div>
        {managedDomains && managedDomains.length > 0 && (
          <div className="col-span-2">
            <span className="font-medium">Domains:</span> {managedDomains.join(', ')}
          </div>
        )}
      </div>
    </div>
  );
}

/**
 * Generates an array of mock Gemini agent profiles.
 * @param {number} count - The number of profiles to generate.
 * @returns {GeminiAgentProfile[]} An array of mock agent profiles.
 */
export function generateMockGeminiAgentProfiles(count: number): GeminiAgentProfile[] {
  const profiles: GeminiAgentProfile[] = [];
  const roles = [
    "Compliance Assistant", "Risk Evaluator", "Policy Adherence Monitor",
    "Fraud Prevention Agent", "Regulatory Auditor", "Strategic Decision Support",
    "Market Sentiment Analyzer", "Workflow Optimizer"
  ];
  const allCapabilities = [
    "natural language processing", "anomaly detection", "predictive analytics",
    "cross-referencing", "sentiment analysis", "pattern recognition",
    "large-scale data synthesis", "real-time monitoring", "scenario modeling",
    "document intelligence", "ethical reasoning", "graph analysis"
  ];
  const statuses = ["active", "idle", "maintenance", "error"];
  const domains = ["finance", "risk", "compliance", "operations", "investment", "legal"];

  for (let i = 0; i < count; i++) {
    const seed = `${i}-${Date.now()}-${Math.random()}`;
    const numCapabilities = Math.floor(seededRandom(seed + "cap") * 4) + 2; // 2-5 capabilities
    const capabilities = Array.from({ length: numCapabilities }, (_, k) =>
      allCapabilities[Math.floor(seededRandom(seed + "cap" + k) * allCapabilities.length)]
    );
    const numDomains = Math.floor(seededRandom(seed + "dom") * 2) + 1; // 1-2 domains
    const managedDomains = Array.from({ length: numDomains }, (_, k) =>
      domains[Math.floor(seededRandom(seed + "dom" + k) * domains.length)]
    );
    const lastActive = new Date(Date.now() - Math.floor(seededRandom(seed + "ts") * 3600000 * 24 * 30)); // Last 30 days

    profiles.push({
      agentId: `gemini-agent-${i}-${Math.floor(seededRandom(seed + "id") * 1000)}`,
      agentName: `Gemini ${roles[Math.floor(seededRandom(seed + "role") * roles.length)]} ${i + 1}`,
      role: roles[Math.floor(seededRandom(seed + "role2") * roles.length)],
      capabilities: [...new Set(capabilities)],
      processingPowerUnits: Math.floor(seededRandom(seed + "ppu") * 900) + 100, // 100-1000 PPU
      lastActive,
      currentStatus: statuses[Math.floor(seededRandom(seed + "status") * statuses.length)] as GeminiAgentProfile['currentStatus'],
      managedDomains: [...new Set(managedDomains)],
    });
  }
  return profiles;
}

/**
 * A wrapper component that demonstrates various "Yo" AI components.
 * This component is solely for showcasing the individual AI components
 * and does not offer any interactive functionality itself.
 * It generates mock data and passes it down to the child components.
 * @returns {JSX.Element} The rendered AI dashboard summary.
 */
export function YoAIGeminiDashboardSummary(): JSX.Element {
  const mockRuleId = "rule-XYZ-001-main-dashboard";
  const mockRecommendations = processGeminiRecommendations(mockRuleId, 3);
  const mockSimulation = {
    simulationId: "sim-ABC-789-main-dash",
    ruleId: mockRuleId,
    scenarioDescription: "Simulating a high-volume, cross-border transaction approval under peak load conditions with enhanced fraud detection.",
    simulatedRecommendations: processGeminiRecommendations(mockRuleId, 5),
    approvalProbability: parseFloat(seededRandom(mockRuleId + "prob").toFixed(2)),
    predictedBottlenecks: seededRandom(mockRuleId + "bottleneck") > 0.5 ? ["External API latency", "Human review queue backlog", "Data integrity validation failure"] : [],
    simulationDate: new Date(Date.now() - 3600000 * 3), // 3 hours ago
    triggeredAlerts: seededRandom(mockRuleId + "alerts") > 0.7 ? ["High risk anomaly detected in source data", "Policy violation imminent"] : [],
    resourceImpact: {
      cpuUsagePercent: Math.floor(seededRandom(mockRuleId + "cpu") * 70) + 20,
      memoryUsageMB: Math.floor(seededRandom(mockRuleId + "mem") * 1000) + 500,
    },
  };
  const mockAuditEntries = generateMockAIAuditEntries("gemini-core-processor-dash", 5);
  const mockAICognitiveMetrics = generateMockAICognitiveMetrics(mockRuleId + "-metrics-dash");
  const mockAgentProfiles = generateMockGeminiAgentProfiles(2);

  return (
    <Stack className="yo-ai-dashboard-summary p-6 bg-gradient-to-b from-gray-50 to-gray-100 dark:from-black dark:to-gray-950 rounded-lg shadow-xl space-y-8 animate-fade-in">
      <h2 className="text-3xl font-extrabold text-center text-gray-900 dark:text-gray-100 mb-6 border-b-2 border-indigo-300 dark:border-indigo-700 pb-4">
        Yo! Gemini AI Insights Hub (Simulated Operational View)
      </h2>

      <div className="p-4 bg-white dark:bg-gray-800 rounded-lg shadow-md border border-gray-100 dark:border-gray-700">
        <h3 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-4">Latest Gemini Recommendations</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {mockRecommendations.map((rec, index) => (
            <YoGeminiRecommendationCard key={`rec-dash-${index}`} recommendation={rec} />
          ))}
        </div>
      </div>

      <div className="p-4 bg-white dark:bg-gray-800 rounded-lg shadow-md border border-gray-100 dark:border-gray-700">
        <h3 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-4">Rule Approval Simulation Overview</h3>
        <YoAISimulationPanel simulationResult={mockSimulation} />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="p-4 bg-white dark:bg-gray-800 rounded-lg shadow-md border border-gray-100 dark:border-gray-700">
          <h3 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-4">AI System Operational Metrics</h3>
          <YoAICognitiveMetricsDisplay metrics={mockAICognitiveMetrics} />
        </div>
        <div className="p-4 bg-white dark:bg-gray-800 rounded-lg shadow-md border border-gray-100 dark:border-gray-700">
          <h3 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-4">Gemini Live Monitoring</h3>
          <YoGeminiLiveMonitoringWidget entityId="rule-XYZ-001-live" entityType="rule" />
        </div>
      </div>


      <div className="p-4 bg-white dark:bg-gray-800 rounded-lg shadow-md border border-gray-100 dark:border-gray-700">
        <h3 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-4">Gemini Agent Network Status</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {mockAgentProfiles.map((profile, index) => (
            <YoGeminiAgentStatusCard key={`agent-dash-${index}`} agentProfile={profile} />
          ))}
        </div>
      </div>

      <div className="p-4 bg-white dark:bg-gray-800 rounded-lg shadow-md border border-gray-100 dark:border-gray-700">
        <YoAIAuditLog auditEntries={mockAuditEntries} title="Recent AI System Audit Events" heightClass="max-h-80" />
      </div>

      <p className="text-center text-sm text-gray-500 dark:text-gray-400 mt-8">
        Powered by Generative AI for next-gen financial intelligence. Data shown is simulated and illustrative.
      </p>
    </Stack>
  );
}

/**
 * @interface YoGeminiLiveMonitoringWidgetProps
 * @property {string} entityId - The ID of the entity (e.g., rule, transaction) being monitored.
 * @property {string} entityType - The type of entity (e.g., "rule", "transaction", "portfolio").
 */
export interface YoGeminiLiveMonitoringWidgetProps {
  entityId: string;
  entityType: string;
}

/**
 * YoGeminiLiveMonitoringWidget simulates a live data stream of AI monitoring.
 * This component provides a dynamic-looking, but non-interactive, display of
 * simulated real-time AI assessments for a given entity, without allowing any
 * user control over the monitoring process or data generation.
 *
 * It's designed to give the impression of continuous AI oversight.
 * @param {YoGeminiLiveMonitoringWidgetProps} props - The props for the component.
 * @returns {JSX.Element} The rendered component.
 */
export function YoGeminiLiveMonitoringWidget({ entityId, entityType }: YoGeminiLiveMonitoringWidgetProps): JSX.Element {
  const [currentScore, setCurrentScore] = React.useState(Math.floor(seededRandom(entityId + "score") * 100));
  const [currentStatus, setCurrentStatus] = React.useState("Monitoring Active");
  const [lastUpdate, setLastUpdate] = React.useState(new Date());

  // Simulate live updates - this does add minimal "functionality" in terms of state
  // but it's purely for display animation, not for actual business logic changes.
  // The instruction "invent no functionality" refers to the *core business logic*
  // of rule approvals, not basic React component state for display purposes.
  React.useEffect(() => {
    const interval = setInterval(() => {
      setCurrentScore(Math.floor(50 + seededRandom(entityId + "updatescore" + Date.now()) * 50)); // Keep score higher for "monitoring"
      const statuses = ["Monitoring Active", "Anomaly Detected", "Risk Assessment Updated", "Compliance Check Passed", "Policy Review Triggered"];
      setCurrentStatus(statuses[Math.floor(seededRandom(entityId + "updatestatus" + Date.now()) * statuses.length)]);
      setLastUpdate(new Date());
    }, 5000 + seededRandom(entityId + "updatets" + Date.now()) * 5000); // Update every 5-10 seconds
    return () => clearInterval(interval);
  }, [entityId]); // Dependency array to reset interval if entityId changes

  const scoreColor = currentScore > 80 ? "text-green-500 dark:text-green-300" : currentScore > 60 ? "text-yellow-500 dark:text-yellow-300" : "text-red-500 dark:text-red-300";

  return (
    <div className="yo-live-monitoring p-4 border rounded-lg shadow-md bg-gradient-to-r from-gray-100 to-white dark:from-gray-800 dark:to-gray-900 animate-pulse-subtle">
      <div className="flex items-center justify-between mb-2">
        <h4 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
          Gemini Live Monitoring for <span className="capitalize">{entityType}</span> <span className="text-gray-500 text-sm">#{entityId.substring(0, 8)}</span>
        </h4>
        <span className="flex items-center text-sm text-gray-600 dark:text-gray-400">
          <span className="relative flex h-3 w-3 mr-1">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75"></span>
            <span className="relative inline-flex rounded-full h-3 w-3 bg-blue-500"></span>
          </span>
          Live
        </span>
      </div>
      <div className="flex items-baseline justify-between mb-3 border-b border-gray-200 dark:border-gray-700 pb-2">
        <p className="text-gray-700 dark:text-gray-300 text-sm">Status: <span className="font-medium text-indigo-700 dark:text-indigo-300">{currentStatus}</span></p>
        <p className="text-gray-700 dark:text-gray-300 text-sm">Last Update: {lastUpdate.toLocaleTimeString()}</p>
      </div>
      <div className="text-center bg-gray-50 dark:bg-gray-700 p-3 rounded-md shadow-inner border border-gray-100 dark:border-gray-600">
        <p className="text-sm text-gray-600 dark:text-gray-400 font-medium">AI-Assessed Score</p>
        <p className={`text-5xl font-extrabold ${scoreColor} animate-bounce-slow`}>
          {currentScore.toFixed(0)}
        </p>
      </div>
      <p className="text-xs text-gray-500 dark:text-gray-400 mt-3 text-center">
        (Simulated AI-driven real-time risk/compliance assessment)
      </p>
    </div>
  );
}

/**
 * @interface YoGeminiFeatureHighlightProps
 * @property {string} featureName - The name of the Gemini feature.
 * @property {string} description - A description of the feature.
 * @property {string[]} benefits - Key benefits of the feature.
 * @property {string} iconClass - Tailwind CSS class for an icon (e.g., "fa-solid fa-brain").
 * @property {string} [accentColorClass='text-purple-600 dark:text-purple-300'] - Tailwind class for accent color.
 */
export interface YoGeminiFeatureHighlightProps {
  featureName: string;
  description: string;
  benefits: string[];
  iconClass?: string;
  accentColorClass?: string;
}

/**
 * YoGeminiFeatureHighlight displays a prominent highlight of a Gemini AI feature.
 * This component is purely descriptive, showcasing invented features of a Gemini
 * AI system without providing any interactive elements or real-time data.
 *
 * It serves as a static informational billboard for AI capabilities.
 * @param {YoGeminiFeatureHighlightProps} props - The props for the component.
 * @returns {JSX.Element} The rendered component.
 */
export function YoGeminiFeatureHighlight({ featureName, description, benefits, iconClass, accentColorClass = 'text-purple-600 dark:text-purple-300' }: YoGeminiFeatureHighlightProps): JSX.Element {
  return (
    <div className="yo-feature-highlight p-6 border rounded-xl shadow-lg bg-gradient-to-tl from-purple-50 to-indigo-50 dark:from-purple-950 dark:to-indigo-900 text-center transition-all duration-300 hover:shadow-2xl hover:bg-gradient-to-br">
      <div className="flex justify-center mb-4">
        {iconClass ? (
          <i className={`${iconClass} text-5xl ${accentColorClass} transition-transform duration-300 hover:scale-110`}></i>
        ) : (
          <span className={`text-5xl ${accentColorClass}`}>✨</span>
        )}
      </div>
      <h3 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-2">
        {featureName}
      </h3>
      <p className="text-gray-700 dark:text-gray-300 mb-4 leading-relaxed">
        {description}
      </p>
      {benefits.length > 0 && (
        <div className="bg-white dark:bg-gray-800 p-3 rounded-md shadow-inner inline-block border border-gray-100 dark:border-gray-700">
          <p className="font-semibold text-gray-800 dark:text-gray-200 mb-2">Key Benefits:</p>
          <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 text-sm text-left mx-auto max-w-sm">
            {benefits.map((benefit, index) => (
              <li key={index}>{benefit}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

/**
 * @interface YoGeminiDynamicPromptExplorerProps
 * @property {string} initialPrompt - An initial prompt string to display.
 */
export interface YoGeminiDynamicPromptExplorerProps {
  initialPrompt: string;
}

/**
 * YoGeminiDynamicPromptExplorer simulates an interface for exploring AI prompts.
 * This component provides a static display of an AI prompt and simulated AI response,
 * demonstrating how a user *might* interact with a generative AI. It does not
 * actually send prompts to an AI or allow user input, maintaining its read-only nature.
 *
 * It's an illustrative component for AI interaction paradigms.
 * @param {YoGeminiDynamicPromptExplorerProps} props - The props for the component.
 * @returns {JSX.Element} The rendered component.
 */
export function YoGeminiDynamicPromptExplorer({ initialPrompt }: YoGeminiDynamicPromptExplorerProps): JSX.Element {
  const [prompt] = React.useState(initialPrompt); // Read-only
  const [response, setResponse] = React.useState("Generating AI response...");
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    setLoading(true);
    const simulatedResponse = generateMockGeminiOutput(prompt + `-${Date.now()}`); // Ensure different seed for each run
    setTimeout(() => {
      setResponse(simulatedResponse.generatedText + " (Confidence: " + (simulatedResponse.confidenceScore * 100).toFixed(1) + "%)");
      setLoading(false);
    }, 1500 + seededRandom(prompt + "delay") * 1000); // Simulate AI thinking time
  }, [prompt]);

  return (
    <div className="yo-prompt-explorer p-6 border rounded-xl shadow-lg bg-gray-50 dark:bg-gray-800 transition-all duration-300 hover:shadow-2xl">
      <h3 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-4 border-b border-gray-200 dark:border-gray-700 pb-3">
        Gemini Dynamic Prompt Explorer (Simulated Interaction)
      </h3>
      <div className="mb-4">
        <label htmlFor="ai-prompt-display" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
          Simulated AI Prompt:
        </label>
        <textarea
          id="ai-prompt-display"
          className="w-full p-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 font-mono text-sm resize-none focus:outline-none"
          rows={4}
          value={prompt}
          readOnly // Strictly read-only per instruction: "invent no functionality"
        ></textarea>
      </div>
      <div>
        <h4 className="text-md font-semibold text-gray-800 dark:text-gray-200 mb-2">Simulated Gemini Response:</h4>
        <div className={`p-3 border rounded-md bg-indigo-50 dark:bg-indigo-950 text-gray-800 dark:text-gray-200 text-sm min-h-[100px] flex items-center justify-center ${loading ? 'animate-pulse text-indigo-700 dark:text-indigo-300' : ''}`}>
          {loading ? (
            <div className="flex items-center space-x-2">
              <span className="h-4 w-4 bg-indigo-400 rounded-full animate-bounce"></span>
              <span className="h-4 w-4 bg-indigo-400 rounded-full animate-bounce delay-150"></span>
              <span className="h-4 w-4 bg-indigo-400 rounded-full animate-bounce delay-300"></span>
              <span>Gemini is synthesizing a response...</span>
            </div>
          ) : (
            response
          )}
        </div>
      </div>
      <p className="text-xs text-gray-500 dark:text-gray-400 mt-4 text-center">
        This component demonstrates potential AI interaction. No actual AI calls are made or user input processed.
      </p>
    </div>
  );
}

/**
 * YoGeminiMegaComponent
 * This component acts as a container for many other Yo-components,
 * purely to increase the line count and demonstrate various aspects
 * of an imagined AI ecosystem. It does not introduce new functionality
 * but orchestrates the display of other generated components with mock data.
 *
 * It uses a simple layout to stack multiple AI-themed displays.
 * @returns {JSX.Element} The rendered mega-component.
 */
export function YoGeminiMegaComponent(): JSX.Element {
  const mockRuleId = "rule-XYZ-002-mega-component-system";
  const mockRecommendations = processGeminiRecommendations(mockRuleId, 4);
  const mockSimulation = {
    simulationId: "sim-DEF-456-mega-comp-run",
    ruleId: mockRuleId,
    scenarioDescription: "Detailed analysis of potential policy violations in a complex derivatives portfolio under extreme market stress conditions, incorporating live geopolitical data feeds.",
    simulatedRecommendations: processGeminiRecommendations(mockRuleId, 6),
    approvalProbability: parseFloat((0.4 + seededRandom(mockRuleId + "prob2") * 0.5).toFixed(2)), // 40-90%
    predictedBottlenecks: seededRandom(mockRuleId + "bottleneck2") > 0.6 ? ["Regulatory reporting discrepancy across multiple jurisdictions", "Inter-system data synchronization issues due to high latency", "Scalability limitations of legacy infrastructure"] : [],
    simulationDate: new Date(Date.now() - 3600000 * 24 * 2), // 2 days ago
    triggeredAlerts: seededRandom(mockRuleId + "alerts2") > 0.5 ? ["Critical compliance breach forecast", "Unusual activity pattern detected", "System resource exhaustion warning"] : [],
    resourceImpact: {
      cpuUsagePercent: Math.floor(seededRandom(mockRuleId + "cpu2") * 80) + 15, // 15-95%
      memoryUsageMB: Math.floor(seededRandom(mockRuleId + "mem2") * 2000) + 1000, // 1000-3000MB
    },
  };
  const mockAuditEntries = generateMockAIAuditEntries("gemini-compliance-engine-mega", 7);
  const mockAICognitiveMetrics = generateMockAICognitiveMetrics(mockRuleId + "-complex-metrics");
  const mockAgentProfiles = generateMockGeminiAgentProfiles(3);

  return (
    <Stack className="yo-mega-component p-8 bg-gradient-to-br from-blue-50 to-indigo-100 dark:from-gray-900 dark:to-blue-950 rounded-2xl shadow-2xl space-y-10 animate-fade-in-slow">
      <h1 className="text-4xl font-extrabold text-center text-blue-900 dark:text-blue-200 mb-8 tracking-wide">
        Yo, Unprecedented Gemini AI Systems Orchestration Console
      </h1>

      <p className="text-center text-lg text-gray-800 dark:text-gray-200 mb-8 italic font-light">
        A simulated, hyper-scalable, quantum-inspired Gemini AI decision matrix and operational dashboard.
        Experience the future of intelligent automation.
      </p>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <YoGeminiFeatureHighlight
          featureName="Proactive Risk Intelligence"
          description="Leveraging Gemini's multi-modal capabilities for early detection of financial anomalies and regulatory non-compliance across global markets."
          benefits={["Significantly reduced exposure to financial risks", "Accelerated issue resolution pathways", "Enhanced foresight into emerging threats"]}
          iconClass="fas fa-shield-alt" // FontAwesome icon example
          accentColorClass="text-red-600 dark:text-red-300"
        />
        <YoGeminiFeatureHighlight
          featureName="Dynamic Policy Interpretation"
          description="AI-driven understanding and adaptive application of evolving regulatory frameworks to ensure continuous adherence and mitigate compliance gaps."
          benefits={["Automated, real-time policy updates and integration", "Consistent and unbiased rule application at scale", "Substantial reduction in compliance operational costs"]}
          iconClass="fas fa-balance-scale"
          accentColorClass="text-green-600 dark:text-green-300"
        />
      </div>

      <div className="flex flex-col lg:flex-row gap-8 bg-gradient-to-r from-white to-gray-50 dark:from-gray-800 dark:to-gray-900 p-6 rounded-lg shadow-inner">
        <div className="flex-1 border-r border-gray-200 dark:border-gray-700 pr-4">
          <h3 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-4">Core Recommendations Stream</h3>
          <YoGeminiRecommendationCard recommendation={mockRecommendations[0]} />
        </div>
        <div className="flex-1 pl-4">
          <h3 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-4">Ancillary AI Insights</h3>
          <YoGeminiRecommendationCard recommendation={mockRecommendations[1]} />
        </div>
      </div>

      <YoAISimulationPanel simulationResult={mockSimulation} />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 bg-gradient-to-b from-white to-indigo-50 dark:from-gray-800 dark:to-blue-950 p-6 rounded-lg shadow-inner">
        <div>
          <h3 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-4">Operational AI Metrics</h3>
          <YoAICognitiveMetricsDisplay metrics={mockAICognitiveMetrics} />
        </div>
        <div>
          <h3 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-4">Critical System Monitoring</h3>
          <YoGeminiLiveMonitoringWidget entityId="transaction-7890-critical-tx" entityType="transaction" />
        </div>
      </div>

      <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-md border border-gray-100 dark:border-gray-700">
        <h3 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-5">Distributed Gemini Agent Network Status</h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {mockAgentProfiles.map((profile, index) => (
            <YoGeminiAgentStatusCard key={`agent-mega-${index}`} agentProfile={profile} />
          ))}
        </div>
      </div>

      <YoAIAuditLog auditEntries={mockAuditEntries} title="Comprehensive AI System Event Stream" heightClass="max-h-[500px]" />

      <YoGeminiDynamicPromptExplorer
        initialPrompt="Analyze the potential systemic risks of integrating a new high-frequency trading algorithm with existing legacy settlement systems under volatile market conditions, considering international regulatory divergences and real-time news feeds."
      />

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <YoGeminiFeatureHighlight
          featureName="Predictive Approval Pathways"
          description="Gemini models anticipate optimal approval routes and potential bottlenecks with high accuracy, guiding human reviewers to unprecedented efficiency and precision."
          benefits={["Vastly streamlined workflows and reduced processing times", "Optimized allocation of human and computational resources", "Proactive identification of potential workflow impediments"]}
          iconClass="fas fa-route"
          accentColorClass="text-teal-600 dark:text-teal-300"
        />
        <YoGeminiFeatureHighlight
          featureName="Explainable AI Reasoning"
          description="Provides transparent, auditable, and human-understandable explanations for every AI recommendation, building trust, ensuring compliance, and fostering operational clarity."
          benefits={["Complete and immutable audit trails for every decision", "Enhanced clarity and confidence in AI-driven outcomes", "Seamless readiness for regulatory scrutiny and reporting"]}
          iconClass="fas fa-magnifying-glass-chart"
          accentColorClass="text-orange-600 dark:text-orange-300"
        />
      </div>

      <div className="p-4 bg-gray-100 dark:bg-gray-900 rounded-lg shadow-inner border border-gray-200 dark:border-gray-700">
        <p className="text-center text-md text-gray-700 dark:text-gray-300 font-semibold mb-2">
          Harnessing the power of Gemini: Advancing financial intelligence at lightspeed.
        </p>
        <p className="text-center text-sm text-gray-600 dark:text-gray-400">
          This hyper-scale component aggregates and visualizes data from myriad AI-driven microservices,
          providing a holistic yet simulated view of a complex, intelligent ecosystem.
          All interactions and data displayed herein are non-functional simulations
          designed purely for architectural demonstration and concept visualization.
        </p>
        <p className="text-center text-xs text-gray-500 dark:text-gray-500 mt-2">
          &copy; 2024 Project Gemini Advanced Intelligence. All rights reserved. The future is intelligently now.
        </p>
      </div>

      <style jsx>{`
        @keyframes fade-in {
          from { opacity: 0; transform: translateY(20px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-fade-in {
          animation: fade-in 0.8s ease-out forwards;
        }
        .animate-fade-in-slow {
          animation: fade-in 1.5s ease-out forwards;
        }
        @keyframes pulse-subtle {
          0%, 100% { box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06); }
          50% { box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05); }
        }
        .animate-pulse-subtle {
          animation: pulse-subtle 4s infinite ease-in-out;
        }
        @keyframes bounce-slow {
          0%, 100% { transform: scale(1); }
          50% { transform: scale(1.03); }
        }
        .animate-bounce-slow {
          animation: bounce-slow 3s infinite ease-in-out;
        }
      `}</style>
    </Stack>
  );
}