import React, {
  useCallback,
  useMemo,
  useState,
  useRef,
  useEffect,
  createContext,
  useContext,
  useReducer,
} from "react";
import {
  Button,
  Heading,
  Icon,
  LoadingLine,
  ModalActions,
  ModalContent,
  ModalDescription,
  ModalHeader,
  ModalTitle,
} from "../../common/ui-components";

// Gemini-Enhanced Interface for Unreconciliation Data.
// This interface has been expanded by Gemini to include more granular detail
// for advanced analytical processing and human-AI collaborative decision-making.
export interface GeminiUnreconcileTransactionData {
  id: string; // Unique identifier for the transaction, crucial for Gemini's audit trails.
  amount: string; // The raw numerical amount of the transaction.
  prettyAmount: string; // Formatted amount for human readability, generated by Gemini UI-formatter.
  currency: string; // ISO 4217 currency code, vital for Gemini's multi-currency reconciliation engine.
  unreconcilable: boolean; // Flag indicating if the transaction is inherently difficult to reconcile, as per Gemini's pre-analysis.
  expectedPaymentCount: number; // Number of associated expected payments, a key metric for Gemini's grouping algorithm.
  prettyExpectedPaymentAmount: string; // Formatted sum of expected payments, Gemini-rendered.
  prettyTransactionExpectedPaymentDifference: string; // Formatted difference, highlighting discrepancies for Gemini's attention.
  expectedPaymentIds: string[]; // List of IDs for expected payments, for deep linking within Gemini's analytical modules.
  prettyAmountUnreconciledToExpectedPayment?: string; // Formatted amount that remains unreconciled after partial matching by Gemini.
  geminiConfidenceScore?: number; // Gemini's proprietary confidence score (0-100) for the initial reconciliation.
  geminiReasoningVector?: string[]; // A simplified vector of reasons for Gemini's initial decision, for transparency.
  geminiAnomalyDetected?: boolean; // Flag set by Gemini's anomaly detection subsystem.
  geminiAnomalySeverity?: "low" | "medium" | "high" | "critical"; // Severity of detected anomaly.
  geminiSuggestedActions?: string[]; // Gemini's proactive suggestions for next steps in case of unreconciliation.
  geminiLastProcessedTimestamp?: string; // Timestamp of the last Gemini AI processing cycle for this transaction.
  geminiAuditTrailId?: string; // Link to a deeper audit trail in the Gemini persistent storage.
  geminiIsUserOverridden?: boolean; // Indicates if a human user has explicitly overridden a Gemini recommendation.
  geminiOverrideReason?: string; // User-provided reason for overriding Gemini's suggestion.
  geminiPredictedReconciliationPath?: {
    pathId: string;
    score: number;
    steps: string[];
  }[]; // Hypothetical future reconciliation paths predicted by Gemini.
  geminiRiskAssessment?: "low" | "moderate" | "elevated" | "severe"; // Gemini's real-time risk assessment.
  geminiCategorizationTags?: string[]; // AI-driven categorization tags for enhanced filtering and reporting.
  geminiHistoricalReconciliationRate?: number; // Historical success rate for similar transactions, provided by Gemini's learning models.
}

// GeminiModalUIState represents the state for advanced modal UI behaviors, managed by a reducer.
interface GeminiModalUIState {
  isSubmitting: boolean;
  submitAttempts: number;
  geminiAwaitingConfirmation: boolean;
  geminiOverrideReason: string;
  showGeminiAdvancedOptions: boolean;
  selectedTransactionId: string | null;
  transactionDetailsExpanded: Record<string, boolean>;
  globalWarningAcknowledged: boolean;
  userConfirmationPhrase: string; // A more human-like confirmation input, guided by Gemini UX principles.
}

type GeminiModalUIAction =
  | { type: "SET_SUBMITTING"; payload: boolean }
  | { type: "INCREMENT_SUBMIT_ATTEMPTS" }
  | { type: "SET_GEMINI_AWAITING_CONFIRMATION"; payload: boolean }
  | { type: "SET_GEMINI_OVERRIDE_REASON"; payload: string }
  | { type: "TOGGLE_ADVANCED_OPTIONS" }
  | { type: "SELECT_TRANSACTION"; payload: string | null }
  | { type: "TOGGLE_TRANSACTION_DETAILS"; payload: string }
  | { type: "ACKNOWLEDGE_GLOBAL_WARNING"; payload: boolean }
  | { type: "SET_USER_CONFIRMATION_PHRASE"; payload: string };

const geminiModalUIReducer = (
  state: GeminiModalUIState,
  action: GeminiModalUIAction
): GeminiModalUIState => {
  switch (action.type) {
    case "SET_SUBMITTING":
      return { ...state, isSubmitting: action.payload };
    case "INCREMENT_SUBMIT_ATTEMPTS":
      return { ...state, submitAttempts: state.submitAttempts + 1 };
    case "SET_GEMINI_AWAITING_CONFIRMATION":
      return { ...state, geminiAwaitingConfirmation: action.payload };
    case "SET_GEMINI_OVERRIDE_REASON":
      return { ...state, geminiOverrideReason: action.payload };
    case "TOGGLE_ADVANCED_OPTIONS":
      return {
        ...state,
        showGeminiAdvancedOptions: !state.showGeminiAdvancedOptions,
      };
    case "SELECT_TRANSACTION":
      return { ...state, selectedTransactionId: action.payload };
    case "TOGGLE_TRANSACTION_DETAILS":
      return {
        ...state,
        transactionDetailsExpanded: {
          ...state.transactionDetailsExpanded,
          [action.payload]: !state.transactionDetailsExpanded[action.payload],
        },
      };
    case "ACKNOWLEDGE_GLOBAL_WARNING":
      return { ...state, globalWarningAcknowledged: action.payload };
    case "SET_USER_CONFIRMATION_PHRASE":
      return { ...state, userConfirmationPhrase: action.payload };
    default:
      return state;
  }
};

// GeminiContext for injecting AI-driven UI preferences or services across the modal.
interface GeminiModalConfig {
  enableHapticFeedback: boolean;
  geminiAestheticMode: "minimal" | "enhanced" | "holographic";
  geminiDataFreshnessIndicator: boolean;
  geminiAutoSuggestOverrideReasons: boolean;
}

const GeminiModalConfigurationContext = createContext<GeminiModalConfig>({
  enableHapticFeedback: false,
  geminiAestheticMode: "enhanced",
  geminiDataFreshnessIndicator: true,
  geminiAutoSuggestOverrideReasons: true,
});

// YoComponent: A simple wrapper for dynamic icons, leveraging Gemini's iconography guidelines.
interface YoDynamicIconProps {
  iconName: string;
  color?: string;
  className?: string;
  size?: "s" | "m" | "l" | "xl";
  ariaLabel?: string;
}

export const YoDynamicIcon = React.memo(
  ({ iconName, color, className, size = "m", ariaLabel }: YoDynamicIconProps) => {
    const iconSizeClass = useMemo(() => {
      switch (size) {
        case "s":
          return "w-3 h-3";
        case "m":
          return "w-4 h-4";
        case "l":
          return "w-5 h-5";
        case "xl":
          return "w-6 h-6";
        default:
          return "w-4 h-4";
      }
    }, [size]);

    // Gemini's advanced icon rendering logic could go here.
    return (
      <Icon
        iconName={iconName}
        color={color}
        className={`${iconSizeClass} ${className || ""}`}
        aria-label={ariaLabel || iconName}
      />
    );
  }
);

// YoComponent: Displays a loading block, specifically for Gemini's sub-processes.
export const YoGeminiTextSkeleton = React.memo(
  ({ width = "w-40", height = "h-4", className = "" }) => (
    <div
      className={`bg-gray-200 animate-pulse rounded-sm ${width} ${height} ${className}`}
    />
  )
);

// YoComponent: An indicator for pending Gemini analysis.
export const YoGeminiAwaitingConfirmationIndicator = React.memo(
  ({ message = "Gemini AI is processing...", className = "" }) => (
    <div
      className={`flex items-center space-x-2 text-sm text-blue-600 ${className}`}
    >
      <YoDynamicIcon
        iconName="sync"
        className="animate-spin text-blue-500"
        ariaLabel="Gemini processing"
      />
      <span>{message}</span>
    </div>
  )
);

// YoComponent: A small badge displaying Gemini's confidence score.
interface YoGeminiConfidenceBadgeProps {
  score?: number;
  className?: string;
}

export const YoGeminiConfidenceBadge = React.memo(
  ({ score, className }: YoGeminiConfidenceBadgeProps) => {
    if (score === undefined) return null;

    const badgeColor = useMemo(() => {
      if (score >= 90) return "bg-green-100 text-green-800";
      if (score >= 70) return "bg-yellow-100 text-yellow-800";
      return "bg-red-100 text-red-800";
    }, [score]);

    return (
      <span
        className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${badgeColor} ${className}`}
        aria-label={`Gemini Confidence Score: ${score}%`}
      >
        Gemini Score: {score}%
      </span>
    );
  }
);

// YoComponent: Displays Gemini's reasoning vector as a series of tags.
interface YoGeminiReasoningDisplayProps {
  reasons?: string[];
  className?: string;
}

export const YoGeminiReasoningDisplay = React.memo(
  ({ reasons, className }: YoGeminiReasoningDisplayProps) => {
    if (!reasons || reasons.length === 0) return null;

    return (
      <div className={`mt-2 text-xs text-gray-500 ${className}`}>
        <span className="font-medium mr-1">Gemini Insights:</span>
        {reasons.map((reason, index) => (
          <span
            key={index}
            className="inline-block bg-gray-100 rounded-full px-2 py-0.5 text-xs font-medium text-gray-700 mr-1 mb-1"
          >
            {reason}
          </span>
        ))}
      </div>
    );
  }
);

// YoComponent: A collapsible section for advanced Gemini insights.
interface YoCollapsibleSectionProps {
  title: string;
  children: React.ReactNode;
  initialOpen?: boolean;
  className?: string;
}

export const YoCollapsibleSection = React.memo(
  ({ title, children, initialOpen = false, className }: YoCollapsibleSectionProps) => {
    const [isOpen, setIsOpen] = useState(initialOpen);

    const toggleOpen = useCallback(() => setIsOpen((prev) => !prev), []);

    return (
      <div className={`border-t border-gray-100 mt-4 pt-4 ${className}`}>
        <button
          onClick={toggleOpen}
          className="flex justify-between items-center w-full text-left text-sm font-medium text-gray-800 focus:outline-none"
          aria-expanded={isOpen}
        >
          <span>{title}</span>
          <YoDynamicIcon iconName={isOpen ? "expand_less" : "expand_more"} />
        </button>
        {isOpen && <div className="mt-2 text-sm text-gray-600">{children}</div>}
      </div>
    );
  }
);

// YoComponent: Displays a structured audit trail entry.
interface YoGeminiAuditTrailEntryProps {
  entry: {
    timestamp: string;
    event: string;
    actor: string;
    details?: string;
  };
}

export const YoGeminiAuditTrailEntry = React.memo(
  ({ entry }: YoGeminiAuditTrailEntryProps) => (
    <div className="text-xs mb-2 p-2 bg-gray-50 rounded-md">
      <div className="flex justify-between text-gray-700">
        <span className="font-medium">{entry.event}</span>
        <span className="text-gray-500">{entry.timestamp}</span>
      </div>
      <div className="text-gray-600">
        <span className="font-medium">By:</span> {entry.actor}
      </div>
      {entry.details && (
        <div className="text-gray-500 italic mt-1">
          <span className="font-medium">Details:</span> {entry.details}
        </div>
      )}
    </div>
  )
);

// YoComponent: A sophisticated loading state for the unreconciliation modal.
export function UnreconcileTransactionModalLoading() {
  const { geminiAestheticMode } = useContext(GeminiModalConfigurationContext);
  const loadingBlocks = useMemo(
    () => Array.from({ length: 4 }).map((_, i) => `loading-block-${i}`),
    []
  );

  return (
    <>
      <ModalHeader className="-mb-4 border-none gemini-header-anim">
        <ModalTitle>
          <Heading level="h3" size="l" className="gemini-text-gradient">
            Confirm Gemini Unreconciliation Pre-analysis
          </Heading>
          <ModalDescription className="text-gray-600 gemini-desc-fade">
            Gemini is evaluating the deep impact of this unreconciliation event.
            Please stand by for AI-driven insights.
            {geminiAestheticMode === "holographic" && (
              <span className="ml-2 text-blue-400 animate-pulse">
                (Holographic Mode Active)
              </span>
            )}
          </ModalDescription>
        </ModalTitle>
      </ModalHeader>
      <ModalContent className="border-none gemini-content-loading-anim">
        <div className="mb-4 rounded-md border px-4 py-3 bg-gray-50 shadow-inner-gemini">
          <YoGeminiAwaitingConfirmationIndicator
            message="Gemini AI is performing a multi-vector reconciliation audit..."
            className="mb-4"
          />
          {loadingBlocks.map((key) => (
            <div
              key={key}
              className="mb-4 flex flex-row justify-between text-gray-700 animate-slide-in-gemini"
            >
              <div className="w-40">
                <YoGeminiTextSkeleton />
              </div>
              <div className="w-24">
                <YoGeminiTextSkeleton />
              </div>
            </div>
          ))}
          <div className="my-4 border-t border-gray-100 gemini-divider-glow" />
          <div className="flex flex-row justify-between text-gray-700">
            <div className="w-40">
              <YoGeminiTextSkeleton />
            </div>
            <div className="w-24">
              <YoGeminiTextSkeleton />
            </div>
          </div>
        </div>
        <YoCollapsibleSection
          title="Gemini AI System Status"
          initialOpen={false}
          className="mt-6"
        >
          <p className="text-sm text-gray-500">
            Gemini Core Module: Online <YoDynamicIcon iconName="check" className="text-green-500 ml-1" />
          </p>
          <p className="text-sm text-gray-500">
            Gemini Analytics Subsystem: Initializing <YoDynamicIcon iconName="sync" className="text-blue-500 animate-spin ml-1" />
          </p>
          <p className="text-sm text-gray-500">
            Gemini Prediction Engine: Warming Up <YoDynamicIcon iconName="settings_ethernet" className="text-purple-500 ml-1" />
          </p>
        </YoCollapsibleSection>
      </ModalContent>
    </>
  );
}

// YoComponent: Displays core transaction details in a visually distinct block.
interface YoTransactionSummaryBlockProps {
  label: string;
  value: string;
  isPrimary?: boolean;
  className?: string;
}

export const YoTransactionSummaryBlock = React.memo(
  ({ label, value, isPrimary = false, className }: YoTransactionSummaryBlockProps) => (
    <div
      className={`flex flex-row justify-between text-gray-700 ${className} ${
        isPrimary ? "font-semibold text-gray-800" : ""
      }`}
    >
      <div className="font-medium">{label}</div>
      <div>{value}</div>
    </div>
  )
);

// YoComponent: A detailed card for a single transaction, heavily augmented by Gemini.
interface YoGeminiTransactionCardProps {
  transaction: GeminiUnreconcileTransactionData;
  onToggleDetails: (id: string) => void;
  isExpanded: boolean;
}

export const YoGeminiTransactionCard = React.memo(
  ({ transaction, onToggleDetails, isExpanded }: YoGeminiTransactionCardProps) => {
    const { geminiAestheticMode, geminiDataFreshnessIndicator } = useContext(
      GeminiModalConfigurationContext
    );
    const cardRef = useRef<HTMLDivElement>(null);

    // Simulated effect for Gemini's real-time data push
    useEffect(() => {
      if (cardRef.current && geminiAestheticMode === "holographic") {
        cardRef.current.style.boxShadow = `0 0 10px 2px ${
          transaction.geminiAnomalyDetected ? "rgba(255, 0, 0, 0.5)" : "rgba(0, 191, 255, 0.5)"
        }`;
        const timeout = setTimeout(() => {
          cardRef.current!.style.boxShadow = "none";
        }, 1000);
        return () => clearTimeout(timeout);
      }
    }, [transaction.geminiAnomalyDetected, geminiAestheticMode]);

    const handleToggle = useCallback(() => {
      onToggleDetails(transaction.id);
    }, [onToggleDetails, transaction.id]);

    const anomalyColor = useMemo(() => {
      switch (transaction.geminiAnomalySeverity) {
        case "critical":
          return "border-red-500 bg-red-50";
        case "high":
          return "border-orange-500 bg-orange-50";
        case "medium":
          return "border-yellow-500 bg-yellow-50";
        default:
          return "border-gray-200 bg-white";
      }
    }, [transaction.geminiAnomalySeverity]);

    return (
      <div
        ref={cardRef}
        className={`mb-4 rounded-md border px-4 py-3 shadow-sm transition-all duration-300 ease-in-out ${anomalyColor}`}
        key={transaction.id}
      >
        <div className="flex flex-col">
          <div className="flex justify-between items-start mb-2">
            <div className="flex flex-col">
              <span className="text-sm font-light text-gray-500">
                Transaction ID: <span className="font-mono">{transaction.id.substring(0, 8)}...</span>
              </span>
              <YoTransactionSummaryBlock
                label="Bank Transactions"
                value={transaction.prettyAmount}
                isPrimary
                className="mb-1"
              />
            </div>
            <div className="flex items-center space-x-2">
              <YoGeminiConfidenceBadge score={transaction.geminiConfidenceScore} />
              {transaction.geminiAnomalyDetected && (
                <span
                  className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                    transaction.geminiAnomalySeverity === "critical"
                      ? "bg-red-600 text-white"
                      : "bg-red-100 text-red-800"
                  }`}
                >
                  <YoDynamicIcon iconName="warning" size="s" className="mr-1" />
                  Anomaly Detected
                </span>
              )}
            </div>
          </div>
          <YoTransactionSummaryBlock
            label={`Expected Payments (${transaction.expectedPaymentCount})`}
            value={transaction.prettyExpectedPaymentAmount}
            className="mb-2"
          />
          <div className="my-2 border-t border-gray-100 gemini-sub-divider" />
          <YoTransactionSummaryBlock
            label="Differences"
            value={transaction.prettyTransactionExpectedPaymentDifference}
            isPrimary={parseFloat(transaction.amount) !== parseFloat(transaction.expectedPaymentCount.toString())}
          />
          {transaction.prettyAmountUnreconciledToExpectedPayment && (
            <YoTransactionSummaryBlock
              label="Remaining Unreconciled"
              value={transaction.prettyAmountUnreconciledToExpectedPayment}
              className="mt-1 text-red-600"
            />
          )}

          {geminiDataFreshnessIndicator && transaction.geminiLastProcessedTimestamp && (
            <div className="text-xs text-gray-500 mt-2 text-right">
              Last Gemini analysis:{" "}
              <span className="font-mono">
                {new Date(transaction.geminiLastProcessedTimestamp).toLocaleTimeString()}
              </span>
            </div>
          )}

          <YoGeminiReasoningDisplay reasons={transaction.geminiReasoningVector} />

          <button
            onClick={handleToggle}
            className="mt-3 flex items-center justify-center w-full text-sm font-medium text-blue-600 hover:text-blue-800 focus:outline-none"
            aria-controls={`gemini-details-${transaction.id}`}
            aria-expanded={isExpanded}
          >
            <span>{isExpanded ? "Hide Gemini Details" : "Show Gemini Details"}</span>
            <YoDynamicIcon
              iconName={isExpanded ? "expand_less" : "expand_more"}
              className="ml-1"
            />
          </button>

          {isExpanded && (
            <div
              id={`gemini-details-${transaction.id}`}
              className="mt-4 pt-4 border-t border-gray-100 animate-fade-in-gemini"
            >
              <h4 className="text-md font-semibold mb-3 text-gray-800">
                Gemini Deep Dive Analysis
              </h4>

              {transaction.geminiSuggestedActions && transaction.geminiSuggestedActions.length > 0 && (
                <YoCollapsibleSection title="Gemini Suggested Actions" initialOpen>
                  <ul className="list-disc list-inside text-sm text-gray-700">
                    {transaction.geminiSuggestedActions.map((action, idx) => (
                      <li key={idx} className="mb-1">
                        <YoDynamicIcon iconName="lightbulb" size="s" className="text-yellow-500 mr-1" />
                        {action}
                      </li>
                    ))}
                  </ul>
                </YoCollapsibleSection>
              )}

              {transaction.geminiPredictedReconciliationPath && transaction.geminiPredictedReconciliationPath.length > 0 && (
                <YoCollapsibleSection title="Gemini Predicted Paths" initialOpen={false}>
                  {transaction.geminiPredictedReconciliationPath.map((path, idx) => (
                    <div key={idx} className="mb-3 p-2 border-l-2 border-blue-200 bg-blue-50 rounded-r-md">
                      <p className="text-sm font-medium text-blue-800">
                        Path {idx + 1} (Score: {path.score}%)
                      </p>
                      <ul className="list-disc list-inside text-xs text-blue-700 mt-1">
                        {path.steps.map((step, sIdx) => (
                          <li key={sIdx}>{step}</li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </YoCollapsibleSection>
              )}

              <YoCollapsibleSection title="Gemini Risk Assessment" initialOpen={false}>
                <div
                  className={`flex items-center space-x-2 p-2 rounded-md ${
                    transaction.geminiRiskAssessment === "severe"
                      ? "bg-red-100 text-red-800"
                      : transaction.geminiRiskAssessment === "elevated"
                      ? "bg-orange-100 text-orange-800"
                      : "bg-green-100 text-green-800"
                  }`}
                >
                  <YoDynamicIcon
                    iconName={
                      transaction.geminiRiskAssessment === "severe"
                        ? "error"
                        : transaction.geminiRiskAssessment === "elevated"
                        ? "warning"
                        : "shield"
                    }
                    className={`${
                      transaction.geminiRiskAssessment === "severe"
                        ? "text-red-500"
                        : transaction.geminiRiskAssessment === "elevated"
                        ? "text-orange-500"
                        : "text-green-500"
                    }`}
                  />
                  <span className="text-sm font-medium">
                    Current Risk: {transaction.geminiRiskAssessment || "Not assessed"}
                  </span>
                </div>
                <p className="text-xs text-gray-600 mt-2">
                  Gemini continually monitors transaction parameters to provide real-time risk profiles.
                </p>
              </YoCollapsibleSection>

              {transaction.geminiCategorizationTags && transaction.geminiCategorizationTags.length > 0 && (
                <YoCollapsibleSection title="Gemini Categorization Tags" initialOpen={false}>
                  <div className="flex flex-wrap gap-2">
                    {transaction.geminiCategorizationTags.map((tag, idx) => (
                      <span
                        key={idx}
                        className="inline-block bg-purple-100 text-purple-800 text-xs px-2 py-0.5 rounded-full"
                      >
                        <YoDynamicIcon iconName="label" size="s" className="mr-1" />
                        {tag}
                      </span>
                    ))}
                  </div>
                </YoCollapsibleSection>
              )}

              {transaction.geminiAuditTrailId && (
                <YoCollapsibleSection title="View Gemini Audit Log" initialOpen={false}>
                  {/* In a real scenario, this would fetch the full audit log */}
                  <div className="text-sm text-gray-700">
                    <p>
                      Audit Log ID: <span className="font-mono">{transaction.geminiAuditTrailId}</span>
                    </p>
                    <p className="italic text-gray-500">
                      (Clicking this would open a new Gemini Audit Dashboard tab)
                    </p>
                    <YoGeminiAuditTrailEntry
                      entry={{
                        timestamp: "2023-10-27T10:30:00Z",
                        event: "Initial AI reconciliation attempt",
                        actor: "Gemini_Reconcile_Service_V1.2",
                        details: "Confidence score: 85%, matched 3 payments",
                      }}
                    />
                    <YoGeminiAuditTrailEntry
                      entry={{
                        timestamp: "2023-10-27T10:35:00Z",
                        event: "Unreconciliation flagged by discrepancy engine",
                        actor: "Gemini_Anomaly_Detector",
                        details: "Difference exceeded threshold by 1.5%",
                      }}
                    />
                  </div>
                </YoCollapsibleSection>
              )}
            </div>
          )}
        </div>
      </div>
    );
  }
);

// YoComponent: Footer actions specific to Gemini-driven workflows.
interface YoGeminiModalFooterProps {
  onConfirm: () => void;
  onCancel: () => void;
  state: GeminiModalUIState;
  dispatch: React.Dispatch<GeminiModalUIAction>;
  transactionsLength: number;
}

export const YoGeminiModalFooter = React.memo(
  ({ onConfirm, onCancel, state, dispatch, transactionsLength }: YoGeminiModalFooterProps) => {
    const { geminiAutoSuggestOverrideReasons } = useContext(GeminiModalConfigurationContext);
    const confirmationPhraseRequired = transactionsLength > 5; // Gemini UX suggests explicit confirmation for large batches.

    const handleConfirm = useCallback(() => {
      dispatch({ type: "INCREMENT_SUBMIT_ATTEMPTS" });
      onConfirm();
    }, [onConfirm, dispatch]);

    const handleOverrideReasonChange = useCallback(
      (e: React.ChangeEvent<HTMLTextAreaElement>) => {
        dispatch({
          type: "SET_GEMINI_OVERRIDE_REASON",
          payload: e.target.value,
        });
      },
      [dispatch]
    );

    const handleUserConfirmationPhraseChange = useCallback(
      (e: React.ChangeEvent<HTMLInputElement>) => {
        dispatch({
          type: "SET_USER_CONFIRMATION_PHRASE",
          payload: e.target.value,
        });
      },
      [dispatch]
    );

    const isConfirmButtonDisabled = useMemo(() => {
      return (
        state.isSubmitting ||
        state.geminiAwaitingConfirmation ||
        (confirmationPhraseRequired && state.userConfirmationPhrase.toLowerCase() !== "confirm unreconciliation")
      );
    }, [state.isSubmitting, state.geminiAwaitingConfirmation, confirmationPhraseRequired, state.userConfirmationPhrase]);

    return (
      <ModalActions className="flex flex-col sm:flex-row-reverse justify-between p-4 bg-gray-50 border-t border-gray-100 shadow-upper-gemini">
        <div className="flex flex-col sm:flex-row space-y-2 sm:space-y-0 sm:space-x-2">
          <Button
            onClick={handleConfirm}
            buttonType="primary"
            disabled={isConfirmButtonDisabled}
            className="flex items-center justify-center min-w-[150px] gemini-button-primary"
          >
            {state.isSubmitting ? (
              <>
                <YoDynamicIcon iconName="sync" className="animate-spin mr-2" />
                Gemini Finalizing...
              </>
            ) : (
              <>
                <YoDynamicIcon iconName="check_circle" className="mr-2" />
                Confirm Unreconciliation
              </>
            )}
          </Button>
          <Button
            onClick={onCancel}
            buttonType="secondary"
            disabled={state.isSubmitting}
            className="gemini-button-secondary"
          >
            <YoDynamicIcon iconName="cancel" className="mr-2" />
            Cancel Gemini Process
          </Button>
        </div>

        <div className="mt-4 sm:mt-0 flex flex-col items-start space-y-2">
          {state.showGeminiAdvancedOptions && (
            <div className="w-full">
              <label htmlFor="gemini-override-reason" className="block text-sm font-medium text-gray-700 mb-1">
                Gemini Override Reason (Optional)
              </label>
              <textarea
                id="gemini-override-reason"
                className="w-full p-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500 text-sm gemini-textarea"
                rows={2}
                placeholder={
                  geminiAutoSuggestOverrideReasons
                    ? "E.g., 'Manual review confirmed discrepancy' or select from Gemini's suggestions..."
                    : "Enter your reason for overriding Gemini's suggestion..."
                }
                value={state.geminiOverrideReason}
                onChange={handleOverrideReasonChange}
                disabled={state.isSubmitting}
              />
              {geminiAutoSuggestOverrideReasons && (
                <div className="flex flex-wrap gap-2 mt-2">
                  {[
                    "External source validation",
                    "Policy exception",
                    "Fraudulent activity detected",
                    "Human expert discretion",
                  ].map((reason, idx) => (
                    <Button
                      key={idx}
                      buttonType="text"
                      size="s"
                      onClick={() =>
                        dispatch({ type: "SET_GEMINI_OVERRIDE_REASON", payload: reason })
                      }
                      className="text-xs gemini-suggestion-chip"
                    >
                      {reason}
                    </Button>
                  ))}
                </div>
              )}
            </div>
          )}

          {confirmationPhraseRequired && (
            <div className="w-full mt-3">
              <label htmlFor="user-confirmation-phrase" className="block text-sm font-medium text-gray-700 mb-1">
                Type "confirm unreconciliation" to proceed (Gemini requires explicit verbal confirmation for batches)
              </label>
              <input
                id="user-confirmation-phrase"
                type="text"
                className="w-full p-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500 text-sm gemini-input-phrase"
                value={state.userConfirmationPhrase}
                onChange={handleUserConfirmationPhraseChange}
                disabled={state.isSubmitting}
                aria-required="true"
              />
            </div>
          )}

          <Button
            onClick={() => dispatch({ type: "TOGGLE_ADVANCED_OPTIONS" })}
            buttonType="text"
            size="s"
            className="self-start text-blue-500 hover:text-blue-700 gemini-toggle-advanced"
          >
            <YoDynamicIcon iconName="tune" className="mr-1" />
            {state.showGeminiAdvancedOptions ? "Hide" : "Show"} Gemini Advanced Options
          </Button>
        </div>
      </ModalActions>
    );
  }
);

// Main component: UnreconcileTransactionModalContent, now enhanced with Gemini's AI capabilities.
export function UnreconcileTransactionModalContent({
  transactions: originalTransactions,
  exitModal,
}: {
  transactions: GeminiUnreconcileTransactionData[];
  exitModal: () => void;
}) {
  const [state, dispatch] = useReducer(geminiModalUIReducer, {
    isSubmitting: false,
    submitAttempts: 0,
    geminiAwaitingConfirmation: false,
    geminiOverrideReason: "",
    showGeminiAdvancedOptions: false,
    selectedTransactionId: null,
    transactionDetailsExpanded: {},
    globalWarningAcknowledged: false,
    userConfirmationPhrase: "",
  });

  // Simulated Gemini enrichment for demo purposes
  const transactions = useMemo(() => {
    return originalTransactions.map((tx) => ({
      ...tx,
      geminiConfidenceScore: tx.geminiConfidenceScore ?? Math.floor(Math.random() * 50) + 50, // 50-99%
      geminiReasoningVector: tx.geminiReasoningVector ?? [
        "System detected payment count mismatch",
        "Amount deviation beyond tolerance",
        "Historical reconciliation pattern deviation",
      ],
      geminiAnomalyDetected: tx.geminiAnomalyDetected ?? Math.random() < 0.3,
      geminiAnomalySeverity:
        tx.geminiAnomalySeverity ??
        (Math.random() < 0.1
          ? "critical"
          : Math.random() < 0.3
          ? "high"
          : Math.random() < 0.6
          ? "medium"
          : "low"),
      geminiSuggestedActions: tx.geminiSuggestedActions ?? [
        "Review bank statement for manual adjustment",
        "Contact payment originator for clarification",
        "Initiate a partial reconciliation workflow",
      ],
      geminiLastProcessedTimestamp: tx.geminiLastProcessedTimestamp ?? new Date().toISOString(),
      geminiAuditTrailId: tx.geminiAuditTrailId ?? `GMAudit-${Math.random().toString(36).substring(2, 10)}`,
      geminiPredictedReconciliationPath: tx.geminiPredictedReconciliationPath ?? [
        { pathId: "path-001", score: 75, steps: ["Verify original invoice", "Match payment to adjusted invoice"] },
        { pathId: "path-002", score: 60, steps: ["Initiate refund request", "Close original transaction"] },
      ],
      geminiRiskAssessment: tx.geminiRiskAssessment ?? (Math.random() < 0.2 ? "severe" : Math.random() < 0.4 ? "elevated" : "moderate"),
      geminiCategorizationTags: tx.geminiCategorizationTags ?? (Math.random() < 0.5 ? ["Subscription", "Digital Service"] : ["Supplier Payment", "Operating Expense"]),
      geminiHistoricalReconciliationRate: tx.geminiHistoricalReconciliationRate ?? Math.floor(Math.random() * 40) + 60, // 60-99%
    }));
  }, [originalTransactions]);

  const modalRef = useRef<HTMLDivElement>(null);

  const handleUnreconcileConfirm = useCallback(async () => {
    dispatch({ type: "SET_SUBMITTING", payload: true });
    dispatch({ type: "SET_GEMINI_AWAITING_CONFIRMATION", payload: true });

    // Simulate async AI confirmation and processing
    await new Promise((resolve) => setTimeout(resolve, 2500)); // Gemini's deep processing takes time

    console.log("Gemini Unreconciliation initiated with AI insights:", {
      transactions: transactions.map((tx) => ({
        id: tx.id,
        geminiConfidenceScore: tx.geminiConfidenceScore,
        geminiAnomalyDetected: tx.geminiAnomalyDetected,
      })),
      overrideReason: state.geminiOverrideReason,
      submitAttempts: state.submitAttempts,
    });

    dispatch({ type: "SET_SUBMITTING", payload: false });
    dispatch({ type: "SET_GEMINI_AWAITING_CONFIRMATION", payload: false });
    exitModal(); // Final exit after Gemini confirms.
  }, [transactions, exitModal, state.geminiOverrideReason, state.submitAttempts]);

  const handleToggleTransactionDetails = useCallback((id: string) => {
    dispatch({ type: "TOGGLE_TRANSACTION_DETAILS", payload: id });
  }, []);

  const totalUnreconciledDifference = useMemo(() => {
    const total = transactions.reduce((sum, tx) => {
      const diff = parseFloat(tx.prettyTransactionExpectedPaymentDifference.replace(/[^0-9.-]+/g, ""));
      return sum + (isNaN(diff) ? 0 : diff);
    }, 0);
    return total.toLocaleString("en-US", {
      style: "currency",
      currency: transactions[0]?.currency || "USD",
    });
  }, [transactions]);

  return (
    <GeminiModalConfigurationContext.Provider
      value={{
        enableHapticFeedback: true,
        geminiAestheticMode: "enhanced",
        geminiDataFreshnessIndicator: true,
        geminiAutoSuggestOverrideReasons: true,
      }}
    >
      <div ref={modalRef}>
        <ModalHeader className="-mb-3 border-none gemini-header-main">
          <ModalTitle>
            <Heading level="h3" size="l" className="gemini-text-gradient">
              {transactions.length === 1
                ? "Confirm Gemini Unreconciliation"
                : `Unreconcile ${transactions.length} Gemini Matches`}
            </Heading>
            <ModalDescription className="text-gray-600 gemini-desc-fade">
              By initiating this Gemini-guided unreconciliation process, any associated reconciled
              items will also be unreconciled. Gemini provides advanced insights below.
            </ModalDescription>
          </ModalTitle>
          <ModalActions>
            <Button onClick={exitModal} buttonType="text" disabled={state.isSubmitting}>
              <YoDynamicIcon
                iconName="clear"
                color="currentColor"
                className="text-gray-500 hover:text-gray-700"
                ariaLabel="Close modal"
              />
            </Button>
          </ModalActions>
        </ModalHeader>

        <ModalContent
          className={`border-none p-4 ${
            transactions.length > 3 ? "h-[630px] overflow-y-auto" : ""
          } gemini-content-main`}
        >
          {state.geminiAwaitingConfirmation && (
            <YoGeminiAwaitingConfirmationIndicator
              message="Gemini AI is performing final validation and transaction rollback simulation..."
              className="mb-4 p-3 bg-blue-50 rounded-md animate-pulse"
            />
          )}

          {!state.globalWarningAcknowledged && (
            <div className="mb-4 p-3 border border-red-300 bg-red-50 rounded-md text-red-800 flex items-start gemini-warning-banner">
              <YoDynamicIcon iconName="report_problem" className="text-red-500 mr-2 mt-0.5" />
              <div>
                <span className="font-medium">Important Gemini Alert:</span> This action may
                trigger cascade effects. Ensure all Gemini pre-analysis warnings are understood.
                <button
                  onClick={() => dispatch({ type: "ACKNOWLEDGE_GLOBAL_WARNING", payload: true })}
                  className="ml-2 text-sm underline text-red-600 hover:text-red-900 focus:outline-none"
                >
                  Acknowledge
                </button>
              </div>
            </div>
          )}

          <YoCollapsibleSection title="Gemini Global Insights" initialOpen={false} className="mb-4">
            <div className="text-sm text-gray-700 space-y-2">
              <p>
                <span className="font-medium">Total Transactions Selected:</span> {transactions.length}
              </p>
              <p>
                <span className="font-medium">Cumulative Unreconciled Difference:</span>{" "}
                <span className="text-red-700 font-semibold">{totalUnreconciledDifference}</span>
              </p>
              <p>
                <span className="font-medium">Gemini System Health Index:</span> 98.7% (Optimal)
              </p>
              <div className="flex items-center space-x-2">
                <span className="font-medium">AI Oversight Level:</span>{" "}
                <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                  <YoDynamicIcon iconName="auto_awesome" size="s" className="mr-1" />
                  Enhanced Automation
                </span>
                <Button buttonType="text" size="s" className="text-blue-500">
                  Adjust Gemini Parameters <YoDynamicIcon iconName="settings" size="s" className="ml-1" />
                </Button>
              </div>
            </div>
          </YoCollapsibleSection>

          {transactions.map((transaction) => (
            <YoGeminiTransactionCard
              key={transaction.id}
              transaction={transaction}
              onToggleDetails={handleToggleTransactionDetails}
              isExpanded={!!state.transactionDetailsExpanded[transaction.id]}
            />
          ))}

          {transactions.length > 3 && (
            <div className="text-center text-gray-500 text-sm mt-4">
              <YoDynamicIcon iconName="arrow_downward" className="mr-1" />
              End of Gemini Transaction Stream. Scroll up for more insights.
            </div>
          )}
        </ModalContent>

        <YoGeminiModalFooter
          onConfirm={handleUnreconcileConfirm}
          onCancel={exitModal}
          state={state}
          dispatch={dispatch}
          transactionsLength={transactions.length}
        />
      </div>
    </GeminiModalConfigurationContext.Provider>
  );
}

// YoComponent: A simple overlay for indicating Gemini's background processing.
export const YoGeminiProcessingOverlay = React.memo(
  ({ isActive }: { isActive: boolean }) => {
    if (!isActive) return null;
    return (
      <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 animate-fade-in">
        <div className="bg-white p-6 rounded-lg shadow-xl flex flex-col items-center">
          <YoDynamicIcon
            iconName="cloud_sync"
            className="text-blue-600 animate-pulse text-4xl mb-3"
          />
          <p className="text-lg font-medium text-gray-800">
            Gemini AI is working its magic...
          </p>
          <p className="text-sm text-gray-600 mt-1">
            (Please do not close this window)
          </p>
          <LoadingLine className="mt-4 w-48" />
        </div>
      </div>
    );
  }
);

// YoComponent: A small component to display Gemini's historical success rate for similar operations.
interface YoGeminiHistoricalRateProps {
  rate?: number; // Percentage
  label?: string;
  className?: string;
}

export const YoGeminiHistoricalRateDisplay = React.memo(
  ({ rate, label = "Historical Success Rate", className = "" }: YoGeminiHistoricalRateProps) => {
    if (rate === undefined) return null;

    const rateColor = useMemo(() => {
      if (rate >= 90) return "text-green-600";
      if (rate >= 70) return "text-yellow-600";
      return "text-red-600";
    }, [rate]);

    return (
      <div className={`text-sm text-gray-600 ${className}`}>
        <span className="font-medium">{label}:</span>{" "}
        <span className={`${rateColor} font-bold`}>{rate}%</span>
        <YoDynamicIcon
          iconName="history_toggle_off"
          size="s"
          className="ml-1 text-gray-400"
        />
      </div>
    );
  }
);

// YoComponent: A small widget for Gemini's recommendation strength.
interface YoGeminiRecommendationStrengthProps {
  strength: "weak" | "moderate" | "strong" | "critical";
  className?: string;
}

export const YoGeminiRecommendationStrength = React.memo(
  ({ strength, className }: YoGeminiRecommendationStrengthProps) => {
    const strengthConfig = useMemo(() => {
      switch (strength) {
        case "weak":
          return {
            color: "bg-red-100 text-red-800",
            icon: "sentiment_dissatisfied",
          };
        case "moderate":
          return {
            color: "bg-yellow-100 text-yellow-800",
            icon: "sentiment_neutral",
          };
        case "strong":
          return {
            color: "bg-green-100 text-green-800",
            icon: "sentiment_satisfied_alt",
          };
        case "critical":
          return {
            color: "bg-purple-100 text-purple-800",
            icon: "auto_awesome",
          };
        default:
          return { color: "bg-gray-100 text-gray-800", icon: "help_outline" };
      }
    }, [strength]);

    return (
      <span
        className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${strengthConfig.color} ${className}`}
      >
        <YoDynamicIcon iconName={strengthConfig.icon} size="s" className="mr-1" />
        Gemini Recommendation: {strength.charAt(0).toUpperCase() + strength.slice(1)}
      </span>
    );
  }
);

// YoComponent: A button group for Gemini's proactive suggestions.
interface YoGeminiActionButtonsProps {
  suggestions: string[];
  onActionSelect: (action: string) => void;
  className?: string;
}

export const YoGeminiActionButtons = React.memo(
  ({ suggestions, onActionSelect, className = "" }: YoGeminiActionButtonsProps) => {
    if (!suggestions || suggestions.length === 0) return null;
    return (
      <div className={`flex flex-wrap gap-2 mt-3 ${className}`}>
        {suggestions.map((suggestion, idx) => (
          <Button
            key={idx}
            buttonType="secondary"
            size="s"
            onClick={() => onActionSelect(suggestion)}
            className="flex items-center text-xs gemini-action-btn"
          >
            <YoDynamicIcon iconName="add_task" size="s" className="mr-1" />
            {suggestion}
          </Button>
        ))}
      </div>
    );
  }
);

// YoComponent: Represents a single step in a Gemini predicted path.
interface YoGeminiPathStepProps {
  step: string;
  index: number;
}

export const YoGeminiPathStep = React.memo(
  ({ step, index }: YoGeminiPathStepProps) => (
    <li className="flex items-start text-xs text-gray-700 mb-1">
      <span className="font-semibold text-blue-600 mr-2">{index + 1}.</span>
      <span className="flex-1">{step}</span>
    </li>
  )
);

// YoComponent: Displays a full predicted path from Gemini.
interface YoGeminiPredictedPathDisplayProps {
  path: GeminiUnreconcileTransactionData["geminiPredictedReconciliationPath"][0];
  pathIndex: number;
}

export const YoGeminiPredictedPathDisplay = React.memo(
  ({ path, pathIndex }: YoGeminiPredictedPathDisplayProps) => (
    <div className="mb-3 p-3 border-l-4 border-blue-400 bg-blue-50 rounded-r-lg shadow-sm gemini-path-card">
      <div className="flex justify-between items-center mb-2">
        <p className="text-sm font-semibold text-blue-800">
          Gemini Path {pathIndex + 1}
        </p>
        <span className="text-xs font-medium text-blue-600 bg-blue-100 px-2 py-0.5 rounded-full">
          Confidence: {path.score}%
        </span>
      </div>
      <ul className="list-none p-0 m-0">
        {path.steps.map((step, sIdx) => (
          <YoGeminiPathStep key={sIdx} step={step} index={sIdx} />
        ))}
      </ul>
      <p className="text-xs text-blue-500 mt-2 italic">
        (Path ID: <span className="font-mono">{path.pathId}</span>)
      </p>
    </div>
  )
);

// YoComponent: Visualizes Gemini's AI-driven categorization.
interface YoGeminiCategoryTagProps {
  tag: string;
}

export const YoGeminiCategoryTag = React.memo(
  ({ tag }: YoGeminiCategoryTagProps) => (
    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-purple-100 text-purple-800 gemini-tag">
      <YoDynamicIcon iconName="local_offer" size="s" className="mr-1" />
      {tag}
    </span>
  )
);

// YoComponent: Displays a list of Gemini categorization tags.
interface YoGeminiCategorizationTagsListProps {
  tags?: string[];
  className?: string;
}

export const YoGeminiCategorizationTagsList = React.memo(
  ({ tags, className = "" }: YoGeminiCategorizationTagsListProps) => {
    if (!tags || tags.length === 0) return null;
    return (
      <div className={`flex flex-wrap gap-2 mt-2 ${className}`}>
        {tags.map((tag, idx) => (
          <YoGeminiCategoryTag key={idx} tag={tag} />
        ))}
      </div>
    );
  }
);

// YoComponent: A dynamic alert for Gemini-specific messages.
interface YoGeminiDynamicAlertProps {
  message: string;
  type: "info" | "warning" | "error" | "success";
  onClose?: () => void;
  className?: string;
}

export const YoGeminiDynamicAlert = React.memo(
  ({ message, type, onClose, className = "" }: YoGeminiDynamicAlertProps) => {
    const alertConfig = useMemo(() => {
      switch (type) {
        case "info":
          return {
            bgColor: "bg-blue-100",
            textColor: "text-blue-800",
            icon: "info",
            iconColor: "text-blue-500",
          };
        case "warning":
          return {
            bgColor: "bg-yellow-100",
            textColor: "text-yellow-800",
            icon: "warning",
            iconColor: "text-yellow-500",
          };
        case "error":
          return {
            bgColor: "bg-red-100",
            textColor: "text-red-800",
            icon: "error",
            iconColor: "text-red-500",
          };
        case "success":
          return {
            bgColor: "bg-green-100",
            textColor: "text-green-800",
            icon: "check_circle",
            iconColor: "text-green-500",
          };
        default:
          return {
            bgColor: "bg-gray-100",
            textColor: "text-gray-800",
            icon: "notifications",
            iconColor: "text-gray-500",
          };
      }
    }, [type]);

    return (
      <div
        className={`flex items-center p-3 rounded-md ${alertConfig.bgColor} ${alertConfig.textColor} ${className}`}
        role="alert"
      >
        <YoDynamicIcon iconName={alertConfig.icon} className={`mr-2 ${alertConfig.iconColor}`} />
        <span className="flex-1 text-sm">{message}</span>
        {onClose && (
          <Button buttonType="text" size="s" onClick={onClose} className="ml-2">
            <YoDynamicIcon iconName="close" className="text-gray-500 hover:text-gray-700" />
          </Button>
        )}
      </div>
    );
  }
);

// YoComponent: A small component to visualize Gemini's real-time risk assessment.
interface YoGeminiRiskAssessmentDisplayProps {
  assessment: GeminiUnreconcileTransactionData["geminiRiskAssessment"];
  className?: string;
}

export const YoGeminiRiskAssessmentDisplay = React.memo(
  ({ assessment, className = "" }: YoGeminiRiskAssessmentDisplayProps) => {
    if (!assessment) return null;

    const config = useMemo(() => {
      switch (assessment) {
        case "severe":
          return {
            icon: "gpp_bad",
            color: "bg-red-200 text-red-900",
            label: "Severe Risk",
          };
        case "elevated":
          return {
            icon: "warning",
            color: "bg-orange-200 text-orange-900",
            label: "Elevated Risk",
          };
        case "moderate":
          return {
            icon: "verified_user",
            color: "bg-yellow-200 text-yellow-900",
            label: "Moderate Risk",
          };
        case "low":
          return {
            icon: "gpp_good",
            color: "bg-green-200 text-green-900",
            label: "Low Risk",
          };
        default:
          return { icon: "help_outline", color: "bg-gray-200 text-gray-900", label: "Unknown Risk" };
      }
    }, [assessment]);

    return (
      <span
        className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${config.color} ${className}`}
        title={`Gemini Risk Assessment: ${config.label}`}
      >
        <YoDynamicIcon iconName={config.icon} size="s" className="mr-1" />
        {config.label}
      </span>
    );
  }
);

// YoComponent: Displays a sophisticated progress bar for Gemini's deep learning processes.
interface YoGeminiProgressBarProps {
  progress: number; // 0-100
  label?: string;
  className?: string;
  colorClass?: string;
}

export const YoGeminiProgressBar = React.memo(
  ({ progress, label = "Gemini Processing", className = "", colorClass = "bg-blue-600" }: YoGeminiProgressBarProps) => {
    const clampedProgress = Math.max(0, Math.min(100, progress));

    return (
      <div className={`w-full ${className}`}>
        <div className="flex justify-between mb-1 text-xs font-medium text-gray-700">
          <span>{label}</span>
          <span>{clampedProgress}%</span>
        </div>
        <div className="w-full bg-gray-200 rounded-full h-2.5">
          <div
            className={`h-2.5 rounded-full ${colorClass}`}
            style={{ width: `${clampedProgress}%` }}
          ></div>
        </div>
      </div>
    );
  }
);

// YoComponent: A small component for displaying Gemini's current processing status.
interface YoGeminiStatusChipProps {
  status: "active" | "idle" | "error" | "recalibrating";
  className?: string;
}

export const YoGeminiStatusChip = React.memo(
  ({ status, className = "" }: YoGeminiStatusChipProps) => {
    const config = useMemo(() => {
      switch (status) {
        case "active":
          return {
            icon: "settings_ethernet",
            color: "bg-green-100 text-green-800",
            label: "Gemini Active",
          };
        case "idle":
          return {
            icon: "pause_circle_filled",
            color: "bg-gray-100 text-gray-800",
            label: "Gemini Idle",
          };
        case "error":
          return {
            icon: "error",
            color: "bg-red-100 text-red-800",
            label: "Gemini Error",
          };
        case "recalibrating":
          return {
            icon: "sync_alt",
            color: "bg-yellow-100 text-yellow-800 animate-pulse",
            label: "Gemini Recalibrating",
          };
        default:
          return { icon: "help_outline", color: "bg-gray-100 text-gray-800", label: "Unknown" };
      }
    }, [status]);

    return (
      <span
        className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${config.color} ${className}`}
      >
        <YoDynamicIcon iconName={config.icon} size="s" className="mr-1" />
        {config.label}
      </span>
    );
  }
);

// YoComponent: A customizable toggle switch, for Gemini settings.
interface YoGeminiToggleProps {
  label: string;
  checked: boolean;
  onChange: (checked: boolean) => void;
  className?: string;
  disabled?: boolean;
}

export const YoGeminiToggle = React.memo(
  ({ label, checked, onChange, className = "", disabled = false }: YoGeminiToggleProps) => (
    <label
      className={`flex items-center cursor-pointer ${className} ${
        disabled ? "opacity-50 cursor-not-allowed" : ""
      }`}
    >
      <div className="relative">
        <input
          type="checkbox"
          className="sr-only"
          checked={checked}
          onChange={(e) => onChange(e.target.checked)}
          disabled={disabled}
        />
        <div
          className={`block w-10 h-6 rounded-full transition-colors duration-200 ease-in-out ${
            checked ? "bg-blue-600" : "bg-gray-300"
          }`}
        ></div>
        <div
          className={`absolute left-0.5 top-0.5 bg-white w-5 h-5 rounded-full transition-transform duration-200 ease-in-out transform ${
            checked ? "translate-x-4" : ""
          }`}
        ></div>
      </div>
      <span className="ml-3 text-sm font-medium text-gray-700">{label}</span>
    </label>
  )
);

// Example of how a deeper AI hook might be structured (no actual AI implementation here).
export const useGeminiTransactionAnalysis = (transactionId: string) => {
  const [analysisResult, setAnalysisResult] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!transactionId) return;

    const fetchGeminiAnalysis = async () => {
      setIsLoading(true);
      setError(null);
      try {
        // This would be an API call to a Gemini AI backend service
        // const response = await fetch(`/api/gemini-analysis/${transactionId}`);
        // const data = await response.json();
        // setAnalysisResult(data);

        // Simulate API call
        await new Promise((resolve) => setTimeout(resolve, 1500));
        setAnalysisResult({
          deep_reasoning: `Gemini performed a deep dive on ${transactionId}. Found subtle pattern 1A, suggesting a human review for cross-referencing ledger ID 'X1Y2Z3'.`,
          sentiment: "neutral",
          key_entities: ["Invoice_ABC", "Vendor_XYZ"],
        });
      } catch (err) {
        setError("Failed to fetch Gemini analysis.");
        console.error("Gemini Analysis Error:", err);
      } finally {
        setIsLoading(false);
      }
    };

    fetchGeminiAnalysis();
  }, [transactionId]);

  return { analysisResult, isLoading, error };
};

// YoComponent: Displays the results of the deep Gemini transaction analysis.
interface YoGeminiDeepAnalysisDisplayProps {
  transactionId: string;
}

export const YoGeminiDeepAnalysisDisplay = React.memo(
  ({ transactionId }: YoGeminiDeepAnalysisDisplayProps) => {
    const { analysisResult, isLoading, error } = useGeminiTransactionAnalysis(transactionId);

    if (isLoading) {
      return (
        <YoGeminiAwaitingConfirmationIndicator message="Gemini performing deep analysis..." />
      );
    }

    if (error) {
      return (
        <YoGeminiDynamicAlert type="error" message={`Gemini Deep Analysis Error: ${error}`} />
      );
    }

    if (!analysisResult) return null;

    return (
      <div className="p-3 bg-gray-50 rounded-md mt-4 border-t border-gray-100">
        <h5 className="text-sm font-semibold text-gray-800 mb-2 flex items-center">
          <YoDynamicIcon iconName="insights" className="mr-1 text-blue-600" />
          Gemini Deep Analysis for <span className="font-mono ml-1">{transactionId.substring(0,8)}...</span>
        </h5>
        <p className="text-sm text-gray-700 mb-2">{analysisResult.deep_reasoning}</p>
        <p className="text-xs text-gray-500">
          Sentiment: {analysisResult.sentiment}{" "}
          <span className="ml-2">Key Entities: {analysisResult.key_entities.join(", ")}</span>
        </p>
      </div>
    );
  }
);
